### ISSUE TITLE
Remove my shots when you are not logged in

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1000]
Instead it should have "Made With PageShot" and should link to the homepage

![image](https://cloud.githubusercontent.com/assets/44390/13444763/cac56552-dfcd-11e5-89ec-ff4441dd6381.png)

[design](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/133851373)

**Comment by fzzzy** [comment]
Bram, is the asset for the color pageshot logo available somewhere?

**Comment by brampitoyo** [comment]
This is the Pageshot icon Bryan had designed, that I had converted to SVG:

https://www.dropbox.com/s/9u4t3tb385tbg5d/pageshot.svg

For the moment, we can resize it to the appropriate dimension shown in the screenshot (width: 32, height: 30).

**Comment by fzzzy** [comment]
I fixed this recently.
