### ISSUE TITLE
Toolbar icon assets

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1009]
Bryan Bell had designed these. Note the different versions meant for Mac, Windows and dark themes (where the colours are inverted to white):

https://www.dropbox.com/sh/qt1iyj05q48m2e2/AABrrnOu37_-7NbkUMsNMEGSa

**Comment by fzzzy** [comment]
Can we get svg copies of each of the variations too?

**Comment by fzzzy** [comment]
Opened #1027 to acquire and switch to an svg icon
