### ISSUE TITLE
Share panel design tweaks

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1015]
In the share panel:

![image](https://cloud.githubusercontent.com/assets/44390/13537122/fce77560-e208-11e5-96b3-6561f5ab1446.png)

The share buttons should be spaced out to the full width, and the text box/copy button should also be full width. Also a colon after "get a ..."

**Comment by brampitoyo** [comment]
Measurements and design specs:

![measurements - share overlay 2x](https://cloud.githubusercontent.com/assets/51007/13558364/0ef18f3c-e468-11e5-9b55-c6583a5f775a.png)
