### ISSUE TITLE
notificationbox doesn't reload well

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1023]
I get an exception like this sometimes after reload:

```
JPM [error]   Message: TypeError: aChild.eventCallback is not a function
  Stack:
    _removeNotificationElement@chrome://global/content/bindings/notification.xml:205:15
_finishAnimation@chrome://global/content/bindings/notification.xml:311:15
_showNotification@chrome://global/content/bindings/notification.xml:267:13
appendNotification@chrome://global/content/bindings/notification.xml:174:15
initialize@resource://gre/modules/commonjs/toolkit/loader.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/lib/notificationbox.js:205:19
...
```

I don't really understand it though.

**Comment by ianb** [comment]
Worth looking at the stylesheet service as well.  Also make sure we tear down the notification box on unload (there is code to do that, but it might not work).  Not sure if this breaks worse when the topbar is open on reload.

**Comment by fzzzy** [comment]
I couldn't make much progress on this. The topbar is correctly dismissed on reload, but the shot context is not torn down and the crosshairs and selection lightbox are not removed. It seems we are sending a message to the worker telling it to remove the injected elements from the page, but the context is getting killed before it has a chance to actually process the message.

**Comment by ckprice** [comment]
There is no notification box.
