### ISSUE TITLE
Images for zoom in / out magnifying glasses

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1041]
svg format

**Comment by brampitoyo** [comment]
Let’s try using arrows for now. If it doesn’t work or unclear, we can use magnifying glass.

Zoom in:
https://www.dropbox.com/s/twlcvgn4vxjm67w/zoom-in.svg

Zoom out:
https://www.dropbox.com/s/yup2mmccu4grlc4/zoom-out.svg
