### ISSUE TITLE
Use jpm sign

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1054]
We should make it possible to sign the XPI via jpm sign

**Comment by fzzzy** [comment]
To use, just "jpm sign --api-key <key> --api-secret <secret>", where key and secret are obtained on addons.mozilla.org under API Credentials. It seems to take forever; using the web interface might be better for now since more feedback on what is happening is provided.

**Comment by fzzzy** [comment]
Still doesn't seem to work, says "Signature has expired" even though I just generated a new key.

**Comment by fzzzy** [comment]
I guess this requires more work involving a "jwt"

https://github.com/mozilla/testpilot/blob/master/addon/bin/sign

**Comment by ianb** [comment]
Ah, JWT is a way of signing things, I guess that's how the auth to jpm sign actually works?  Maybe we can just copy that script for our use?

**Comment by fzzzy** [comment]
According to more info from folks on #testpilot, we should just be able to use jpm sign. They used the api for some reason related to their continuous integration. But, I just keep getting "Signature has expired" when I try it, even after regenerating keys.

**Comment by fzzzy** [comment]
I was finally able to make it work, but only by explicitly passing --xpi=path/to/mozilla-pageshot.xpi. If I don't, it takes too long to generate the xpi and the jwt is expired by the time it gets used. Should probably file a bug against jpm.
