### ISSUE TITLE
Design shot index card box-shadow

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1076]
It wasn't in the previous specs.  I put in `box-shadow: 2px 2px 5px rgba(0, 0, 0, 0.5);`

**Comment by brampitoyo** [comment]
Actually, in the specs, I didn’t specify a box shadow value at all. Each item has `background-color: #fff` and the page itself has `background-color: #f4f4f4`. It gives it a nice contrast without any need for shadow.

Have a look at the specs below.

![measurements - site previews shot index page 1x](https://cloud.githubusercontent.com/assets/51007/13833013/5f9598f8-ec46-11e5-8204-b5950a6f909a.png)
