### ISSUE TITLE
Design fixes on shot index

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1098]
Example:

![image](https://cloud.githubusercontent.com/assets/44390/13968177/3452558a-f049-11e5-8d50-64c5bcfa585f.png)

Or header with a search:

![image](https://cloud.githubusercontent.com/assets/44390/13968184/4c891756-f049-11e5-87ed-1f1756c25e1f.png)

We also need design for an empty search result.

**Comment by ianb** [comment]
Also we need some design for when there's not full results

**Comment by ianb** [comment]
From [Invision](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/135603249):

![image](https://cloud.githubusercontent.com/assets/44390/13968406/92c885ac-f04a-11e5-813c-4c66d0722b67.png)

**Comment by brampitoyo** [comment]
Fixed measurements:
![measurements - site previews shot index page](https://cloud.githubusercontent.com/assets/51007/13970807/06fbc7b8-f0f0-11e5-860c-85c574b7eca4.png)

Something you might have missed is the 1px grey line that sits between the image preview area and the page title:
![measurements - site previews shot index page](https://cloud.githubusercontent.com/assets/51007/13970968/4af97270-f0f1-11e5-8b35-ad5484512df3.png)

Lastly, here’s the measurement for the page’s header and footer, which includes logo and avatar dimension, as well as font sizes:
![measurements - shot index page header and footer 2x](https://cloud.githubusercontent.com/assets/51007/13971862/84389528-f0f8-11e5-8737-6f45687b158f.png)

**Comment by brampitoyo** [comment]
The task I have left is to design how the search box will fit besides the PageShot logo. It should be simple.

@ianb, can we center all the elements on this page, instead of aligned left like what we have currently?

**Comment by ianb** [comment]
When centering, the margin between the boxes should be exactly what it is now, and the flex is just the left and right margin.  

Todo still: design search and the no-search-results page.

**Comment by TLHuang** [comment]
@brampitoyo I'm not sure if there is an avatar icon in My Shots page? I saw it in the design that you proposed, but it didn't show in the current My Shots page.

**Comment by brampitoyo** [comment]
@TLHuang You’re right. The avatar icon was proposed in my design, but it was never necessary for PageShot to work, so it was taken out of the final design. Sorry for the oversight!

**Comment by ianb** [comment]
* We'll do partial opacity on the results when a search is entered but the search hasn't been done
* Only when you press enter will we do the actual search.  When you press enter the items will remain translucent until the search results come back, at which point we display the search results with full opacity.
* When you press enter and there are no results, we put up a big icon and message.
* When you make a successful search, at the very bottom we put the number of search results.  For technical reasons we won't support any pagination.

**Comment by TLHuang** [comment]
Thank you Ian for the summary! Here is the visual spec, and the flow is just the same as what we discussed last time, please take a look at the PDF file. I also upload the assets here. Let me know if any questions.

[My Shot Index Page Spec.pdf](https://github.com/mozilla-services/pageshot/files/381236/My.Shot.Index.Page.Spec.pdf)
[issue1098 images.zip](https://github.com/mozilla-services/pageshot/files/381235/issue1098.images.zip)

**Comment by ckprice** [comment]
@johngruen to check it out.

**Comment by pdehaan** [comment]
@johngruen Fixed via #1383?
