### ISSUE TITLE
Shut off old pageshot server

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1102]
To do (all in Virginia):

- [x] Remove EC2 instance
- [x] Remove load balancer (might be two?)
- [x] Remove RDS
- [x] Security group
- [x] DNS
- [ ] pageshotfzzzy Beanstalk

**Comment by ckprice** [comment]
Assigning to Ian and moving it to Next Tasks.

**Comment by ianb** [comment]
@fzzzy: I'm not sure if the Beanstalk instance should be shut down, can you review and shut it down if necessary?

**Comment by fzzzy** [comment]
No, we still use the beanstalk instance for pageshot.dev.mozaws.net.
