### ISSUE TITLE
Change global `font-family` value

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1111]
We do this so that our font family value matches, as closely as possible, the OS that user has running.

This should apply to the PageShot web interface.

As for the homepage, I still recommend changing the `font-family` value to the one below. If we can’t, let’s just stick with the current Open Sans stack.

`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen-Sans", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif`

**Comment by fzzzy** [comment]
Fixed by https://github.com/mozilla-services/pageshot/pull/1209
