### ISSUE TITLE
Modify .flag-button

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1112]
I realised just now that showing a red flag at all times is a bad idea. It might saturate user with information that they very rarely need to deal with.

Firstly, let’s change the graphic a little bit. [Here’s an updated flag svg that’s been turned grey](https://dl.dropboxusercontent.com/content_link/RfoUHEEtIRmeUioucwhuVI2iouX1oyOWQy1utXDwC6hD9Qb7rCbfif5BqSN4bixw/file).

Secondly, let’s also reduce the padding in the CSS a little bit:

    .flag button {
      padding: 6px 5px;
      ...
    }

If done right, the flag button should look like this:

![screen shot 2016-04-06 at 12 01 48](https://cloud.githubusercontent.com/assets/51007/14301875/65737110-fbef-11e5-8881-6ba3018b0805.PNG)

Sorry for the mistake!

**Comment by fzzzy** [comment]
Hey Bram, I went to work on this but the grey svg flag link is now 404. Can you provide a new link and then re-assign me to the issue? Thanks!

**Comment by brampitoyo** [comment]
Sorry for the overdue response!

Reuploaded file: https://cl.ly/3l3O2G3U3q3x/download/flag.svg
