### ISSUE TITLE
Redesign error popup

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1125]
The error message popup is kind of ugly and unhelpful.  We should give it a little redesign to make it nicer, and also **include a message asking the person to retry what they were doing** – intermittent errors happen, and retrying often works.

**Comment by brampitoyo** [comment]
Do you have a screenshot of what this error message looks like?

**Comment by ianb** [comment]
Example:
![image](https://cloud.githubusercontent.com/assets/44390/14898590/22f12ad4-0d4d-11e6-8259-088daa5888ef.png)

**Comment by ianb** [comment]
Let's change it to just a single generic error message, with no details.  We can have a "more info" link that shows the details of the error (maybe just opening a data URL in a new tab).

Example of the tab crash error in Firefox:

<img width="805" alt="screen shot 2016-07-05 at 5 08 09 pm" src="https://cloud.githubusercontent.com/assets/44390/16601578/14826ace-42d3-11e6-9c40-b1f535371b97.png">

**Comment by TLHuang** [comment]
A quick question about this error message. I've tried using Pageshot on Firefox start page, and it did show this error message. 
Can we know if the PageShot doesn't work on this page before the users hit the button? So I can maybe show a badge on the PageShot button that tells the users the page can't support PageShot in advance.

**Comment by fzzzy** [comment]
Yes, we have another issue for doing something sane on chrome pages (like about:newtab)

https://github.com/mozilla-services/pageshot/issues/1167

**Comment by brampitoyo** [comment]
> …I can maybe show a badge on the PageShot button that tells the users the page can't support PageShot in advance.

Good idea.

While PageShot may not be able to work on the page, I think that we should still offer the link to open “My Shots”?

**Comment by TLHuang** [comment]
> While PageShot may not be able to work on the page, I think that we should still offer the link to open “My Shots”?

Agree! The users should be able to view all the shots while the screen capture is not working. I will  add a link on the error popup.

**Comment by TLHuang** [comment]
The initial design for error popup.

It would be good to let users know whether PageShot works on this page, therefore, if something goes wrong, there will show a forbidden symbol on the top right of PageShot button.

![popup error - badge](https://cloud.githubusercontent.com/assets/4092794/16800901/362f2132-492a-11e6-9160-1d9328fe72dd.png)

The users can tap on the icon to see the error message, and they are still able to go to My Shots.

![popup error - expand](https://cloud.githubusercontent.com/assets/4092794/16800902/36309f3a-492a-11e6-8f05-7f163b0fd17c.png)

**Comment by johngruen** [comment]
@fzzzy alternate design. just disable the button on chrome pages

**Comment by TLHuang** [comment]
Update the visual spec based on the previous discussion, and the assets include the disabled pageshot icon.

[Error Popup Spec.pdf](https://github.com/mozilla-services/pageshot/files/393288/Error.Popup.Spec.pdf)
[issue1125 images.zip](https://github.com/mozilla-services/pageshot/files/393287/issue1125.images.zip)
