### ISSUE TITLE
Bug when activating PageShot more than once

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1132]
From a [comment](https://www.reddit.com/r/firefox/comments/4fubyg/does_mozilla_have_a_highlight_addon_similar_to/d2ctdh6):

> 4) Things get a little messed up if the toolbar button is clicked twice on page. To reproduce:
> a) Click the toolbar button
> b) Either take a shot and save it or just directly cancel it
> c) While on the same page, click the toolbar button again
> Observed behaviour: The rolldown toolbar shows up fine. But even after having made a selection, the cross-hairs don't disappear. I can save the screenshot fine, but although the rolldown toolbar disappears, the cross-hairs don't. If I cancel taking the shot, the cross-hairs still remain until I reload the page.

I think shooter-interactive-worker is getting activated multiple times, and/or not cleaned up.

**Comment by ianb** [comment]
I can't reproduce this anymore.  I wonder if this is fixed because of the changes in #1123

**Comment by fzzzy** [comment]
This seems fixed on the deployed version.
