### ISSUE TITLE
Clean up behavior when trying to shoot a XUL page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1134]
XUL pages (e.g., about;preferences) can't be shot, but we figure that out slightly late.  It flashes the toolbar, which we might want to suppress, or at least we might want to pop up a useful error message.

**Comment by brampitoyo** [comment]
Two alternative behaviours we can consider:

1. Disable the PageShot toolbar button on all XUL pages
2. Or, when you visit these pages and click on the PageShot button, it will do nothing

**Comment by ianb** [comment]
Designs are in #1125 – this bug is for actually popping up a message at the appropriate time (instead of doing nothing)

**Comment by ckprice** [comment]
Closing as dup of https://github.com/mozilla-services/pageshot/issues/1125#issuecomment-235720265
