### ISSUE TITLE
Point to My Shots button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1144]
After you've taken at least one shot, and before you've clicked on the topbar My Shots button, we should put up a dialog that points to the button and tells you that you can find all your shots there.

After the user clicks the My Shots button once the dialog will no longer appear.

**Comment by ianb** [comment]
Here's what it looks like:
![image](https://cloud.githubusercontent.com/assets/44390/14898393/17a5cc4e-0d4c-11e6-885f-d7226050e2da.png)

**Comment by ianb** [comment]
Have the panel follow the [styleguide panel](http://firefoxux.github.io/StyleGuide/#/components/panels)

**Comment by brampitoyo** [comment]
I did a quick mockup using Blake’s panel style:
![screen shot 2016-05-04 at 10 03 51](https://cloud.githubusercontent.com/assets/51007/14999787/8fb16a8a-11df-11e6-9e44-65edfddb918f.PNG)

Code:
```
<div class="panel">
  <div class="panel-arrowUp"></div>
  <div class="panel-section panel-section-header">
    <div class="text-section-list">
      Click this button to view all the shots you’ve taken
    </div>
  </div>
</div>
```

**Comment by ianb** [comment]
The resources here don't seem to have the right styles for this: http://firefoxux.github.io/StyleGuide/#/resources

I changed the structure in 595369727f582a1aaa1f83cfae38e8de966ad283 to match this, but have mostly left the styles.

**Comment by brampitoyo** [comment]
I’ve made a working demo here, based on the stylesheet found on http://firefoxux.github.io/StyleGuide/static/style.css

http://codepen.io/brampitoyo/pen/JKjvzZ

What do you think?
