### ISSUE TITLE
Fix design of Chrome top bar

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1151]
It looks like this currently:

![image](https://cloud.githubusercontent.com/assets/44390/15169891/e9c4886a-1705-11e6-93c7-e722bd542d3a.png)

It should look like the Firefox topbar:

![image](https://cloud.githubusercontent.com/assets/44390/15169899/f8672eb8-1705-11e6-9034-798680bb64d5.png)

**Comment by brampitoyo** [comment]
I reckon it’s even better if the Chrome version could match the visual design specs. It’s hard to achieve in Firefox, but maybe more possible in Chrome?

![measurements - save toolbar 1x](https://cloud.githubusercontent.com/assets/51007/15170004/860be72e-1795-11e6-8ab9-c8dff130a3f2.png)

**Comment by ianb** [comment]
Latest attempt:

![image](https://cloud.githubusercontent.com/assets/44390/15347172/8d786ad4-1c84-11e6-9a86-5b2087084203.png)

I'm not sure what the background color of the Close/Cancel button is (we call it Cancel in Firefox).  Getting the My Shots button aligned right is very hard.

**Comment by fzzzy** [comment]
You could use position: relative; top: Xpx; to move the images in the My Shots button down.

**Comment by ianb** [comment]
No longer applicable due to design changes in the capture
