### ISSUE TITLE
Improve manifest.json icons

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1159]
We just refer to one icon, I think we can do something fancier?

**Comment by brampitoyo** [comment]
Chrome seems to recommend these sizes:

* 16x16: used as favicon for pages that the extension invokes
* 32x32: Windows often requires this size
* 48x48: used on `chrome://extensions`
* 128x128: used on Chrome Webstore and the extension installation UI

Is there any size I’m missing? I suppose it’s not too hard to design a 64x64 and 256x256 variant of these icons for HiDPI display.

**Comment by ianb** [comment]
There's some other [manifest.json](https://developer.chrome.com/extensions/manifest) stuff we should add in too.

**Comment by ianb** [comment]
We also need [toolbar icons](https://developer.chrome.com/extensions/browserAction) which are recommended in 19 and 38 pixels.  I've tried using the SVG and it didn't work, so we'll need to resize it.

We have a 64px size, but no 48px.  So in total we need:

* [ ] 19px
* [ ] 38px
* [ ] 48px
* [ ] 256px

**Comment by brampitoyo** [comment]
Updated the assets list.

**Comment by brampitoyo** [comment]
Note that 19x19 has the same icon as 16x16, but positioned differently (centred) within the frame. Same goes for 38x38.

16x16
![16x16](https://cloud.githubusercontent.com/assets/51007/15311739/f1f46b6c-1c51-11e6-8975-f367d14610b4.png)

19x19
![19x19](https://cloud.githubusercontent.com/assets/51007/15311740/f60de836-1c51-11e6-97a5-abc3ecf77125.png)

32x32
![32x32](https://cloud.githubusercontent.com/assets/51007/15311742/f9495076-1c51-11e6-84f3-f8bc4745345b.png)

38x38
![38x38](https://cloud.githubusercontent.com/assets/51007/15311746/000960d6-1c52-11e6-994d-23e5e7d99199.png)

48x48
![48x48](https://cloud.githubusercontent.com/assets/51007/15311749/060b2316-1c52-11e6-8db3-08f604fa6deb.png)

128x128
![128x128](https://cloud.githubusercontent.com/assets/51007/15311752/094f11ea-1c52-11e6-85c7-c4a43113a1d6.png)

256x256
![256x256](https://cloud.githubusercontent.com/assets/51007/15311755/0ce9c016-1c52-11e6-94c5-8dfe99c3ef27.png)
