### ISSUE TITLE
Check out Awesome Screenshot Minus

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1174]
[Awesome Screenshot Minus](https://chrome.google.com/webstore/detail/awesome-screenshot-minus/bnophbnknjcjnbadhhkciahanapffepm?hl=en) is a Chrome extension

**Comment by ianb** [comment]
## Summary

* The Chrome-native desktop capture is useful to know about
* The selection is similar to ours, we might want to look at the design

## Overview

When you click the button you get a menu:

![image](https://cloud.githubusercontent.com/assets/44390/18686296/1738f83c-7f41-11e6-9558-c86c9d6fc389.png)

The selection is reminiscent of what we have, but with the buttons outside the selection and with the size:

![image](https://cloud.githubusercontent.com/assets/44390/18686406/6fcca872-7f41-11e6-86a8-767d5527338d.png)

If you select close to the bottom of the page you just have to scroll down to get to the buttons.  I like how the buttons pop on top of the shadow.

You can "capture desktop" which I assume uses a Chrome Extension API with a special selector:

![image](https://cloud.githubusercontent.com/assets/44390/18686491/b8ba2a50-7f41-11e6-9972-b8869f105a43.png)

"Delayed capture" has a fixed 3 second countdown then does a full screen capture.

"Capture entire page" does the full length of the page (as opposed to "capture visible part of page").  Not sure how it does this on Chrome, it's not super simple, and it seems to put some real effort into it.  The length is still limited in that case.

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1fXdzNzljwYlt1VKULb3rWD7dUjx2c2G29mRrDj-7Xi0/edit)

**Comment by rixx** [comment]
Just so it's been said: kudos for learning from others and documenting it, it's very nice to see this.
