### ISSUE TITLE
Assets for Chrome store

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1177]
There's several assets we might want to add for the Chrome store:
- [x] Name (as opposed to "Short Name" which would be PageShot)
- [ ] Detailed description ("Focus on explaining what the item does and why users should install it.")
- [x] Icon (128x128: "For square icons, use alpha to make 16 of the 128 pixels per side transparent (96x96 visual weight). Your icon should be flat; avoid noticeable perspective, 3D, and shadows. Don’t use text in your icon.")
- [ ] Screenshots, exactly 1280x800 or exactly 640x400 ("Provide preferably 4 or 5 screenshots of your app (up to a maximum of 5). If your app supports multiple locales, you can provide locale-specific screenshots. Your screenshot should have square corners and no padding (full bleed). We prefer screenshots to be 1280x800 pixels in size, as they will be used in future high dpi displays. Currently, the Chrome Web Store will downscale all screenshots to 640x400, so if your screenshots will not look good downscaled (eg. have a lot of text) or if 1280x800 is too big for your app (screenshot of low resolution game), we also support 640x400 pixels screenshots.")
- [ ] YouTube video (maybe?)
- [ ] Promotional tile images, sizes: 440x280, 920x680, 1400x560 ("Provide images that the store can use to promote your item. The more images you provide, the more prominently your item will be featured. Fill the entire region, using square corners and no padding (full bleed). Use a medium or dark background.
  Avoid text in the image as much as possible. Don’t put white elements along the edges of the image; the edges should be well defined. Don't use a screenshot. Your image should display well when reduced to half size.")
- [x] Decide if we can participate in [Google Play for Education ToS](https://developer.chrome.com/webstore/play_edu_tos)
- [ ] Link to privacy policy
- [x] Decide if we want to do [inline installation](https://developer.chrome.com/webstore/inline_installation?hl=en-US)

**Comment by ianb** [comment]
Re: Education, COPPA worries me: "The laws of some countries, includi ng the United States, impose restrictions on the online collection and use of information from children. You acknowledge that You are responsible for ensuring that each app that You include in Play for Education complies with the Children’s Online Privacy Protection Act and all other applicable laws and regulations."

**Comment by brampitoyo** [comment]
Here’s the icon asset for Chrome webstore, which is sized at 128x128 but has the icon fit inside a 96x96 frame.

![128x128-webstore](https://cloud.githubusercontent.com/assets/51007/15311931/d70e8b64-1c53-11e6-8955-dbfacab752db.png)

**Comment by ianb** [comment]
Current description:

> PageShot takes clips and screenshots from pages, and can save a permanent copy of a page
PageShot lets you save and share anything on the web.  Take clips of pages, save a permanent copy of the entire page, or do both together.
> 
> PageShot can save temporary or restricted pages, giving you a personal backup of anything you see on the web.
> 
> Share with anyone with just the link!

**Comment by ianb** [comment]
What it looks like:

![image](https://cloud.githubusercontent.com/assets/44390/15520968/af5b0324-21ce-11e6-88f0-8c6f8c42fef2.png)

**Comment by ianb** [comment]
Example of where the promotional tiles are used:

![image](https://cloud.githubusercontent.com/assets/44390/15520994/d5097d4e-21ce-11e6-983f-c3a298d4980b.png)

**Comment by ianb** [comment]
Can't do Chrome Education because of COPA.

Won't do inline installation, as it requires some more review, and the store page is fine.

Name: PageShot: screenshot and save full pages

Current Description:

> PageShot lets you save and share anything on the web.  Take clips of pages, save a permanent copy of the entire page, or do both together.
> 
>PageShot can save temporary or restricted pages, giving you a personal backup of anything you see on the web.
> 
> Share with anyone with just the link!

**Comment by ianb** [comment]
We'll have to revisit these questions soon, but not in this form.
