### ISSUE TITLE
Delete your account is gone

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1182]
Because we lost the profile button, we also lost the ability to delete your account (which was part of that interface).

Maybe this wouldn't be too hard to add back in to the shot index page?

**Comment by ianb** [comment]
Note the actual login flow is tied to Firefox, and doesn't apply to Chrome.  (Really we need to switch to a web login flow and ditch the browser/addon-based flow)

**Comment by ianb** [comment]
We need to figure out where to put the control (probably My Shots somewhere?)

**Comment by brampitoyo** [comment]
Assuming that the My Shots page don’t use infinite scrolling, we can put this link somewhere on the bottom/footer area. What do you think?

**Comment by ianb** [comment]
Footer would be okay, though it feels a bit obscure.

**Comment by ianb** [comment]
We'll do this in a stand-alone page, and put a link in the footer to this page.  The page will explain the very permanent nature of the deletion.

**Comment by ianb** [comment]
Here's the [old code](https://github.com/mozilla-services/pageshot/blob/0204faabc016b69e2db4495c9cd1ba1fce37a2a5/server/src/views/profile.js#L123)

**Comment by ianb** [comment]
Brian Smith points out the "account" notion isn't one we actually talk about anywhere else.  We should probably label this "delete all your shots and info"
