### ISSUE TITLE
Review GA events

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1183]
We should review all the events sent to GA.  I suspect some things that could be captured aren't currently.

**Comment by ianb** [comment]
[METRICS.md](https://github.com/mozilla-services/pageshot/blob/master/METRICS.md) is a guide of what we should be sending

**Comment by ianb** [comment]
Note METRICS.md now contains a specification of event category, action, and label.  Sometimes label is blank, which I think is okay.

**Comment by fzzzy** [comment]
Check to make sure the user id we use is consistent across the addon and the website.

**Comment by ckprice** [comment]
Something that may be useful: https://github.com/mozilla/testpilot/blob/master/docs/README-GOOGLE-ANALYTICS.md

**Comment by ianb** [comment]
Note: you can see events in GA [here](https://analytics.google.com/analytics/web/?authuser=0#report/defaultid/a49796218w101460360p105413474/)

**Comment by ianb** [comment]
Note: I have confirmed that both the add-on and site GA use deviceId without any hashing as the GA userId.
