### ISSUE TITLE
In content, combine add-on information to GA

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1185]
We should be sure we can identify when a person is viewing their own shot (vs. a shot belonging to someone else), and whether the user has PageShot installed.

We have fairly easy access to this information via the server and deviceId, but we might want to add some specific events or properties to GA based on this information.

**Comment by fzzzy** [comment]
Ian verified that the same identifier is being used for both the add-on ga events and content ga events, so this is done already.
