### ISSUE TITLE
"Copy" banner covers the zoom in/out button

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1189]
I deployed the latest version, but the copy banner covers the other piece of ui that was in that area.

![screen shot 2016-06-24 at 5 44 25 pm](https://cloud.githubusercontent.com/assets/46048/16351408/5eafaa42-3a33-11e6-84a4-f087e3d41abe.png)

**Comment by brampitoyo** [comment]
This is definitely an unintended effect. The “Copy” banner is supposed to be located underneath the dark overlay.

Can we move it back using CSS?

**Comment by fzzzy** [comment]
That makes sense, but then it will still cover the zoom in button when the dark overlay is not visible and the full page is visible. Should we move either the copy banner or the zoom button to the left side?

**Comment by brampitoyo** [comment]
Right. I’ve failed to account for this scenario.

Let’s move the copy banner to the left side, then, so it doesn’t compete with the zoom in/out button.

**Comment by fzzzy** [comment]
Sounds good to me.

**Comment by fzzzy** [comment]
It looks good now.

![screen shot 2016-06-27 at 3 51 52 pm](https://cloud.githubusercontent.com/assets/46048/16393505/1f954d8c-3c7f-11e6-8d3f-409ec94f5481.png)
