### ISSUE TITLE
Replace top panel with a focused overlay menu

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1191]
My initial design:

![edit initial alternate 1x](https://cloud.githubusercontent.com/assets/51007/16403928/3c84e34c-3d4e-11e6-8d92-0f41bf3550f5.png)

Helen Huang is going to help us refine Pageshot’s visual and UI design, and I think that this issue is a perfect one to start on.

**Comment by ianb** [comment]
Right now we don't have anything equivalent to "Full page" (which presumably is a full page image).  Capturing the full page isn't very hard, but it will be large which might cause upload problems (these sometimes happen already in my experience), and we don't have any patterns for displaying an image like that, or distinguishing it from the other full page.  It would be an interesting experiment, but I think would take too much work.

That leaves us with 3 items, which then breaks the whole layout.  We probably shouldn't have a layout that only works with a certain number of options.  Though having a "help" item wouldn't be unreasonable.

We should definitely think about the "Code" option – I don't like the name, doesn't really make sense.  "Page copy" might be a way of distinguishing from "Screenshot".  "Archive" might be another alternative to "copy".

**Comment by ianb** [comment]
Language thoughts:

archive.org obviously uses the word "archive".  But they call individual captures "snapshots", and refer to the verb "save" ("491 billion web pages saved over time").

archive.is says "My url is alive and I want to archive its content ___" and "I want to search the archive for saved snapshots"

Unfortunately both these use the term "snapshot" which doesn't help.  But connecting this to what archive.org does is a positive IMHO.  So far we don't have a conclusion on the language.

OH ANOTHER THING: we need a link to My Shots, i.e., the equivalent of what this accomplishes:

![image](https://cloud.githubusercontent.com/assets/44390/16433747/674af6d6-3d51-11e6-9273-7e33be15c563.png)

**Comment by TLHuang** [comment]
![option_1](https://cloud.githubusercontent.com/assets/4092794/16554891/4b5540a0-4204-11e6-99e0-cb89c6d22645.png)
Here is a proposal which is following the panel style on Firefox desktop. On my perspective, keep using the same components like panels is a benefit to our users, they might have the mindset that opens up a panel to do something. When the users don't need it, just tap on the area outside of the panel and it collapses automatically. 

For the link to My Shots, now it's on the bottom of the panel and renamed as Show All Shots. Also, I modified the item name Selections to Region and Visible to Window, based on some screen captured software, but it's just an option and we can still discuss this.

The last thing is the icon for Code function, it seems the draft one might be confused with Text copy or something, so I tried to come out another proposal and would like to have some feedbacks. Thank you!

**Comment by TLHuang** [comment]
![option_2](https://cloud.githubusercontent.com/assets/4092794/16556919/4e39ad78-420f-11e6-9090-5bca1feb75e2.png)
![option_3](https://cloud.githubusercontent.com/assets/4092794/16556920/4e3bbc1c-420f-11e6-82b7-242fb5f25422.png)
There are the other proposals which are following the initial design. Showing the menu in the middle of the screen could let the users easily find it, but it will need more hints like transitions to tell the users where it comes and how to open it again.

**Comment by ianb** [comment]
Some (unstructured) thoughts:

In user testing we got positive feedback on the specific term "My Shots", so I'd want to keep that.  (We do potentially have a rebranding coming up, but I'd be sad if we lost the term "shot".)  I also am presuming that clicking on it will open a new tab with My Shots, and so maybe it should look like a navigational element (e.g., with an underline).  Maybe a good phrase would be "Open My Shots"

I have a (perhaps irrational) dislike of panels, but I don't *hate* the panel you propose, it's definitely nicer with big buttons and images than it would be with plain text menu items.

One issue we've seen with Hello is that we get a huge drop in users between clicking the Hello icon and engaging with Hello, and I blame some of that on how fleeting and non-committal panels are.  Of course it's possible (likely?) the user didn't actually want to engage with the tool despite clicking on the button, but we're making it really easy for them to escape the experience.  By taking over the content we're putting them in an obviously modal situation, where there's clear next steps, and to escape they have to take a specific action (there should be a "cancel" option somewhere).

Another positive part of taking over the page is that we have a lot of room for FTU if we choose.

Also it's very obvious that the actions apply to *this* page.  A downside is that "Open My Shots" *doesn't* apply to this page and so it seems weird, while it seems very normal in a panel.

Re: "Window" – we're taking a shot of the content portion of the page only, and not the chrome.  This could be confusing?  I doubt most people would even want a shot of the entire window (with non-focused tabs, bookmark toolbar, etc), but it might not be clear.  But I agree "visible" isn't very good either, and Window feels like a better attempt.  People will figure it out once they use it.  

I can see the blue dashes *inside* the window chrome in the icon, but they are so small I didn't notice them until I looked closely.  I like the way you did it in the panel with a solid blue rectangle, I think the differences pop out better.

We need to think of some better way to talk about the DOM Copy.  I don't like `</>` as it alludes to HTML, which makes it feel like a coder tool, and the user will never actually see HTML.  I think my preferred description is "Full page archive", but how do we represent that visually?  An [article icon](https://www.google.com/search?q=article+icon&tbm=isch)?  Makes it feel more like a "page" and less like an "image":

![image](https://cloud.githubusercontent.com/assets/44390/16597460/9b136b8e-42be-11e6-8616-700fd2c0804f.png)

**Comment by fzzzy** [comment]
What's coming to mind for me is a paste pot and brush, and scrapbook. But I'm not sure how well that would translate into an icon.

**Comment by TLHuang** [comment]
I can change to “Open My Shots”, that's very easy to understand. As you mention, it will open a new tab with My Shots when you click that button, and we already have this pattern in Firefox. You can see the menu panel as reference, tap on the hamburger icon and then go to 'open sync preferences’. Maybe I can try to add an icon beside My Shots as a hint.

For your concern from Hello experience, I can understand it’s frustrated that the panel disappears immediately when you click somewhere else on the screen but you don’t mean to close the panel. 

However, the behaviour on PageShot is a quite different with Hello. In PagesShot, the users don’t need to do complex tasks, for example login or turn off notifications, all they need is click one function either capture a Region or open My Shots, then the mission of panel is done. That’s why I think using panel is suitable for PageShot. Also, we should carefully use blocking the whole screen, because it will interrupt the things that users is doing and force the users to look at it, sometimes people might feel annoying. I will consider using that when the thing is really important and will effect the users. Does it make sense?

I agree that the icons which using a solid blue rectangle look better, and yes, the code icon didn't present the idea well right now. I finally get the idea of archive the full page, I will keep exploring a better way. Thank you for the references.

**Comment by ianb** [comment]
> That’s why I think using panel is suitable for PageShot. Also, we should carefully use blocking the whole screen, because it will interrupt the things that users is doing and force the users to look at it

That's exactly why I think we should block the whole screen: if the user wants to use PageShot, then they should use PageShot right after hitting the button, or else they should hit Cancel.  There's no other action, and there's no reason to multitask between reading the page and using PageShot.  You do need to look at the page when making a selection, but we have a different interface for that.

**Comment by TLHuang** [comment]
> We need to think of some better way to talk about the DOM Copy. I don't like </> as it alludes to HTML, which makes it feel like a coder tool, and the user will never actually see HTML. I think my preferred description is "Full page archive", but how do we represent that visually? An article icon? Makes it feel more like a "page" and less like an "image":

There are some concepts around the DOM Copy icon; please take a look at the image I attached. The idea is to show the page is cached, and the image and texts are still selectable. Personally, I prefer the first one on the left, which looks simpler. I also tried to put it with the other icons and see how they work.

![cached page options](https://cloud.githubusercontent.com/assets/4092794/16724579/fc78c18c-4785-11e6-8c7e-4b5b325e0c0f.png)

![panel style-2](https://cloud.githubusercontent.com/assets/4092794/16724580/fc7c9528-4785-11e6-8fca-31f7c7bf302c.png)

As I know we haven't had a conclusion about the name of this function, so I temporarily name it as Cached Page, just want to keep the name shorter, but feel free to share your thoughts.

**Comment by ianb** [comment]
Yeah, the folder/arrow is a great metaphor, also my favorite.  Reminds me of my parents printing out web pages and saving them in piles ;) – which is basically a way to achieve the same thing we're doing with PageShot.  I think we have a design!

**Comment by brampitoyo** [comment]
Awesome, @TLHuang. I think we’ve found a few visual metaphors that really suited this feature.

How do we know that they’re good?

Test Pilot or Heartbeat will help us perform some comprehension test. If we show this mockup to testers and ask them what each icon + text will do, we can then select the combination that’s the most understandable.

I personally like the second one because the window chrome makes it look less like a picture and more like an “app”. I also like the fourth one because it evokes a paper metaphor: you print something, then you save it into a physical container. Really, any of these four options can work.

#### Panel vs. overlay

##### Panel is easy

* More Firefox-y. It looks standard, like it belongs with the rest of the browser.
* Easy to dismiss. You can argue that it’s not prominent enough.
* If you misclick, the consequence isn’t that high. Just click elsewhere.

##### Overlay is hard

* Less Firefox-y
* Hard to dismiss
* If you misclick, the page will darken and you may be confused:
  * What just happened? An overlay just showed up and I have no idea what it is
  * How do I go back to normal?
  * Is this a part of the webpage itself, or something separate?
  * It looks like [an overlay banner ad](http://exitintent.org/static/exit-popup-case-studies/bloggetroostercomwpcontentuploads201502oneclassexitpopuppng-f8e2f01c1076aa813e0d2078dabbd830.png). I should uninstall it.

What Helen has done was to improve the overlay dialogue so it looks more native.

Here are a few more suggestions I would make:

* The proposed design already looks like a Firefox dialogue. Can we make it look even more Firefox-y? For example, when you mouseover or click an icon, it should have a light grey outline [like a Firefox list item](http://firefoxux.github.io/StyleGuide/#/components/panels).
* The big cancel button makes it easy to dismiss. This is an improvement over my previous design. The user user can also click anywhere on the darkened area to quit
* In order to make it look less like a site overlay or a banner ad, explore some different solutions:
  * Try adding a logo to the overlay (I’m concerned that a logo will make the interface busy – see if it still looks good)
  * Try making the background a blur (can we do this with CSS filters?) or a different colour (maybe use white instead of black)

Does this help?

**Comment by TLHuang** [comment]
Thanks everyone for your positive feedback about the icons. I can't decide which one is the best option for the users, so like Bram said, we can do comprehension tests.

Thanks Bram! I totally agree with what you said, and you mentioned 

> It looks like an overlay banner ad. I should uninstall it.

That is the thing I'm worried about. Besides, the panel looks standard, and it would be easier if Firefox integrates PageShot as default function one day.

**Comment by TLHuang** [comment]
Upload the icons, just in case they will be needed for the testing.

[issue1911 images.zip](https://github.com/mozilla-services/pageshot/files/393311/issue1911.images.zip)
