### ISSUE TITLE
Remove 3rd party code?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1196]
Re: https://github.com/mozilla-services/pageshot/tree/master/static/homepage/js

Not sure if we want to remove those files and use something like Bower for the front-end dependencies.
That way we don't have 3rd party code in the repo (at the expense of having another build tool).

**Comment by ianb** [comment]
The homepage is kind of hacked together, I'd want to wait until we have some alternate plan for the homepage before worrying about that.  Note everything under `homepage/` is strictly for https://pageshot.dev.mozaws.net/, not any of the inner pages.

**Comment by fzzzy** [comment]
One technique I have used in the past is to require the static files in the package.json (assuming there is an npm package with those files) and symlink to where npm will install them from homepage/

**Comment by ianb** [comment]
Note #1253

**Comment by ianb** [comment]
This has all been cleared out with the new homepage design.
