### ISSUE TITLE
Verify Travis-CI is working

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1203]
My recent PR (and earlier PRs) passed with flying colors, but it looks like there was some JPM `EACCES` error in the Travis-CI logs which sounds super suspicious &mdash; although the build still exited with a status code of `0`.

```
...
JPM [info] Inject bootstrap.js and install.rdf in /tmp/jid1-NeEaf3sAHdKHPA@jetpack-0.1.0.xpi
JPM [info] Creating updateRDF...
JPM [info] Created XPI at /tmp/jid1-NeEaf3sAHdKHPA@jetpack-0.1.0.xpi
JPM [info] Creating a new profile
JPM [info] Using temporary profile at
JPM [info]     /tmp/ab6b8217-89d5-46af-a7f0-6fed4bbfe314
JPM [error] Error: spawn EACCES
The command "pwd && ls && cd $TRAVIS_BUILD_DIR/build/addon && jpm test -v" exited with 0.

Done. Your build exited with 0.
```

**Comment by pdehaan** [comment]
Not sure if JPM or Firefox is to blame for the random `EACCES` error in Travis-CI logs, but this may be interesting: https://docs.travis-ci.com/user/firefox/

Reminded me of [**activity-stream**'s .travis.yml file](https://github.com/mozilla/activity-stream/blob/a7bae6d626985da6b2b28e3f3109250fafa87c6e/.travis.yml#L13-L14), which has the following:

```yaml
addons:
  firefox: "46.0"
```

May enable us to get rid of our various **mozilla-download** dependency tweaks in our [.travis.yml file](https://github.com/mozilla-services/pageshot/blob/5f258326797770a1db5a10a85a44da5c472bd1e9/.travis.yml#L19):

```yaml
before_script:
  - npm install -g jpm mozilla-download
  - npm install
  - make all
  - cd ..
  - mozilla-download --branch mozilla-central --product firefox firefox
  - export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
  - cd $TRAVIS_BUILD_DIR/
```

**Comment by fzzzy** [comment]
I think this was fixed by https://github.com/mozilla-services/pageshot/pull/1267
