### ISSUE TITLE
Upgrade to newer version of Node?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1204]
Currently our Docker and Travis-CI seems to specify we're using Node 0.12 (which is super old).

According to https://github.com/nodejs/LTS#nodejs-long-term-support-working-group, it looks like 0.12 is in "maintenance" support, which ends 2016-12-31 (5 months).
We could switch to the current LTS release, Node v4, which has support up until **2018-04-01**, or switch to the active release, Node v6, which has support up until **2019-04-01**.

**Comment by ianb** [comment]
I've updated my local copy of Node to 6.2.1, and it's working fine (after upgrading Babel).  So probably all we have to do is update the some of the build pieces to use a newer version.

**Comment by fzzzy** [comment]
I also switched to 6 locally. I vote 6.

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla-services/pageshot/pull/1284
