### ISSUE TITLE
Consider something to A/B test

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1208]
If we don't have any A/B tests, we then don't have the capacity to add A/B tests (in terms of reporting and cohort selection).  Can we do an A/B test up-front to make sure we can quickly do them later?

**Comment by wresuolc** [comment]
Test Pilot is hoping to do the heavy lifting for this in https://github.com/mozilla/testpilot/issues/477

**Comment by ianb** [comment]
Let's start with A/B(/C) testing the DOM Copy button (e.g., "Code", "Full Page Archive", "Copy Page", etc).  We might also want to A/B test the presence of "EXPERIMENTAL" on that button as well.

**Comment by ianb** [comment]
Note we'll have to do some metrics work of our own, to get the A/B status into Google Analytics.
