### ISSUE TITLE
Add commit and build information to /__version__ route

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1215]
Currently we have the following information from the PageShot [`/__version__`](https://pageshot.dev.mozaws.net/__version__) route:

```json
{
  "commit": "",
  "source": "https://github.com/mozilla-services/pageshot/",
  "version": "June 24, 2016 21:09:13 UTC"
}
```

It'd be nice to have the exact commit and possibly the Circle-CI `build` number or whatever. Here's the information we get from the [Test Pilot `/__version__`](https://testpilot.firefox.com/__version__) route in prod:

```json
{
  "build": "https://circleci.com/gh/mozilla/testpilot/506",
  "commit": "ac480a9bea2be7fb0c7e866a4274cdd9945c719a",
  "source": "https://github.com/mozilla/testpilot",
  "version": "2016-06-09"
}
```

More details of the `/__version__` endpoint can be found in the [**Dockerflow** Version Object](https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md) document.

**Comment by fzzzy** [comment]
The commit field was fixed last week; the test is a nice to have that I don't think we will get done for the first launch.
