### ISSUE TITLE
A few warnings from addons-linter

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1219]
Nothing really surprising or actionable given the complexity of the add-on, but probably worth filing the current output here for future reference, or in case we want to maybe try integrating the **addons-linter** flow into our Travis-CI/Circle-CI testing (to make sure we don't have any errors or anything).

### Steps to reproduce:

```sh
$ make xpi
$ npm i addons-linter -D
$ ./node_modules/.bin/addons-linter ./build/mozilla-pageshot.xpi -o text
```

### Actual results: 

> #### Validation Summary:
> 
> errors:          0
> notices:        0
> warnings:        11

> #### WARNINGS:

> | Code | Message | Description | File:Line:Column |
> |------|---------|-------------|------------------|
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/headless.js:35:1
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/is-public.js:2:18
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/helperworker.js:19:1
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/multiclip.js:3:14
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/main.js:20:1
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/main.js:21:15
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/notificationbox.js:74:14
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/notificationbox.js:79:19
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/randomstring.js:1:29
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/screenshot.js:4:1
> | `LOW_LEVEL_MODULE` | Usage of low-level or non-SDK interface | Your add-on uses an interface which bypasses the high-level protections of the add-on SDK. This interface should be avoided, and its use may significantly complicate your review process. | lib/user.js:1:727

**Comment by ianb** [comment]
Each of these represents a specific choice we made to use a non-SDK library (e.g., FxA, UITour, high-quality random numbers, custom XUL and stylesheets, cookies clearing, rich clipboards).

WONTFIX for now, even if we have a record.  Though we could consider removing some UITour references, which I don't think we are making use of.

**Comment by fzzzy** [comment]
Can we break these out into bugs for things that we can address? We should remove uitour at least, and look into whether there are sdk equivalents for any of the things we still use. Also, perhaps bugs should be filed against the add-on sdk for any functionality we still require that does not have a high level equivalent?
