### ISSUE TITLE
My Shots page text is hard to read (white on gray)

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1220]
After going to https://pageshot.dev.mozaws.net/shots (with no saved Shots), I noticed that there was actually some white text against an impossibly contrasted gray background.

![my_shots](https://cloud.githubusercontent.com/assets/557895/16632607/bdc929fa-4379-11e6-8702-4ea787824751.png)

![my_shots](https://cloud.githubusercontent.com/assets/557895/16632622/d7aa8f94-4379-11e6-9878-45bbcf30db47.png)

**Comment by ianb** [comment]
One of the last items on #1098 is to specify how the empty search result should look.  I literally forgot we even had text (because I also couldn't see it).

**Comment by ianb** [comment]
Closing because we'll fix this in #1098
