### ISSUE TITLE
Blank page after clicking background on Shot details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1221]
Found in https://pageshot.dev.mozaws.net/__version__:

```json
{ "source": "https://github.com/mozilla-services/pageshot/",
  "version": "June 24, 2016 21:09:13 UTC",
  "commit": "" }
```

---

### Steps to reproduce:

1. Install PageShot and take a snapshot of the testpilot.firefox.com page (or whatever, but your snap should be small &mdash; not full page).
2. Click on the black background.

### Actual results:

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/16633125/911ea6a2-437c-11e6-96e8-28806d8666ff.png)
**Figure 1:** Before.

---

![firefox_test_pilot](https://cloud.githubusercontent.com/assets/557895/16633163/c751d456-437c-11e6-8d23-1005ad955e30.png)
**Figure 2:** After.

---

~~The details seems to have a React warning (even before clicking anything) saying:~~

> _~~Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:~~_
>
> - ~~(client) firefox.com</a><img height="16" width="1~~
> - ~~(server) firefox.com</a><img style="margin-right:~~

**UPDATE:** This looks like it was already reported in #1107.

**Comment by fzzzy** [comment]
Yes, this is an issue. If you hit "save full page", clicking outside the clip will reveal the full page behind it. But you shouldn't be able to hide the clip if the full page was not saved.

**Comment by ianb** [comment]
@pdehaan: do you have the URL of the shot you took?

**Comment by pdehaan** [comment]
I just took the homepage of https://testpilot.firefox.com, but the URL of the Shot is: https://pageshot.dev.mozaws.net/dC1rhJdEeuWbwwCP/testpilot.firefox.com
