### ISSUE TITLE
A few 404s when viewing my saved full screen Shots

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1222]
Found in https://pageshot.dev.mozaws.net/__version__:

``` json
{ "source": "https://github.com/mozilla-services/pageshot/",
  "version": "June 24, 2016 21:09:13 UTC",
  "commit": "" }
```

---
### Steps to reproduce:
1. Install add-on and take a full page snap of https://www.npmjs.com/package/yargs
2. View the Shot on PageShot (https://pageshot.dev.mozaws.net/d6SGrgCiW86R9oM0/www.npmjs.com)
3. Open your DevTools console.
### Actual results

![yargs](https://cloud.githubusercontent.com/assets/557895/16633770/a44b2996-437f-11e6-8218-e4b85bed44ab.png)

Since we're seemingly "serving" the content from https://pageshotcontent.dev.mozaws.net/, I'm guessing it may flood our HTTP logs and show as 404s.
My guess here is that the assets on npmjs.com are just relative and not fully qualified.

![yargs](https://cloud.githubusercontent.com/assets/557895/16633874/139ec94c-4380-11e6-9831-d0a5d5b83185.png)

Not sure how easy of that is to fix, but I guess the flip side of the coin is that we could add the external domain to any URL which starts with "/{path}" or prefix "https:" to any url starting with "//{domain}/{path}", although if the external content loads HTTP content from our HTTPS site, we may get ugly CORS errors in the console.

**Comment by ianb** [comment]
Using the inline CSS functionality, it tries to rewrite these URLs.  I wonder with that pref on that this would work?
