### ISSUE TITLE
Unexpected behavior when searching saved Shots

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1223]
Found in https://pageshot.dev.mozaws.net/__version__:

```json
{ "source": "https://github.com/mozilla-services/pageshot/",
  "version": "June 24, 2016 21:09:13 UTC",
  "commit": "" }
```

---

### Steps to reproduce:
1. Install the add-on and take a few Shots. (I have shots for https://testpilot.firefox.com/ and https://www.npmjs.com/package/yargs)
2. Go to your https://pageshot.dev.mozaws.net/shots page.
3. Type (slowly): `n`, `p`, `m`

### Actual results:
![my_shots](https://cloud.githubusercontent.com/assets/557895/16634137/40ae3c50-4381-11e6-8beb-a6d865228064.png)
![my_shots](https://cloud.githubusercontent.com/assets/557895/16634147/47a25a96-4381-11e6-9b07-941979df48c4.png)
![my_shots](https://cloud.githubusercontent.com/assets/557895/16634154/4d670f6c-4381-11e6-935d-2518e5e4c9a3.png)

For some reason, my "npm" result shows on "n" and "npm" but not "np".
For other reasons (probably same reason), my "firefox test pilot" result only shows up when I type "firefox" and not "f", "fi", "fir", "fire", "firef", or "forefo".

**Comment by ianb** [comment]
We're using PostgreSQL's built-in full text search, which tokenizes all the words, and so it doesn't handle partial results.  But this has caused problems for me in practice.

We add the URL to the search terms, but we really could do a LIKE query instead of just a full text query, at least on the URL and title.  I think that would cover a lot of these cases.

**Comment by pdehaan** [comment]
Oddly, trying to search for "firefox tes" unleashed the hounds of hell, and started returning HTTP/500 errors.

![my_shots](https://cloud.githubusercontent.com/assets/557895/16634283/cde5bed6-4381-11e6-98ac-639e41244ecb.png)

---

> Error refreshing: 500 XMLHttpRequest { onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "https://pageshot.dev.mozaws.net/sho…", status: 500, statusText: "Internal Server Error", responseType: "", response: "Error rendering page: error: syntax…" }1shotindex-bundle.js:39:7

Trying to see that `responseURL` gives me this: https://pageshot.dev.mozaws.net/shots?data=json&q=firefox%20t

> Error rendering page: error: syntax error in tsquery: "firefox t"

**Comment by ianb** [comment]
I'm now getting `Error rendering page: error: remaining connection slots are reserved for non-replication superuser connections` which sounds like Postgres is down?

**Comment by fzzzy** [comment]
Sounds like we're not putting the postgres connection back in the pool on an error.

**Comment by pdehaan** [comment]
I'm getting the same error (and really hoping I didn't DDoS our Postgres instance with some query string hackery).

**Comment by ianb** [comment]
Connection problem noted in #1231 

Putting this in Next Tasks, since I don't think we'll adjust the search for the first release.

**Comment by ianb** [comment]
Due to our new substring matching on title and url, this is fixed
