### ISSUE TITLE
The version of Tabzilla you are using is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1224]
### Steps to reproduce:
1. Go to https://pageshot.dev.mozaws.net/
2. Open Developer Tools' "Console" tab.

### Actual results:

> "The version of Tabzilla you are using is deprecated and will be removed in the future.
> Please update to the new static version here: https://github.com/mozilla/tabzilla/"

**Comment by pdehaan** [comment]
You can install Tabzilla via npm: https://www.npmjs.com/package/mozilla-tabzilla (and include the CSS/Sass fairly easily).

But a major reason to kick the deprecated Tabzilla to the curb is that we currently show a big banner for the -moz-gear-store, which has since been deprecated itself.

🐢
🐢
🐢

**Comment by fzzzy** [comment]
The homepage will be replaced by a homepage hosted by Test Pilot and will probably be completely rewritten for that, so we probably don't have to do anything here.

**Comment by ianb** [comment]
I'm not sure we want to replace the homepage entirely with a Test Pilot homepage.  I never liked how hello.firefox.com redirected, and I'm not that comfortable with doing the same to PageShot.

**Comment by ianb** [comment]
See also #1253

**Comment by ianb** [comment]
This got removed from the homepage.
