### ISSUE TITLE
PageShot homepage prompts to install add-on in Firefox even though already installed

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1225]
Not sure if we should re-prompt to [Install] the add-on if it's already installed, or if we should try and detect if the add-on is installed and instead redirect them to https://pageshot.dev.mozaws.net/shots

![pageshot](https://cloud.githubusercontent.com/assets/557895/16637132/b5e5715e-4391-11e6-9758-12ab9ffe7f05.png)

**Comment by ianb** [comment]
Also depends on #1253

**Comment by ianb** [comment]
I don't think we'll have the install button on the homepage anymore, instead you'll have to go through Test Pilot, which presumably knows how to check this.
