### ISSUE TITLE
Passing empty `rev` key to asset URLs

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1226]
### Steps to reproduce:
1. Install add-on
2. Go to https://pageshot.dev.mozaws.net/shots

### Actual results:

We seem to be almost passing a `rev` to a bunch of of the assets, but the value is blank. I assume this is some sort of cache-buster URL (which we aren't busting):

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>My Shots</title>
    <link rel="shortcut icon" href="/static/img/pageshot-icon-32.png?rev=">
    <script src="/static/js/shotindex-bundle.js?rev="></script>
    <link rel="stylesheet" href="/static/css/shot-index.css?rev=">
  </head>
  <body>
    ...
  </body>
</html>
```

**Comment by fzzzy** [comment]
This is a dup of https://github.com/mozilla-services/pageshot/issues/1120
