### ISSUE TITLE
Switch to Gulp/Grunt instead of Bash-themed scripts and Makefile?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1228]
It looks like we have some pretty hefty and OS-specific ./bin/ scripts and ~315 line Makefile.
Not sure if it's worth it to convert the majority of that a bit more beginner friendly tool like Gulp or even Grunt so it has better cross platform support.
May just depend on if we think we'll have external contributors who'd need to use these tools or not.

**Comment by ianb** [comment]
We used to use Gulp, maybe event Grunt a long time ago?  I really disliked them.

Webpack *maybe*, but having used it on a different side project I'm not too impressed with it either.  Makefiles have staying power.
