### ISSUE TITLE
Review all FIXMEs

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1229]
Ref: https://github.com/mozilla-services/pageshot/issues/1195#issuecomment-231197375

```sh
$ grep -irn "FIXME" . --exclude-dir={build,node_modules,vendor}
```

(Not a great `grep` as it doesn't handle multi-line comments, but hey...)

---

- [x] ./addon/data/annotate-position.js:8:      `// FIXME: not sure if this is a reasonable fallback`
- [ ] ./addon/data/extractor-worker.js:55:    `// FIXME: location.href isn't what Readability expects (but I am`
- [x] ./addon/data/extractor-worker.js:95:      `// FIXME: handle relative links`
- [ ] ./addon/data/framescripts/make-static-html.js:100:    `// FIXME: utf8?`
- [ ] ./addon/data/framescripts/make-static-html.js:116:  `// FIXME: this is a global that is reset on each run, and then added to by`
- [ ] ./addon/data/framescripts/make-static-html.js:126:      `// FIXME: not sure if resources should ever have funny protocols?`
- [ ] ./addon/data/framescripts/make-static-html.js:227:    `// FIXME: should we skip contextmenu, since the menus can't do anything?`
- [ ] ./addon/data/framescripts/make-static-html.js:247:    `// FIXME: should check that hidden elements are skipped`
- [ ] ./addon/data/framescripts/make-static-html.js:288:    `// FIXME: is seamless actually a thing?`
- [ ] ./addon/data/framescripts/make-static-html.js:361:    `// FIXME: not sure what elements this can be on`
- [ ] ./addon/data/framescripts/make-static-html.js:437:      `// FIXME: I'm not sure why this happens, but when it does we can't serialize`
- [ ] ./addon/data/framescripts/make-static-html.js:467:      `// FIXME: just haven't enumerated svg attributes`
- [ ] ./addon/data/framescripts/make-static-html.js:558:            `// FIXME: doesn't respect <base href>`
- [ ] ./addon/data/framescripts/make-static-html.js:788:        `// FIXME: these should be included except with the appropriate media restriction`
- [ ] ./addon/data/framescripts/screenshot.js:8: `// FIXME: this is a hack to take a shot of the iframe in the viewer`
- [x] ./addon/data/selector-snapping.js:20:      `// FIXME: some objects aren't visible, and should be excluded`
- [ ] ./addon/data/selector-snapping.js:42:    `// FIXME: should probably make sure all page edges are in the list`
- [x] ./addon/data/selector-ui.js:11:  `// FIXME: I guess this is disabled because it doesn't work well?`
- [ ] ./addon/data/selector-ui.js:23:    `// FIXME: I can't decide when this is necessary`
- [ ] ./addon/data/shooter-interactive-worker.js:309:        `// FIXME: not sure if this is useful:`
- [ ] ./addon/data/shooter-interactive-worker.js:466:  `// FIXME: maybe annotating based on the corners is a bad idea,`
- [x] ./addon/data/viewerworker.js:90: `// FIXME: not sure if this might mess up an in-content onerror handler, though I suppose`
- [x] ./addon/lib/errors.js:105:    `Also watches any promise returned by the function (FIXME: probably it`
- [ ] ./addon/lib/helperworker.js:108:      `// FIXME: we aren't using this, but it does allow richer clipboard access`
- [x] ./addon/lib/main.js:95:        `// FIXME: the label and the identifier for this button are conflated`
- [ ] ./addon/lib/multiclip.js:49:  `// FIXME: we are using null instead of a sourceWindow.  Not sure how to handle`
- [ ] ./addon/lib/multiclip.js:61:  `// FIXME: figure out images`
- [ ] ./addon/lib/shooter.js:110:      `// FIXME: determine if the notification box is just automatically hidden in this case`
- [ ] ./addon/lib/shooter.js:114:      `// FIXME: determine if the notification box is just automatically hidden in this case`
- [ ] ./addon/lib/shooter.js:204:      `// FIXME: there shouldn't be this disconnect between arguments to captureTab`
- [ ] ./addon/lib/shooter.js:279:        `// FIXME: maybe pop up an explanation here?`
- [ ] ./addon/lib/shooter.js:514:      `// FIXME: maybe pop up an explanation here?`
- [ ] ./bin/_set_package_version:8:    `# FIXME: try to make a unique less date-oriented version number`
- [ ] ./bin/start-server.sh:6: `# FIXME: should move all these into env.production:`
- [ ] ./chrome-extension/background.js:87:    `// FIXME-chrome: need to figure out the reason the extension was created`
- [ ] ./chrome-extension/background.js:140:      `// FIXME: give proper reason`
- [ ] ./chrome-extension/chrome-shooter.js:28:    `// FIXME: check if page is private:`
- [ ] ./chrome-extension/chrome-shooter.js:113:        `// FIXME: should figure out a way to wait for saveShotFullPage to complete/succeed before continuing:`
- [ ] ./chrome-extension/site-helper.js:36:  `// FIXME: implement`
- [ ] ./Makefile:65: `# FIXME: obviously this is a tedious way to describe these:`
- [ ] ./Makefile:159: `# FIXME: unsure if this is relevant, given other rules:`
- [x] ./Makefile:175: `# FIXME: not sure what purpose this has, given _set_package_version`
- [ ] ./server/src/clientglue.js:105:      `// FIXME: a lame way to do an error message`
- [x] ./server/src/contentcheck.js:27:      `// FIXME: working around a bug in domino: https://github.com/fgnass/domino/issues/53`
- [ ] ./server/src/contentcheck.js:39:  `// FIXME: should confirm <base href> is correct`
- [ ] ./server/src/db.js:41: `// FIXME: make these so they don't need to be exported`
- [x] ./server/src/exporter.js:55:    `// FIXME: I don't think an exception here will reject`
- [x] ./server/src/linker.js:5: `// FIXME: move this to server.js or somewhere else, so git-rev doesn't get included in the bundle`
- [ ] ./server/src/pages/admin/server.js:9: `// FIXME: this should be an FxA id, but due to a bug we're using device IDs`
- [ ] ./server/src/pages/admin/server.js:27:    `// FIXME: terrible workaround for fxa account not being stored:`
- [x] ./server/src/pages/shotindex/controller.js:26: `// FIXME: this works, but we don't have a way to know when to trigger the refresh`
- [ ] ./server/src/pages/shotindex/view.js:87:    `// FIXME: this time limiting may not be right`
- [ ] ./server/src/reactrender.js:32:    `// FIXME: we should just inline the addReactScripts functionality in this function:`
- [ ] ./server/src/reactruntime.js:9:    `// FIXME: this should probably include some standard CSS or other boilerplate`
- [ ] ./server/src/reactruntime.js:10:    `// FIXME: should also include (at least optionally) GA`
- [ ] ./server/src/server.js:153:    `// FIXME: maybe a crude attempt to ensure some santization of parameters:`
- [ ] ./server/src/server.js:257:  `// FIXME: need to hash secret`
- [ ] ./server/src/server.js:376:    `// FIXME: this doesn't make sense for comments or other stuff, see https://github.com/mozilla-services/pageshot/issues/245`
- [ ] ./server/src/server.js:554:  `// FIXME: this just gets deleted due to ON DELETE CASCADE`
- [ ] ./server/src/server.js:565: `// FIXME: this can't the right way to do this...`
- [x] ./server/src/servershot.js:9: `// FIXME: need to sometimes look for anything that has the wrong version`
- [ ] ./server/src/servershot.js:375: `// FIXME: What is the difference between Shot.getFullShot and Shot.get?`
- [x] ./server/src/servershot.js:692:  `// FIXME: active shots with no clips appear to be 404, but all deleted shots have`
- [ ] ./server/src/views/frame.js:16:    `// FIXME implement analytics tracking here`
- [ ] ./server/src/views/frame.js:111:    `// FIXME: totally hacky way to handle this,`
- [ ] ./server/src/views/frame.js:401:    `let shotDomain = this.props.shot.url; // FIXME: calculate`
- [ ] ./server/src/views/frame.js:680:    `// FIXME: save the value that it was changed to?  Yes!  Not sure where to put it.`
- [ ] ./server/src/views/frame.js:762:    `shotDomain: req.url, // FIXME: should be a property of the shot`
- [ ] ./server/src/views/frame.js:828:    `shotDomain: req.url // FIXME: should be a property of the shot`
- [ ] ./shared/shot.js:20:  `// FIXME: this is rather naive, obviously`
- [ ] ./shared/shot.js:88:  `// FIXME: totally ad hoc and probably incorrect, but we can't`
- [ ] ./shared/shot.js:154:  `// FIXME: not a proper uuid`
- [ ] ./shared/shot.js:491:  `// FIXME: no delete, nor comment editing`
- [ ] ./shared/shot.js:493:  `// FIXME: deprecate`
- [ ] ./shared/shot.js:541:    `// FIXME: we shouldn't support both openGraph.title and ogTitle`
- [ ] ./shared/shot.js:815:  `// FIXME: either we have to notify the shot of updates, or make`
- [ ] ./shared/shot.js:838:  `// FIXME: either we have to notify the shot of updates, or make`
- [ ] ./shared/shot.js:865:  `// FIXME: either we have to notify the shot of updates, or make`
- [ ] ./static/css/panel.scss:22:  `/* FIXME: it seems like any font attribute can be set to -moz-use-system-font,`
- [ ] ./static/css/panel.scss:25:  `/* FIXME: currently font-family: -moz-use-system-font results in a serif`
- [ ] ./static/css/profile.scss:50:  `// FIXME: when 100%, it goes over the padding of the .panel, making it not`
- [ ] ./static/css/shot-index.scss:1: `// FIXME: need to include these from a single location:`
- [ ] ./static/css/shot-index.scss:69:      `// FIXME: check border radius`
- [ ] ./static/css/styles.scss:340:  `/* FIXME: ellipsis doesn't really work, because the end of the title is`
- [ ] ./static/css/styles.scss:602:  `// FIXME: copied from panel.scss .simplified-edit-button`
- [ ] ./static/homepage/help.html:22:      `<!-- FIXME: change color of image: -->`
- [ ] ./static/homepage/index.html:145:          `<!-- FIXME: figure out the main points, get images for each point -->`
- [ ] ./static/homepage/index.html:227:                `<li class=""><a href="https://twitter.com/FIXME" target="_blank">Twitter</a></li>`
- [ ] ./static/js/content-helper.js:72:    `// FIXME: adjust using height/width`
- [ ] ./static/js/content-helper.js:85:  `// FIXME: this doesn't seem to do the right thing, but I don't know why:`

**Comment by ianb** [comment]
I think this is all the FIXMEs we're going to fix for now, we can open a new ticket later (with up-to-date FIXMEs) if we want to do another review.
