### ISSUE TITLE
Check Postgres connection pooling

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1231]
We should do some load testing (even locally) and make sure that the PG connection pool doesn't exhaust itself.

**Comment by fzzzy** [comment]
If my reading of the docs is correct, we may not actually be using connection pooling right now. Unless we are using an older version where the pooling worked differently than currently described.

**Comment by ianb** [comment]
Fixed in 6a6993004da7fd94030d77d5943aba76f360befd (probably)
