### ISSUE TITLE
PageShot errors if you try and take a shot of Activity Stream

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1236]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/16747733/3bb7ce58-4775-11e6-8cf1-e471d8f405b9.png)

It seems like the [Activity Stream](https://github.com/mozilla/activity-stream) add-on hosts all of its pages internally as "resource://blah/blah/blah" and PageShot literally can't even. So it fails kind of hard and dumps all over the Browser Console with a big error.

Obviously that error door-hanger should be less ugly, and we should probably fail a lot nicer in these edgey edge cases.

![window](https://cloud.githubusercontent.com/assets/557895/16747585/82d6da5a-4774-11e6-9d24-32f7ee5c8d6e.png)

![browser_console](https://cloud.githubusercontent.com/assets/557895/16747599/9865b332-4774-11e6-9a23-6701165a186b.png)

**Comment by pdehaan** [comment]
Probably related (or maybe not, what do I know), but if I try and take a "Shot" of my Google homepage (about:blank) in Google Chrome extension, then nothing happens.
No errors, no warnings, no UI, no feedback of any sort.

**Comment by pdehaan** [comment]
Possibly dupe of #1125

**Comment by ianb** [comment]
See also #1167

**Comment by johngruen** [comment]
#1125
