### ISSUE TITLE
PageShot erases everything in my clipboard

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1237]
### Steps to reproduce:
1. Install PageShot add-on.
2. Copy some text into your clipboard.
3. "Shot" a page and then try and paste your **step 2** clipboard contents somewhere.

### Actual results:
Your clipboard contents from **step 2** are erased by **step 3**.

### Expected results:
Please don't erase my clipboard contents without my permission. I may have lost something valuable.

**Comment by ianb** [comment]
We've talked about having a "undo clipboard copy" somewhere, though I don't know where exactly it would go (notification popup?  Can we do that?)

**Comment by pdehaan** [comment]
It should be off by default, and either buried in about:addons preference, or probably just have a "Copy to Clipboard" button in the "My Shots" section where we already have [Save full page] [Share] and [Delete] buttons. One extra click by the user, but at least doesn't erase all that code I happened to be copy-pasta from Sublime Text, or whatever.

Actually, there is already a "Copy" button behind the Share dropdown, so it really is only 2 extra clicks for a user to copy/share the link if they need it.

![my_shots](https://cloud.githubusercontent.com/assets/557895/16748302/2bb662c8-4778-11e6-8698-8d8b9f3672dc.png)

**Comment by fzzzy** [comment]
Maybe we should pop open the share panel automatically so access to the copy button is only one more click away.

**Comment by ianb** [comment]
Let's stop the automatic copy, but open up the share panel immediately on page open:

![image](https://cloud.githubusercontent.com/assets/44390/16973887/2f089d84-4dfd-11e6-8b3f-9759252b6e07.png)

We have to make sure the yellow popup doesn't conflict with the share panel.
