### ISSUE TITLE
Audit information on Google Chrome Store

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1238]
Ref: #864

We probably want to make sure everything on the Google Chrome Store is kosher and aligned with what's on Test Pilot.

<img width="1007" alt="pageshot_-_chrome_web_store" src="https://cloud.githubusercontent.com/assets/557895/16748537/75e4a282-4779-11e6-9e5f-fadd1004223d.png">

&mdash; Via: https://chrome.google.com/webstore/detail/pageshot/flhjebpmjblnihhioankmibfdkdiaahi

**Comment by ianb** [comment]
FYI, the Chrome Extension is "hidden" – it won't show up in the store unless you find the link somewhere.

**Comment by pdehaan** [comment]
@ianb: Click the [Install] button on https://pageshot.dev.mozaws.net/ homepage and you get the Chrome extension.

**Comment by ianb** [comment]
Well yes, we publish the link there ;)  TBD for release

**Comment by ianb** [comment]
Closing since we're not going to publish under this name or in this style.
