### ISSUE TITLE
Inconsistent header height

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1243]
![hugo_-_front_matter](https://cloud.githubusercontent.com/assets/557895/16788991/41b46d86-485e-11e6-9ecc-2670db25901e.png)
**Figure 1:** When taking a Shot, the header is 38px high.

---

![hugo_-_front_matter](https://cloud.githubusercontent.com/assets/557895/16788932/c9ab0c28-485d-11e6-86ce-36a9afe17f7e.png)
**Figure 2:** When *viewing* saved Shots, the header is 65px high.

**Comment by brampitoyo** [comment]
We may be able to get @TLHuang’s help on making the two designs consistent. @ianb, what’s your thought?

Helen, for your reference, the ‘short’ 38px panel is what will appear when you choose “Selection”.

**Comment by fzzzy** [comment]
One thing we might not be able to do is change the 38px height, because it is a special chrome topbar that is specified in xul and hard to style. We might be able to change the height, but no promises.

**Comment by ianb** [comment]
The height is specified in our CSS file, it's already taller than the default height.

**Comment by fzzzy** [comment]
Ok good!

**Comment by TLHuang** [comment]
@brampitoyo Sure, I can help this. But it seems closed...?

**Comment by fzzzy** [comment]
@TLHuang I just made the chrome topbar the same size as the in-content topbar. This is what it looks like now:

![screen shot 2016-07-14 at 10 52 26 am](https://cloud.githubusercontent.com/assets/46048/16843944/31c444d8-49b1-11e6-8a76-4ad42c6bb3cc.png)
![screen shot 2016-07-14 at 10 52 39 am](https://cloud.githubusercontent.com/assets/46048/16843946/36083090-49b1-11e6-8aaf-cbab984c3804.png)

I think it looks fine, but if you want to make any more design changes just go ahead and reopen the bug

**Comment by TLHuang** [comment]
@fzzzy They look good to me! Thanks for letting me know.
