### ISSUE TITLE
Decide on what homepage should be

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1253]
We should consider what if anything should be on the homepage (currently https://pageshot.dev.mozaws.net)

**Comment by ckprice** [comment]
For the First Launch, we will not be linking to the homepage.

Pending question: what should we do if someone lands on pageshot.net?

**Comment by brampitoyo** [comment]
> what should we do if someone lands on pageshot.net?

Maybe we can send them to the Pageshot product page on Test Pilot?

**Comment by fzzzy** [comment]
John is going to create a simple static page that says something like "PageShot is now in Test Pilot."

**Comment by fzzzy** [comment]
This was fixed by https://github.com/mozilla-services/pageshot/pull/1333
