### ISSUE TITLE
Use `getAddonByID` to determine if Test Pilot is installed. Send a GA event if not.

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1256]

**Comment by ckprice** [comment]
Quick note that you can check that the Test Pilot add on is installed with [`unsafeWindow.navigator.testpilotAddon = true`](https://github.com/mozilla/testpilot/blob/master/addon/data/set-installed-flag.js#L11).

**Comment by fzzzy** [comment]
@ckprice I can't seem to get that to work. Even with the Test Pilot add-on installed, window.navigator.testpilotAddon is always "null". unsafeWindow.navigator.testpilotAddon is null also.

**Comment by ckprice** [comment]
DUH! There's a [whitelist of URL's](https://github.com/mozilla/testpilot/blob/669382791a4cd897d7b6bc11702dd2512007d806/addon/index.js#L58) that can use this function. So if you go to mozilla.org and use the command in the console, you should see it returning correct values.

I don't know exactly how that would work with your add-on.

**Comment by fzzzy** [comment]
Yes, I see that it does work from mozilla.org. Any idea what we should do to expose this info to the add-on?

**Comment by ckprice** [comment]
Hm, we use a [PageMod to set this flag](https://github.com/mozilla/testpilot/blob/669382791a4cd897d7b6bc11702dd2512007d806/addon/index.js#L101) which bases access on a set of URLs. I think this opens up some broader questions in general.

I'm going to level-set here and confirm that this is still a requirement for First Launch from legal.

**Comment by fzzzy** [comment]
@ckprice That sounds good. If we don't have to check for the test pilot add-on at first launch, then we avoid the whole issue. :)

**Comment by ckprice** [comment]
Elvin noted that since we are only distributing through the TP website, we can remove this check/action.

He did have a question of whether or not it was possible to determine if a lot of people started installing this outside of Test Pilot? @ianb @clouserw

**Comment by ianb** [comment]
I'm guessing we need to do something like this to figure out if it's installed: https://github.com/mozilla/testpilot/blob/821d5ee15d8bb8407e9903e1517178e3f0afd126/addon/lib/metrics.js#L151

We could send a GA event based on this.
