### ISSUE TITLE
Make the new browser chrome topbar look better

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1259]
With the new overlay panel ui, this is what the browser chrome topbar looks like:

![screen shot 2016-07-18 at 4 01 01 pm](https://cloud.githubusercontent.com/assets/46048/16928473/de9a64a6-4d00-11e6-937f-a195c42b2485.png)

We should probably give it a design makeover. (Bigger fonts?)

**Comment by brampitoyo** [comment]
@fzzzy How much can we style this bar? I recall hearing that we can’t really control the button style or text sizes?

**Comment by fzzzy** [comment]
It would be best for the code's sake if we could design a flow for this that didn't involve the chrome topbar.

**Comment by TLHuang** [comment]
Per discussion, we all agree to remove the topbar if possible. Here is the concept that has floating buttons around the selection area.

After clicking Region on the menu, It directly shows where the cursor is when entering Region Capture mode, and the instruction will be on top of the screen. Consider the users may move cursor before they read the sentence, I think to show the instruction next to the cursor is not a good idea.

![region capture](https://cloud.githubusercontent.com/assets/4092794/17134646/fcc15b7a-535d-11e6-8e8e-de498a519591.png)


When the user selects an area, the floating buttons will appear next to the ending point. If the cursor moves from top left to the bottom right, and the buttons will show on the bottom right. That's the basic rule. However, if there is no enough space for showing the buttons under the selection, then it shows on the bottom left instead. Please take a look at the mockups for different conditions, and let me know if any questions or concerns. Thank you!

![region capture - select an area 1](https://cloud.githubusercontent.com/assets/4092794/17135431/5c1bd10a-5362-11e6-8f3e-7ee8f2fa43d0.png)
![region capture - select an area 2](https://cloud.githubusercontent.com/assets/4092794/17135438/61bb1f3a-5362-11e6-8ca5-67d7ae7f7116.png)
![region capture - select an area 3](https://cloud.githubusercontent.com/assets/4092794/17135439/61fbfb9a-5362-11e6-9a21-769bf0523283.png)
![region capture - select an area 4](https://cloud.githubusercontent.com/assets/4092794/17135440/61ff01be-5362-11e6-87bb-3c97e5218540.png)

**Comment by johngruen** [comment]
Hi @TLHuang, @fzzzy and I discussed the UX here and there are a lot of edge cases with re-positioning the buttons relative to dragging. Could you provide a mock-up where the buttons have a fixed position near the top of the browser window? My thought here is that they might appear dimly as the user drags and then become fully opaque when the user releases a drag.

**Comment by TLHuang** [comment]
Hi @johngruen, Thanks for the feedbacks! Yes, I agree that the previous proposal with flexible buttons is much complicated, and have to consider where to show the buttons in different cases. If we aim to have fixed buttons, here are few concepts: 

・**Buttons on the top right of the browser window**: As the feedback, to have the buttons near the top of the window.

![region capture - select an area 3 1](https://cloud.githubusercontent.com/assets/4092794/17166528/09e7e1f0-540a-11e6-817a-52e3b3f6eb82.png)
![region capture - select an area 3 2](https://cloud.githubusercontent.com/assets/4092794/17166333/e30d51ba-5408-11e6-91cf-960cd4df9f77.png)

・**Buttons on the bottom center of the browser window**: Most users are used to select an area from top to bottom. To have buttons near the bottom of the browser window could make the process more smoothly.

![region capture - select an area 2 1](https://cloud.githubusercontent.com/assets/4092794/17166258/63d0b964-5408-11e6-8a48-25f0be447b2a.png)
![region capture - select an area 2 2](https://cloud.githubusercontent.com/assets/4092794/17166259/63d259e0-5408-11e6-9097-5e0cc1edd175.png)
![region capture - select an area 2 3](https://cloud.githubusercontent.com/assets/4092794/17166257/63ce87ca-5408-11e6-8197-6dd64165d25a.png)

Does it helpful?
