### ISSUE TITLE
Track down and expose silent errors

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#126]
In many cases when PageShot has an error the result is nothing happens.  Like you hit the shot button and it does nothing.  Or the selection tool works, but something breaks before the page is created and the panel comes up.

If we are light on testing (we certainly are now), we should try to be heavy on exposing our errors.

I propose some simple wrappers that can be used widely that catch errors.  These should catch exceptions and failed promises.  The error should show up on the console, but should also show up in the interface clearly.

We can use a decorator pattern for most of these, like:

```
const someFunc = catcher(function () {
    return promise;
});
```

It should notice Promise return values and also wrap those.  Though it might be problematic if we have resolvable errors in a promise, and the catcher puts in a noisy error handler.  I'm not sure if there's a way to add a error handler that only gets called if nothing else handles the error?  There might be other approaches as well.

Ideally we'd also give the catcher enough context to show something at least a little useful, but maybe starting with a bare error would be sufficient.

I worry that this will get really noisy, but if all we do is apply this catcher on an on-needed basis I think we'll get to a decent place fairly quickly.

**Comment by ianb** [comment]
I'm declaring victory, even though the battle is never truly over!

**Comment by kitcambridge** [comment]
It also looks like `Promise.jsm` exposes a [`Promise.Debugging` interface](https://dxr.mozilla.org/mozilla-central/source/toolkit/modules/Promise-backend.js#579) for observing uncaught errors...

```js
let {Promise: {Debugging: promiseDebugging}} = Cu.import('resource://gre/modules/Promise.jsm', {});

promiseDebugging.clearUncaughtErrorObservers();

promiseDebugging.addUncaughtErrorObserver(onPromiseError);
function onPromiseError({message, date, fileName, stack, lineNumber}) {
  // Report error.
}

promiseDebugging.flushUncaughtErrors();
```
