### ISSUE TITLE
Not showing favicons on Chrome?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1260]
https://pageshot.dev.mozaws.net/__version__

``` js
{ "source": "https://github.com/mozilla-services/pageshot/",
  "version": "July 15, 2016 00:24:59 UTC",
  "commit": "adceb6f" }
```

---

I just randomly noticed that in Firefox [Nightly] I get pretty little favicons next to most of the results on my /shots page, but I don't see them in Google Chrome.

![my_shots](https://cloud.githubusercontent.com/assets/557895/16929245/aa4ce7e2-4ceb-11e6-9fd9-6c88c74c413a.png)
**Figure 1:** PageShot in Firefox Nightly.

---

![my_shots](https://cloud.githubusercontent.com/assets/557895/16929259/bdc0228a-4ceb-11e6-94fb-fcb6fcd6f046.png)
**Figure 2:** PageShot in latest Chrome (Release channel).

**Comment by ianb** [comment]
We'll revisit this with the new WebExtension (which borrows from the Chrome extension, but is also a major rewrite)
