### ISSUE TITLE
Saved shots aren't shared between Firefox and Chrome

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1261]
Not really a "bug", per se, but definitely something that users may find a bit confusing if they use _both_ Firefox and Chrome add-ons.

I currently have PageShot installed in both Chrome [Release] and Firefox Nightly, but my saved shots aren't persistent between the two browsers (see https://github.com/mozilla-services/pageshot/issues/1260#issue-166186417). I can't think of a clean way to share them, apart from muddy the waters by forcing FxA integration so we can can assign to a specific user account (regardless of current browser).

But currently if I need to track down that one sweet Shot I took of a page, I need to go and search in 2 different browsers.

**Comment by brampitoyo** [comment]
I wonder if there’s a non-account solution we can use to solve this problem? Wild idea: when you have two versions of PageShot on the same browser or any browser, you can “connect” one to the other, and then it will be merged.

**Comment by ianb** [comment]
We have most of the login structure in the product, we just have to expose it and do some extra work.  OTOH, a pairing solution would still be easier, but would probably feel a bit weird to people.

**Comment by ianb** [comment]
Probably in some future release (post-54) we'll support FxA and that will resolve this.
