### ISSUE TITLE
Check if publicSentryDSN can/should be used

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1276]
I'm pretty sure the Sentry instance is only accessible internally, so everything related to publicSentryDSN is invalid/unnecessary.  But we should make sure we confirm this, and remove if so.

**Comment by fzzzy** [comment]
The public sentry dsn is used by the javascript client, because the dsn must be sent to the client and can't be protected.

https://github.com/getsentry/sentry/issues/3696

https://docs.getsentry.com/hosted/clients/javascript/config/

(Search for "public" in this url for some detail)
