### ISSUE TITLE
Implement basic CSP

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1289]
We should do some simple [CSP](https://wiki.mozilla.org/Security/Guidelines/Web_Security#Content_Security_Policy) for the PageShot site.  Review with @marumari

**Comment by marumari** [comment]
Totally, and I'd be glad to help!  Just let me know what you need!

**Comment by fzzzy** [comment]
@marumari Ok, here is what I came up with. On pageshot.net, we use data: img urls, inline scripts (we really should get rid of these), and inline styles. We have a separate domain, ${CONTENT_NAME}, which is something like pageshot-user-content.net (I forget exactly which domain was registered), which serves only images. So here is the CSP for pageshot.net:

    default-src 'self'; img-src 'self' ${CONTENT_NAME} data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' 

And here is the CSP for pageshot-user-content.net:

    default-src 'self'

**Comment by marumari** [comment]
Hmm, this is definitely a great start.  I will say that 'unsafe-inline' removes the primary protection in CSP, where it protects against XSS.  If you'd like, I can take a look at your current setup and see if I can make it work even with the specific inline scripts that are there?

Just point me at a site!  :)

**Comment by fzzzy** [comment]
You can take a look at pageshot.dev.mozaws.net. We use an inline script tag to inject the model data at the bottom of a static html page rendered by react on the server. This way the html is generated on the server so the client renders immediately, and the react model data is also in the initial http reqeuest so react is also hooked up client side immediately. We also use an inline script tag to set up google analytics.

**Comment by fzzzy** [comment]
@marumari Here is an actual shot page you can look at without having to install the addon and take a shot yourself:

https://pageshot.dev.mozaws.net/PCNaDLCZm2En4Roc/news.ycombinator.com

The homepage is old and going to be replaced with a static html page.

**Comment by marumari** [comment]
So this is a bit safer:

Content-Security-Policy: default-src 'none'; img-src 'self' data:; script-src 'self' https://www.google-analytics.com data: 'sha256-WK8AtmNP50jXw08a5QM2S9Hrn0JJskuI1+x5/XVQmZc=' 'sha256-Ub8fMcWIlO7PdfQBiWxuCMR93Kb+BCq8Q+q3lBIBctc=' 'sha256-FjWmmbGm4dMUksz9XrLAWMxLWvdowAZX8W0HkNRBrNM='; style-src 'self' 'unsafe-inline'

Using the sha256 tags means that you will have to update CSP whenever those inline scripts change.  You're much better off moving them to an external JavaScript file if possible.

script-src data: is also really unsafe -- about as unsafe as script-src 'unsafe-inline' -- because somebody can just inject a <script src="data:..."> tag about as easily a plain <script> tag.  I believe there are ways to get around having to do that with Google Analytics; I'm looking into it now.

**Comment by fzzzy** [comment]
The script tag changes for every page -- it has the full model data for the page in it. I think it will be best if we move that script to another url. This means an additional round trip has to be made to load the dynamic parts of the page. I guess that is a tradeoff we have to make.

I don't think we need to allow data for script, only image.

I think moving the google analytics script to it's own url shouldn't be hard.

**Comment by marumari** [comment]
You don't use data:, but Google Analytics injects a data: script into the page.  😦  There are ways around it, I'm just trying to figure them out.

As for the additional RTT, with HTTP/2 pipelining, the penalty should be pretty minimal.  You just need to support HTTP/2, is all.  :)

**Comment by marumari** [comment]
But yes, you are right in that it is impossible to make CSP work safely with something that injects arbitrary (and polymorphic) JavaScript into a page.

There is another way you can make it work, though -- are your CSP headers generated inside the application, or are they served from the upstream webserver?

**Comment by marumari** [comment]
If your CSP header is generated by the application, you can generate a nonce when you are generating the page.  Then you just need:

`Content-Security-Policy: script-src 'nonce-totallyrandomdatahere'`

And pair that with:

`<script nonce="nonce-thatsamerandomdatahere">...</script>`

That would allow you to put whatever arbitrary script you want in a page without generating the extra RTT.

**Comment by fzzzy** [comment]
Ok, I've been thinking about this a lot and I think the nonce is the way to go. Thanks!

I created https://github.com/mozilla-services/pageshot/issues/1305 to track this.
