### ISSUE TITLE
Consider expiration on image-only shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1290]
2-week expiration probably doesn't make sense for images.  We might want to remove expiration entirely, or default to indefinite.

**Comment by brampitoyo** [comment]
I’d prefer expiration to be removed. If we’re concerned about saving storage space, what we can do is put old shots into archive, and when user accesses these shots, a new DOM copy can be fetched from the server (of course, the risk here is that the copy might have changed from last time).

**Comment by ckprice** [comment]
Not something we're going to reach for first launch.
