### ISSUE TITLE
Create a /privacy and /terms page & add links to footer

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1292]
- [ ] Create a /privacy page.
- [ ] Create a /terms page.
- [ ] Add new "Privacy" and "Terms" links to the Shots view (probably in some kind of pinned footer).
- [ ] Add "Delete My Shots" link to the footer.
- [ ] Add "[Report IP Infringement](https://www.mozilla.org/en-US/about/legal/report-infringement/)" link to the footer.

![Shots view](https://s3.amazonaws.com/f.cl.ly/items/190Z2I1n2I251S2d2s0s/Image%202016-07-27%20at%2012.36.19%20PM.png?v=b14897be)

This is a blocker for launch.

**Comment by ianb** [comment]
I *think* all we need is a template or static page that we can use as the basis of these pages

**Comment by ianb** [comment]
Per #1182 to delete account we'll just need a link to `<a href="/delete-account/">` (I'm creating the confirmation page at that location)

**Comment by ianb** [comment]
I've created a component in https://github.com/mozilla-services/pageshot/blob/master/server/src/footer-view.js where "standard" links should go.  It's currently displayed only on the Shot Index, not on individual shots.  It doesn't have any styling yet.

**Comment by ckprice** [comment]
Updated summary to include "Report IP Infringement" link.

**Comment by ckprice** [comment]
This issue is no longer blocked. All content has been approved by legal.

**Comment by fzzzy** [comment]
Verified fixed on pageshot.dev.mozaws.net -- will be deployed to pageshot.net soon
