### ISSUE TITLE
Once pageshot.net goes live (this week), we should remove the ability to install the add-on

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1294]
This page will be available on production soon, and legal noted that we should not allow users to access the add-on from the domain. This is due to our PN and TOS not being finalized.

Related: https://github.com/mozilla-services/pageshot/issues/1253

**Comment by fzzzy** [comment]
I replaced the homepage with a very simple static page. This satisfies the legal requirement. There is another issue open that John self-assigned to make a prettier page.
