### ISSUE TITLE
Check out Website Downloader

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#1310]
https://websitedownloader.io/

“Download all the HTML source code and assets of any website.”

**Comment by ianb** [comment]
This is a web service.  You simply type in the address of a site and it starts (from its servers) downloading the pages on the site.  Apparently the service itself is managed at least in part through WordPress.  You have to pay to get the zip file:

![image](https://cloud.githubusercontent.com/assets/44390/18687006/c199287c-7f43-11e6-98fb-f1daa6a76b26.png)

That's silly money!  It may well just be using `wget --mirror`.

**Comment by pdehaan** [comment]
> That's silly money! It may well just be using `wget --mirror`

YOU JUST SAVED ME $3400!
