### ISSUE TITLE
Visual polish on the interstitial modal & buttons

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1314]
Comments from meeting today

- interstitial modal is odd now that there's only one thing to do.
- reducing clicks could be an option here to fix this.
- polish on save/cancel buttons.

**Comment by johngruen** [comment]
@fzzzy how about this?
![simplified snap flow](https://cloud.githubusercontent.com/assets/3323249/17605633/5c1fcd26-5fe9-11e6-808b-f6b8d7813be3.png)

**Comment by fzzzy** [comment]
Looks good. I like having the my shots button next to the shoot button. I'll work on it tomorrow.

**Comment by ianb** [comment]
I like the My Shots icon.  The message ("Drag or click on the page to select a region. Press ESC to cancel") feels kind of sloppy to me, like in this example where the beginning of the message is right next to "Pilot" (and it feels similar on most pages in practice).

We used to have some styling where the help message had a slightly darker background, similar to the full screen warning.

**Comment by johngruen** [comment]
@ianb I think the main thing is to get rid of the interstitial screen there...I can tweak this in the CSS once we get that cleared out.
