### ISSUE TITLE
String review for launch

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1315]
- [x] Confirm and update product name (with or without space). name will be `Page Shot` with a space.
- [x] Confirm page shot is legally viable as a name (cleared in [bug 1296738](https://bugzilla.mozilla.org/show_bug.cgi?id=1296738))
- [ ] "Click an element to select, drag a region to select, or press ESC to cancel"
- [ ] "Share to email and social networks:"
- [ ] "Get a shareable link to this shot:"
- [ ] "Saved from {google.com} {just now}" (where google.com is the TLD of the origin of the shot, and {just now} is a description of how long ago, e.g., "1 minute ago", "4 days ago")
- [ ] "expires in {13 days}"
- [ ] "keep for {Select time:} [save] [cancel]" where {Select time:} is a select box with "Indefinitely", "10 minutes", etc.
- [ ] Shot index header: "PageShot: My Shots"
- [ ] "Are you sure you want to delete the stop permanently?"
- [ ] Email template: Subject: "Fwd: {original page title}", body: "{original page title}\n\n{pageshot link}\n\nSource: {original link}"
- [ ] "Delete account / delete all shots" (link in footer of My Shots)
- [ ] "You can delete your account. This will permanently and immediately delete all your shots and all links. This cannot be undone. ¶ Are you sure you want to delete your account and all shots?"
- [ ] "Delete account" / "cancel" (buttons on Delete Account confirmation page)
- [ ] "Account deleted ¶ Your account has been deleted. Please uninstall the PageShot add-on. To uninstall go to the Tools menu and open Add-ons. ¶ If you do not uninstall PageShot, then all new shots you create will be created under a new account. All shots you previously made have been permanently deleted."

**Comment by johngruen** [comment]
@ckprice added that we need to to a legal review of the name

**Comment by ckprice** [comment]
Taking this to create a copy document with screenshots.

**Comment by ckprice** [comment]
Copy document distributed. Passing this back to @johngruen.
