### ISSUE TITLE
CSP error on shot index

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1324]
I get this error on My Shots:

`Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src http://localhost:10080 http://www.google-analytics.com 'nonce-1092a44b-11b4-4e0d-8826-45d859578c83'”).`

**Comment by fzzzy** [comment]
The file and line number info shown in the console at the right side can be useful in determining which element is triggering the error. Unfortunately react seems to not pretty print it's html output, and when I searched google about configuring react to pretty print the output I came up empty. Maybe there's an express middleware for pretty printing it?

It may be an inline script element that didn't have the nonce added.

**Comment by ianb** [comment]
Might (or might not) be related to #1113, specifically for now the favicon is served remotely.

**Comment by fzzzy** [comment]
Are you able to reproduce this with a --scratch profile? I don't seem to see it.

**Comment by ianb** [comment]
Yes, just recreated it with a scratch profile:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src http://localhost:10080 http://www.google-analytics.com 'nonce-645540ef-16ab-4ba9-a4cf-25149eb75a34'”).shots:7
Content Security Policy: The page’s settings blocked the loading of a resource at https://news.ycombinator.com/favicon.ico (“img-src http://localhost:10080 http://localhost data:”).
```

**Comment by fzzzy** [comment]
Ah, I see them in the browser console.

**Comment by fzzzy** [comment]
Ok, I fixed the big script csp problem (missing nonce), but now we have the issue of what to do about favicons. Can we save the favicon as part of the shot, instead of loading them all from remote servers?

**Comment by ianb** [comment]
I'll get them to proxy, it's probably easy I just have to remember how it works
