### ISSUE TITLE
My Shots should feel more like a button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1339]
The button doesn't feel like a button:

![image](https://cloud.githubusercontent.com/assets/44390/17682480/7a38f3f2-6311-11e6-8658-7cc294bc20e1.png)

Specifically I think when you hover over it you shouldn't see the crosshairs, and maybe you should get a hand icon.

**Comment by ianb** [comment]
My Shots doesn't work on [this website](http://www.vox.com/2016/8/16/12486586/2016-worst-year-ever-violence-trump-terrorism):

![image](https://cloud.githubusercontent.com/assets/44390/17709396/8cf99ac6-63ae-11e6-8e46-5b772221feda.png)

z-index I suppose?

**Comment by johngruen** [comment]
@fzzzy @ianb we should remove the crosshairs until the initial mousedown outside of the button?
