### ISSUE TITLE
Delete from shot index page

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1346]

**Comment by johngruen** [comment]
@fzzzy I would like to do something like activity stream here:

![screen shot 2016-08-19 at 4 17 22 pm](https://cloud.githubusercontent.com/assets/3323249/17823035/83390310-6628-11e6-8f8f-ccc4c60dc63d.png)
![screen shot 2016-08-19 at 4 17 16 pm](https://cloud.githubusercontent.com/assets/3323249/17823036/833cc25c-6628-11e6-9070-a73852d981f7.png)

This menu would have delete, share and go to site UI baked in

**Comment by johngruen** [comment]
https://mozilla.invisionapp.com/share/WF8V8N1NX#/screens/194888784_Home1

**Comment by ChenMorpheus** [comment]
Please find the link below for the detailed UX spec, and let me know if any questions, thanks.
https://mozilla.invisionapp.com/share/ER934Y4ND#/197767855_1-1_Shot_Page

**Comment by ianb** [comment]
I started the work in 9cb179e65eb2ace8c1028fec344d2d0bc9f0430d – it adds an icon in the corner:

![image](https://cloud.githubusercontent.com/assets/44390/20362882/a24369ec-ac02-11e6-97e0-ed77bda224ac.png)

Clearly it needs a background on the image.  It throws up a confirmation:

![image](https://cloud.githubusercontent.com/assets/44390/20362903/be9adfe4-ac02-11e6-92ab-6b132cfb5fd7.png)

When you confirm the model is refreshed, with the shot item gone.

This is just a start, but I thought I'd put something in to get things moving.

**Comment by johngruen** [comment]
@fzzzy looks like we can close this
