### ISSUE TITLE
Confirm internal referrers don't expose URLs to GA

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1357]
I realize while we use redirects to hide URLs from external links, we do not do this for some internal links.  We should confirm that Google Analytics doesn't receive shot URLs in that case.

**Comment by fzzzy** [comment]
If we enforce https only, then referrers will never be sent ever.

**Comment by ianb** [comment]
Internally?  I mean for instance that when I am on a shot page (say `https://pageshot.net/asd483jw/test.com`) and click on My Shots (going to `https://pageshot.net/shots`) then GA shouldn't see that original URL.

**Comment by fzzzy** [comment]
I see what you mean. I wonder if it is even possible to prevent that.

**Comment by ianb** [comment]
I'm thinking some GA configuration, the same way we hide the URL itself from GA.

It appears that GA [doesn't send the info](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#referrer) though I'm a little surprised.  We can probably confirm simply by looking closely at the network traffic.  To be extra sure we can still use `ga('set', 'referrer', 'hashed value')`

**Comment by ianb** [comment]
Examples of data sent when going to shot index from `http://localhost:10080/IBFy7YyMjOEfGYWY/news.ycombinator.com`:

```
(Form POST)
v=1
_v=j44
a=772808640
t=event
_s=4
dl=%2Fa-shot%2Funknown
ul=en-us
de=UTF-8
dt=Hacker%20News
sd=24-bit
sr=1280x800
vp=1127x381
je=1&ec=web
ea=goto-myshots
el=goto-myshots
_u=SACAAAABI~
jid=
cid=2007318195.1471549512
uid=anon7ca85200-ee78-b943-9bdf-f5be888e67a6
tid=UA-49796218-30&z=2140986084

(img)
_s=1
_u=QACAAAABI~
_v=j44
a=731944498
cid=2007318195.1471549512
de=UTF-8
dl=/a-shot/unknown
dp=/a-shot/unknown
dt=My Shots
je=1
jid=
sd=24-bit
sr=1280x800
t=pageview
tid=UA-49796218-30
uid=anon7ca85200-ee78-b943-9bdf-f5be888e67a6
ul=en-us
v=1
vp=1127x381
z=784322950
```

So I'm pretty sure it's all OK.  Note this does expose a bug where I believe `/shots` is attempting to be hashed, but fails.
