### ISSUE TITLE
Resize cannot be made on the opposite area of the selected grab point

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1360]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608171130

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- PageShot add-on is installed on a clean profile.

[Steps to reproduce]:
1  Go to any page (eg: imdb.com).
2. Click on the "PageShot" button from browser toolbar.
3. Perform a selection.
4. Grab one of the resize points of the selection and drag it to the opposite side.
5. Observe the behavior of the selection area.

[Expected result]:
- The selection expands in the opposite side.

[Actual result]:
- The selection is locked when the grab point reaches the opposite point.

[Notes]:
- Instead of expanding on the other side, the selection area is moved.
- Added a screen recording with the issue: https://goo.gl/l5vVw8

**Comment by ianb** [comment]
Technically it *seems* right that when you drag over the opposite edge that it would then flop over.  But I can't think of a reason why that would be useful.  So I made a change where it will bump out the opposite side (65px) if you drag one side right up to the other side as in this example.
