### ISSUE TITLE
The selection disappears when trying to use the browser window scroll bars

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1361]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608171130

[Affected Platforms]:
- All Windows
- All Linux

[Prerequisites]:
- PageShot add-on is installed on a clean profile.

[Steps to reproduce]:
1  Go to any page (eg: imdb.com).
2. Click on the "PageShot" button from browser toolbar.
3. Perform a selection on the page.
5. Try to scroll the page using the window scroll bars.

[Expected result]:
- The selection is kept while scrolling in order to be able to extend it.

[Actual result]:
- The selection disappears when clicking the scroll bars or any area outside the selection.

[Notes]:
- If the browser window is smaller than the area wanted to be selected, the user is forced to scroll trough other methods than using the scroll bars (eg: trough mouse for vertical, keyboard for horizontal).
- Added a screen recording with the issue: https://goo.gl/DBR7p5

**Comment by ianb** [comment]
Note this happens because even a click on a scrollbar registers as a click in the document.  My best guess at figuring out if this happens is that the click appears to have a target of the actual `<html>` element.
