### ISSUE TITLE
Style conflict on My Shots button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1362]
Example:

![image](https://cloud.githubusercontent.com/assets/44390/17747078/bb9844a2-6478-11e6-8f3e-c13cfe39b4fb.png)

On: http://www.heydonworks.com/article/on-writing-less-damn-code

**Comment by johngruen** [comment]
probably a good idea to prefix all CSS used in screenshot capture with something unlikely to conflict with other pages styles

**Comment by fzzzy** [comment]
We do already use prefixes, but the problem is cascading and specificity. In sass, we can use `@extend .pageshot-reset;` on every element that is used in content, but it really causes the output css to explode in size. (We have to do it anyway though)
