### ISSUE TITLE
Add mozbrowser permission and use it

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#137]
[mozbrowser](https://developer.mozilla.org/en-US/docs/Web/API/Using_the_Browser_API) is a Firefox-specific high-permission API that lets a site have greater control over a frame.  We have to be careful using it since we know it will not be available on other browsers.

What it allows us to do is frame live sites, not just our own shots.  And it allows us to track the navigation that happens inside an iframe.  (Because we use `<base target="_blank">` typically navigation doesn't happen inside the iframe, but we could make that conditional.)

[This addon](https://github.com/mykmelez/tcpsocketpup) demonstrates how to enable the permission:

```javascript
var { Cu } = require("chrome");
Cu.import("resource://gre/modules/Services.jsm");
Services.prefs.setBoolPref("dom.mozBrowserFramesEnabled", true);
const BROWSER_PERM = "browser";
let principleUri = Services.io.newURI("https://foo.com", null, null);
let principle = Services.scriptSecurityManager.getNoAppCodebasePrincipal(principleUri);
Services.perms.addFromPrincipal(principle, BROWSER_PERM, Services.perms.ALLOW_ACTION);
```

We also have to figure out a way to clean up on addon uninstall, running:

```javascript
Services.perms.removeFromPrincipal(principle, BROWSER_PERM);
```

**Comment by CaptainCalliope** [comment]
Regarding other browsers, is this an API that can be polyfilled, and if so, performantly?

**Comment by ianb** [comment]
No, this is a high permission API, built for implementing the Firefox OS browser, and couldn't be polyfilled.

**Comment by ianb** [comment]
This doesn't relate well to what we're doing now.
