### ISSUE TITLE
The yellow "This page is only visible to you until you share the link" message is still displayed even if the share pop-up is dismissed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1379]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608191128

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608191128) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to any page (eg imdb.com).
2. Click on the "PageShot" button from browser toolbar, make a selection and save it.
3. After you are redirected to the shot page, press the blue "Share" button.
4. Observe the share pop-up and the yellow message behavior.

[Expected result]:
- The share pop-up and the yellow message are both dismissed after pressing the "Share" button. 

[Actual result]:
- Only the share pop-up is dismissed leaving the yellow message hanging on the page.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/9hze62

**Comment by fzzzy** [comment]
Yes, it goes away after a specified timeout. I can hide it if the share panel is not visible too.

**Comment by ianb** [comment]
Let's put the message that currently goes in the yellow box into the share panel itself, then they close and open at the same time, no weirdness.
