### ISSUE TITLE
Sometimes error popup renders weird

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1380]
Example:

![image](https://cloud.githubusercontent.com/assets/44390/17819569/22c9e626-660e-11e6-9769-e3d0001b1ca7.png)

Haven't figured out a pattern.

**Comment by johngruen** [comment]
@ianb i see this thing quite frequently on my local version. sometimes even when pageshot is actually working on the page

**Comment by fzzzy** [comment]
Odd, I have never seen this.

**Comment by johngruen** [comment]
We've refactored this
