### ISSUE TITLE
Get rid of shot deleted page

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1384]
it's not remotely necessary :)

**Comment by ianb** [comment]
I think we put it in there because it seemed strange not to say *anything* when the deletion actually happens, and we don't have any other messaging approach.  Do you think it's fine with nothing, or would the message go somewhere else?

**Comment by johngruen** [comment]
Less is more. Let's start with nothing, see how that goes.

**Comment by johngruen** [comment]
I'd rather have a transient notification on the main page or something but let's start with getting rid of the extra click this page creates
