### ISSUE TITLE
Make PageShot compatible with e10s

### ISSUE THREAD

**Issue by clouserw** [mozilla-services/pageshot#1388]
Or maybe it already is?  I think we'd just need to add permissions: {'multiprocess': true} to the package and then test it.  Some links on compatibility concerns are at https://blog.mozilla.org/addons/2016/08/02/multi-process-firefox-and-add-ons-a-call-to-action/

**Comment by ianb** [comment]
It should be compatible, and we test it primarily with e10s.  Is adding `permissions: {multiprocess: true}` to package.json all we need to do?  This doesn't seem to be documented very well for Jetpack.

**Comment by clouserw** [comment]
Yeah.  I got that idea off of https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/package_json .  And I think it should be a list, so:

> 'permissions': [
>     'multiprocess': true
> ]

although, to be honest, I see it written both ways when googling for example code...
