### ISSUE TITLE
Optimize SVGs in static/img

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1389]
I noticed a few SVGs were unoptimized (because I am weird and creepy), and found a few interesting things.
1. While [./static/img/question-mark.svg](https://raw.githubusercontent.com/mozilla-services/pageshot/master/static/img/question-mark.svg) is a beautiful SVG, it seems wildly inefficient.
2. [./static/img/glyph-search-16.svg](https://github.com/mozilla-services/pageshot/blob/master/static/img/glyph-search-16.svg) is invalid, as noted while I tried running SVGO (SVG optimizer) CLI tool. **UPDATE:** Fixed in #1390
### Steps to reproduce:
1. Install SVGO locally: `$ npm i svgo`
2. Run SVGO against static/img/ folder: `$ ./node_modules/.bin/svgo static/img`
3. Read it.
4. Weep.
### Actual results:

``` sh
$ ./node_modules/.bin/svgo static/img/
Processing directory 'static/img/':

arrow-right.svg:
Done in 35 ms!
0.469 KiB - 63.3% = 0.172 KiB

clock.svg:
Done in 26 ms!
2.539 KiB - 65.2% = 0.885 KiB

close.svg:
Done in 7 ms!
0.758 KiB - 53.2% = 0.354 KiB

delete-thumbnail.svg:
Done in 13 ms!
1.12 KiB - 64.3% = 0.399 KiB

flag.svg:
Done in 5 ms!
0.356 KiB - 50.4% = 0.177 KiB

glyph-forward-16-white.svg:
Done in 20 ms!
0.696 KiB - 9.5% = 0.63 KiB

glyph-forward-16.svg:
Done in 10 ms!
0.69 KiB - 9.2% = 0.627 KiB

Error in parsing SVG: Text data outside of root node.
Line: 13
Column: 1
Char: a
```

After fixing that SVG locally (removing that pesky trailing `a` character), and re-running SVGO, it looks like everything else optimized correctly, saving an average of 60-80% filesize.

**Comment by ianb** [comment]
We should remove unused images (#1407) before doing this.

**Comment by ianb** [comment]
Note this is done on build, so future SVGs will also be optimized automatically as part of the build.
