### ISSUE TITLE
Add Favicon everywhere!

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1395]
Currently there's no favicon, we should use the pageshot logo as the favicon on all pages.

**Comment by fzzzy** [comment]
If you make the asset for it then assign it to me i'll hook it up.

**Comment by johngruen** [comment]
@fzzzy I think you can just use: https://github.com/mozilla-services/pageshot/blob/master/static/img/pageshot.svg

and 

`<link rel="icon" type="image/svg+xml" href="path/to/icon">`

**Comment by fzzzy** [comment]
You can use an svg and don't have to make an .ico any more for a favicon? What wonderful times we live in on the web in 2016

**Comment by johngruen** [comment]
@fzzzy i spoke to soon
http://caniuse.com/#feat=link-icon-svg

**Comment by johngruen** [comment]
lemmie make you a favicon

**Comment by fzzzy** [comment]
Crap. It'll be a glorious day when .ico is dead

**Comment by johngruen** [comment]
on the other hand: http://caniuse.com/#feat=link-icon-png

just use: https://github.com/mozilla-services/pageshot/blob/master/static/img/pageshot-icon-32.png

**Comment by ianb** [comment]
Note I've seen some problems with nosniff and favicon content types on the site, we should confirm that all works okay.

To implement the icon should be added to HeadTemplate in reactruntime, to frame.js (which is view that doesn't use reactruntime), and to the homepage.
