### ISSUE TITLE
If the error description is too long, the text is not entirely visible on the displayed pop up 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1397]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608220738

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608220738) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to http://9gag.com/gag/aAP6N7o.
2. Click on the "PageShot" button from browser toolbar and click on the 9gag image in order to make a selection.
3. Click on the "Save" button. 
4. After the error message is displayed, press the "Cancel" button.
5. Repeat steps #2 and #3.
6. Observe the error message.

[Expected result]:
- The error message is entirely visible on the pop up.

[Actual result]:
- The "PageShot may not be able..." message is not entirely visible.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/vaiaFy
<hr>
![error](https://cloud.githubusercontent.com/assets/19226534/17860373/fdf76942-6895-11e6-9edc-5092124eef39.png)

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue, but is still somehow reproducible. The error box is indeed a bit bigger now, and the "PageShot may not be able to work..." message is entirely visible. But it seems that under this message, another one is displayed and is not entirely visible.

![long error](https://cloud.githubusercontent.com/assets/19226534/18088907/e44548b2-6ec5-11e6-9248-6fe3a391d987.png)

**Comment by fzzzy** [comment]
Aha, I guess that is because the error box used to show more than one error and have a scrollbar. I guess you see this when you generate more than one error in a row?

**Comment by SoftVision-CosminMuntean** [comment]
Yes. If you follow the steps from the first comment, you generate two errors in a row and the second error is not entirely visible.
