### ISSUE TITLE
The YouTube sidebar and header with search area displayed on top of the Page Shot selection functionality

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1398]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608220738

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608220738) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to www.youtube.com.
2. Click on the "PageShot" button from browser toolbar.
3. Try to make a selection on the Youtube sidebar or on the YouTube header with search area.

[Expected result]:
- The YouTube sidebar and header can be selected in order to make a shot.

[Actual result]:
- The Page shot overlay and selection functionality appear to be under YouTube sidebar and header making the selection difficult.

[Notes]:
- The mentioned areas can be selected even with this UI issue, and are displayed in the saved screenshot. 
- Added a screen recording with the issue: https://goo.gl/4ebxka

**Comment by ianb** [comment]
Looks like a z-index problem
