### ISSUE TITLE
Remove unused CSS rules

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1414]
We should remove CSS that doesn't affect any current markup

**Comment by ianb** [comment]
Initial report:

# Unused CSS rules:
  - [/static/css/profile.css](http://localhost:10080/static/css/profile.css?rev=6f60241)
    - `.toolbar-button { float: left; margin: auto 5px; }`
    - `.panel { border-radius: 5px; box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.5); background: rgb(255, 255, 255) none repeat scroll 0% 0%; color: rgb(0, 0, 0); padding: 1em; text-align: start; font-size: 13px; }`
    - `.panel a, .panel a:visited { color: rgb(0, 149, 221); }`
    - `.panel a:hover, .panel a:focus { text-decoration: none; }`
    - `.avatar-container { text-align: center; height: 80px; width: 80px; }`
    - `.avatar-container img { height: 100%; }`
    - `#profile { position: fixed; z-index: 1; width: 250px; }`
    - `.panel .label { font-weight: bold; font-size: 13px; margin-bottom: 8px; margin-top: 10px; }`
    - `.panel input[type="text"] { width: 95%; font-size: 13px; }`
    - `.sync-buttons { list-style: outside none none; padding-left: 0px; }`
    - `.sync-buttons li { margin-top: 0.5em; }`
  - [/static/css/styles.css](http://localhost:10080/static/css/styles.css?rev=6f60241)
    - `#frame { border: 0px none; margin-top: 65px; margin-bottom: 4em; box-shadow: 0px -5px 5px rgba(0, 0, 0, 0.5); }`
    - `#private-notice { position: fixed; right: 15px; top: 255px; font-family: sans-serif; font-size: 11px; border-radius: 4px; padding: 7px 7px 1px; background-color: rgb(235, 213, 90); color: rgb(0, 0, 0); cursor: pointer; z-index: 2; }`
    - `.arrow-up { position: relative; top: -23px; left: 225px; width: 0px; height: 0px; border-left: 5px solid transparent; border-right: 5px solid transparent; border-bottom: 5px solid rgb(235, 213, 90); }`
    - `.window-scrolled-down #toolbar { visibility: visible; }`
    - `.window-scrolled-fully #toolbar { visibility: visible; }`
    - `#profile-widget { position: fixed; top: 15px; left: 15px; z-index: 2; }`
    - `#navigate-toolbar { position: fixed; top: 0px; right: 0px; padding: 14px; z-index: 2; height: 23px; width: 160px; text-align: right; text-shadow: 1px 1px 2px rgb(0, 0, 0); font-size: 12px; }`
    - `#full-page-button { position: fixed; left: 0px; right: 0px; bottom: 0px; height: 2em; text-align: center; z-index: 1001; }`
    - `.window-scrolled-fully #full-page-button { visibility: hidden; }`
    - `#full-screen-thumbnail { position: fixed; left: 0px; right: 0px; bottom: 2em; text-align: center; z-index: 1001; }`
    - `#full-screen-thumbnail img { box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.5); cursor: pointer; }`
    - `#full-page-button-scrollable { visibility: hidden; height: 2em; margin-top: 500px; text-align: center; }`
    - `.window-scrolled-fully #full-page-button-scrollable { visibility: visible; }`
    - `.full-page-button-arrow { color: rgb(51, 51, 51); }`
    - `.full-page-button-text { color: rgb(0, 0, 0); }`
    - `.full-page-button-styles { background-color: rgb(255, 255, 255); background-image: linear-gradient(rgb(255, 255, 255), rgb(244, 244, 244)); border-radius: 99px; color: rgb(0, 149, 221); display: inline-block; font-size: 12px; padding: 0.4em 1.5em; text-decoration: none; border: 1px solid rgb(171, 171, 171); }`
    - `.clip-count { position: relative; bottom: 7px; right: 15px; }`
    - `.instructions { position: absolute; top: 0.5em; right: 0.5em; }`
    - `.link-button { cursor: pointer; color: rgb(133, 133, 133); background: transparent none repeat scroll 0% 0%; border: 1px solid rgb(212, 212, 212); padding: 4px; border-radius: 4px; }`
    - `.link-button.delete-button { color: rgb(221, 0, 0); }`
    - `#info { position: absolute; top: 0.5em; left: 100px; right: 100px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; text-align: center; }`
    - `a#collection-link { text-decoration: underline; }`
    - `#comment-container { position: fixed; width: 500px; min-height: 12px; padding: 9px; top: 40px; right: 10px; border-radius: 0px 0px 4px 4px; z-index: 100; background-color: rgb(0, 83, 159); cursor: pointer; }`
    - `#comment-editor { width: 100%; height: 35px; }`
    - `#comment-instructions { cursor: pointer; font-size: xx-small; }`
    - `#clip { cursor: pointer; position: relative; top: 2px; }`
    - `.clip-container div { margin: 3em; }`
    - `.text-clip { background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); border: 1px solid rgb(170, 170, 170); box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.5); }`
    - `.text-clip a { color: rgb(0, 0, 0); }`
    - `.clip-anchor-link { margin-bottom: 4em; font-size: 13px; color: rgb(149, 149, 149); }`
    - `.clip-anchor-link:hover { color: rgb(242, 242, 242); }`
    - `.selection { border-top: 1px solid rgb(153, 153, 153); }`
    - `.goto-selection { cursor: pointer; float: right; }`
    - `.white-background { background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); text-align: left; }`
    - `.main-link img { height: 1em; position: relative; top: 2px; left: 2px; }`
    - `.upload-full-page { color: rgb(9, 150, 248); background: transparent none repeat scroll 0% 0%; border-radius: 4px; border: 1px solid rgb(9, 150, 248); height: 32px; cursor: pointer; vertical-align: middle; padding: 6px 15px; font-size: 12px; }`
    - `#full-page-checkbox { visibility: hidden; }`
    - `.flag-button { margin-left: 15px; border-radius: 4px; border: 1px solid rgba(0, 0, 0, 0.35); height: 32px; background: rgb(252, 252, 252) none repeat scroll 0% 0%; color: rgb(0, 0, 0); cursor: pointer; vertical-align: middle; padding: 8px 15px; }`
    - `#share-buttons-panel { position: fixed; top: 75px; right: 15px; z-index: 99; border-radius: 4px; border: 1px solid rgba(0, 0, 0, 0.35); box-shadow: 0px -2px 5px rgba(0, 0, 0, 0.5); color: rgb(0, 0, 0); background-color: rgb(255, 255, 255); padding: 15px; text-align: left; }`
    - `#share-buttons-panel div { margin-bottom: 7px; }`
    - `#share-buttons-panel a { padding: 7px; }`
    - `#share-buttons { display: flex; flex-direction: row; }`
    - `#share-buttons a { margin: auto; }`
    - `.copy-shot-link-input { border-top-left-radius: 4px; border-bottom-left-radius: 4px; height: 22px; width: 170px; }`
    - `.copy-shot-link-button { background: rgb(47, 168, 225) none repeat scroll 0% 0%; color: rgb(255, 255, 255); border-radius: 0px 4px 4px 0px; border: 1px solid rgba(0, 0, 0, 0.35); height: 28px; width: 75px; cursor: pointer; }`
    - `#more-shot-actions-menu { margin-left: 15px; }`
    - `#main-title { font-size: 24px; font-weight: 300; color: rgb(242, 242, 242); }`
    - `#copy-flag { background: rgb(242, 88, 32) none repeat scroll 0% 0%; color: rgb(255, 255, 255); text-decoration: none; font-family: -apple-system,BlinkMacSystemFont,"Segoe UI","Roboto","Oxygen-Sans","Ubuntu","Cantarell","Fira Sans","Droid Sans","Helvetica Neue",sans-serif; text-align: center; text-transform: uppercase; padding: 3px 40px; font-size: 13px; font-weight: bold; line-height: 1.5rem; width: 100px; position: fixed; top: 80px; left: -60px; transform: rotate(-45deg); box-shadow: 0px 6px 20px rgba(0, 0, 0, 0.5); }`
    - `.metadata { margin-bottom: 4em; }`
    - `.comment-bubble { cursor: pointer; margin-right: 0.5em; position: relative; top: 19px; }`
    - `.comment-holder { display: inline-block; position: relative; top: -3.25em; width: 400px; background-color: rgb(242, 242, 242); color: rgb(252, 252, 252); border-radius: 4px; text-align: left; }`
    - `.comment-holder div { margin: 0px; padding: 15px 20px; }`
    - `.comment-user { display: inline-block; width: 10em; }`
    - `.comment-date { display: inline-block; width: 5em; }`
    - `.comment-text { display: inline-block; font-size: 13px; line-height: 18px; }`
    - `#use-pageshot-to-create { position: fixed; left: 0px; right: 0px; bottom: 0px; padding: 1em 3em 1em 1em; background-color: rgb(242, 242, 242); color: rgb(0, 0, 0); z-index: 2000; box-shadow: 0px -2px 5px rgba(0, 0, 0, 0.5); }`
    - `#use-pageshot-to-create a { color: rgb(0, 0, 0); text-decoration: underline; }`
    - `#banner-close { position: absolute; right: 0px; top: 0px; padding: 1em; cursor: pointer; }`
    - `.navigate-clips { background-color: rgba(255, 255, 255, 0.05); }`
    - `.navigate-clips.disabled { opacity: 0.5; background-color: inherit; }`
    - `.button { display: inline-block; background-color: rgb(92, 184, 92); color: rgb(255, 255, 255); font-size: 18px; padding: 6px 12px; border-radius: 6px; border: 1px solid rgb(76, 174, 76); }`
    - `.button:hover { text-decoration: underline; }`
    - `.intro-js-highlight-overlay { background: transparent none repeat scroll 0% 0%; border: 2px solid rgb(0, 137, 219); }`


# Resources:
  - [/images/9fb93f38-9343-463f-ba57-b3470b0ef6a3](http://localhost:10080/images/9fb93f38-9343-463f-ba57-b3470b0ef6a3)
  - [/static/img/bgtexture.png](http://localhost:10080/static/img/bgtexture.png)
  - [/static/img/pageshot-icon-32.png](http://localhost:10080/static/img/pageshot-icon-32.png?rev=6f60241)
  - [/oembed](http://localhost:10080/oembed?url=http%3A%2F%2Flocalhost%3A10080%2F8fJbysRMzT2NDEP9%2Fnews.ycombinator.com)
  - [/static/img/clock.svg](http://localhost:10080/static/img/clock.svg?rev=6f60241)
  - [/static/img/pageshot-icon-32.png](http://localhost:10080/static/img/pageshot-icon-32.png?rev=6f60241)
  - [/static/img/garbage-bin.png](http://localhost:10080/static/img/garbage-bin.png?rev=6f60241)

**Comment by ianb** [comment]
On the shot index page:

# Unused CSS rules:
  - [/static/css/shot-index.css](http://localhost:10080/static/css/shot-index.css?rev=6f60241)
    - `.no-shots { display: flex; flex-direction: column; justify-content: center; margin: 96px auto 0px; }`
    - `.no-shots .large-icon { background: transparent url("../img/pageshot.svg") no-repeat scroll center center / auto 120px; flex: 0 0 120px; opacity: 0.3; }`
    - `.no-shots .no-shots-string { margin-top: 24px; text-align: center; font-size: 20px; }`
    - `.title-container a { color: rgb(0, 0, 0); text-decoration: none; }`

# Used resources:
  - [/static/img/glyph-forward-16-white.svg](http://localhost:10080/static/img/glyph-forward-16-white.svg)
  - [/static/img/pageshot-icon-32.png](http://localhost:10080/static/img/pageshot-icon-32.png?rev=6f60241)
  - [/static/img/pageshot-icon-32.png](http://localhost:10080/static/img/pageshot-icon-32.png?rev=6f60241)
  - [/static/img/glyph-search-16.svg](http://localhost:10080/static/img/glyph-search-16.svg)
  - [/static/img/pageshot.svg](http://localhost:10080/static/img/pageshot.svg)
  - [/static/img/glyph-forward-16-white.svg](http://localhost:10080/static/img/glyph-forward-16-white.svg)
  - [/static/img/glyph-forward-16.svg](http://localhost:10080/static/img/glyph-forward-16.svg)

**Comment by pdehaan** [comment]
Nnnnneat!
@ianb What tool did you use to determine dead CSS/resources?

**Comment by ianb** [comment]
@pdehaan I added a tool to PageShot: https://github.com/mozilla-services/pageshot/pull/1419/commits/13164018eb7ca140f68a5a37fe8a2bea65e20929
