### ISSUE TITLE
Explore ‘growing into the chrome’ ideas

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#142]
How do you convey the fact that the user and reader are looking not at the original page itself, but only at a snapshot of it?

Ian says:
>growing into the chrome […] might allow for less intrusive view on Firefox while still making it clear that this isn't the original page.

Let’s explore this idea.

**Comment by CaptainCalliope** [comment]
More of an observation than a suggestion, but I find the way in which the browser chrome visually mutates when you hit the Menu Customization button rather interesting. The blueprint motif behind everything implies a workspace of some kind.

It would be interesting to create an in-chrome visual language for web content that is fully within the power of the user/fully within the domain of the user agent. I imagine such a visual language would be useful for (and could be informed by) work the Webmaker team is doing with their 'MakerFox' protoypes: https://github.com/MozillaFoundation/plan/issues/335

**Comment by ianb** [comment]
With the full border around the page I think this is clear
