### ISSUE TITLE
Add Open Graph/Twitter info to homepage

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1423]
Meta bug ahoy!

Currently our meta/title/link tags look like this on the skeleton homepage:

```html
<link href="/homepage/css/style.css" rel="stylesheet">
<link rel="icon" type="image/png" href="/static/img/pageshot-icon-32.png">
<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<meta name="description" content="Share anything on the web with anyone using PageShot.">
<meta name="viewport" content="width=320, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<title>
      Welcome to PageShot
    </title>
```

If I browse pageshot.net on my computer, and then get it as a Highlight in Activity Stream, it looks barren, like this:

![new_tab](https://cloud.githubusercontent.com/assets/557895/18016646/459e6dec-6b82-11e6-8862-ff635b643234.png)

When we redesign the new homepage after the site is launched, we should make sure we sprinkle some `og:image` style tags into the homepage for improved Facebook/Twitter sharing and Activity Stream display.

**Comment by ianb** [comment]
There are og attribtues on https://testpilot.firefox.com/experiments/page-shot that can be copied to https://pageshot.net
