### ISSUE TITLE
The "Terms of Service" and "Privacy Notice" pages are not available

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1427]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608300731

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608300731) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite.
2. Click on the "PageShot" icon from browser toolbar and click the "My Shots" button.
3. Scroll to the bottom of the page and click either "Terms of Service" or "Privacy Notice" link and observe the loaded page.

[Expected result]:
- The pages are successfully loaded and correctly rendered.

[Actual result]:
- Step 4: The page is loaded but the "Cannot GET /terms" is displayed in the top left side of the page.
- Step 5: The page is loaded but the "Cannot GET /privacy" is displayed in the top left side of the page.

[Notes]:
- Added a screen recording with the issue: http://goo.gl/A4vOlo.

**Comment by fzzzy** [comment]
Dup of #1292
