### ISSUE TITLE
Remove chrome-extension?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1434]
Ref: https://github.com/mozilla/testpilot/issues/1291

Currently we have a chrome-extension at [/chrome-extension](https://github.com/mozilla-services/pageshot/tree/master/chrome-extension), but we don't seem to be offering it to users (either via Test Pilot or via the site).

Not sure if we're actively maintaining the extension anymore, or if we just delete it, or move it into a branch in case we want to resurrect it in the future.

**Comment by johngruen** [comment]
@pdehaan at the very least we should remove this route for the time being

**Comment by fzzzy** [comment]
I verified that there's no route to this; the folder chrome-extension is dead code at the moment, but let's clean that up later.

**Comment by fzzzy** [comment]
I'll just move it into stretch instead of closing it, actually.

**Comment by ianb** [comment]
Done in the webextension branch
