### ISSUE TITLE
Pageshot.net redirects me to dev server instance after taking a shot

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1435]
### Steps to reproduce:
1. Install add-on via https://pageshot.net/homepage/install.html
2. Take a shot of a thing and stuff.

### Actual results:
After taking said shot, I'm redirected to https://pageshot.dev.mozaws.net/JFNmqnBFPL1n1sj6/pageshot.net

This seems like some crazy crossed streams.

![](http://i.imgur.com/JugbjIY.gif)

### Expected results:
Shots taken using an add-on installed via **prod** server (or Test Pilot) should keep me on the **prod** stack, and never the twain shall meet.

**Comment by fzzzy** [comment]
Doh.

**Comment by fzzzy** [comment]
Fixed by the deploy to prod.
