### ISSUE TITLE
Explore integration with SocialAPI

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#144]
More specifically, investigate ways that we can use the SocialAPI button to share PageShot links via Twitter, Facebook, etc.

**Comment by ianb** [comment]
Besides the share button just existing and doing its things, two things I can imagine:

- Sharing richer content, when appropriate.  For Facebook and Twitter we expect them to just pick up the metadata we've already added to the page.  For email we can potentially provide richer content to share.

- Awareness of when something is shared and use a link generated to track its life.  That is, if PageShot can create a URL with tracking information, then get a notification that the URL was sent to a particular destination, we can then tell the author when people arrive from that location.  E.g., I share it via gmail, I create a specific link, SocialAPI/gmail tells PageShot that the link was sent to bob@example.com, I can now tell the author that when that link is followed that it means bob@example.com saw the content.

/cc @mixedpuppy

**Comment by ianb** [comment]
We should discuss this with @mixedpuppy

**Comment by ianb** [comment]
Share Panel seems to be superseding this.
