### ISSUE TITLE
Website favicons are displayed as cropped on saved shots

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1447]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608310127

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608310127) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a New Tab.
2. Click on the "PageShot" button from browser toolbar.
3. Observe the websites favicons for the saved shots.

[Expected result]:
- Websites favicons are entirely visible for saved shots. 

[Actual result]:
- Websites favicons are saved cropped on the shots.

[Notes]:
- Added a screen shot with the issue:

![favicons](https://cloud.githubusercontent.com/assets/19226534/18166351/5bdbac84-7053-11e6-86f7-15025807914d.png)

**Comment by ianb** [comment]
I'm not seeing this locally, not sure what's going on...

![image](https://cloud.githubusercontent.com/assets/44390/18214202/50acffca-7111-11e6-89e8-423ae3baacba.png)

**Comment by johngruen** [comment]
@ianb i've seen this locally as well, probably as easy as explicity declaring the size. I can look into it.

**Comment by ianb** [comment]
Closing because we haven't seen this for a while.  If anyone notices it again it can be reopened or recreated.
