### ISSUE TITLE
The icons from "My Shots" button are not displayed on Test Pilot pages

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1448]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608180837

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608180837) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to https://testpilot.firefox.com/.
2. Click on the "PageShot" button from browser toolbar and observe "My Shots" button.

[Expected result]:
- The icons from the "My Shots" button are correctly displayed.

[Actual result]:
- The icons displayed on the button before and after "My Shots" text are not visible.

[Notes]:
- Added a screen shots with the issue: 

![my shots button](https://cloud.githubusercontent.com/assets/19226534/18205650/c5d2de54-712b-11e6-95b6-e9a50f143881.png)

**Comment by ianb** [comment]
Huh, I cannot figure out where the conflict is; the `background-image` rule is active and doesn't seem to be overridden by anything else on the page.

**Comment by fzzzy** [comment]
Look for something that changes the background position or the text indent? I had similar problems on another page

**Comment by fzzzy** [comment]
I don't see any rules which are being set from anywhere which seem to be causing this :(

**Comment by ianb** [comment]
We could try simplifying the markup and CSS.  It was quirky because XUL was very finicky.  Maybe it could be a plain `<div><img src="icon1" height/width />My Shots <img src="icon2" height/width /></div>` ?

**Comment by ianb** [comment]
Note that the iframe approach did not fix this.  The images are blocked by CSP.  I don't believe there's much (reasonable) that we can do about this.

**Comment by pdehaan** [comment]
Could we just inline the images as data URIs?

**Comment by fzzzy** [comment]
We actually already do inline them as data urls, but data urls are blocked by the csp :)
