### ISSUE TITLE
Page selection position is horizontally changed when maximizing the browser window

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1449]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201608180837

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201608180837) is installed on a clean profile.
- Browser is maximized.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to any page.
2. Perform a selection and keep in mind its position based on the surrounding elements.
3. Maximize the window and observe the selected area position.

Expected result]:
- The selection remains in the same place no matter if the browser window is resized or maximized.

[Actual result]:
- The selection remains in the same place vertically but changes its position horizontally forcing the user to redo the selection.

[Notes]:
- This issue is not reproducible on Google Sheets pages (see this screen recording: http://goo.gl/dFPRLV).
- Added a screen recording with the issue: http://goo.gl/BJQKyt.

**Comment by ianb** [comment]
I don't think there's any way to resolve this.  There's no real basis we have for moving the selection around once it's been made – like in this example the margins change, so if we just multiplied the selection coordinates to be relative to the window size then the selection still wouldn't stay where it was intended to.
