### ISSUE TITLE
Searches should be performed on change, not on submit

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1458]
On the shot index page, i start typing a search, i expect results to return immediately not when i hit enter. Also when i delete my query i expect the UI to reset to show all searches.

**Comment by fzzzy** [comment]
We switched it from searching on every keystroke for performance and stability reasons. Also, the way we implement search right now in postgres, only whole words match, not partial words, and so there won't be any results until you type a whole word anyway.

I do think we should do this, but it's not as trivial as just changing the ui.

**Comment by ianb** [comment]
I'm going to implement this with a 2 second delay (i.e., you have to not type anything for 2 seconds before a search is sent), and a minimum of 4 characters (i.e., if you type "tes" it won't search, but "test" will search).  The normal enter/submit will also still work, with no delay.

**Comment by ianb** [comment]
I went with 1 second, 2 seconds seemed too long.

I also implemented @TLHuang's idea of dimming the shot cards when the search results below don't match what's in the search box above.  So as you first start typing everything dims, and if you pause and search catches up then it becomes fully opaque again.
