### ISSUE TITLE
Search by domain

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1459]
### Current
I have a shot from nytimes.com i search 'nyt' and no results return

### Expected
Shots from domains with 'nyt' substring return

**Comment by fzzzy** [comment]
This is because of how we implemented full text search in postgres; only whole words match, not partial words.

**Comment by fzzzy** [comment]
I'm not convinced we can get this done by first launch.

**Comment by johngruen** [comment]
@fzzzy, fair enough, but right now search is the differentiating feature for page shot. Let's talk about how we can improve the experience because it's not at all transparent how it works now.

**Comment by ianb** [comment]
In e0e8cef5e1484a045cb945c2f5c824a09e81165f we search the URL and title for any string match, not just full text.  However, it doesn't handle rank.  In the case when there are no full text results, but if there is a URL match, then items are ordered (in abc00231141fb19511f4e477ab03bd56796a144a) based on date.  If there are URL-only (or title-substring-only) matches but also full text matches, the URL-only will always sort last.  It's not super obvious to me how to fix this in SQL, though it might not be hard (if I knew).

**Comment by fzzzy** [comment]
That ordering seems fine, except maybe it should be reverse date? Newest to oldest?
