### ISSUE TITLE
Routing cleanup for / and /shots

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1462]
## Version 1

*STR*
I don't have pageshot installed, go to /shots, i get an unstyled message

*Expected*
I go to the styled homepage telling me about test pilot

## Version 2
*STR* 
I go to pageshot home page with pageshot installed and i get the 'go to Test Pilot page

*Expected*
I go to /shots

**Comment by ianb** [comment]
I made a commit for Version 1 (redirect to /).

We've debated Version 2 in the past, but it means that someone who uses PageShot can't see the homepage itself.  E.g., I want to send you a link `I'm enjoying using https://pageshot.net` but now I can't see what is actually on the other side of that link.

**Comment by johngruen** [comment]
@ianb this is a 'just for now' issue. i can't see a reason why anyone would need to see the / route with the add-on installed. Further, there's no clear way to get to /shots from /.

If /shots routes home then it's no different sharing from that route

**Comment by johngruen** [comment]
Solution: Put a 'my shots button' on the landing page and call it a day

**Comment by ianb** [comment]
Solution noted in #1507
