### ISSUE TITLE
Test what shots look like when posted to Facebook, Twitter

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1467]
We have some information to help make those posts better, but we need to confirm what they really look like.

**Comment by ianb** [comment]
Should be fixed with #1542, but we should test again once the change goes live.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla-services/pageshot/issues/1562

Also, here's what I get from the Facebook Open Graph Sharing debugger:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fpageshot.dev.mozaws.net%2F1LSzd989On8jpiNW%2Fwww.reddit.com

<img width="1050" alt="sharing_debugger_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/557895/18684798/64ac5bb6-7f2a-11e6-890d-26dfcb03aba4.png">
<img width="1034" alt="sharing_debugger_-_facebook_for_developers" src="https://cloud.githubusercontent.com/assets/557895/18684825/7d6ce79c-7f2a-11e6-8689-71cad31af314.png">

**Comment by ianb** [comment]
Yes, that's what I saw, I think that's all okay?  Seems lame it complains about the twitter card stuff.  I don't see any particular value to app_id for the moment.

**Comment by pdehaan** [comment]
Still poking at it.
Looking at our meta tags via my meta-scraper:

```html
$ ./bin/cli.js --url https://pageshot.dev.mozaws.net/1LSzd989On8jpiNW/www.reddit.com

<link rel="alternate" type="application/json+oembed" href="https://pageshot.dev.mozaws.net/oembed?url=https%3A%2F%2Fpageshot.dev.mozaws.net%2F1LSzd989On8jpiNW%2Fwww.reddit.com" title="r/gaming &#x2022; /r/gaming oEmbed">
<link rel="icon" type="image/png" href="/static/img/pageshot-icon-32.png?rev=f6111c2">
<link rel="shortcut icon" href="/static/img/pageshot-icon-32.png?rev=f6111c2">
<link rel="stylesheet" href="/static/css/frame.css?rev=f6111c2">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:description" content="From reddit.com">
<meta property="og:image" content="https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397">
<meta property="og:image:height" content="347">
<meta property="og:image:width" content="863">
<meta property="og:title" content="r/gaming &#x2022; /r/gaming">
<meta property="og:type" content="website">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:description" content="From reddit.com">
<meta property="twitter:image" content="https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397">
<meta property="twitter:title" content="r/gaming &#x2022; /r/gaming">
<title>r/gaming &#x2022; /r/gaming</title>
```

versus the Twitter card sample code at https://dev.twitter.com/cards/types/summary-large-image:

```html
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@nytimes">
<meta name="twitter:creator" content="@SarahMaslinNir">
<meta name="twitter:title" content="Parade of Fans for Houston’s Funeral">
```

Not sure if we want to change our `<meta property="twitter:*">` to `<meta name="twitter:*"/>`. I don't know if it matters or if Twitter/Facebook normalize that anyways, but might be nice to see if changing the Twitter specific meta tags clears up any warnings, etc.

**Comment by ianb** [comment]
Fixed in Twitter per https://github.com/mozilla-services/pageshot/issues/1562#issuecomment-249013424

Seems good in Facebook too:

![image](https://cloud.githubusercontent.com/assets/44390/18764328/7f9329fc-80d6-11e6-887b-0e17ad433f93.png)
