### ISSUE TITLE
The bottom of the saved shot preview page displays an unneeded dark grey section depending on the image dimension

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1469]
[Affected versions]:
- Nightly 51.0a1
- Mozilla Page Shot 0.1.201609062200

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201609062200) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to any page.
2. Click on the "Page Shot" button from browser toolbar and perform a small selection.
3. Save the selection and observe the saved shot preview page.

Expected result]:
- The bottom of the page has the same color like the background that surrounds the image.

[Actual result]:
- Under the image, the page displays an unneeded section in dark grey color. 

[Notes]:
- This issue is not reproducible if a large shot is saved.
- Added a screen recording with the issue: http://goo.gl/2LF6b9.

**Comment by johngruen** [comment]
This looks fixed in latest master
