### ISSUE TITLE
Move legal HTML out of model.js?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1476]
Re: [./server/src/pages/legal/model.js](https://github.com/mozilla-services/pageshot/blob/master/server/src/pages/legal/model.js),

This is a bit awkward to edit/modify when the line is 7800 characters long in a single string. (just see my super-rad diff in https://github.com/mozilla-services/pageshot/pull/1474/files)

Not sure if easier to move into some "privacy.html" and "terms.html" so we can edit/lint those more easier-ly.

```js
const readFile = require('fs').readFileSync;

const terms = {
  title: "Terms of Service",
  content: readFile("terms.html").toString()
};

const privacy = {
  title: "Privacy Notice",
  content: readFile("privacy.html").toString()
};

exports.createModel = function (req) {
  const base = req.baseUrl;
  if (base === "/terms") {
    return terms;
  }
  return privacy;
};
```

FWIW, the "/terms" file seems fine, but there is a syntax error in "/privacy".

**Comment by ianb** [comment]
+1 on using readFile (maybe relative to `__dirname`)

**Comment by fzzzy** [comment]
I'd rather the markup be moved into jsx so we don't have to use dangerouslySetInnerHTML.

**Comment by pdehaan** [comment]
All the places we're currently using `dangerouslySetInnerHTML()`:
https://github.com/mozilla-services/pageshot/search?utf8=%E2%9C%93&q=dangerouslySetInnerHTML

![](https://linustechtips.com/main/uploads/monthly_09_2015/post-104353-0-89256600-1443512974.jpg)

**Comment by fzzzy** [comment]
Export isn't even turned on right now and text clips have been gone for probably almost a year, so the only place we actually need it right now is the Raven activation.

**Comment by fzzzy** [comment]
We could actually move the raven activation script to it's own url to avoid having to use dangerouslySetInnerHTML at all.
