### ISSUE TITLE
Screenshots look a bit blurry

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1478]
Not sure if this was from my non-retina screen, but the screenshot looks slightly blurry:

https://pageshot.dev.mozaws.net/S2hEXUGyma6zrIim/github.com

![mozilla-services_pageshot](https://cloud.githubusercontent.com/assets/557895/18331371/46d226c8-7513-11e6-9db5-8db9b071cde0.png)

Versus

![pageshot_model_js_at_master_ _mozilla-services_pageshot](https://cloud.githubusercontent.com/assets/557895/18331376/5064a972-7513-11e6-8800-c14980e8c56e.png)

**Comment by ianb** [comment]
This is probably #1006

**Comment by pdehaan** [comment]
I'll buy that. Closing in favor of #1006.
