### ISSUE TITLE
Add tooltips to Share and Delete icons on shot details page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1479]
```js
{
  source: "https://github.com/mozilla-services/pageshot/",
  description: "Page Shot application server",
  version: "September 07, 2016 21:18:59 UTC",
  commit: "ff447ed",
  contentOrigin: "pageshotcontent.dev.mozaws.net",
  commitLog: "https://github.com/mozilla-services/pageshot/commits/ff447ed"
}
```

https://pageshot.dev.mozaws.net/S2hEXUGyma6zrIim/github.com

If I hover over the "Share" and :garbage: icon for >3s, I don't seem to get a tooltip for the buttons. We should probably add a basic `title` attribute for `<button class="share-button" />` and `<button class="trash-button" />`.

![mozilla-services_pageshot](https://cloud.githubusercontent.com/assets/557895/18331443/da6a6f58-7513-11e6-94bf-277f0c6082d8.png)

**Comment by ianb** [comment]
I added a title to the trash icon in 76714f3c8ad8d842bd3e25e06213696c28e38b85

I think the Share icon is self-explanatory

**Comment by johngruen** [comment]
Nobody had trouble in user testing, so yeah
