### ISSUE TITLE
Screenshot Save Is really slow sometimes

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1501]
![slow-shot](https://cloud.githubusercontent.com/assets/3323249/18395613/6a3290dc-76bf-11e6-8518-de869f87d028.gif)

There's more than a second btwn clicking the screenshot and anything happening.

**Comment by ianb** [comment]
It's not clear from the video where the pause is.  Is this after you click Save?

There is a problem where it's only after the clip has completely uploaded that we open the tab.  I suggested in #1146 that we should open the tab right away, and let the server catch up (showing a waiting message there, I suppose).  It didn't seem important enough to do for release, but we could revisit that decision.

**Comment by johngruen** [comment]
@ianb from the time the cursor who goes from pointer back to auto until the new tab...

**Comment by ianb** [comment]
Solution described in #1509
