### ISSUE TITLE
Add a Download link on the frame page between share and delete

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1508]
I will provide an SVG icon shortly

**Comment by ianb** [comment]
I'd suggest we construct a filename something like:

`PageShot-{creation-year}-{month}-{day}-{domain}-{title}.png`

The title should be a filename-safe and of some limited length.  Hopefully year-month-day won't confuse people too much, while letting it sort nicely.  Mostly we shouldn't have a UUID in the filename.

**Comment by johngruen** [comment]
wfm

**Comment by johngruen** [comment]
@fzzzy class the button as 'button secondary'

**Comment by johngruen** [comment]
here's an svg icon

https://gist.github.com/johngruen/87df6a3e6e37ac7e1cf264d875c6c45f
