### ISSUE TITLE
If a selection with reduced height is performed too close to the top of the page, the "Cancel" and "Save" buttons are not visible

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1522]
[Affected versions]:
- Nightly 51.0a1
- Mozilla PageShot 0.1.201609130809

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201609130809) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to https://en.wikipedia.org/wiki/Main_Page.
2. Click on the "Page Shot" button from browser toolbar.
3. On the top corner of the page perform a selection with reduced height over the account section area.
3. Observe the "Save" and "Cancel" buttons.

Expected result]:
- The "Save" and "Cancel" buttons are visible.

[Actual result]:
- The "Save" and "Cancel" buttons are not visible because are displayed on the top part of the selection.

[Notes]:
- Added a screen recording with the issue: http://goo.gl/4aH028.

**Comment by ianb** [comment]
Maybe we can use the same logic we use to decrease the size of the handles (look in selector-ui.js for `pageshot-small-selection`), and add a class which lets the Save/Cancel render below the selection entirely.

**Comment by ianb** [comment]
We're discussing solutions in #1629
