### ISSUE TITLE
Local Latency Flag causing problems

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1524]
@ianb Two issues here when i set the local latency flag you describe in #1515:

1. I get an error, after the 5000ms delay, maybe this is just b/c of local nonsense, but it'd be nice to understand what's up
2. On the original page I'm capturing from, the select area never clears, yet the buttons don't do anything

Here's a video:
https://www.dropbox.com/s/fsnrz8y3nfleovt/Local-latency-glitch.mov?dl=0

**Comment by ianb** [comment]
I opened #1532 to describe case 2.  Case 1 will be fixed in 94b3feaf70bc922ff38869114623fd326d7c29db
