### ISSUE TITLE
404 on https://pageshot.dev.mozaws.net/static/img/bgtexture.png

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1528]
Looks like this may have been deleted in recent https://github.com/mozilla-services/pageshot/pull/1512 PR.

```json
{ "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "September 14, 2016 15:18:14 UTC",
  "commit": "8120a43",
  "contentOrigin": "pageshotcontent.dev.mozaws.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/8120a43" 
}
```

![welcome_to_page_shot](https://cloud.githubusercontent.com/assets/557895/18534056/9a33746e-7a9c-11e6-87f7-77e1447ad736.png)

**Comment by ianb** [comment]
I'm assuming @johngruen intended to delete the CSS rule and didn't, I will remove the rule in ecadd95d1f8a0a8a933290a4046fd7ef4541aa6a
