### ISSUE TITLE
Page Shot icon from the browser toolbar, is hardly visible on Developer Edition bowser

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1537]
[Affected versions]:
- Aurora 50.0a2
- Mozilla Page Shot 0.1.201609141513

[Affected Platforms]:
- All Windows
- All Mac OS

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201609141513) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite.
2. Observe the "Page Shot" icon from the browser toolbar.

[Expected result]:
- The "Page Shot" icon has the same color as the others icons from the browser toolbar and is perfectly visible.

[Actual result]:
- The Page Shot icon is hardly visible. 

[Notes]:
- Probably this reproduces on all dark themes available for Firefox or on Firefox high contrast theme.
- Added a screen shot with the issue:

![aurora chanel page shot icon](https://cloud.githubusercontent.com/assets/19226534/18591162/30ae4452-7c3a-11e6-9ba2-4c6745b517c9.png)

**Comment by pdehaan** [comment]
IIRC, I think @dannycoates helped with this on TestPilot (see  https://github.com/mozilla/testpilot/pull/1182).

**Comment by ianb** [comment]
Got it all worked out via IRC.  I'm making the foreground of the icon `#f2f2f2` which I *think* is the right color.
