### ISSUE TITLE
"My Shots" button is not working and the icons from the button are not displayed on Instagram website

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1539]
[Affected versions]:
- Firefox 48.0.2 and up
- Mozilla Page Shot 0.1.201609141513

[Affected Platforms]:
- All Windows
- All Mac OS

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201609141513) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and go to www.instagram.com.
2. Click on the "Page Shot" icon from the browser toolbar.
3. Observe "My Shots" button from the top right corner of the page.
4. Click the "My Shots" button.

[Expected result]:
- Step 3: The icons from the "My Shots" button are correctly displayed.
- Step 4: After clicking the button you are redirected to the saved shots page.

[Actual result]:
- Step 3: The icons displayed on the button, before and after "My Shots" text are not visible. 
- Step 4: After the button is clicked, a selection is performed instead of opening the saved shots page.

[Notes]:
- Only in Instagram site,  the "My Shots" button is actionable only on the bottom part. The action radius seems broken, you need to click the bottom part of the button to work.
- Also, the "Cancel" and "Save" buttons from selection functionality, are wrongly positioned one above the other.
- Added a screen recording with the issue: https://goo.gl/XLqDGq.

**Comment by ianb** [comment]
Instagram seems to be working now (except for #1997 which I'll address in that ticket)
