### ISSUE TITLE
Styled 404 page?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1548]
Ideally nobody would ever see 404 pages, but as somebody who always struggles to find the latest XPI while we get this moved over to Test Pilot, I've probably seen it far too often.

### Spoiler alert:

![mozilla_firefox](https://cloud.githubusercontent.com/assets/557895/18649689/b658baa0-7e75-11e6-8780-3cf145ecdc3d.png)

---

### Steps to reproduce:

```sh
$ http get http://pageshot.dev.mozaws.net/homepage/mozilla-pageshot.xpi -v

GET /homepage/mozilla-pageshot.xpi HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: pageshot.dev.mozaws.net
User-Agent: HTTPie/0.9.1

HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 9
Content-Security-Policy: default-src 'self'; img-src 'self' www.google-analytics.com pageshotcontent.dev.mozaws.net data:; script-src 'self' www.google-analytics.com 'nonce-ae993b24-eaf2-450d-aa93-596c3aeaa4f9'; style-src 'self' 'unsafe-inline' https://code.cdn.mozilla.net; connect-src 'self' www.google-analytics.com; font-src https://code.cdn.mozilla.net;
Content-Type: text/plain; charset=utf-8
Date: Mon, 19 Sep 2016 21:29:01 GMT
ETag: W/"9-ngdvWIX1zBakta643krf9Q"
Server: nginx/1.8.1
X-Frame-Options: DENY
X-Powered-By: Express

Not found
```

**Comment by ianb** [comment]
Added in 3ba6f266127608e18a987492c902babbe792d715

Looks like this:

![image](https://cloud.githubusercontent.com/assets/44390/19486683/f72a17b6-9524-11e6-8a8f-025723d957b0.png)

Leaving this ticket open to review the styling and message.  Look in `server/src/pages/not-found/view.js` for the actual copy.
