### ISSUE TITLE
Odd redirect behavior w/ Activity Stream

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1551]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18650298/39ea1596-7e79-11e6-854b-0cb7bc088580.png)

I have the [Activity Stream](https://testpilot.firefox.com/experiments/activity-stream) experiment installed, and the above version of Page Shot. 

If I open a new tab, then find something I want to Shot on that page, I click the Page Shot icon in the toolbar, expecting to take a screenshot. Instead I am redirected to https://pageshot.dev.mozaws.net/shots without any notice or doorhanger.

### Actual results:
Impossible to screenshot Activity Stream pages w/ Page Shot?

### Expected results:

Ability to screenshot, or a message explaining why it isn't possible -- like this message when I try and grab a shot of about:config:

![about_config_and_tough-cookie](https://cloud.githubusercontent.com/assets/557895/18650402/c8933110-7e79-11e6-8d54-606081ed5844.png)

**Comment by ianb** [comment]
Right now we are treating the Activity Stream page the same as about:newtab, and doing the same thing that Pocket does – treating a button click on new tab as a shortcut to My Shots.

Arguably `resource://activity-streams/data/content/activity-streams.html#/timeline` should be treated differently than `resource://activity-streams/data/content/activity-streams.html#/`, but I dunno.  @johngruen : thoughts?

**Comment by pdehaan** [comment]
And in debugging another bug I just filed, I think I see the reasoning:

```js
  if (url.startsWith("resource:") || url === "about:blank" || url === "about:newtab") {
    tabs.activeTab.url = backend + "/shots";
    return;
}
```
&mdash; via [/addon/lib/main.js:212-215](https://github.com/mozilla-services/pageshot/blob/bb66ece08b1a773d9dbf18f16673e87ddac3656a/addon/lib/main.js#L212-L215)

**Comment by ianb** [comment]
I think the resource: test is too general, we should be catching Activity Stream URLs specifically, but the specific behavior you found is what we intended.

**Comment by ianb** [comment]
If the resource URL is an HTML page, yes, there's nothing stopping us from taking a shot of it.  Typically only add-ons have resource pages, so we can only think about whether it makes sense given other specific add-ons (and I haven't been testing with any add-ons besides Activity Stream, so I haven't really thought it through).

**Comment by ianb** [comment]
We're going to keep the redirect behavior in.
