### ISSUE TITLE
Twitter Card preview doesn't look so great

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1562]
![blank_skitch_document](https://cloud.githubusercontent.com/assets/557895/18680920/777d2140-7f1a-11e6-87d4-5c60b88b3690.png)

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18680943/960d7d94-7f1a-11e6-9c6b-6739d4e82039.png)

I took this shot: https://pageshot.dev.mozaws.net/1LSzd989On8jpiNW/www.reddit.com

If you type ^^^ that URL into the Twitter Card validator at https://cards-dev.twitter.com/validator, you get this:

<img width="590" alt="card_validator___twitter_developers" src="https://cloud.githubusercontent.com/assets/557895/18680979/cda57356-7f1a-11e6-909d-9881fe413ea4.png">

---

If I run my Page Shot shot URL through my handy [meta-scraper](https://github.com/pdehaan/meta-scraper) CLI, I get the following `<link>`, `<meta>`, and `<title>` tags:

```sh
./bin/cli.js --url https://pageshot.dev.mozaws.net/1LSzd989On8jpiNW/www.reddit.com
```

```html
<link rel="alternate" type="application/json+oembed" href="https://pageshot.dev.mozaws.net/oembed?url=https%3A%2F%2Fpageshot.dev.mozaws.net%2F1LSzd989On8jpiNW%2Fwww.reddit.com" title="r/gaming &#x2022; /r/gaming oEmbed">
<link rel="icon" type="image/png" href="/static/img/pageshot-icon-32.png?rev=a61aef1">
<link rel="shortcut icon" href="/static/img/pageshot-icon-32.png?rev=a61aef1">
<link rel="stylesheet" href="/static/css/frame.css?rev=a61aef1">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:description" content="From reddit.com">
<meta property="og:image" content="https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397">
<meta property="og:image:height" content="347">
<meta property="og:image:width" content="863">
<meta property="og:title" content="r/gaming &#x2022; /r/gaming">
<meta property="og:type" content="website">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:description" content="From reddit.com">
<meta property="twitter:image" content="https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397">
<meta property="twitter:title" content="r/gaming &#x2022; /r/gaming">
<title>r/gaming &#x2022; /r/gaming</title>
```

The `twitter:image` image looks pretty kosher, so not 100% sure what's going on, unless it is some CSP error or something:

![](https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397)
-- https://pageshot.dev.mozaws.net/images/73fc80ec-a3ad-4c29-b7d1-79dfc8430397

**Comment by ianb** [comment]
Weird indeed.  I wonder if there's any image size requirements on these images?

**Comment by pdehaan** [comment]
/cc @chuckharmston -- Did you ever see this while implementing the Test Pilot share/social stuff?
Curious why my `<meta property="og:image">` and `<meta property="twitter:image">` _looks_ legit, but the image doesn't seem to render in the validator.

I'll see if I can create some dummy HTML in a gist and see if I can get Twitter to validate against that, since seemingly there isn't a direct input text field. At least that'll let me see if `<meta property="twitter:image">` vs `<meta name="twitter:image">` makes a difference.

**Comment by chuckharmston** [comment]
@pdehaan I don't see anything obvious. Could be that the image file doesn't have an extension?

**Comment by pdehaan** [comment]
I found some Facebook sharing best practices: https://developers.facebook.com/docs/sharing/best-practices

Definitive Twitter data isn't as easy to find. So far I found https://dev.twitter.com/cards/types/summary-large-image:

> #### `twitter:image`

> A URL to a unique image representing the content of the page. You should not use a generic image such as your website logo, author photo, or other image that spans multiple pages. **Images for this Card should be at least 280px in width, and at least 150px in height.** Image must be less than 1MB in size.

We definitely are larger than those dimensions, but not sure about filesize. Dimensions from above meta scraping are:

```html
<meta property="og:image:height" content="347">
<meta property="og:image:width" content="863">
```

**Comment by ianb** [comment]
This is looking okay now:

![image](https://cloud.githubusercontent.com/assets/44390/18764240/1e7d9c9c-80d6-11e6-9556-a358fcbaa2d3.png)

When the image is too wide it just gets truncated:

![image](https://cloud.githubusercontent.com/assets/44390/18764279/44bb474c-80d6-11e6-9dc7-e25e17f711cf.png)
