### ISSUE TITLE
Trying to share a Page Shot shot on Twitter or Facebook gives me an about:blank page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1563]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18681413/d0174c7a-7f1c-11e6-8ff2-c1a89b8282ed.png)

I have the following _super rad_(tm) Shot: https://pageshot.dev.mozaws.net/0jwCSt1vR3lvgFnd/www.bing.com

When I go to the page above, and click the Share button, and then select Facebook or Twitter, it launches a new tab/window and the address is about:blank, which is a pretty quick dead end.

---

I have a Browser Console which says this:

![browser_console](https://cloud.githubusercontent.com/assets/557895/18681476/25e86a62-7f1d-11e6-84a8-27ca5b4103c8.png)

Looks like the background.bundle.js file is view-source:moz-extension://1fef7b30-90fd-c447-846f-4faa5bbca13a/js/background.bundle.js which could be any of these, but I have reasons to suspect "Tracking Protection Experiment" maybe:

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18681531/56715f40-7f1d-11e6-8873-5e717fdc0bc4.png)

**Comment by pdehaan** [comment]
Disabling Block/Tracking Protection seems to launch Twitter as expected... Ruh roh.

**Comment by ianb** [comment]
I don't see an error in the page or browser console that explains this, though I assume it's an exception of some sort.  The share links are super-simple, just `<a href="https://twitter.com/home?status={message}" target=_blank>` – there *is* an onClick handler that sends a GA event, but it doesn't do anything else and expects the default handler to still fire.  (And something does fire, just with about:blank.)

**Comment by pdehaan** [comment]
from @groovecoder in IRC:

>  this doesn’t just affect pageshot.dev.mozaws.com :( from https://davidwalsh.name/ I can’t visit twitter.com either :(
> i.e., clicking on the twitter link

**Comment by ianb** [comment]
Nothing for us to fix then, see https://github.com/mozilla/blok/issues/155 for (eventual) resolution
