### ISSUE TITLE
Update home page link to deep link to the Page Shot experiment page.

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1564]
Need slug.

I wouldn't consider this a hard blocker for launch though.

**Comment by pdehaan** [comment]
Re: https://github.com/mozilla-services/pageshot/search?utf8=%E2%9C%93&q=testpilot.firefox

I imagine it'd need to be changed in these possibly these 1-2 places (depending on whether we want a hyphenated slug or not):

1. [server/src/pages/homepage/view.js:42](https://github.com/mozilla-services/pageshot/blob/7d4fd791255f41178a6e4ae9906b20e921746e2b/server/src/pages/homepage/view.js#L42):

    ```html
<a className="button primary" href="https://testpilot.firefox.com/">Coming soon to Firefox Test Pilot</a>
```

1. [server/src/pages/leave-page-shot/view.js:54](https://github.com/mozilla-services/pageshot/blob/f5b79cc35aa9c9092f3a9c2a928c1ca42571ba90/server/src/pages/leave-page-shot/view.js#L54):

    ```html
<a className="button primary" href="https://testpilot.firefox.com/experiments/page-shot">Go to Test Pilot</a>
```

**Comment by ianb** [comment]
Let's avoid using `pageshot` some places and `page-shot` other places.

**Comment by johngruen** [comment]
`pageshot` is fine

**Comment by johngruen** [comment]
on second thought, or slug should be `page-shot`, i realize this is a little less than internally consistent on the page shot end, but it matches the overall Test Pilot naming pattern
