### ISSUE TITLE
Share button doesn't align nicely on Chrome

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1565]
Due to the topbar...

![image](https://cloud.githubusercontent.com/assets/44390/18682070/76de9f5a-7f30-11e6-906c-bbb767b8101e.png)

**Comment by pdehaan** [comment]
For comparison sake, here's what it looks like on today's Firefox Nightly (52.0a1):

![bing_and_add-ons_manager_and_nightly](https://cloud.githubusercontent.com/assets/557895/18682210/34540b76-7f20-11e6-9012-e748f8ab6248.png)

Also note that on Chrome there is an unfortunate gap between the "get a shareable link" text input and the Copy button (which doesn't exist on FF Nightly).

**Comment by ianb** [comment]
I wonder if it would work to make the share panel a child of the share button?  Then they'd move around together.
