### ISSUE TITLE
about:addons page is a bit overwhelming

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1569]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/18690553/6e273e86-7f43-11e6-80f2-b8532dc5a94a.png)

Not sure if we _need_ all those configs listed in about:addons (and want users fiddling with them) versus hiding them behind about:config flags.

Turns out, finding all the configs in about:config was a bit tricky though, as I only got 2 results when searching for "pageshot":

![about_config](https://cloud.githubusercontent.com/assets/557895/18690606/c8b8e0e8-7f43-11e6-94f5-4a1422cad7f0.png)

If you want to find _all_ the values, you need to search for "jid1-NeEaf3". Not sure why it's so cryptic, but it seems to be the [/addon/package.json's `id` property](https://github.com/mozilla-services/pageshot/blob/9034ffed3ff4b26c2b62ee8734f04775e4940b99/addon/package.json#L4): 

```js
"id": "jid1-NeEaf3sAHdKHPA@jetpack",
```

For Activity Stream and Test Pilot, I can just search for "@activity-streams" and "@testpilot" respectively.

**Comment by ianb** [comment]
The current id is random.  I suppose we could change the id of the package now, after release we won't be able to.  We can switch a bunch of these to be hidden in package.json.

**Comment by ianb** [comment]
I hid most of the things, leaving just:

![image](https://cloud.githubusercontent.com/assets/44390/18731459/aba6ea52-8021-11e6-8dae-85fb2c32e73b.png)
