### ISSUE TITLE
Implement a new panel concept

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#157]
As [clipped here](https://pageshotpages.appspot.com/summary/nWone0WVM_/www.lucidchart.com)

![image](https://cloud.githubusercontent.com/assets/44390/6274120/c0613e8a-b83a-11e4-97d5-bcd6a3d292b3.png)

**Comment by brampitoyo** [comment]
Better quality screenshot below. Note that I’ve updated the popover slightly over at Lucidchart:
![pageshot-popover](https://cloud.githubusercontent.com/assets/51007/6282176/5b857d4a-b935-11e4-8395-88a1080639ae.png)
