### ISSUE TITLE
multiple errors in the same session makes the error panel width grow

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1600]
STR

* go to about:addons
* try to take a page shot
* do it again and again

**Comment by ianb** [comment]
I think this is a bug in Nightly (e.g., try to hit the Test Pilot button when the Test Pilot panel is already open)

**Comment by ckprice** [comment]
This is probably a Test Pilot bug.

**Comment by ianb** [comment]
I think this is okay now.
