### ISSUE TITLE
Direct Feedback to Discourse

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1604]
We have a [Discourse topic](https://discourse.mozilla-community.org/t/about-the-page-shot-category/11036) – maybe that's the best way for people to give feedback, and it helps get the discussion going?  (I've noticed Discourse has been pretty quiet for experiments)

**Comment by fzzzy** [comment]
Yeah I think this is a good idea.

**Comment by ckprice** [comment]
Closing this as our email feedback list is doing well.
