### ISSUE TITLE
https://pageshot.net/ still says "coming soon"

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/pageshot#1605]
What should we change this to?

**Comment by meandavejustice** [comment]
![2016-09-28_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1844554/18929300/f690e37c-8591-11e6-9cbe-27856d46206d.png)

**Comment by ianb** [comment]
"Try it out with Firefox Test Pilot"?

**Comment by pdehaan** [comment]
@johngruen @ckprice  What say ye? What should the https://pageshot.net/ homepage say now that we've released on Test Pilot?

I can do a quick PR if it's just a string change. Or if it's a more complex auto-forwarder with actual work, I'll leave it to the big kids.

**Comment by ianb** [comment]
@pdehaan : nothing more than a string change, the behavior is still how we want it.

Another language suggestion (more action-oriented): "Install Page Shot with Firefox Test Pilot"

**Comment by ckprice** [comment]
I'm making an executive decision: `Install Page Shot with Firefox Test Pilot`.

Thanks!
