### ISSUE TITLE
enabling error

### ISSUE THREAD

**Issue by DGIFFORD2003** [mozilla-services/pageshot#1608]
shot page will not enable

**Comment by ianb** [comment]
Could this be the same thing as in https://github.com/mozilla/testpilot/issues/1468 ?  (If that doesn't work, it's another installation problem with Test Pilot that we're looking at.)

**Comment by ckprice** [comment]
@DGIFFORD2003 please try to restart. Closing in favor of https://github.com/mozilla/testpilot/issues/1474.
