### ISSUE TITLE
Can not install Page Shot...

### ISSUE THREAD

**Issue by Samizdata** [mozilla-services/pageshot#1609]
I have tried 5 or 6 times today to enable Page Shot, which looks like an awesome tool to me.  Unfortunately, every time I try to do so, I see the following...

http://imgur.com/Y64fYkn

Any ideas anyone?  (I do have other Test Pilot experiements currently running...)

**Comment by ianb** [comment]
I wonder if this is https://github.com/mozilla/testpilot/issues/1468 ?

The fix was to uninstall the Test Pilot extension and then re-install it.  If you try that and it works, please report back!

**Comment by Samizdata** [comment]
Yup.  Apparently so.  At the very least, it seems to load with no issues.  Now to get the rest of the Experiments I used up and running.  Cheers!
On 9/28/2016 9:30:29 PM, Ian Bicking <notifications@github.com> wrote:
I wonder if this is mozilla/testpilot#1468 [https://github.com/mozilla/testpilot/issues/1468] ?
The fix was to uninstall the Test Pilot extension and then re-install it. If you try that and it works, please report back!

**Comment by Samizdata** [comment]
Actually, I take that back with caveats.  Page Shot installed, but now No More 404's is throwing the same error (had been previously installed).

**Comment by deepdivingspearo** [comment]
Was also not able to install this and any new test pilot feature.
Workaround: Disabling test pilot addon > re-enabling it > restarting browser fixed the issue for me.

**Comment by ckprice** [comment]
Closing in favor of https://github.com/mozilla/testpilot/issues/1474.
