### ISSUE TITLE
Add option for a fullpage screenshot

### ISSUE THREAD

**Issue by myBestSoftAndPref** [mozilla-services/pageshot#1613]
There is not **"choose all page"** option like in [Screengrab (fix version)](https://addons.mozilla.org/en-US/firefox/addon/screengrab-fix-version/)
or even in Developer Tools instruments.

It's really weird situation for so big corporation with good programmers like Mozilla!

**Comment by fzzzy** [comment]
We actually did have this feature in earlier versions of Page Shot but we really simplified the product down to the bare minimum for launch. I do think this would be a very useful feature. Hopefully we will be able to add it back in soon.

**Comment by ianb** [comment]
@myBestSoftAndPref : out of curiosity, when you say "choose all page" do you mean the entire visible area, or the entire page including lower parts of the page that may not be visible?

Also, can you share what you want to use the whole-page capture for?  This might help us figure out where to put the controls and how to describe them in a later version.

**Comment by jnachtigall** [comment]
@myBestSoftAndPref @ianb I'm not the OP but did an upvote. 

For me this would be entire page, i.e. exactly what `screenshot --fullpage` does in the devtools. To me, this is the one USP that pageshot has over other screenshot software where this is technically not possible. (Before `screenshot --fullpage` me and other people usually did several screenshots and then post-edited them in Gimp/Photoshop to assemble them back together)

I use this very often to share screenshots with desigerns / devlopers where I only have a desktop which is `y` pixels high (e.g. 768), but the area that is of interest is bigger than `y` (e.g. a longish page).

**Comment by jnachtigall** [comment]
FWIW, if the dragging (area selection) would scroll the page down when it hits the bottom so that the actual screenshot area can be bigger than the screen size, then this might be also ok instead of a fullpage option. 

Maybe also make the selection snappy towards the edges of the browser window so that's it's easy to select the full width/height.

**Comment by ianb** [comment]
#193 describes the scroll-near-edge-of-page feature.  I opened #1658 about making sure the snapping that does exist includes the edges of the screen.

If you are patient you can currently make a selection larger than the size of the screen by resizing, scrolling, resizing, until you've got it to the size you want.

**Comment by ianb** [comment]
This will land in a simple state in 40088fe95482c936c657ddce94fe694e4bc5aecd (pending review) looking like:

![image](https://cloud.githubusercontent.com/assets/44390/19203232/c4143a78-8c9b-11e6-9b32-9e701716aeed.png)

I just added two vertically-stacked buttons for the two options.  Obviously we'll want to review the UX.  Both buttons capture the respective regions and immediate save/upload and open a new tab.

**Comment by johngruen** [comment]
@ianb could you make all three buttons the same width?

**Comment by johngruen** [comment]
https://mozilla.invisionapp.com/share/WF8V8N1NX#/screens/194888784_Home1

**Comment by fzzzy** [comment]
I think this is fixed now in master, right?

**Comment by ChenMorpheus** [comment]
Hi all,
We came up with the visual style with Windows shot and Fullpage shot. Please find the link below for more details, and let me know if we need to file another ticket, thanks.

https://mozilla.invisionapp.com/share/ER934Y4ND#/197768052_1-1_Select_Modes

**Comment by johngruen** [comment]
@ChenMorpheus we may roll this out iteratively, can you provide the icon assets from the spec as SVGs?

**Comment by fangshih** [comment]
Here are the icons assets, Thanks! 
[#1613 Fullpage-icon-Assets.zip](https://github.com/mozilla-services/pageshot/files/555131/1613.Fullpage-icon-Assets.zip)

**Comment by ianb** [comment]
This feature was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
