### ISSUE TITLE
No /contribute.json

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/pageshot#1625]
I found a bug in page shot and want to file but couldn't find it in either bugzilla or github.com/mozilla

Thanks to IRC I found this repo here. 

If only there was a https://pageshot.net/contribute.json I would be able to find it.  :)

**Comment by ianb** [comment]
Note the issue link is also on https://testpilot.firefox.com/experiments/page-shot – but contribute.json would be easy enough to add as well.

I'll add a separate issue for adding a GitHub link to https://pageshot.net/

**Comment by pdehaan** [comment]
Ref: https://www.contributejson.org/
Not sure if there'd be an easy way to auto-generate the contribute.json from our existing package.json values, or if the schema is radically different.

**Comment by ianb** [comment]
I'd be inclined to just hardcode it in server.js.

**Comment by pdehaan** [comment]
Wow, package.json as a contribute.json _ALMOST_ works, apart from the odd fact that contribute.json expects a `repository` property to have a nested `license` property (whereas package.json has the `license` as a top-level property).

Schema snippet:
```
        "repository": {
            "properties": {
                "clone": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "tests": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "required": [
                "url",
                "license"
            ],
            "type": "object"
        },
```
