### ISSUE TITLE
Add GitHub link somewhere to the homepage

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1626]
The [homepage](https://pageshot.net/) would be a reasonable place for a GitHub link, as well as the footer itself.

**Comment by pdehaan** [comment]
Yeah, for Test Pilot we have a GitHub [and Twitter] icon and we just right-float them in the footer:

![firefox_test_pilot_and_inline-selection_scss_ _pageshot](https://cloud.githubusercontent.com/assets/557895/18966957/34449ae6-8638-11e6-8391-d9d8a5cca540.png)
