### ISSUE TITLE
Reduce the number of steps required to get a sharable URL into your clipboard

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/pageshot#1627]
I currently use Jumpshare.com here on my mac. 
[It's the best of all terrible when it comes to displaying the image](https://www.peterbe.com/plog/screenshot-sharing-performance-comparison). Page Shot beats it easily! (Just need to fix the [static asset cache](https://github.com/mozilla-services/pageshot/issues/1624))

However, what it gets right is the number of step. Here's how I take and share a screenshot:

1) Cmd-Shift-4
2) Drag an area and release the mouse click
3) ...wait a 1 second...
4) Go to irc, email, document, and Cmd-V to paste in the URL to the image. 

With Page Shot I have to...:

1) Click the icon in the upper right-hand corner
2) Drag an area and release the mouse click
3) Click the Save button
4) Wait for it to redirect and load the pageshot.net permalink URL for that new shot. 
5) In the upper right-hand corner, click the Copy button
6) Go to irc, email, document, and Cmd-V to paste in the URL to the image. 

What would make it much much faster is if, like Jumpshare, as soon as I release the click after dragging an area it should put the pageshot.net permalink URL in my clipboard. Even before the image has been uploaded. By the time I've managed to go back to my IRC window (or whatever I'm doing to share my screenshot) and pasted it in with some message and the time it takes my friend to click it, that should be enough time to do the upload in the background. 

And if my friend is super fast and clicks my permalink, and the image isn't there yet it could be aware of that in code and say so and refresh the page automatically when the content is ready.

**Comment by pdehaan** [comment]
FWIW, I currently have a bunch of code in my clipboard (or whatever), so I generally get pretty salty when an app decides that it should just erase everything in my clipboard without my consent.

**Comment by fzzzy** [comment]
Page Shot originally copied the link to the clipboard automatically. Since that can have unintended consiquences we took it out. Maybe it should be a configurable option that is off by default so people can choose for themselves.

**Comment by pdehaan** [comment]
> Page Shot originally copied the link to the clipboard automatically.

That's right! I forgot I was complaining about that recently...
Ref: **PageShot erases everything in my clipboard** #1237

**Comment by ianb** [comment]
Technically we determine the URL the moment you hit the PageShot button, so we don't have to worry about Save finishing.  The upload progress page could also contain a copy button, though we'd want to make sure it was placed right where the ultimate copy button goes, as it'd be easy to go for it at exactly the moment the page finishes uploading.  

We could have a setting (maybe in the share panel itself), but settings are a bummer if we can avoid them.

We talked about having copy with undo, i.e., you could "undo" the autocopy and get your old clipboard content back.  That actually would be nearly as easy as any of the other techniques (less UI surface area), though it seems like an uncommon choice.

**Comment by peterbe** [comment]
I'm aware that my big issue text could be broken up into smaller bits. Just trying to help by dumping my impressions. 

1) Interesting that it bothers people that it erases what you previously had in the clipboard. I think I've grown so used to it that I'm not even questioning it any more and it's automatically reminding me that if I take a screenshot my clipboard will be erases. 
Big +1 for a config option to switch on automatic copy-to-clipboard. 

2) I'm still not convinced about the "Save" and "Cancel" buttons. I think it should automatically assume "Save" and if I don't like it I could just ignore copying the URL it generated. 

3) Part of Instagrams success was that it felt fast. The trick they did was that they started uploading the JPG (in the background) whilst the user was typing in a text and when the user presses the Save/Upload button it just re-affirms that it should be saved. Made it feel snappy.

4) Undo copy-to-clipboard might be technically possible but it just doesn't feel very natural and I think people would spend too much time understanding that concept than it's worth. Can't even think of one app I use daily where I can undo a copy-to-clipboard. 

5) @ianb I love! that the URL is predetermined before the server upload finishes! But what happens to viewing the permalink if the upload is still taking a long time?

**Comment by ckprice** [comment]
> 1) Cmd-Shift-4
> 2) Drag an area and release the mouse click
> 3) ...wait a 1 second...
> 4) Go to irc, email, document, and Cmd-V to paste in the URL to the image. 

+1 to this. Folks (read: me) are used to this type of clipboard action.

**Comment by johngruen** [comment]
We should spec UX for this: 
- user makes a selection
- hits save
- gets notice that shot is saved to clipboard

**Comment by ianb** [comment]
The link copying is filed in #1734.  I'm closing this ticket, if there's any other ideas anyone wants to pull out ideally they'll go in new tickets as well.

**Comment by ChenMorpheus** [comment]
We came up with new visual style of toast. Please find the link below or #1844 for more details, and let me know if any questions, thanks.
https://mozilla.invisionapp.com/share/ER934Y4ND#/197768052_1-1_Select_Modes
