### ISSUE TITLE
Would like to drag the selection around, but can only resize it.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1628]
Once I select an area, I'd like to be able to adjust it by moving it around. I'm only able to resize it, which is very cumbersome.

If I'm not hovering near one of the blue resize squares, let me click and drag the whole selection.

**Comment by fzzzy** [comment]
Great idea, thanks.

**Comment by ianb** [comment]
This change was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
