### ISSUE TITLE
Place Save and Cancel UI outside of selection.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1629]
On small selections, the resizing UI is overlapped by the buttons, which is cumbersome. In the screenshot below, I'm not able to use some of the resize controls.

<img width="180" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18967525/60120d28-863a-11e6-9f1c-3c95b1d9e9b8.png">

Can we place action buttons below or beside the selection?

**Comment by ianb** [comment]
[Awesome Screenshot](https://github.com/mozilla-services/pageshot/issues/1174) does this:

![image](https://cloud.githubusercontent.com/assets/44390/18686406/6fcca872-7f41-11e6-86a8-767d5527338d.png)

Visually I also preferred this, the buttons pop better when they are over the shadow.

**Comment by ianb** [comment]
Work in 8ba92239b7bfd5a42e28c3de0fab44997d6ae1f0

Unfortunately if you select right at the bottom with the iframe approach the buttons are inaccessible.  It could be fixed, but this commit doesn't fix that.
