### ISSUE TITLE
Strange selection behaviour when "inverting" selection size.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1630]
![seleciton-lop](https://cloud.githubusercontent.com/assets/25212/18967595/a7713298-863a-11e6-8562-33581bf4e522.gif)

This looks weird. If I drag from the bottom right past the top left, can we just invert the selection so the top-left corner becomes the bottom-right and I continue drawing my box? That would be the standard behaviour.

**Comment by ianb** [comment]
Yes, this is the behavior I intentionally implemented when fixing the problem of a selection collapsing to no height or width.  The inverted selection is common, but I couldn't come up with a reason for it (outside of algorithmic simplicity).  Instead this is intended as a way to kind of bump the selection.

**Comment by flukeout** [comment]
With the current behaviour, it's doubtful that I'll get the top-left corner to end up exactly where I want it after one of the 'bumps' so I'll end up having adjusting it anyway - not sure it saves much time.

**Comment by johngruen** [comment]
@ianb i've had a few people mention this to me on slack. i think inverting the selection is the expected behavior here.

**Comment by flukeout** [comment]
+1 @johngruen - stick with expected behaviour unless the new way provides some special utility.

I could see the current way being useful as a reset for the top-left corner, but not in it's current "jumpy" implementation. If you were able to move the top left corner smoothly as you moved your mouse, that _might_ be useful.

**Comment by ianb** [comment]
This change was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
