### ISSUE TITLE
Help copy in overlay is not always noticeable.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1631]
Can we put the helper copy in a box with a darker background so it's always readable? In the screenshot below, I probably wouldn't even have noticed the copy in the context of a whole browser window.

<img width="634" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18967656/edbab44a-863a-11e6-97fc-e31eb7957e64.png">

**Comment by ianb** [comment]
3px padding, fully rounded border, black (or only slightly translucent?) background

**Comment by fangshih** [comment]
I was wondering if we bring down the overlay background to be darker, and make the copy in the center of the page. So it helps the visibility.  
![pageshot_hint_1](https://cloud.githubusercontent.com/assets/4862573/19509845/3e969784-9613-11e6-9d4e-bea7779503ee.png)

Or If it's still not obvious enough, maybe adding a little Pageshot Guy to grab user's attention?
What do you think? 

![pageshot_hint_2](https://cloud.githubusercontent.com/assets/4862573/19510080/386d8344-9614-11e6-8a72-c111bbbe8212.png)

**Comment by johngruen** [comment]
@fangshih I like the second treatment here. Can you provide the font size, you're using, along with an SVG of the icon?

**Comment by fangshih** [comment]
Attached with the SVG icon, font size and background color.  
[#1631 Overlay Visual Spec.zip](https://github.com/mozilla-services/pageshot/files/555198/1631.Overlay.Visual.Spec.zip)

**Comment by ianb** [comment]
A simple change was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
