### ISSUE TITLE
Selections near the edge of the window/screen sometimes have their Save & Cancel UI cut off.

### ISSUE THREAD

**Issue by flukeout** [mozilla-services/pageshot#1638]
The left edge of this screenshot is where my screen ends.

<img width="104" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18970121/e81800a6-8644-11e6-9f41-a7d012416914.png">

**Comment by flukeout** [comment]
In a related issue, wide selections near the top of the browser window also get their UI cut off. This one might actually be more important, as it's quite reasonable to take screenshots of page header elements like navigation UI etc...

<img width="1198" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18970187/250aefa0-8645-11e6-9bf7-b1aa5b910f48.png">

**Comment by ianb** [comment]
Thanks for the report!  We're going to track this problem and possible resolutions in #1629
