### ISSUE TITLE
Improve the Email Share Graphic

### ISSUE THREAD

**Issue by Caspy7** [mozilla-services/pageshot#1650]
Firstly, the UX on this is altogether great. Good job!

However I do have a bit of a nit with the Email Icon under Share.

I say it has poor "glance-ability." When I scanned the icons I readily identified all of them until I got to the last one (the email) which I had to stare at a second to figure out what it was. That is to say, I assert that its too complex and at the very least does not look enough like a simple envelope at a glance.

aside: I was talking with a friend (an artist) because I wanted her opinion on the colors (I thought they seemed to clash sort of, but that may be my modified [F.lux] display colors).  Anyway, she said she thought the colors were fine, but said something else so here's a snippet of the conversation:

Friend: If I saw it on a page though I'd probably have to hover over it or click to see what exactly it does though. 
Me: Curious, what made you say this?
F: Because I'm not exactly sure what it does. The FB, Twitter, & Pinterest icons I easily recognize & know what they do 
Me: thanks for your input 
F: Sure
F: Sometimes it helps that I'm non-techy :)
Me: yup :)
Me: what if it were a simple envelope? No extra decorations. What would you think it does?
F: Sends an email

I'd also add that I think the Firefox branding is unnecessary. It makes it more complex/busy and is confusing. It probably contributed to my friend's confusion. At an earlier point in the conversation she said she recognized it as an envelope and letter, so that bit is clear enough. 
While the other icons in the list use branding that associates directly with their purpose, the Firefox branding doesn't. 

I'd suggest making it a much more simple envelope.

**Comment by johngruen** [comment]
@Caspy7 thanks for the input, i just stole that graphic from Firefox Accounts when i put that page together :)

**Comment by johngruen** [comment]
Need a simpler envelope image to replace the attached should be a 60px x 60px SVG, preferably with a solid color background to match the other icons:
<img width="388" alt="screen shot 2016-10-05 at 5 45 16 pm" src="https://cloud.githubusercontent.com/assets/3323249/19132884/a2f3348a-8b23-11e6-8b6f-645c1649e760.png">

**Comment by fangshih** [comment]
Updated the envelope image to current firefox envelope glyph style, also with a solid color background in SVG file. Hope it works! 
[#1650 envelope-svg.zip](https://github.com/mozilla-services/pageshot/files/552960/1650.envelope-svg.zip)

**Comment by johngruen** [comment]
Thanks @fangshih, I'll make sure this gets in
