### ISSUE TITLE
Add the standard Share icon to the Share button

### ISSUE THREAD

**Issue by Caspy7** [mozilla-services/pageshot#1651]
The share icon (like this http://www.symbols.com/gi.php?type=1&id=1836 ) is becoming more widely recognized especially with its use on mobile devices.

Adding it before the "Share" text  could help to make the button more quickly recognized.

**Comment by johngruen** [comment]
Good idea!

**Comment by johngruen** [comment]
<img width="254" alt="screen shot 2016-10-05 at 4 29 51 pm" src="https://cloud.githubusercontent.com/assets/3323249/19130407/03502816-8b19-11e6-9039-01727a304b65.png">

**Comment by johngruen** [comment]
I will get a share icon to @fzzzy

**Comment by fangshih** [comment]
Hey guys, here is the share icon svg. 

[glyph share svg.zip](https://github.com/mozilla-services/pageshot/files/535454/glyph.share.svg.zip)

**Comment by johngruen** [comment]
Thanks @fangshih!
