### ISSUE TITLE
Why only 14 days by default?

### ISSUE THREAD

**Issue by peterbe** [mozilla-services/pageshot#1654]
As with so many many pastebins that have long since expired why only make it available for 14 days? Why not a year? 

If it's storage $$$ perhaps we can tackle that by putting old pictures in some cheap storage and if requested, and it's expired from our database we can retrieve the image from the cheap storage and reload it into the database. 

14 days is really short and I suspect that media where I'd paste the link lasts longer than 14 days. E.g. github issues, emails, tweets.

**Comment by ianb** [comment]
14 days has everything to do with the fact this is an experiment, and we can't make promises about long-term storage because we can't make promises about anything.  That said, we could probably make a 30 day promise.  Just not a forever promise.

**Comment by ckprice** [comment]
Closing this issue; we may change this in the future by the above issue provides the answer to this question.
