### ISSUE TITLE
Cannot update the add-on

### ISSUE THREAD

**Issue by JosefVitu** [mozilla-services/pageshot#1674]
Hi. Firefox (50.0b3) seems to be trying to update the Page Shot add-on, but every attempt to do so fails with the following error:

`1475489256419	addons.xpi	WARN	Download of https://testpilot.firefox.com/files/pageshot/pageshot-0.1.201609272025 failed: 403 Forbidden`

Currently installed version: 0.1.201609222137

**Comment by wresuolc** [comment]
I forgot the .xpi file extension.  This is fixed and will be live in <10min .  Thanks for the report and sorry for the troubles.
