### ISSUE TITLE
Review homepage title

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1678]
Current title is `Welcome to Page Shot` and on Test Pilot it is `Firefox Test Pilot - Page Shot`

Neither is good for the homepage IMHO.  We need to say something about what Page Shot actually does.  Something about Firefox and screenshots.

**Comment by ianb** [comment]
Since I'm in the homepage for #1423 I'm going to update it to `Page Shot, a screenshot tool for Firefox`

**Comment by johngruen** [comment]
@ianb seems like a reasonable fix for now...what's the traffic like to the home page?

**Comment by ianb** [comment]
We only fixed our tracking for the homepage yesterday, but the traffic appears negligible.  (I had to visit the page to make sure it was working.)
