### ISSUE TITLE
Popup causes Min-Vid to hide

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1680]
STR:
1. Play video in Min-Vid.
2. Use the Page Shot to create a screenshot.
2. (optional, not tested without this step) Make page shot showing an error. (it always does in my case)

What happens: The page shot error popup makes the min vid video go away. Audio keeps playing.

What should happen: Do not hide the min vid video window.

https://github.com/meandavejustice/min-vid/issues/380

Firefox 49.0
Linux x64

**Comment by ianb** [comment]
@rugk : could you open this in https://github.com/meandavejustice/min-vid/issues ?

This is the issue tracker for Page Shot

**Comment by ianb** [comment]
Oh wait, I was being dense

**Comment by rugk** [comment]
Did already. @pdehaan said in https://github.com/meandavejustice/min-vid/issues/380#issuecomment-251207011 I should open an issue here too:

**Comment by ianb** [comment]
Whoops, yes, I wasn't reading thoroughly enough.

**Comment by ianb** [comment]
I looked more closely at this – this seems to be purely a min-vid issue.  If any popup happens (such as when you click the Test Pilot button) it causes min-vid to get in this state.  So I don't think this has any relation specifically to Page Shot.

**Comment by pdehaan** [comment]
Actually, I asked @rugk to file the issue here because of this line in his original bug report:

> \2. (optional, not tested without this step) Make page shot showing an error. (it always does in my case)

**Comment by rugk** [comment]
Al right, as for this issue have a look at https://github.com/mozilla-services/pageshot/issues/1683
