### ISSUE TITLE
Unable to capture over popups like firefox Min-vid plugin

### ISSUE THREAD

**Issue by shashikumarraja** [mozilla-services/pageshot#1687]
Testing Environment-
Os-Ubuntu 16.04 LTS
Browser- Firefox 49.0

Sequence-
1.Start Firefox Min-Vid plugin
2.Now try to capture the entire page
3.The capture do not work for min-vid layout part.
4.This could be an issue with other types of overlapping popup as well.
Please refer to the screenshot for more details-
![5](https://cloud.githubusercontent.com/assets/13863716/19076450/732fd7fc-8a66-11e6-8623-e4201e19d149.png)

**Comment by SoftVision-PaulOiegas** [comment]
Thanks for the report but I think this will be a wontfix. The Page Shot add-on functionality is meant only for the browser window content. Min Vid is a player that overlaps the browser window (on top of it) and can be dragged also outside of it. That means it will never be captured by something that is oriented on the browser and not on the operating system desktop.
