### ISSUE TITLE
Rewrite navbar to use flexbox

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1701]
I think that would help with #1622 and other issues we have with the navbar at different sizes.

[This library](http://roylee0704.github.io/react-flexbox-grid/) looks like it might be helpful here.

**Comment by johngruen** [comment]
@ianb i already did this :)

**Comment by johngruen** [comment]
https://github.com/mozilla-services/pageshot/blob/master/static/css/frame.scss#L20

**Comment by pdehaan** [comment]
Fixed via https://github.com/mozilla-services/pageshot/pull/1512
