### ISSUE TITLE
Update dependencies Greenkeeper found

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1703]
I closed its first PR, #1642, because the React upgrades seemed to break the build.  But it had many dependencies that could be easily updated.

**Comment by ianb** [comment]
At this moment I think it would make sense to just upgrade everything, and then work out any build problems.  `npm outdated` gives the information.

**Comment by fzzzy** [comment]
I agree. What problems were you seeing with the react upgrade?

**Comment by ianb** [comment]
Browserify wasn't able to find some file, after doing a clean build (`rm -rf node_modules ; make clean`) – I didn't look into it further.

**Comment by fzzzy** [comment]
That's a different issue that is already in master. For a while now I have had to do `rm -rf node_modules; rm -rf build; npm install; make all` to do a clean build.

**Comment by ianb** [comment]
The clean build wasn't the problem – rather the build problem only showed itself when I did a clean build.

**Comment by fzzzy** [comment]
Yes, the problem was that the node_modules weren't installed before running make all. This problem is in master. I just verified by updating all the modules; I can recreate the problem by running make all without a node_modules, but if I delete node_modules and build, followed by a npm install, and a make all, it works fine with all dependencies updated.

**Comment by ianb** [comment]
Maybe we need `all: npm addon server` in the Makefile then (though `npm` is the first dependency of the other two rules, so it seems superfluous)

**Comment by fzzzy** [comment]
Sure, but that is a different bug that should be filed. It has nothing to do with updating the deps.

**Comment by ianb** [comment]
I think the Makefile uses things that get npm-installed just to setup the basic environment, so in practice npm install just has to be run before make.  The scripts ensure this at least.  I don't think there's anything else worth fixing there.

**Comment by fzzzy** [comment]
Sounds good!
