### ISSUE TITLE
Create a list of incompatible add-ons

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#1705]

**Comment by ckprice** [comment]
We believe there is ability to have this in the Test Pilot site.

**Comment by ianb** [comment]
We can add a list of incompatible add-ons to the [yaml file](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/page-shot.yaml).  [Example PR](https://github.com/mozilla/testpilot/pull/1538)
