### ISSUE TITLE
Option to auto-email self

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#171]
What cloud storage do people trust?  Email!  Maybe an option to auto-email content, or a one-click button to email something to yourself.  (With an FxA login we have a verified email address.)

A sophisticated use of this would do something like auto-archive those emails, but we can't really expect people to do that.

We'd want to produce nice bundled bits of content.  This can be a little challenging in an email context.

**Comment by brampitoyo** [comment]
This came up as an idea in the meeting with the Task Continuity team.

Can we create a service that will allow user to send an email to save@pageshot.com everytime they’d like to save an article?

The idea is pretty simple: user sends a new email to save@pageshot.com, with a URL (mandatory) and note on either the title or the body of the email (optional). In a few moment’s time, PageShot will send them back a screenshot, along with a link to view the page in context.

![email-to-pageshot](https://cloud.githubusercontent.com/assets/51007/7109593/0c154202-e1f5-11e4-935f-498111b7703b.png)

**Comment by ianb** [comment]
The email interaction would be somewhat hard to implement, as it's a very different flow from what we're doing.  This however would be [very useful for Richard Stallman](https://pageshot.dev.mozaws.net/1428933040273/xxx), if we want a one-person feature ;)

**Comment by ianb** [comment]
This does not seem applicable to our current experience.
