### ISSUE TITLE
Not enable

### ISSUE THREAD

**Issue by Monxl** [mozilla-services/pageshot#1712]
I tried to install the pageshot but it 's not working.Is this not availlable in Europa I'm trying this for a number of days in the hope the addon strarts working.I hope there is a solution because I like the idea I didn't try the other addons but I will.Best regards Corstiaan
[Image 1.pdf](https://github.com/mozilla-services/pageshot/files/515575/Image.1.pdf)

**Comment by SoftVision-CosminMuntean** [comment]
@Monxl do you have any anti-virus or firewalls installed? Maybe your issue could be also related to firewall or antivirus configurations (see this issue: #1474).

Also, what version of Test Pilot do you have installed? To check this please go to about:addons > Extensions tab at left and click 'More' link next to Test Pilot listing.

**Comment by ianb** [comment]
@Monxl : we believe this problem is fixed on the Test Pilot site.  Please try again and reopen this bug if it's still not working for you.

**Comment by Monxl** [comment]
Hello It's all working perfect now Thanks.

**Comment by Monxl** [comment]
Hello Next problem I have a 404 page and there are issues with the tracking connection.When a enable this I have problems with loading websites and there is a internet connection stop. This happend twice on differend days. I hope yuo can fix this.Best regards Corstiaan
[Image 404.pdf](https://github.com/mozilla-services/pageshot/files/527522/Image.404.pdf)

**Comment by fzzzy** [comment]
@monxl That sounds like a different bug, can you open a new issue for this and provide more details? When you say "tracking connection" do you mean "tracking protection"?

Thank you.
