### ISSUE TITLE
Test out iframe approach for preventing style conflicts

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1725]
An iframe with a transparent background may reduce the number of style conflicts we encounter. Two possible approaches:

postion: absolute; top: 0; left: 0; right: 0; bottom: 0;

An absolutely positioned element with top: 0; left: 0; and height and width of the entire page (would this help with selections that are bigger than the viewport?)

**Comment by fzzzy** [comment]
I tried three approaches:

1) iframe with https url
2) iframe with data: url
3) iframe with blob: url

All three approaches were workable, but all three approaches can be blocked by a strict csp, such as the one used by github. Also, a lot of effort will be required to move much of the code from synchronous to asynchronous through postMessage. Although this approach will solve the style conflicts we are currently encountering on a site-to-site basis, the csp issue is insurmountable and so we'll have to just keep doing the best we can with the approach we have.

It seems that extensions that are able to inject content and dom nodes into a page are a backdoor around csp. Perhaps the hole will be closed at some point.

**Comment by fzzzy** [comment]
Oh, also, using the following css produced very good results:

  postion: absolute;
  top: 0px;
  left: 0px;
  border: none;
  width: <width of the original body element>;
  height: <height of the original body element>;

**Comment by ianb** [comment]
We might want to look at uBlock.  The element picker uses an iframe, and works on GitHub.  

The code is [here](https://github.com/gorhill/uBlock/blob/a1fa4d0fe96c3488010b36371599a18fc4002394/src/js/scriptlets/element-picker.js#L1373)

It looks pretty workable.

**Comment by ianb** [comment]
We need to go through all issues labeled [style cleanup](https://github.com/mozilla-services/pageshot/issues?q=is%3Aopen+is%3Aissue+label%3A%22style+cleanup%22) and confirm they are fixed by this.

**Comment by ianb** [comment]
Note #1997 is probably a regression from this

**Comment by ianb** [comment]
Regressions and a style cleanup issue all addressed in #2021
