### ISSUE TITLE
Investigate Clipular

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#173]
https://www.clipular.com

![clipular](https://cloud.githubusercontent.com/assets/51007/6549556/51a830fe-c67a-11e4-81f8-9a9f9db88b6b.PNG)

Although their interface can be a bit clunky (takes two click to highlight an area, takes two click to snapshot the entire page), they have the same basic idea as PageShot.

Pay particular attention to the way their Scissor Tool snap precisely to the edges of object (div, images, paragraphs). It makes snapping precise pixels very easy, but here’s the key difference: unlike many other tools with auto snap functionalities, Clipular’s allows you to select elements that aren’t right next to each other in the HTML code.

This means that it covers corner cases a lot better. I can select part of the content, plus the sidebar, very precisely and easily (http://www.clipular.com/c/5287276725665792.png?k=j9tybSUoFCTPA6fdIDYx9RJSXe4)

**Comment by ianb** [comment]
They are using the technique we talked about some – basically using element boundaries as the snap points.  

I was thinking about the fact that those elements are scattered all over the page.  Do you snap to elements near your cursor?  I don't think we actually want that.  If I start in the top left and move to the bottom right, but there is something in the bottom left I want to include, then that bottom left element is a valid snap point.  Maybe the reasonable thing is to make a full grid of every reasonable boundary on the page and use that for snapping.

I'm in the selection code right now, so I'll probably give this a try.

**Comment by brampitoyo** [comment]
I agree about turning snap points into grid that would apply to the whole page. This will make aligning things a lot simpler.

At some point, though, we’re going to have pages with so many elements in so many alignments. This model won’t work then.

**Comment by ianb** [comment]
A rundown of how it works:

- When you click the icon you get a panel.  Nothing has been done at that time.
- On the top of the panel are three options:
  1. Scissors (manually select a region)
  2. Camera (take a screenshot of the whole page)
  3. My Clips (go to the dashboard in a new tab – though it seems to reuse an existing dashboard tab when it can)
- At the bottom of the panel is a carrousel of recent clips.  It might be the last 24 hours or something – it doesn't just show the last 5.
- Above the recent clip is a series of buttons: Facebook, Twitter, Google+, Tumblr, Email, download.

The email they handle themselves, with some rich email and it seems like they have some kind of summary they expose.  They are saving title and URL, though it's not always exposed.  [Here](http://www.clipular.com/posts/4992799465275392?k=o0728fcO51MwR_j5kBeBSVwldAo) is a destination page.  You can see they use the Open Graph metadata to make it display well when sharing the link on different services.  Each page has a Facebook comment section.

When you download you get a png with no metadata.

On the dashboard you can add tags, and these become collections.  [Here](https://www.clipular.com/users/5914353720098816/collections/os) is a couple random links put into a collection.  Collections can be public, private, or shared with a specific group.  You can also add a note to a page, though this is only exposed on the dashboard and these collection pages.  Definitely some navigational inconsistency here, I assume they just haven't worked it all out yet.

When selecting a region they use a page-wide/high crosshairs that feels nice.

**Comment by ianb** [comment]
Maybe it's because I use option-arrow and option-backspace for editing more than the average person, but I can say that the keyboard shortcut of option-option (twice in a row) is annoying for me.

**Comment by ianb** [comment]
Another small feature: it does snapping, but if you hold Option while selecting it turns the snapping off.  It includes popup help:

![screen shot 2015-03-26 at 10 59 32 am](https://cloud.githubusercontent.com/assets/44390/6850433/389505a8-d3a7-11e4-9b76-ab54d66bcbd4.png)

**Comment by ianb** [comment]
I figured out why the keyboard shortcut is so annoying: it doesn't work right.  So when I hit option-backspace, release option, then hit option again (to backspace over another word) it pops up.  If done properly it would notice I hit backspace in between and not trigger the keyboard shortcut.

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1L8qkab1Bs88kbXwaakN0BsCsJtaft9RsqMM1TUM1IBQ/edit)
