### ISSUE TITLE
Copy link to shot after Save

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1734]
Per the discussion in #1627, we will restore the link-copying functionality we had before.

We'll just copy the URL.  We'll pop up a standard notification popup like before.

**Comment by ianb** [comment]
Here's what the popup looks like (on Mac, not sure what it looks like on Windows:

![image](https://cloud.githubusercontent.com/assets/44390/19318121/f1847f2a-906c-11e6-8ea3-3a914898505a.png)

This will land in accfe28caac94c5a46009d861a2c84323c18581e (barring changes).  Should have review.

We used a "link" icon, but arguably a clipboard icon would be better.

**Comment by SoftVision-CosminMuntean** [comment]
This is how it looks on Windows: 

![saved link notification](https://cloud.githubusercontent.com/assets/19226534/19477060/1f68b0dc-9545-11e6-8b65-d9d2b75fc230.png)


It seems that the "link" icon is wrongly positioned and the Firefox icon is not displayed. Should I log a new bug for this?

**Comment by ianb** [comment]
@SoftVision-CosminMuntean : no, not worth a bug, we don't have much control over how that popup looks.
