### ISSUE TITLE
Fork uBlock Origin's Element picker

### ISSUE THREAD

**Issue by davidhedlund** [mozilla-services/pageshot#1739]
Please have a look on the [Element picker](https://github.com/gorhill/ublock/wiki/element-picker) that ships with [uBlock Origin](https://github.com/gorhill/ublock).

See [source code](https://github.com/gorhill/uBlock/blob/master/src/js/scriptlets/element-picker.js) and [CSS](https://github.com/gorhill/uBlock/blob/master/src/epicker.html) of the Element picker

**Comment by davidhedlund** [comment]
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by ianb** [comment]
Is there something about the uBlock element picker that you particularly like?  We are planning on indicating with hover what would be selected with a click (#1633) though it will be much more subtle than uBlock (because we also have the dragging option).

**Comment by davidhedlund** [comment]
@ianb That sounds great. I assume that the uBO picker is well developed. I would consider using that code and add the extra dragging option.

**Comment by ianb** [comment]
Thanks for the pointer, it's been very helpful.  I'm closing this bug out, but we'll be using lessons from what uBlock has done.

**Comment by davidhedlund** [comment]
@ianb Thanks.
