### ISSUE TITLE
Investigate Qwote.io

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#174]
https://www.qwote.io/

![qwote.io](https://cloud.githubusercontent.com/assets/51007/6549554/43e63358-c67a-11e4-8533-674364da5be5.PNG)

One way to select an area to highlight is by using the Select Tool (crosshair): click the tool first, then highlight the area.

Another way is to do it Medium-style: highlight the area first, then click the tool.

Like http://highly.co/, Qwote.io takes the latter approach. Is this the right approach for us? Is it worth it to have two different ways to highlight, or would it be feature-creep?

**Comment by ianb** [comment]
I signed up, but early access is restricted so I can't say much more.

If you select something then hit the PageShot button, I would like it to take that selection.  But that shouldn't be the only way to access that functionality.

**Comment by ianb** [comment]
Looking at it now:

- You have to have the addon installed to view quotes, not just to create them, so no fancy technology there
- Anytime you select text, the qwote button pops up.  So it's ubiquitous.
- Images get a qwote button overlaid, similar to how Pinterest extensions work.  It's on all (large?) images
- The link you share is a qwote link, that redirects to the original page.  I think the idea is that the link can check if you have Qwote installed, and get you to install the addon before redirecting.

**Comment by ianb** [comment]
Having the addon installed, I get this kind of thing all the time: 
![screen shot 2015-03-24 at 4 12 42 pm](https://cloud.githubusercontent.com/assets/44390/6813057/a2a8a318-d240-11e4-813a-f07b8405a1dd.png)

Now I'm a chronic text selector, so my experience might not be universal, but it's really annoying.

**Comment by ianb** [comment]
(The Pinterest-style button on image hover is actually worse, but I guess it serves to constantly remind me of the availability of the tool.)

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1HBUNmxGpIuTXMn4hWKUQNITAtlpKeONAzvsh7QlHMD8/edit)
