### ISSUE TITLE
Tracking protection

### ISSUE THREAD

**Issue by Monxl** [mozilla-services/pageshot#1746]
I mean tracking protection.There is not much more to tell.When I start the tracking protection it works with the first two websites and then the sites keep hanging and after a moment the internetconnection is gone.After disabeling tracking protrection and reboot all works again. I tried all kind of things like emptying caches. Is it possible that an other tracking program hinders tracking protrection I have the protection from FF enabled.Best regards Monxl

**Comment by ianb** [comment]
@Monxl : I think you have the wrong bug tracker, this is specifically for issues with Page Shot.  Can you open this in the Tracking Protection bug tracker?  Thanks.

That bug tracker is here: https://github.com/mozilla/blok/issues/new
