### ISSUE TITLE
Investigate Saved.io

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#175]
http://saved.io/

![saved.io](https://cloud.githubusercontent.com/assets/51007/6549549/2c4322c4-c67a-11e4-96f0-44de5cf36847.PNG)

Saved.io is less like PageShot and more like Delicious: a traditional bookmarking service for link. But the way it saves and organises is pretty ingenious: it uses the URL bar.

* To save a bookmark, type saved.io/ in front of URL (e.g. saved.io/mozilla.org)
* To save a bookmark to a new list, type listname.saved.io/ in front of URL (e.g. tech.saved.io/mozilla.org)

I have doubt that Saved.io’s approach will work for any but the most advanced users, so feel free to close this issue if it’s no longer relevant.

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1DoJkF2v4zCsp3KzlYo18QcpSxGyuH5dNpQeauLnlP88/edit)
