### ISSUE TITLE
The "Save full page" option displays "Page Shot is out of order." error

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1755]
[Affected versions]:
- Firefox 48.0.1 and up
- Mozilla PageShot 0.1.201610170741

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest PageShot add-on (v0.1.201610170741) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to any page.
2. Click the Page Shot icon from the browser toolbar.
3. Click the "Save full page" button from the top right corner of the page. 
4. Observe the browser behavior.

[Expected result]:
- The entire website is captured and you are redirected to the saved shot preview page.

[Actual result]:
- You are redirected to the upload page and a "Page Shot is out of order." error is displayed.

[Notes]:
- I have tested this with a custom build created from GitHub repository.
- Added a screen recording with the issue: https://goo.gl/EQ4b5p.
- Here are some console errors observed while trying to save a full page: https://goo.gl/f6tA51.

**Comment by ianb** [comment]
This error is because the pageshot.net server hasn't been updated to accept the full page clips.  This should work locally with an up-to-date build of the server.  There's a slight change that `make clean` might be necessary when running the server locally (I think the change should be picked up automatically, but maybe not.)

**Comment by fzzzy** [comment]
@SoftVision-CosminMuntean I haven't updated pageshot.dev.mozaws.net in a while. I'll try to keep it more up to date from now on.

**Comment by SoftVision-CosminMuntean** [comment]
Thanks @fzzzy!

I have retested this using the latest build from "pageshot.dev.mozaws.net" and the issue is not reproducible.
