### ISSUE TITLE
"Download" and "Delete" buttons are refocused after performing the actions

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1756]
[Affected versions]:
- Firefox 48.0.1 and up
- Mozilla Page Shot 0.1.201610170741

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Page Shot add-on (v 0.1.201610170741) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to any page.
2. Click the Page Shot icon from the browser toolbar and save a selection.
3. Click the "Download" or "Delete" button from the top right of the page.
4. Click "Cancel" button on the displayed pop up and observe the button state.

[Expected result]:
- The displayed pop up is dismissed and the "Download" / "Delete" button loses focus.

[Actual result]:
- The displayed pop up is dismissed, but the "Download" button is refocused (pressed state).

[Notes]:
- The pressed state of the buttons is dismissed if you click anywhere on the page.
- Added a screen recording with the issue: https://goo.gl/ftk9vb.

**Comment by ianb** [comment]
We're okay with this – we're letting the browser choose focus behavior here.
