### ISSUE TITLE
Test if shots can be images

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1757]
It might be cool if you could do `<img src="https://pageshot.net/a9e8fkwe/example.com">` and it would just work.  I *think* this is possible by looking at the Accept header.  If this works, we might consider renaming the URLs so they appear to be images (mostly appending `.png` to the URL).  Then in some contexts where images are treated specially you could link to a shot directly.

(Concept came from [this](https://discourse.mozilla-community.org/t/where-do-you-want-to-paste-shots/11466/2?u=ianbicking) discussion)

**Comment by ianb** [comment]
Bummer, can't be done.  The [Accept headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values#Values_for_an_image) for images are `*/*` in Firefox, Safari, and IE 8-.

**Comment by pdehaan** [comment]
I think imgur.com may do something like this.

https://imgur.com/RGzKytY is an HTML page with header and sidebar and chrome.
Append ".gif", ".jpg", or ".png" to the URL and you get just the image (which is great for hot linking or whatever): https://i.imgur.com/RGzKytY.gif
Also note that it seems to inject that subtle "i." subdomain when you link directly to the image as well. :/

**Comment by ianb** [comment]
It's a slightly different approach, yes – basically easily hackable URLs.  If we thought that was useful it would be quite easy to implement for Page Shot as well.  Note actual clip URLs are unrelated to the shot URL for privacy reasons, though it would be easy to get back and forth between the views when using this technique.  Imgur doesn't try to provide privacy, only publishing, so it's not an issue there.
