### ISSUE TITLE
My Shots empty space images

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1770]
There's a couple images that @TLHuang created that I think we should incorporate from [this zip file](https://github.com/mozilla-services/pageshot/files/393110/issue1098.images.zip)

The first is when you open My Shots and have no shots:

![img-no shots](https://cloud.githubusercontent.com/assets/44390/19483786/2f4418cc-951b-11e6-8bde-0927b9e60dd8.png)

The next is when you search and get no results:

![img-no result](https://cloud.githubusercontent.com/assets/44390/19483795/36e99480-951b-11e6-995a-1cbab6b7824e.png)

**Comment by ianb** [comment]
We'd like to put these in as SVGs instead of the PNGs in the zip file.

**Comment by fangshih** [comment]
Here is the SVG assets, Thanks! 
[Empty space assets.zip](https://github.com/mozilla-services/pageshot/files/541304/Empty.space.assets.zip)
