### ISSUE TITLE
Share button wraps

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1780]
This is how it looks now on my computer:

![image](https://cloud.githubusercontent.com/assets/44390/19493803/cdc9fc3e-9541-11e6-8a4d-9fa12a1c9d40.png)

**Comment by fzzzy** [comment]
I can't repro this, so you should probably try to fix it @ianb

**Comment by ianb** [comment]
I also changed the style, putting the icon after "Share", removing the background color, changing it to white, and putting a slight-darker-blue stroke around it:

![image](https://cloud.githubusercontent.com/assets/44390/19609346/40799030-979c-11e6-8e76-deaa9e978d6a.png)
