### ISSUE TITLE
The preview instructions background is wrongly displayed on specific websites

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1785]
[Affected versions]:
- Firefox 49.0.1 and up
- Mozilla PageShot 0.1.201610191113

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201610191113) is installed on a clean profile.

[Steps to reproduce]:
1  Open the browser with the profile from prerequisite and navigate to "www.amazon.com".
2. Click the Page Shot icon from the browser toolbar and observe the preview instructions background from the top of the page.

[Expected result]:
- The preview instructions background is correctly displayed.

[Actual result]:
- The preview instructions background is narrower than the text.

[Notes]:
- On Instagram website, the preview instructions is displayed on the middle of the page (here is the screenshot with the issue: https://goo.gl/wKWVbZ).
- I have tested this with a custom build created from GitHub repository.
- Added a screenshot with the issue: 

![preview instructions](https://cloud.githubusercontent.com/assets/19226534/19525951/5f687e6a-962b-11e6-92c8-f58a925b4c4f.png)

**Comment by ianb** [comment]
Well, the preview instructions are fine now, though I'll note #1997 does show up on instagram.
