### ISSUE TITLE
Support different simultaneous media types on clipboard

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#179]
The clipboard can hold more than one media type at the same time.  Right now we have it sometimes taking an HTML representation, and sometimes a link, and if you paste the HTML into plain text then it is automatically converted.  But we would like to control those different versions ourselves.  A standard copy should:

* In a text context, take just the link to the shot
* In an HTML context, take the title of the shot, the link to the shot, and an img tag linking to the snippet
* In an image context, take the data of the image

This appears to be possible using transferables, as described in [Using the clipboard](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Using_the_clipboard).  This is *not* possible using the [Addon-SDK clipboard module](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/clipboard) (which is what we currently use).

**Comment by brampitoyo** [comment]
It might be interesting to take both the shot title and link in a text context, because it could help user with remembering what the content of the clipboard is all about. On the other hand, it might be trying to do too much.

Will context-aware paste still work when user Ctrl+V in another browser or application that’s not Firefox?

**Comment by ianb** [comment]
It probably does make sense to include the title, as it's easier to delete that after pasting than to recreate it.  I think we'll only fully understand context-aware pasting when we try it, but it is a part of the system clipboard and should work across applications.

**Comment by ianb** [comment]
We are doing something with this now (using the included multiclip module)
