### ISSUE TITLE
make shot page responsive

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#1792]
30% of shares are viewed on mobile. We should have a mobile responsive view for this sort of page:

https://pageshot.net/ELQi9ixejX33Xc6k/accounts.firefox.com

**Comment by youwenliang** [comment]
I quickly made a mockup for the shared page mobile view: https://mozilla.invisionapp.com/share/3S90SSAH8 

I added an "image focus" mode where all the UI disappear and showing only the image (And users can zoom in & out with finger gestures)
Any thoughts? @johngruen

**Comment by johngruen** [comment]
HEy @youwenliang I think the only thing this is missing is a bit of branding...We want people to know they're looking at a Page Shot image :)

**Comment by ianb** [comment]
Do we need sharing in the mobile view, or can we rely on people using the native sharing techniques?

**Comment by johngruen** [comment]
@ianb @youwenliang i would prefer if we used native sharing UI here as well

**Comment by youwenliang** [comment]
Thanks for the feedback @ianb @johngruen 
I've updated the mockup: https://mozilla.invisionapp.com/share/2W93B20U8
(Add back "made with pageshot" and add native sharing UI for both Android & iOS)

**Comment by johngruen** [comment]
Moving sprints
