### ISSUE TITLE
Send GA event when someone copies a pageshot URL from the awesomebar

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1793]
We'd want to check with @Mardak about how this would work, but it's possible.

**Comment by Mardak** [comment]
https://github.com/mozilla/loop/blob/master/add-on/chrome/bootstrap.js#L466-L471

That monkey-patches into the command handling of the urlbar. It's fragile in that multiple add-ons monkey-patching results in oddness when they unload in different orders than when loading.

**Comment by ianb** [comment]
We won't be able to do this after porting to a WebExtension
