### ISSUE TITLE
Load model data in separate async request

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1805]
We inline the model into pages, but we could fetch it async.

**Comment by fzzzy** [comment]
Isn't the whole point to inline the model so that it is synchronously present? I mean, we spent a lot of time getting the server architecture to do that

**Comment by ianb** [comment]
We effectively load twice the amount of data in the initial page body as we need to – everything in rendered form, then the underlying model in an embedded script/JSON.

That said, if we fetch the data async then we decrease the page size, but make another request, and have to calculate the data twice on the server.  With memcached or something it wouldn't be a big deal, but I don't want to go down that path right now.

Erasing milestone for discussion, I think we probably just shouldn't do this.

**Comment by ianb** [comment]
After discussion, we just aren't going to do this.
