### ISSUE TITLE
Classify users in GA

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1806]
(Please edit this description to provide the most accurate description given discussion)

When looking at metrics, we should be able to classify users roughly by usage.  I propose 3 classes:

**Engaged:** these are people who have decided to use Page Shot, and make somewhat regular use.

**Evaluating:** these are people who have installed Page Shot and are considering adding it to their toolset.

**Disengaged:** these are people who do not use Page Shot, do not appear to be evaluating it, but haven't uninstalled the add-on.

We need formal criteria to separate these groups, and we need to add this as a parameter in GA.
## Criteria:

(proposed)
1. An engaged person has used Page Shot in the last month(?) (clicking the Page Shot button, or visiting My Shots... or any shot page?)  An engaged person has had at least 3 days when they created a shot.
2. An evaluating person has installed or used Page Shot in the last month(?), but does not qualify as engaged.
3. A disengaged person is neither of the above.
## Parameter:

Unsure.  I've looked [here](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters) but didn't find any parameters that seemed right.  Custom dimension?

**Comment by johngruen** [comment]
@ianb i think in a week or so we'll have enough data in survey gizmo to start reasoning about this explicitly, but this would be a good thing to discuss with Gareth next week

**Comment by ianb** [comment]
I'll put this in the optimization backlog for tracking

**Comment by ianb** [comment]
Closing as this is not actionable right now.  It's on the backlog, and can be reopened if we decide to work on it.
