### ISSUE TITLE
Release Altair

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1812]
For release we should:
- [x] Bump version number to "1"
- [x] Create changelog (#1702)
- [x] Create tag
- [x] Create Bugzilla ticket
- [x] Note `SET_CACHE=true` in Bugzilla ticket #1787
- [x] Generate pageshot.net add-on and get it deployed on testpilot site
- [x] On dev server deploy confirm caching
- [x] Run `bin/load_test_exercise.py --times 100 https://pageshot.stage.mozaws.net`
- [x] Post to [Discourse](https://discourse.mozilla-community.org/c/test-pilot/page-shot)
- [x] Note release in GA as annotation
- [x] Confirm our add-ons update properly
- [x] Close Altair milestone
- [x] Make a copy of this ticket in Betelgeuse for the next release
- [x] Comment on any [tickets closed during the release](https://github.com/mozilla-services/pageshot/issues?utf8=%E2%9C%93&q=is%3Aissue%20closed%3A%3E%3D2016-10-05), made by other people, to tell them their issue is fixed in release.

**Comment by fzzzy** [comment]
I mentioned that we will be doing a release in a post to discourse. Will update the post when the release is live.

https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687

**Comment by fzzzy** [comment]
Ticket created.

https://bugzilla.mozilla.org/show_bug.cgi?id=1312768

SET_CACHE=true noted.

**Comment by fzzzy** [comment]
I sent the add-on to Wil. There should probably be a checklist step for this. We should also try to get a more automated add-on deployment story in place.

**Comment by fzzzy** [comment]
I tested that SET_CACHE=true generates correct cache headers on pageshot.dev.mozaws.net. (there was a bug in this that we fixed at the last minute yesterday)

**Comment by fzzzy** [comment]
What arguments should be used with load_test_exercise.py?

**Comment by ianb** [comment]
Concerning the release:

Looking at events from October 27-31, the open-browser event

`open-browser/startup` (total): 707,694

`open-browser/startup` App Version `1.0.201610251521`: 582,702

That's not too bad, **82%**.  Looking at only October 31:

total: 141,039, with App Version: 130,839, for **92%** deployment.

Given this I think the update went okay, though I'll be curious if that 8% sticks around.
