### ISSUE TITLE
email sharing - can email service me specified by user?

### ISSUE THREAD

**Issue by davehnp** [mozilla-services/pageshot#1813]
Just started experimenting with pageshot
Is there a way to select which email provider is opened when clicking on the sharing mail icon?
Thanks in advance

**Comment by ianb** [comment]
There are [instructions here](https://support.mozilla.org/en-US/kb/change-program-used-open-email-links) on how to set the email client for Firefox generally (which is what Page Shot will use).

Note the screenshot there isn't up-to-date anymore, it looks like this now:

![image](https://cloud.githubusercontent.com/assets/44390/19653254/7a46ee72-99d9-11e6-8cab-92c49f776934.png)
