### ISSUE TITLE
Full Web Page Capture On Single Click

### ISSUE THREAD

**Issue by shivarajnaidu** [mozilla-services/pageshot#1817]
If we can capture entire wep page (not screen) on single click.. it will be awesome..
And I like this ad-don very much.. 

Thanks to Mozilla :+1:  :heart:

**Comment by ianb** [comment]
This is implemented in #1613 and you should see it in the next release (due out early this week).

**Comment by ianb** [comment]
This feature was released in the [v1 release](https://discourse.mozilla-community.org/t/new-release-1-0-1-coming-this-week/11687/3) which went out on October 26th.
