### ISSUE TITLE
Generated file name can be too long

### ISSUE THREAD

**Issue by Akronix** [mozilla-services/pageshot#1820]
The title web page can be long.
Hence, the generated file name when downloading the shot (`download` attribute in the download button) can be too long and be rejected when saving in some file systems.
Also, as the title starts to be long, the shot-info div starts to grow and, at some point, it doesn't fit on the width of the browser and the user has to scroll horizontally to find the Share, Download and Delete buttons.
I'll upload an image to better show what I mean.

I'd be happy to help with this :)

**Comment by ianb** [comment]
We have an issue for the title overflow issue: #1622

But not the download issue; BTW, the code for that is here: https://github.com/mozilla-services/pageshot/blob/f1fb35aad71cbe6fecb39f6861cd0ff3b8fd31f5/server/src/views/frame.js#L544

**Comment by johngruen** [comment]
@ianb i think this is a separate issue. Not sure what windows and *nix max file name lengths are but we should implement hard cap here.

**Comment by Akronix** [comment]
[In wikipedia there's a compilation of the filenames limits for every file system](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits). It looks like that most modern file systems support until a maximum of 255 bytes / characters. But I'd prudently let it be shorter than that.
