### ISSUE TITLE
The search is not returning any results until more than 3 characters are typed in the Page Shot search bar

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1821]
[Affected versions]:
- Firefox 49.0.2 and up
- Mozilla Page Shot 0.1.201610201533

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest Page Shot add-on (v0.1.201610201533) is installed on a clean profile.
- Have multiple saved shots on the created profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and open a New Tab.
2. Click on the "Page Shot" button from browser toolbar.
3. Type 3 characters that are contained in at least one saved shot in the search field.
4. Observe the page URL and the results for the typed string.
 
[Expected result]:
- The URL is updated with the entered string and the search returns results for it. 

[Actual result]:
- The URL is not updated and the search is not returning any results even if the saved shots contain the entered string.

[Notes]:
- Added a screen recording with the issue: https://goo.gl/WjoJpW.

**Comment by johngruen** [comment]
@SoftVision-CiprianMuresan this is intentional, we can revisit if we get external reports of this being an issue
