### ISSUE TITLE
Add question to survey: where do you use the link?

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1824]
It's useful to know where people want to use Page Shot links, because then we can optimize to the links working well there.

We need to phrase the question properly, then get it put into the Test Pilot survey.

**Comment by johngruen** [comment]
I've emailed @rayborn a set of questions we'd like to see in the surveys based on this issue as well as others we'd added in the prioritization backlog. I'll circle back and close this once that information is in the survey

**Comment by johngruen** [comment]
These are in
