### ISSUE TITLE
Able to take a resize a screenshot outside of the page's viewport

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1831]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19667850/42b4a290-9a08-11e6-9ad8-dfd4a12fd76a.png)
### Steps to reproduce:
1. Go to a site (ie: www.apple.com)
2. Take a Page Shot shot of something near the top of the page.
3. Resize the capture area using one of the handles at the top of the selection area.
4. Drag the selection up vertically, so the resize handles go under(?) the toolbars. This works slightly better if the browser is floating and not fullscreen or maximized.
### Actual results:

![ipad](https://cloud.githubusercontent.com/assets/557895/19667922/ba67a04e-9a08-11e6-88f8-a6bd9d68001b.png)
### Expected results:

You cant drag the handles outside of the visible viewport.

**Comment by ianb** [comment]
I think this fixed in the current release, can you re-verify?

**Comment by ianb** [comment]
I'm pretty confident this is fixed.
