### ISSUE TITLE
"Creating undefined" title on some pages

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1836]
Found in https://pageshot.net/__version__ (848ad59):

``` json
{
  "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "October 04, 2016 18:05:16 UTC",
  "commit": "848ad59",
  "contentOrigin": "pageshot-usercontent.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/848ad59",
  "unincludedCommits": "https://github.com/mozilla-services/pageshot/compare/848ad59...master"
}
```

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19695721/2259e398-9a99-11e6-80bb-f7f5a117505f.png)
---

Randomly spotted this while looking at Activity Stream and seeing a few Page Shot entries with titles saying "Creating undefined":

![new_tab](https://cloud.githubusercontent.com/assets/557895/19695712/17689dee-9a99-11e6-96c6-459a1055d1ec.png)

**Comment by ianb** [comment]
I can't reproduce this, so I don't quite know why it happens.  But I'm changing the creating page to use 'page', like 'Creating page', if it can't find the title for some reason.
