### ISSUE TITLE
Require some dragging before replacing/making selection

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#184]
Right now the selection tool starts the moment you click.  Doesn't matter if you drag at all.  We should have some threshold of dragging before we try to make any selection.

**Comment by brampitoyo** [comment]
Agreed. Additionally, the selection behaviour should make it easy to cancel and back out:

* When the **capture an area of the page** button is selected, the doorhanger closes and the cursor changes to a crosshair
* When user clicks and drags, it makes a selection – in this model, a selection is made no matter how small the area is
* When user clicks without dragging, or hit the Escape key, the cursor changes back into arrow
