### ISSUE TITLE
Add a /favicon.ico file?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1840]
https://pageshot.net/favicon.ico

We already have these:

``` html
<link rel="icon" type="image/png" href="/static/img/pageshot-icon-32.png?rev=848ad59"/>
<link rel="shortcut icon" href="/static/img/pageshot-icon-32.png?rev=848ad59"/>
```

But having a dummy fallback of the standard /favicon.ico would possibly solve some of these odd edge cases where Activity Stream uses a fallback for things with where it can't find an icon (like a JSON `/__version__` endpoint or direct links to images or outbound redirects, etc:

![new_tab](https://cloud.githubusercontent.com/assets/557895/19705819/922ae6fc-9ac3-11e6-90b5-92e0a7687d15.png)

(Where the /favicon.ico fallback seems to be coming via [**mozilla/page-metadata-parser** /parser.js:156-158](https://github.com/mozilla/page-metadata-parser/blob/62edbb6f044515dd83d6093fec9c58d7b871f8a8/parser.js#L156-L158)).

**Comment by ianb** [comment]
We could just put in a permanent redirect from `/favicon.ico` to `/static/img/pageshot-icon-32.png`
