### ISSUE TITLE
Share button wraps

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1842]
After applying #1841 the Share button wraps again:

![image](https://cloud.githubusercontent.com/assets/44390/19706786/7766f516-9ad9-11e6-87c7-55c6ba6a42bc.png)

It's less obvious to me why, compared to last time (with display: flex).

**Comment by ianb** [comment]
It's not exactly wrapping, the width of the button doesn't matter.  It has something to do with flex again – if I remove `display: flex` from buttons then it works (though it's awkwardly aligned).

Note I'm seeing this specifically on Firefox, maybe related to a retina display.  Doesn't happen on Chrome.

**Comment by johngruen** [comment]
I'll fix this up in my cleanup in the AM!
