### ISSUE TITLE
Basic Editing/Drawing Tools

### ISSUE THREAD

**Issue by Caspy7** [mozilla-services/pageshot#1847]
I found [this discourse post](https://discourse.mozilla-community.org/t/feature-request-basic-editing-drawing-tools/11181) requesting the functionality, but no issue on github.

Basic image manipulation can be extremely useful for several cases, particularly for tech support (when a user is illustrating an issue).  Just recently I clipped an email with page shot to share with some others, but then realized there was one piece of sensitive information on it. I couldn't blur or black it out so had to edit it locally and upload it to another service.

Issue https://github.com/mozilla-services/pageshot/issues/1616 suggests annotations such as text and arrows, but I'd like to broaden the request to include other possibilities. Notably the other day I also found myself wanting to crop an image I took.

Features I would introduce for discussion include: Cropping, insert text, free draw, lines, arrows, Boxes (empty and translucent (highlighting)), and the ability to manipulate/resize until after a save.

Too many options and too much complexity would obviously be the antipattern for this.

**Comment by ianb** [comment]
Thanks – we've opened a ticket #1849 to define the UX for this.  I quoted a paragraph of this ticket there, but feel free to add more ideas there too.
