### ISSUE TITLE
show pixel dimensions when dragging selection

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/pageshot#1848]
[I'm filing this for a 3rd party]

When dragging your selection it would be handy to have the pixel dimensions of the image you're making.

When you resized windows in Fluxbox they used to have a small overlay in the center of the window with the X x Y value so you could quickly see the size which seemed like a decent UI.

**Comment by ianb** [comment]
We could copy the Mac screenshot selection behavior here.

**Comment by ianb** [comment]
Work in 491511556ef5e200bcce7b8aa7c7e16d16300733

It looks like this:

![image](https://cloud.githubusercontent.com/assets/44390/20283611/41f92754-aa7f-11e6-82b0-743b136c2189.png)

I couldn't capture the cursor right next to it, but it would be above and to the left of the coordinates.  There's a white/gray shadow, but you can only see that when over a dark background.

It's a little laggy, which I don't like, but I don't know of a better approach to avoid that.

**Comment by ddurst** [comment]
\o/ (I think I am the aforementioned third-party)
