### ISSUE TITLE
Design control to add more clips

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#185]
I think it would be nice to optionally add more than one clip.  The UI we have now always replaces the clip, which I actually think is an okay approach.  But sometimes I might want more than one clip.  Also text clips, so I imagine maybe "add clip [crop]" and "add clip [text select]" to both add things and switch between those two modes.

**Comment by brampitoyo** [comment]
I like the idea of adding more than one clips right from the page versus having to go to PageShot to do it. In fact, this capability already exists on earlier versions of the mockups (circa ~3 weeks ago).

I’ve added it back in and redesigned it to work better with our new doorhanger menu.

However, I can’t resolve one problem. Most services out there chose one way to highlight: they either capture screenshot, or quote DOM text. None of them do both.

Pageshot does both, but having two different select tools is confusing.

In my view, the best approach would be to combine these two approaches: user would select a part of the page by drawing a square using the crosshair cursor. But after selecting an area, Pageshot will separate each element inside (text, image, etc.) and parse the text (so it can be displayed in highlight mode).

What do you think?

**Comment by ianb** [comment]
> In my view, the best approach would be to combine these two approaches: user would select a part of the page by drawing a square using the crosshair cursor. But after selecting an area, Pageshot will separate each element inside (text, image, etc.) and parse the text (so it can be displayed in highlight mode).

I actually played with just this on Friday and have some uncommitted work on it.  My goal though was mostly to keep the searchable text around, and so it overselects text, for instance it would be easy to catch just the bottom of a paragraph and then get a lot of unintended text.

Text selection is pretty specific, and I don't think area selection is entirely an alternative.  But we can put off text selection for a while longer and see how far we can go with area selection.

**Comment by ianb** [comment]
@brampitoyo: If you can give us assets for the close buttons and any other icons that would be helpful

**Comment by brampitoyo** [comment]
Adding more than one clips turned out to be quite a tricky problem to solve. We talked about it on our last meeting (March 19) and came up with the idea of using carousel (or pagination) that allows user to move between multiple clips.

At the moment, the logic for adding and removing clips look like this:

![pageshot-add-a-new-clip](https://cloud.githubusercontent.com/assets/51007/6774754/4b0bde60-d18a-11e4-950d-9f651ac67862.png)

We can talk about it on our next meeting.

**Comment by ianb** [comment]
Is the first selection here a special case?

**Comment by brampitoyo** [comment]
I think so. The first selection must always include auto-detect. Every subsequent selections will include auto-detect only if that option wasn’t selected the first time around.

If we have the capability to auto-detect more than one areas of the page (a la how Facebook allows you to pick a cover image to a story), then we won’t need this special case.

If we do this, then we should give user the capability to pick between many auto-detected parts. This might be a good feature, too (although out of scope of our current discussion):

![pageshot-auto-detect-select](https://cloud.githubusercontent.com/assets/51007/6793464/af7f66f6-d229-11e4-9bc6-92babcb50ba6.png)
