### ISSUE TITLE
My Shots button looks truncated

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1851]
Looks like the _My Shots_ button is a bit cropped on the left side.

![banners_and_alerts_and_the_good_place_-_social_page_-_30_days_to_get_into__thegoodplace](https://cloud.githubusercontent.com/assets/557895/19777938/4c249942-9c2f-11e6-82bd-b0f791d7561b.png)

---

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19777960/6e20c20a-9c2f-11e6-9cf5-4afc66421ab8.png)

**Comment by fzzzy** [comment]
The font on all 3 buttons doesn't look the same, either.

**Comment by pdehaan** [comment]
Odd, tried taking a snap of an IMDb page, and it looks slightly different now:

![banners_and_alerts_and_shoot_the_messenger__tv_series_2016 ___-_imdb_and_yamljs](https://cloud.githubusercontent.com/assets/557895/19778300/f1ecca2e-9c30-11e6-8778-ac939d5cbc37.png)

Sizing looks better, but now "Save visible" and "Save full page" are Times New Roman-ish.

**Comment by johngruen** [comment]
I fixed the font issue in the altair cleanup PR, not sure about the padding though

**Comment by johngruen** [comment]
This should be fixed by #1899

**Comment by ianb** [comment]
I tested this on Cygnus with #1725, and it seems fine on imdb.com (though I'm not sure if that's the site in question).
