### ISSUE TITLE
Make shot page 95% width and add some borders

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1853]
I'm currently taking shots of pages, and then get redirected to pageshot.net and often the pages look 100% the same (assuming I'm taking a full page shot). It'd be nice if we had borders on the shot page or something to more obviously disambiguate the content so I'm not accidentally clicking on the screenshot assuming I'll go to a new article.

**Comment by ianb** [comment]
@johngruen fixed this in a cleanup
