### ISSUE TITLE
Error: call to Function() blocked by CSP

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1856]
I'm seeing the "Error: call to Function() blocked by CSP" error in my Browser Console when I go to the vanilla https://pageshot.net site:

![browser_console](https://cloud.githubusercontent.com/assets/557895/19787805/8b16510c-9c59-11e6-9898-e5d759a95647.png)

---

Found in https://pageshot.net/__version__ (d36a1b4):

``` json
{
  "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "October 24, 2016 22:56:57 UTC",
  "commit": "d36a1b4",
  "contentOrigin": "pageshot-usercontent.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/d36a1b4",
  "unincludedCommits": "https://github.com/mozilla-services/pageshot/compare/d36a1b4...master"
}
```

![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/19787816/9f1a8dbc-9c59-11e6-942e-4fffd069de03.png)

**Comment by ianb** [comment]
I suspect this is some add-on or other injection.  I'm not seeing this myself.
