### ISSUE TITLE
Flash of unstyled content when making a shot

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1867]
I think this was introduced recently.

<img width="1024" alt="screen shot 2016-10-31 at 11 19 15 am" src="https://cloud.githubusercontent.com/assets/46048/19859548/01d49614-9f5c-11e6-8b1c-31b687f8c63c.png">

**Comment by ianb** [comment]
We're not seeing this lately, closing (reopen if it reappears)
