### ISSUE TITLE
Size of elements too small

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1874]
Both the "My shots" and the top bar (where the text is outside of the black thing) do not look good.

![smallelem](https://cloud.githubusercontent.com/assets/11966684/19903669/b918d9b6-a06f-11e6-84fb-4eeeb0a7b216.png)

Firefox 49.0.2

**Comment by fzzzy** [comment]
We have a fix for this, hopefully coming soon.

**Comment by ianb** [comment]
We have a partial fix that will go into the next release.
