### ISSUE TITLE
Investigate incompatibility between Cliqz and Page Shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#1882]
The [Cliqz](https://addons.mozilla.org/en-US/firefox/addon/cliqz/?src=ss) add-on apears to break Page Shot (leading to 401s)

**Comment by ianb** [comment]
I've installed it and will monitor for problems.  It didn't immediately break Page Shot.

**Comment by fzzzy** [comment]
Should we move this to the next milestone?

**Comment by ianb** [comment]
I'll keep seeing how it goes today and if anything comes out of it.  Some of these privacy things are time-based.  (Unless @pdehaan changed any Cliqz settings when he had problems?)

**Comment by pdehaan** [comment]
I don't remember changing any settings in Cliqz. I was just using Nightly and cliqz from AMO.
Only thing I can think of was maybe I was running a new/fake browser profile using `jpm run` or `web-ext` so maybe something didn't like running in an odd temp directory sandbox.

**Comment by ianb** [comment]
I haven't seen any problems, so I think this is generally fine?

**Comment by ianb** [comment]
I just saw this on stage, where Cliqz would remove the authentication cookie for the PUT request to make a shot.  Note that the cookies still existed, and for normal GET requests it still worked.  I didn't try through-the-web non-GET requests.

**Comment by ianb** [comment]
Closing this out, because if we do #2142 then I'm quite sure it will resolve any lingering conflicts we have with Cliqz
