### ISSUE TITLE
Design graphic assets

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#189]
[Graphic asset folder on Dropbox](https://www.dropbox.com/sh/fnk3g6pu01j7qyt/AADi9stBu-u611BFaIKo-O2wa)

### Appear only in Shot panel

* Camera – updated June 5
  * Empty: [PNG](https://www.dropbox.com/s/t5x9757qjf6g4eb/camera-empty.png), [PNG@2x](https://www.dropbox.com/s/jbo52n2vx8mgvt4/camera-empty%402x.png), [SVG](https://www.dropbox.com/s/z9l6knud0y5f2pc/camera-empty.svg)
  * Filled: [PNG](https://www.dropbox.com/s/uytehlruw5pf78u/camera-full.png), [PNG@2x](https://www.dropbox.com/s/aooeup5m2hrrtc4/camera-full%402x.png), [SVG](https://www.dropbox.com/s/07mji289apfcx8a/camera-full.svg)

### Appear only in Library (a.k.a. Recall) panel

* Library (a.k.a. Recall) – updated June 5
  * Empty: [PNG](https://www.dropbox.com/s/7b7x140olqabb2n/library-empty.png), [PNG@2x](https://www.dropbox.com/s/fs7j7c5i2br9b4m/library-empty%402x.png), [SVG](https://www.dropbox.com/s/78fdmm3cp1etozy/library-empty.svg)
* Copy link: [PNG](https://www.dropbox.com/s/7gthj2rbeav6mg5/link.png), [PNG@2x](https://www.dropbox.com/s/57n6yupfgy8o6f5/link%402x.png) – this icon appears to the right of each menu item inside the recall panel. It’s different from the social sharing icon  – updated June 5

### Appear in both panels

* Delete shot – updated May 7
  * [Light gray](http://cl.ly/271a102d3u0w/delete-text-gray.svg)
  * [Red](http://cl.ly/3g0F4625010D/delete-text-red.svg)
* Social sharing icons
  * Facebook: [64x64](https://www.dropbox.com/s/vro9wbk21swyj92/facebook-64.png), [32x32](https://www.dropbox.com/s/1leiohet15a84o8/facebook-32.png), [16x16](https://www.dropbox.com/s/dkh8wm6tjiihwgu/facebook-16.png)
  * Twitter: [64x64](https://www.dropbox.com/s/ki43zweb8sbj6lw/twitter-64.png), [32x32](https://www.dropbox.com/s/7clw5wdoat75k6h/twitter-32.png), [16x16](https://www.dropbox.com/s/cksnzccw1wd0780/twitter-16.png)
  * Pinterest: [64x64](https://www.dropbox.com/s/wr4kp1g228z4th0/pinterest-64.png), [32x32](https://www.dropbox.com/s/8dqx8nxmkpf36nr/pinterest-32.png), [16x16](https://www.dropbox.com/s/cksnzccw1wd0780/twitter-16.png)
* Sharing icons
  * Email: [64x64](https://www.dropbox.com/s/cj5v3zrq3d7qq44/email-64.png), [32x32](https://www.dropbox.com/s/twfojmze8nxrnyc/email-32.png), [16x16](https://www.dropbox.com/s/jyncfgq3vyhow7s/email-16.png)
  * Link: [64x64](https://www.dropbox.com/s/6xnu4otonoa4j39/link-64.png), [32x32](https://www.dropbox.com/s/q5jpsvxxlfrybsp/link-32.png), [16x16](https://www.dropbox.com/s/d3asefjuiaab1j7/link-16.png)
  * Copy code: [64x64](https://www.dropbox.com/s/owseil4stnt7kja/copy-code-64.png), [32x32](https://www.dropbox.com/s/2fgj41w3nt8gkiy/copy-code-32.png), [16x16](https://www.dropbox.com/s/0hmvdn14rt7f93y/copy-code-16.png) – Updated July 21
  * Copy image: [64x64](https://www.dropbox.com/s/jsiu7wm0a6pa01m/copy-image-64.png), [32x32](https://www.dropbox.com/s/9zq8ymdbdguloi7/copy-image-32.png), [16x16](https://www.dropbox.com/s/mwiwr5x8bfrn25u/copy-image-16.png) – Updated July 21

### Appear in navigation area (up top)

* Home – go to the PageShot homepage
  * Empty: [PNG](https://www.dropbox.com/s/isdi8a02d30vfj1/home-empty.png), [PNG@2x](https://www.dropbox.com/s/6j308sho2o69fc0/home-empty%402x.png), [SVG](https://www.dropbox.com/s/qbym5210okwvcd2/home-empty.svg)
  * Filled: [PNG](https://www.dropbox.com/s/kbjm0g9fk5mi6cv/home-filled.png), [PNG@2x](https://www.dropbox.com/s/ex0g9pmq2qsldry/home-filled%402x.png), [SVG](https://www.dropbox.com/s/6w3zkz9vdacfhfr/home-filled.svg)
* Profile – access the user profile menu
  * Empty: [PNG](https://www.dropbox.com/s/pa77x8nv6xpytji/profile-empty.png), [PNG@2x](https://www.dropbox.com/s/1cinith9pyfl96s/profile-empty%402x.png), [SVG](https://www.dropbox.com/s/yxdxci7feey6p2x/profile-empty.svg)
  * Filled: [PNG](https://www.dropbox.com/s/8kej79l0rd9g6hj/profile-filled.png), [PNG@2x](https://www.dropbox.com/s/6agetahqvac6jrf/profile-filled%402x.png), [SVG](https://www.dropbox.com/s/ts1tigz66jogkmp/profile-filled.svg)
* Search: [PNG](https://www.dropbox.com/s/ac9o5rbiihcnnzt/search.png), [PNG@2x](https://www.dropbox.com/s/fp7zkgtgivwep4h/search%402x.png), [SVG](https://www.dropbox.com/s/2f2p3i2z6pgc79h/search.svg)
* Navigation arrow – navigate between clips – updated May 8
  * [Up](http://cl.ly/371t1P3x1i0F/arrow-up.svg)
  * [Down](http://cl.ly/1x0k443v0L1V/arrow-down.svg)
  * [Left](https://www.dropbox.com/s/izn6x0td4nnq6yk/arrow-left.svg)
  * If navigation is disabled, set opacity to 0.4

### Appear in content area

* Comment – add/display comment on clips updated May 7
  * [View](http://cl.ly/371x0K0n1W0B/comment-empty.svg) (if there’s no new comment, set opacity to 0.4)
  * [New comment available](http://cl.ly/2T1U3R373l27/comment-filled.svg)

**Comment by ianb** [comment]
If you are in an icon making mode, a "select text mode" icon would be nice.  I'm making some progress on #194 and feeling excited about it.

Delete thumbnail feels very light – could the lines be thicker?

We could consider adding icons to some buttons, like Copy Link, Delete Shot.

An icon for going to the original site (I think I've seen a right-pointing arrow in your mockups)

Not sure if we want to do anything with the selection handles.  (Right now they are just little squares, which is conveniently easy to mark up in CSS.)

We also have some other views we might want to copy.  In the current PageShot site we have a clipboard icon which copies rich views of the shot to the clipboard.  We may want to keep that functionality.  But I find "copy" icons undecipherable – like I have some kind of cut/copy/paste dyslexia where they all look plausibly equivalent.  Not sure if other people have the same problem.

**Comment by brampitoyo** [comment]
I updated the delete thumbnails link so they look thicker.

I also designed the select image and select text icons. They’re sized 16x16, because the enclosing button size would be somewhere along the lines of 24px high and 28px wide (like Firefox toolbar button), or 32px wide (pdf.js button).

We might also want try a larger-size button. I reckon we can get away with a button that’s twice the proposed size. It would would be 48px high, and the icon inside it would be 32x32.

**Comment by brampitoyo** [comment]
![pageshot-highlight-selection-handle](https://cloud.githubusercontent.com/assets/51007/6724145/17f044ca-ce57-11e4-9698-7ee951798029.png)

* Border and selection handle colour: rgb(50,163,255)
* Inner colour: rgba(50,163,255,.25)
* Border width: 2px
* Selection handle width & height: 8×8px

Some considerations:

* What if we do away with inner colour? It might create confusion.
* Can we animate it, so it’s obvious that you can resize and move it? Might be tricky to code

![selection-handle-animation](https://cloud.githubusercontent.com/assets/51007/6724195/f1124b54-ce57-11e4-9696-b00808abae3f.gif)

**Comment by ianb** [comment]
Characters instead of images are always fine by me.  I think we might have had the arrow launching out of a box though?  Kind of like the conventional icon that shows the link is offsite and/or will open in a new window.  (Not sure if we want the link to load in a new window, probably not?)

**Comment by brampitoyo** [comment]
Something similar to this?

![external-link-icon](https://cloud.githubusercontent.com/assets/51007/6794389/fc1ee3d6-d235-11e4-975c-0da9da5564ad.png)

I think that we shouldn’t open external links in a new tab. User can simply use the back button to navigate back to PageShot after visiting the original page.

But if every link is opened in the same tab, then I think a simple arrow is a sufficient marker, and the arrow-launching icon unnecessary.

**Comment by brampitoyo** [comment]
I just added a bunch of icons. I think the only thing that still needs to be designed is the copy icon for the Recall panel.

**Comment by brampitoyo** [comment]
Added the copy icon for the recall panel.

At the moment, the camera toolbar icon has a white background rather than a transparent one, so I’ve added the transparent PNG version of it and the recall/library panel. I’ve also included the 2xDPI version.

**Comment by brampitoyo** [comment]
Added left-facing blue arrow under the **navigation arrow** section. This arrow is used to navigate back within the recall panel.

**Comment by brampitoyo** [comment]
Added social sharing icons, which took a while to make because rounding up all the icons and making them look good on various sizes was time consuming.

**Comment by fzzzy** [comment]
@brampitoyo I need an icon for "share via email", too.

**Comment by brampitoyo** [comment]
@fzzzy I just added a link to the email sharing icons. Upcoming: sharing icon for link!

**Comment by brampitoyo** [comment]
Added link to link sharing icons.

**Comment by brampitoyo** [comment]
Added search icon.

**Comment by brampitoyo** [comment]
Added home and profile buttons (used on web interface).

**Comment by brampitoyo** [comment]
Organised icons by placement (doorhanger vs. web), and updated link to recall panel (it’s now dark grey and no longer white).

**Comment by ianb** [comment]
We should close this ticket once we are sure that all the images here have been included in PageShot

**Comment by brampitoyo** [comment]
I think I’ve uploaded all the graphic assets thus far, so this ticket can now be closed.
