### ISSUE TITLE
Shot expired page should look prettier

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1893]
Spotted a shot shared in a bug and the shot had expired, and this page looks kind of unpretty:

![firefox_accounts__devices_and_new_issue_ _mozilla-services_pageshot_and_https___pageshot_dev_mozaws_net_homepage_install-test-local_html](https://cloud.githubusercontent.com/assets/557895/19982864/f96794a2-a1c4-11e6-9ada-13038cfef938.png)
**Figure 1:** via https://pageshot.net/ELQi9ixejX33Xc6k/accounts.firefox.com

It should probably be styled to look more like the **Page Not Found** page, or something: https://pageshot.dev.mozaws.net/ELQi9ixejX33Xc6k/accounts.firefox.com

**Comment by ianb** [comment]
That is probably a CSS problem of some sort (e.g., loading the wrong CSS file), it definitely shouldn't look that bad.

**Comment by ianb** [comment]
Expire page was actually broken in master, fixed that in 20380ce1637b6085a22f44187637a8cee20b0d3f

It now looks like this, which isn't great, but not *as* horrible:

![image](https://cloud.githubusercontent.com/assets/44390/19985237/acb5d91e-a1df-11e6-9ce9-37d1d89a89fd.png)

Assigning to @johngruen to finish up.
