### ISSUE TITLE
[release] 2.1.201611042127 on stage

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1907]
Please QA stage. Use this issue to track deployment status to production.

**Comment by fzzzy** [comment]
You can install a copy of the latest addon from https://pageshot.stage.mozaws.net/homepage/install-test-local.html but double check that the backend url in the add-on preferences is set to `https://pageshot.stage.mozaws.net`, because there seems to be an issue with this value being cached or something.

**Comment by ianb** [comment]
One problem found: #1906

**Comment by SoftVision-CosminMuntean** [comment]
I have also logged two new issues: #1918, #1919
