### ISSUE TITLE
Editing text field should be wider

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#1914]
![washington_post__breaking_news__world__us__dc_news___analysis](https://cloud.githubusercontent.com/assets/557895/20025358/d8b914ce-a2aa-11e6-83b7-deb646740e5c.png)
**Figure 1:** Before.

![washington_post__breaking_news__world__us__dc_news___analysis](https://cloud.githubusercontent.com/assets/557895/20025364/edbfa41e-a2aa-11e6-8762-7f04f4fcc45f.png)
**Figure 2:** During editing.

Because my title is pretty long, the editing text input field seems very small and requires too much scrolling.
Not sure if we should set the text input width based _roughly_ on the width of the non-editable text.

**Comment by ianb** [comment]
Let's do this after #1924

**Comment by johngruen** [comment]
Closed due to meh
