### ISSUE TITLE
The share notification messages for saved shots are no longer displayed

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1918]
[Affected versions]:
- Firefox 49.0.2 and up
- Mozilla Page Shot 2.1.201611042127

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Latest PageShot add-on (v2.1.201611042127) is installed on a clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite. 
2. Navigate to any website or a personal website (eg: Facebook, email client, etc).
3. Click on the "PageShot" button from browser toolbar and save a selection on the page.
4. Click on the "Share" button and observe the message under the shareable link.
 
[Expected result]:
- Random website: "This shot is only visible to you until you share the link." message is correctly displayed.
- Personal website: "You've saved a personal version of this shot." message is correctly displayed.

[Actual result]:
- The notification messages are no longer displayed. 

[Notes]:
- I was unable to reproduce this using the Page Shot v1.0.201610251521 installed from Test Pilot.
- Added a screenshot with the issue:

![share notification](https://cloud.githubusercontent.com/assets/19226534/20059693/33da800c-a500-11e6-9320-fc7691c0bb03.png)

**Comment by fzzzy** [comment]
I'm not sure this is actually fixed yet, so let's just reopen this to verify.

**Comment by SoftVision-CosminMuntean** [comment]
I can still reproduce this issue using the latest Page Shot v.2.3.201611081644 installed from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.  

The notification messages are not displayed under the shareable link. Tested on the latest Firefox (49.0.2) release and the latest Nightly (52.0a1) build.

**Comment by fzzzy** [comment]
Yes, so can I. I guess we'll fix it next release.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the Page Shot v.2.6201611151354 installed from stage server. This are the results:
- "This shot is only visible to you until you share the link." message is now displayed under the shareable link, but it does not disappear after 30 seconds like on the older versions.
- The "You've saved a personal version of this shot." message is still not displayed after you save a shot on a personal page.

**Comment by ianb** [comment]
I think there might have been some build/version mixup here.  This is what I see in master:

![image](https://cloud.githubusercontent.com/assets/44390/20354904/2f93cf44-abe5-11e6-8fae-42769280a8d6.png)

**Comment by fzzzy** [comment]
Stage might have a bad database at the moment, and an old version. Dev is I think ok right now. I will try to fix up stage now.

**Comment by SoftVision-CosminMuntean** [comment]
After a shot is saved on a personal page (eg. from gmail or facebook), the "You've saved a personal version of this shot." message is not displayed under the shareable link.
 
Tested with Page Shot (v 4.0.201612191406) installed from stage server.
