### ISSUE TITLE
Inline selection CSS shouldn't affect the .button class

### ISSUE THREAD

**Issue by emmyemi** [mozilla-services/pageshot#1926]
This messes with and/or breaks sites that also use .button, which I imagine is fairly common since it's a simple, nonspecific, and easy to remember class name. Example screenshots (before and after):

![before pageshot](http://i.imgur.com/NBhcUyC.png)
![after pageshot](https://pageshot.net/images/faa272e0-156c-4b23-94b9-80d3cc39a6b4)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that this issue is related to #1596.

**Comment by emmyemi** [comment]
Yep, definitely the same issue. I [forked](https://github.com/emmyemi/pageshot) and changed instances of .button to .pageshot-button to see if that would help, but I've yet to be able to test it.

**Comment by ianb** [comment]
I'm pretty sure this is fixed with #1725, though without a site to test I'm not 100% sure.  But closing anyway.  The fix to #1725 should be released in v3
