### ISSUE TITLE
Add an express error handler that writes to raven

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#1932]
https://expressjs.com/en/guide/error-handling.html

**Comment by ianb** [comment]
We have this already: https://github.com/mozilla-services/pageshot/blob/fd4a512cce629cee3880f120045ad09214a0fd5a/server/src/server.js#L958-L970

**Comment by fzzzy** [comment]
It needs to be added as the last handler in order to work... I'm not sure that is the case
