### ISSUE TITLE
When doing a text selection, capture surrounding context

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#194]
Instead of ripping text out of the page, we could use a text selection as a highlight and select a rectangle of the surrounding context.  For instance:

![image](https://cloud.githubusercontent.com/assets/44390/6702170/664914d4-ccf5-11e4-972d-3856c5139182.png)

Then we get the advantage of an exact selection, and the context that likely makes it more useful.  I'm guessing we'd look for the containing paragraph(s), or previous/next list items, up to a maximum of maybe two lines (2em).

I think we can do this as text and keep enough of the styling, without necessarily relying on an image.  This would let someone select and copy text directly from the clip, and we could also rewrap the text.  We would probably want to over-capture context, and then choose what to show in context.

**Comment by ianb** [comment]
This is partially done now, will cover any integration of these selections in another issue.

**Comment by brampitoyo** [comment]
Yeah. I think this behaviour will solve a lot of problems of highlighting image vs. highlighting text. I’d love to get a demo of it on Tuesday or test out how it feels via an updated add-on.

The next problem to solve is: when you highlight both the image and text from the same part of the page, how do we display the two pieces side by side without confusing the user? Image is great for sending to other people, but text is great for searchability.

**Comment by ianb** [comment]
[Here](https://twitter.com/avibryant/status/579981413358817280) is a sample using multiple selections in one paragraph.

**Comment by brampitoyo** [comment]
Mockups for text selection in doorhanger panel.

Is it possible to highlight text in a native way, then put that selection inside a lightbox after the mouse has been released?

![pageshot-text-selection](https://cloud.githubusercontent.com/assets/51007/7110867/899e9ec8-e20c-11e4-9823-4233936f2fb4.gif)
