### ISSUE TITLE
Allow direct embedding of images

### ISSUE THREAD

**Issue by rugk** [mozilla-services/pageshot#1947]
It would be awesome if I could use the same link for HTML linking and for embedding the image on other sites.

E.g.:
```markdown
Here is a nice [image](https://pageshot.net/BqfbQfLoOuvXP7YF/www.srihash.org).

And here a preview:
![image](https://pageshot.net/BqfbQfLoOuvXP7YF/www.srihash.org)
```

I think with some server tweaks (like UA detection or so) this might be possible, is not it?

**Comment by ianb** [comment]
I thought it would be cool too and investigated it in #1757 – unfortunately there's no way to do this.
