### ISSUE TITLE
[FeatureRequest] Ability to save/copy image without uploading

### ISSUE THREAD

**Issue by saksmt** [mozilla-services/pageshot#1950]
Please, add ability to save/copy image without uploading to pageshot.net. It is not correct for private/sensitive/commercial screenshots to be loaded on public service. Also it's very disappointing when you try to make a screenshot, extension says that URL is copied, but then you see that server is down/buggy like today.

**Comment by ianb** [comment]
Implemented as described in #2024, will be released this week
