### ISSUE TITLE
"Bad response: 504 GATEWAY_TIMEOUT" error displayed after saving a selection on public server

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#1951]
[Affected versions]:
- Firefox 49.0.2
- Mozilla Page Shot 2.3.201611081751

[Affected Platforms]:
- All Windows
- All Mac

[Prerequisites]:
- Test Pilot add-on was previously installed on a new profile from testpilot.firefox.com.
- Page Shot experiment was previously enabled.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
3. Click on "Page Shot" icon from the browser toolbar and save a selection on the page.
3. Observe the browser behavior.
 
[Expected result]:
- The selection is successfully saved.

[Actual result]:
- A "Bad response: 504" error is displayed and the selection is not saved.

[Notes]:
- After looking over browser console logs, it seems that the server might be down. 
- This issue is not reproducible with Page Shot dev installed from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.
- Added a screen shot with the issue:
![error bad response](https://cloud.githubusercontent.com/assets/19226534/20211933/698a2de0-a809-11e6-89e6-0d8b8496089d.png)

- Here are the browser console errors:
![page shot errors](https://cloud.githubusercontent.com/assets/19226534/20211941/6fc3a3e4-a809-11e6-87d5-5968fea6d747.png)

**Comment by braiam** [comment]
Backend server seems down. When trying to access https://pageshot.net/, it informs that Pageshot is not installed. Appears to be another symptom of the same problem.

**Comment by fzzzy** [comment]
Yes, the server is down at the moment. We are working on rolling back.

**Comment by fzzzy** [comment]
We have deployed a new version that may have helped. We will continue to monitor the situation.

**Comment by ianb** [comment]
After a couple cascading problems, we believe we have resolved this issue.
