### ISSUE TITLE
Selection handles misaligned slightly

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#200]
I think the handles are aligned as though they are 10px wide, but they have a 1px border so they are really 12px wide.

**Comment by fzzzy** [comment]
If you use box-sizing: border-box, the borders will be included in the width of the box instead of being added to the width.

**Comment by ianb** [comment]
Probably to be resistant to site CSS it should be explicit about box sizing too

**Comment by ianb** [comment]
I tried to do border-box, and it didn't quite do it.  Not 100% sure what's going on.

**Comment by ianb** [comment]
I think this is better now
