### ISSUE TITLE
"Cannot connect to Page Shot server" message overlaps all windows

### ISSUE THREAD

**Issue by sivaraam** [mozilla-services/pageshot#2006]
When my laptop is offline and when I open firefox (with Page Shot add-on installed) the error message "Cannot connect to Page Shot server" shown overlaps all windows (displayed when the currently active window is a file explorer or another browser). I could not reproduce this on another machine that runs Windows neither in one that runs BOSS Linux. My device details:

_Base system_                : Debian GNU/Linux stretch/sid 64-bit
_Desktop environment_  : GNOME Wayland
_Browser_                       : Firefox Nightly 53.0a1

**Expected result**
Error message displays only when Firefox window.

**Actual result**
The error message overlaps all other windows.

**Suggestion**: It would be nice if the error message was displayed only when the user tries to use Page shot when the device is offline instead of showing when the user starts the browser

**Screen shots**
![screenshot from 2016-11-12 08-27-30](https://cloud.githubusercontent.com/assets/12448084/20629088/aa970b86-b34f-11e6-8237-925dbb92c467.png)

![screenshot from 2016-11-25 19-32-09](https://cloud.githubusercontent.com/assets/12448084/20629130/e1790622-b34f-11e6-9790-d494e453d3f4.png)

**Comment by sivaraam** [comment]
Is there any way could attach screen shots to show the bug ?

**Comment by SoftVision-CosminMuntean** [comment]
@sivaraam Thanks for reporting this issue. If you have a screenshot you can drag it or pasting in the comment area. Also you can click the "selecting them" link from the bottom of the comment area and a window will be displayed in order to select a file.

**Comment by sivaraam** [comment]
@SoftVision-CosminMuntean Sorry didn't notice that. :)

**Comment by sivaraam** [comment]
![screenshot from 2016-11-12 08-27-30](https://cloud.githubusercontent.com/assets/12448084/20629101/be2a0004-b34f-11e6-8874-99167a51402f.png)

**Comment by ianb** [comment]
I think the sticky popup is an issue with Nightly.

We should not bother notifying about login errors on startup though.
