### ISSUE TITLE
Design selections for the shot page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#201]
While the lightbox effect works nicely for making a selection, we also want to display the selection when you click on it in the shot view (scrolling to the original location and highlighting the selection).  The lightbox feels very heavy in this case, since it obscures *everything* except the highlighted area.

**Comment by brampitoyo** [comment]
Selection handle:

![pageshot-highlight-selection-handle](https://cloud.githubusercontent.com/assets/51007/6724145/17f044ca-ce57-11e4-9698-7ee951798029.png)

* Border and selection handle colour: rgb(50,163,255)
* Inner colour: rgba(50,163,255,.25)
* Border width: 2px
* Selection handle width & height: 8×8px

Some considerations:

* What if we do away with inner colour? It might create confusion.
* Can we animate it, so it’s obvious that you can resize and move it? Might be tricky to code.

![selection-handle-animation](https://cloud.githubusercontent.com/assets/51007/6724195/f1124b54-ce57-11e4-9696-b00808abae3f.gif)

**Comment by ianb** [comment]
With some work we can animate it, like in [this example](http://codepen.io/christopheschwyzer/pen/CEwBI).  I like that as a way to make it stand out without coloring.

**Comment by brampitoyo** [comment]
+1 to doing something like the example. Is it possible to have an infinite cycle, like in [this example](http://codepen.io/anon/pen/zxerjM)

**Comment by ianb** [comment]
I think these designs are obsolete?

**Comment by brampitoyo** [comment]
Yes. These designs are obsolete. Animated handles was an awesome idea, but as the web interface get more complex (it can display multiple highlights, etc.), it becomes important to darken the rest of the page. With darkening, the animation is no longer necessary to convey emphasis.
