### ISSUE TITLE
Add footer links in homepage?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#2013]
Found in https://pageshot.net/__version__ (bd71a5d):

```json
{
  "source": "https://github.com/mozilla-services/pageshot/",
  "description": "Page Shot application server",
  "version": "November 15, 2016 13:54:53 UTC",
  "commit": "bd71a5d",
  "contentOrigin": "pageshot-usercontent.net",
  "commitLog": "https://github.com/mozilla-services/pageshot/commits/bd71a5d",
  "unincludedCommits": "https://github.com/mozilla-services/pageshot/compare/bd71a5d...master"
}
```

---

I just noticed that the [/terms](https://pageshot.net/terms) and [/privacy](https://pageshot.net/privacy) pages have beautiful footers with "Terms", "Privacy Notice", "Report IP Infringement", "Send Feedback" and "GitHub" links, but, the homepage doesn't:

![privacy_notice](https://cloud.githubusercontent.com/assets/557895/20688965/fdc76ee8-b577-11e6-9c92-66bd7b2f460a.png)
**Figure 1:** Beautiful footer links.

---

![page_shot__a_screenshot_tool_for_firefox](https://cloud.githubusercontent.com/assets/557895/20688977/0b2b7296-b578-11e6-9c03-6a4486f45a40.png)
**Figure 2:** GitHub logo in footer only. No links to our **Terms of Service** or **Privacy Notice**.

**Comment by ianb** [comment]
Probably we need a complete front page redesign.

**Comment by ianb** [comment]
Closing this as we need to do a complete homepage redesign for the 54 launch
