### ISSUE TITLE
Can we edit the screenshot after take it?

### ISSUE THREAD

**Issue by ganlanyuan** [mozilla-services/pageshot#2030]
Like add some arrow, circle or text.
Refer to [skitch](https://evernote.com/skitch/?BHT-c22225a9-5237-2d40-bb06-9fa0a8059aee.0) which I used a lot when I do trouble shooting.
Thanks

**Comment by pdehaan** [comment]
@ganlanyuan I agree. I think this is a dupe of **"Create an interface to let users annotate shots"** #1849.

**Comment by johngruen** [comment]
Yes, closing as dupe

**Comment by johngruen** [comment]
to be clear, we are going to do this...just tracking the issue through #1849

**Comment by ganlanyuan** [comment]
Thanks
