### ISSUE TITLE
Keyboard shortcuts interfering with writing

### ISSUE THREAD

**Issue by underovsky** [mozilla-services/pageshot#2035]
Hi, I really love the plugin and use it on everyday basis, but there is one really annoying bug.

The ``alt+c`` and ``alt+x`` are used to type ``ć`` and ``ź`` characters in the polish keyboard.

There needs to be an option in plugin settings to change the shortcuts or maybe just turn them off.

**Comment by fzzzy** [comment]
This shouldn't be interfering... the keyboard shortcuts is control-alt-meta-c. Are you experiencing a bug where the shotcut is being triggered with just alt-c? If so, we would appreciate more info about how to reproduce this bug. Thanks!

**Comment by underovsky** [comment]
I did some digging and here's what I found.

Firstly I checked if shortcut is actually right and it is: `combo: "accel-alt-control-c"`. So this wasn't the case.

I'm using Ubuntu and Windows. It turned out it happens only on Windows. I tried both on regular Firefox and Firefox Developer Edition.

So my guess was the keyboard. I came across this Atom issue https://github.com/atom/atom/issues/11289  from March this year.

It turns out that on Windows international keyboards rALT is treated same as CTRL-ALT shortcut.

They did some workaround describing it in this issue ttps://github.com/atom/atom-keymap/issues/35

I may try to actually dig up the solution they did, but need to find some time for it. :)

**Comment by skibbipl** [comment]
OK, I'm having the same problem on Windows. Whenever I try to enter `ć` in firefox page shot opens. I use right Alt + C to enter the letter `ć`.

**Comment by d-rez** [comment]
We need this, I have to disable the addon whenever I'm not using it

**Comment by ianb** [comment]
We'll be disabling the hotkey in the next release (#2107)
