### ISSUE TITLE
Page-wide/high crossbars on selection

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#204]
Big crossbars make it easy to see, e.g., where the bottom left corner could be when you are selecting the top left corner.  Also can be used to indicate snap lines before you start the selection.

**Comment by brampitoyo** [comment]
Is this the kind of page-wide selection crossbar that we’re thinking of?

![page-wide-selection](https://cloud.githubusercontent.com/assets/51007/6773926/fd6c8194-d17c-11e4-9967-5e10654fda71.png)

With the crossbar, we no longer need to change the cursor shape to a crosshair. Plus, we could include a caption that could tell the user exactly what to do.

I designed the crossbar so the caption would always appear on the top-right corner of the bar. As the cursor approaches the corner of the page, the caption position would shift sides so it can always appear in full.

![page-wide-selection-caption-behaviour](https://cloud.githubusercontent.com/assets/51007/6773976/b49b3e1e-d17d-11e4-8e35-f2236bdfb1b0.png)

**Comment by ianb** [comment]
Yes, that's the kind of crosshair I was thinking about.  Open question: after you start the selection, do the crossbars stick around?  Clipular does not keep them around, but does shade out the entire screen until you start the selection (makes it very hard to miss that you are in selection mode).

**Comment by brampitoyo** [comment]
I don’t think the crosshair should stick around after starting the selection. Instead, it should be replaced by a lightbox. In other words, let’s do it like Clipular does it.
