### ISSUE TITLE
Save and Cancel button is not visible when the screenshot of whole window taken

### ISSUE THREAD

**Issue by mMARUF** [mozilla-services/pageshot#2043]
If the screenshot of whole screenshot of whole window is taken, by mouse , there should have been a save and cancel button for the screenshot which is just taken. But unfortunately it is not there. In the attachment, you will see that i have taken the screenshot of whole window with pageshot, but save and cancel button is not visible. 

This issue was produced with : latest Developer Edition (Aurora) 52  

Attachment: https://drive.google.com/open?id=0B75_JfziYeofMm5DNjR6Z1hGRlU

**Comment by ianb** [comment]
We can try to detect when this happens (in `selector-ui.js`) and add a class that causes the buttons to get placed back inside the selection instead of below.

**Comment by petestrash** [comment]
I have also come across this and would like to see a workaround.
