### ISSUE TITLE
page ratio number color is not perfectly noticable in dark developer theme

### ISSUE THREAD

**Issue by mMARUF** [mozilla-services/pageshot#2044]
If we try to take screenshot with pageshot , and if you change the position of the mouse , the ratio of the screen(how much area we area we are selecting for screenshot) is shown in numbers. But , in dark developer theme, the numbers can not be seen easily, A different color(may be wghite) would do the trick. 

This issue was seen in latest Nightly 53
 Attachment : https://drive.google.com/open?id=0B75_JfziYeofZ2dMMTA2TGppUVE

**Comment by ianb** [comment]
I don't think this is related to the dark theme, but just to the dark background of the Test Pilot page that is being captured in the example.

We have a white shadow to try to make it more visible, but we could try to increase the size or contrast of that shadow.
