### ISSUE TITLE
Browser hangs when snapshotting signalfx

### ISSUE THREAD

**Issue by djmitche** [mozilla-services/pageshot#2047]
![screenshot from 2016-12-12 15-45-48](https://cloud.githubusercontent.com/assets/28673/21116077/13b0cde8-c082-11e6-9347-360e9a345325.png)

If I click the pageshot icon, then hover over the lighter-gray "Gecko Pending", the browser freezes.

pageshot 3.3.201611301947

**Comment by 6a68** [comment]
@djmitche Hey, can you still reproduce this issue?

I tried creating a signalfx account, went into one of the demo dashboards, and wasn't able to reproduce this issue on current Dev Edition:

<img width="1389" alt="screen shot 2017-03-14 at 5 09 51 pm" src="https://cloud.githubusercontent.com/assets/96396/23927790/27e18e0c-08d9-11e7-8c04-4f55f4303793.png">

**Comment by djmitche** [comment]
Not anymore, no.
