### ISSUE TITLE
Full-screen autoSelect overshoot issue on Yahoo

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#205]
Website: [yahoo.com](https://yahoo.com)

autoSelect behaviour: selection overshoots too far to the right side of the page, making it impossible to resize.

![Yahoo home page](https://cloud.githubusercontent.com/assets/51007/6795004/9bc9df46-d23e-11e4-8027-dbeb5dfe955c.PNG)

**Comment by ianb** [comment]
autoselect is gone
