### ISSUE TITLE
Release 4.0 Deneb

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#2055]

**Comment by SoftVision-CosminMuntean** [comment]
It seems that the server might be down. I logged a new issue for this: #2057.

**Comment by fzzzy** [comment]
Yes, stage seems to be down at the moment. I will have to work with ops later today to try to get it fixed. Dev is up to date and working.

**Comment by fzzzy** [comment]
Dev had an out-of-date add-on, but I redeployed and it works properly now.

**Comment by SoftVision-CosminMuntean** [comment]
This are the new issues logged:
#2059 - The "Download" button is rarely working
#2058 - If the mouse is moved while you click and hold a button, the button stops working

**Comment by fzzzy** [comment]
We're going to just delay this release until the new year, so we can make sure these bugs get fixed and I can do some test pilot stuff I need to do.

**Comment by fzzzy** [comment]
One more blocker: https://github.com/mozilla-services/pageshot/issues/2073
