### ISSUE TITLE
Feature request: copy text from image

### ISSUE THREAD

**Issue by newsjunkie247** [mozilla-services/pageshot#2056]
It would be great if you could add the option/ability to copy text from saved pages when possible. This is great already but then it would be perfect.

**Comment by ianb** [comment]
If we put the text in an `alt` attribute on the image, and you select the image and copy then paste into a text field, you'll get the alt text.  I thought we did have an alt attribute, but we don't, so I propose we put that back.

**Comment by ianb** [comment]
I put in the `alt` attribute in d017043e4955369c63012b09570725c47810015b – with this if you select the image itself (which requires dragging across the image) then paste into a text field you'll get the text.

It's not a great solution though.  It's not that easy to just select the image.  If you right click and do "Copy Image" then you don't get the alt text.

I'm going to try to add a [contextmenu](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contextmenu) to add a right-click option to the clip image to copy the text.

**Comment by ianb** [comment]
In 40a66578237aaa3246317c8d1ea05f587aeb6d6e I added a context menu, "Copy Image Text" which works better.  (The alt attribute still makes sense, but doesn't really address the use case itself.)
