### ISSUE TITLE
Page Shot buttons are glued to the vertical scroll bar on Windows

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2060]
[Affected versions]:
- Firefox 50.1.0
- Mozilla Page Shot 4.0.201612191406

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.stage.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on "Page Shot" icon from the browser toolbar.
3. Observe the Page Shot buttons from the top right corner of the page.
 
[Expected result]:
- The buttons are correctly displayed with space between them and the vertical scrollbar.

[Actual result]:
- The buttons are glued to the vertical scrollbar.

[Notes]:
- I have also observed that when the overlay covers the entire page, a horizontal scroll bar is also displayed at the bottom of the page.
- Here is a screenrecroding with the issue:

![glued buttons](https://cloud.githubusercontent.com/assets/19226534/21352190/142f1534-c6c9-11e6-9b38-57764c117bab.gif)

**Comment by ianb** [comment]
Probably we just need to move the buttons slightly to the left to fix this.  But it may be harder, we may need to adjust the iframe size to avoid horizontal scrolling (we attempt to do this but maybe we don't).

**Comment by johngruen** [comment]
I think i fixed this
