### ISSUE TITLE
Should be able to customize or disable the keyboard shortcut

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#2065]
This would work around some bugs with foreign keyboard layouts sometimes accidentally triggering the keyboard shortcut.

Also, it is a requested feature:

https://discourse.mozilla-community.org/t/feature-request-ability-to-customize-shortcuts/12732

**Comment by d-rez** [comment]
#2035 should be related.

We need this for the Polish keyboard

**Comment by ianb** [comment]
In the next release we've just removed the keyboard shortcut to avoid these conflicts.  It should be released tomorrow.
