### ISSUE TITLE
My Shots in a sidebar

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#2066]
An interesting idea which was submitted:

https://discourse.mozilla-community.org/t/feature-request-ability-to-customize-shortcuts/12732

**Comment by ianb** [comment]
Did we come up with an actionable plan for this?  I can't recall one.  Bumping back into triage.

**Comment by ianb** [comment]
I don't think we have enough product insight to move forward on this one way or the other.  Closing for lack of next steps or the likelihood of coming up with next steps anytime soon.
