### ISSUE TITLE
Design idea: comment on clip

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#207]
Thinking about annotation, which is something we haven't really thought about much in our designs:

If you think about something like Genius, the basic idea is to highlight something and add an annotation. We have half of that already, and we want comments on the entire shot. But it occurs to me that adding a comment on a clip is almost exactly like an annotation. A clip without an annotation is just saying "look at this!" (presumably it is self-explanatory why you made that clip)

I don't think we have to address this annotation use case right away, but I can imagine with our current designs that we have the carousel of clips, and it wouldn't be crazy to make the comment field attach to the specific clip.  I think this might actually be better even for the (common) single-clip case, to encourage people to make more specific/actionable comments by clearly pairing them with the a clip.

Also, while I liked some of the comment mockups on the shot page, it becomes very confusing when the page has an author, and the viewer is also logged in.  Which identity do you show in the top toolbar?  By attaching the comment to the clip we avoid that ambiguity.

**Comment by brampitoyo** [comment]
Addressed in the latest round of mockups:
![pageshot-clip-comment](https://cloud.githubusercontent.com/assets/51007/7110006/cbd157b8-e1fd-11e4-8176-b0b36e882e28.png)

The next feature to design is viewing and responding to comment in context of the full page.

**Comment by ianb** [comment]
As a design, I think we're done.  #382 is for implementing showing those comments on the shot page (we can enter comments on the panel already)
