### ISSUE TITLE
Blank Image

### ISSUE THREAD

**Issue by Captain-Cheesecake** [mozilla-services/pageshot#2070]
Hi there!

I was doing some work for my youtube channel online and wanted to get a picture of the screen,
when I used pageshot it took the picture as I think it should but when i went to view it, it was just blank.

Hope this is enough info!

CC

**Comment by ianb** [comment]
Can you share the URL of the shot with us?

**Comment by Captain-Cheesecake** [comment]
Ah sorry about that some of my photo editing software was updating and it was just a compatability issue with my remaining programs.
