### ISSUE TITLE
Run npm outdated for Elnath

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#2078]

**Comment by wresuolc** [comment]
I can hook up greenkeeper if you want

**Comment by ianb** [comment]
We actually disabled Greenkeeper because it was too noisy, so we're trying just a single batch update once a sprint as an alternative.

**Comment by pdehaan** [comment]
```sh
$ git rev-parse --short HEAD # 5ec2913

$ nsp check
(+) No known vulnerabilities found

$ npm outdated --depth 0
```


| Package | Current | Wanted | Latest | Location | NOTES
|----|----:|----:|----:|----|----|
| addons-linter |       0.15.12 | 0.15.12 | 0.15.15 | pageshot | patch
| aws-sdk |              2.7.12 |  2.7.12 |  2.7.23 | pageshot | patch
| babel-polyfill | 6.16.0 | 6.16.0 | 6.20.0 | pageshot | minor ❕ 
| browserify | 13.1.1 | 13.1.1 | 13.3.0 | pageshot | minor ❕ 
| convict |               1.5.0 |  1.5.0 |  2.0.0 | pageshot | **major** ⚠️ 
| domino |               1.0.26 | 1.0.26 | 1.0.27 | pageshot |  patch
| eslint |               3.11.1 | 3.11.1 | 3.13.1 | pageshot |  minor ❕ 
| eslint-plugin-react |   6.8.0 |  6.8.0 |  6.9.0 | pageshot | minor ❕ 
| geckodriver |           1.2.0 |  1.2.0 |  1.3.0 | pageshot | minor ❕ 
| node-sass |            3.13.0 | 3.13.0 |  4.3.0 | pageshot | **major** ⚠️ 
| npm-run-all |           3.1.2 |  3.1.2 |  4.0.1 | pageshot | **major** ⚠️ 
| pg |                    6.1.0 |  6.1.0 |  6.1.2 | pageshot | patch
| raven |                0.12.3 | 0.12.3 |  1.1.1 | pageshot | **major** ⚠️ 
| raven-js |              3.9.0 |  3.9.0 |  3.9.1 | pageshot | patch
| react |                15.4.1 | 15.4.1 | 15.4.2 | pageshot | patch
| react-dom |            15.4.1 | 15.4.1 | 15.4.2 | pageshot | patch
