### ISSUE TITLE
Do A/B test on doing an onboarding highlight of Page Shot button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2081]
In the A/B test a group of people will get some notification pointing out the new button to them.  Probably using UITour, or maybe just a panel.

We want to determine if people who are shown the button are more likely to make their first shot.

**Comment by ianb** [comment]
We're going to use a [badge](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_button_action#Badged_buttons) – these can hold arbitrary text.  We'll keep it until the user first clicks the button, or 24 hours.

**Comment by ianb** [comment]
Here's what it looks like with a badge of `" ! "`, which looks good to me:

![image](https://cloud.githubusercontent.com/assets/44390/22043939/ab612fd6-dcd7-11e6-87cf-88865d61c832.png)

I'll be showing it until it is clicked, unless you restart the browser 24 hours after the add-on is installed.  That is, if you keep your browser open the badge will just stick there.

Note any click on the button will turn off the badge, including clicking it on a new tab and going to My Shots.

**Comment by ianb** [comment]
That commit implements this, but it's not entirely "done".  Specifically at least we have to create the custom dimension in GA.  It might be worth having @johngruen review this too, to make sure the test process seems legitimate.

**Comment by fzzzy** [comment]
The "!" feels like an error to me. People might click the button expecting to see an error message, but then they will just see the normal page shot ui.

**Comment by ianb** [comment]
cd3 is setup:

![image](https://cloud.githubusercontent.com/assets/44390/22078793/ee3f68b6-dd7e-11e6-94ef-0c3a6f2d14a0.png)

**Comment by johngruen** [comment]
"Hi" and it should be blue, not red

**Comment by johngruen** [comment]
`#00AFF7`

**Comment by ianb** [comment]
Here's the new version of the badge (2x size):

![image](https://cloud.githubusercontent.com/assets/44390/22082570/f30d8d50-dd8d-11e6-8e39-74e542752cc6.png)
