### ISSUE TITLE
Re-sizing shot has no effect when saving

### ISSUE THREAD

**Issue by petestrash** [mozilla-services/pageshot#2086]
Page shot works fine when you select the area in one move.

But if you want to change the area after the initial selection, pageshot allows you to modify the capture area, but when saved it only shows the initial selection.

V3.3.201611301947,  Windows 10 pro X64

Other then that, I prefer pageshot to snipping tool as I can copy the image from the preview page and directly paste into an email or document without going through file/save as/open etc.

Peter.

**Comment by fzzzy** [comment]
This has been fixed and will be released with version 4.3 very soon, either today or early next week.

Thanks for the report!
