### ISSUE TITLE
Pageshot is out of order if users have installed CLIQZ

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/pageshot#2089]
Pageshot somehow doesn't work if the user has installed CLIQZ. 
Reproduce by following these steps:
1. Start Firefox/Nightly and install CLIQZ.
2. Install Pageshot.
3. Take a shot.

Expected result: It takes you to My Shots page and shows the preview that you just took.

Actual result: It prompts an error message and says 'Page Shot is out of order'.

<img width="758" alt="error message" src="https://cloud.githubusercontent.com/assets/4092794/21799132/ea23e40a-d752-11e6-9540-5746def6f6f6.png">

**Comment by SoftVision-CosminMuntean** [comment]
@TLHuang thanks for reporting this.

I can also reproduce this issue, but only if I have Cliqz installed from AMO. There are some discussions in #1882. 

However, if Cliqz is installed from Test Pilot dev server or from "https://testpilot.firefox.com/files/testpilot@cliqz.com/latest", Page Shot works properly without any problems.

Here are some browser console errors: 
![page shot and cliqz](https://cloud.githubusercontent.com/assets/19226534/21810184/5f9e89ec-d753-11e6-9515-e3b65ab65375.png)

**Comment by ianb** [comment]
I installed it in development, and Cliqz interfered with setting the login cookie.  It appeared to remove the Set-Cookie header from the response entirely (it didn't just affect the cookie jar).

I'm not sure how reproducible this is, I just noticed it on one profile.  I used [this xpi](https://testpilot.firefox.com/files/testpilot@cliqz.com/latest) (taken from the [yaml file](https://github.com/mozilla/testpilot/blob/master/content-src/experiments/cliqz.yaml)).

**Comment by ianb** [comment]
@SoftVision-CosminMuntean experimented with the two add-ons together and didn't encounter a problem.  This might be a more complicated problem than a simple conflict, but for now we don't know.  If you encounter this again please reopen!
