### ISSUE TITLE
Missing an overlay on thumbnails when hovering on My Shots page

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/pageshot#2095]
Need Visual implement!
According to the [ux spec](https://mozilla.invisionapp.com/share/WF8V8N1NX#/screens/197767847), there's a black transparent overlay on thumbnail when hovering, and the delete icon should be white.

**Current screen**
![missing an overlay on thumbnails](https://cloud.githubusercontent.com/assets/4092794/21838517/51c4161a-d80d-11e6-9afc-cea691ca58cb.png)

**Proposed design**
![2-5 delete hovered](https://cloud.githubusercontent.com/assets/4092794/21838597/df9ca5ec-d80d-11e6-9260-70a7a665b455.png)

The measurement is attached, please take a look and let me know if any questions.
[My shot hovered measurement.pdf](https://github.com/mozilla-services/pageshot/files/698139/My.shot.hovered.pdf)

**Comment by ianb** [comment]
Closing so we can create new bugs from the general design review
