### ISSUE TITLE
The size of fox images on My Shots needs to be adjusted

### ISSUE THREAD

**Issue by TLHuang** [mozilla-services/pageshot#2096]
On My Shots page, if users haven't taken a shot or there is no related searching result, it shows fox images to remind users. But the current fox images look smaller than the proposed design, needs adjustment.

**Current**
![current empty page](https://cloud.githubusercontent.com/assets/4092794/21844765/d2c94376-d82a-11e6-8986-d90534d39f9f.png)
![current no shots result](https://cloud.githubusercontent.com/assets/4092794/21844766/d2ce245e-d82a-11e6-94a4-d2718bde8a13.png)

**Proposed design**
![4-1 my shots empty data](https://cloud.githubusercontent.com/assets/4092794/21840108/9b06b040-d816-11e6-86cc-93ac10fe1419.png)
![4-2 no searching results](https://cloud.githubusercontent.com/assets/4092794/21844793/f1181a96-d82a-11e6-97e2-f8fde42c392f.png)

Please refer to the measurement and help to implement.
[4-1 My shots empty data.pdf](https://github.com/mozilla-services/pageshot/files/698527/4-1.My.shots.empty.data.pdf)

**Comment by ianb** [comment]
I changed the image size and text size in 326c1845efc54c806c997ff6f80f4a0e70d5aa49, but I didn't touch any of the other padding.
