### ISSUE TITLE
Interference between Pageshot and Firefox's Users styles (Stylish)

### ISSUE THREAD

**Issue by Nemesis31** [mozilla-services/pageshot#2105]
Hello there,

i have an issue while using Pageshot: the screen becomes completely black.

Here some screenshots:

Pageshot is enabled and Stylish too with [Firefox Black](https://userstyles.org/styles/123988/firefox-black).
<a href="https://up2sha.re/file?f=yXdRNkxmLYPa" target="_blank"><img src="https://up2sha.re/file?l=yXdRNkxmLYPa"/></a>

Pageshot enabled, and [Firefox Black](https://userstyles.org/styles/123988/firefox-black) is disabled.
<a href="https://up2sha.re/file?f=2uBk7FHa7fEG" target="_blank"><img src="https://up2sha.re/file?l=2uBk7FHa7fEG"/></a>

I didn't test with other Firefox's users styles.

The only solution i found to take screenshot with Pageshot is to disable the user style first. But, for me, it's not a great solution ^^ (maybe Firefox Black is to blame...)

**Comment by ianb** [comment]
I think this is because of this rule: 

```
/*about:blank*/
@-moz-document url("about:blank"){html{background:#000!important}}
```

and the iframe we put over it is an inline iframe that might appear to be about:blank.  I don't think we can do anything with this, but maybe that rule could be removed from Firefox Black.

**Comment by Nemesis31** [comment]
Hi,

i commented the line in the script of Firefox Black and, it worked !

Thank you ! :D

**Comment by xenithorb** [comment]
For me it was this style:  https://userstyles.org/styles/18385/about-newtab-firefox-new-tab-dark-darkstate

Which is to prevent new tabs flashing white in my face at night
