### ISSUE TITLE
"Page Shot" icon is slightly darker than the default Firefox icons from the Hamburger Menu

### ISSUE THREAD

**Issue by SoftVision-EmilPasca** [mozilla-services/pageshot#2106]
[Affected versions]:
- Nightly 53.0a1
- Mozilla Page Shot 4.4.201701170830

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Page Shot add-on was previously installed on a new profile from https://pageshot.dev.mozaws.net/homepage/install-test-local.html.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Right-click on the "Page Shot" icon from the browser toolbar and choose the "Move to Menu" option.
3. Click on the Hamburger Menu icon and observe the "Page Shot" icon.

[Expected result]:
- "Page Shot" icon has the same color as the other icons.

[Actual result]:
- "Page Shot" icon is slightly darker than the other icons.

[Notes]:
- Attached a screen recording of the issue:
![issue_pageshot_menu_icon](https://cloud.githubusercontent.com/assets/20083658/22026636/11b24a84-dcda-11e6-9a95-dcc491cbe560.gif)

**Comment by ianb** [comment]
Pocket seems to have the same problem, and we don't have a way to customize the icon based on its position (that is, if we fix the custom panel we will break the main toolbar).  Leaving it as is since we don't have a good solution.
