### ISSUE TITLE
Page Shot functionality broken in latest dev custom build (01/19/2017)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2111]
[Affected versions]:
- Nightly 53.0a1
- Mozilla Page Shot 4.4.201701190836

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot dev custom build (01/19/2017) is installed on a new clean profile.

[Steps to reproduce]:
1. Open the browser with the profile from prerequisite and navigate to any website.
2. Click on the Page Shot icon from browser toolbar and perform a selection.
3. Choose to "Save" the selection and observe the browser behavior.

[Expected result]:
- The selection is successfully saved and you are redirected to the saved shot preview page.

[Actual result]:
- The selection is not saved and a "Page Shot went haywire. Try again or take a shot on another page? abTests is undefined" error is displayed.

[Notes]:
- This issue is only reproducible with the crated custom build from GitHub.
- @ianb - When creating the build we should add some extra commands for A/B testing?
- Here are two screenshots with the browser console errors:
	- https://goo.gl/uVTKWN
	- https://goo.gl/BWRjBr

**Comment by ianb** [comment]
This was because GA wasn't configured and that path was untested.  We believe this to be fixed now.
