### ISSUE TITLE
Page Shot icon is no longer displayed in toolbar after install, on latest Nightly version (Build ID: 20170122030212)

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2123]
[Affected versions]:
- Nightly 53.0a1 (Build ID: 20170122030212)
- Mozilla Page Shot 4.3.201701052116

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- Test Pilot add-on was previously installed on the profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to testpilot.firefox.com page.
2. Click on the Page Shot experiment card and enabled it.
3. Observe the browser toolbar.

[Expected result]:
- The Page Shot icon is displayed in browser toolbar.

[Actual result]:
- The Page Shot icon is not displayed in browser toolbar even if add-on appears to be installed.

[Regression]:
- Looks like the following bug has the changes which introduced the regression: https://bugzilla.mozilla.org/show_bug.cgi?id=1330821

- Last good revision: 645331fa032779e6324e32a11898a55e6c75ee24
- First bad revision: ece477bc26a761831519a9ad9893c504dcd14f03
- Pushlog: https://goo.gl/WPrZTy

[Notes]:
- I have also logged this issue in Bugzilla:  [1333009](https://bugzilla.mozilla.org/show_bug.cgi?id=1333009)
- Here is a screen recording with the issue: https://goo.gl/594qBO.

**Comment by ianb** [comment]
Fixed in 5.1
