### ISSUE TITLE
Do not cut off downloaded images

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2130]
Full Page images have a 5000px limit.  When downloading the image there's no need for the limit, we should remove it.

**Comment by fzzzy** [comment]
Wouldn't creating an extra large screenshot still potentially block the browser? Maybe there's some way we can do it in another thread.

I'd like to argue that we should consider doing some tests to see if we can remove the limitation for uploaded shots, too.

**Comment by ianb** [comment]
I'm concerned more about the hosted size of giant full page images than I am about the browser's effort in capturing them.  That's why I put in the limit originally.  Pages can get crazy long.

**Comment by fzzzy** [comment]
Yes, I know, but I still think we should do some tests to see what the actual sizes are. Even putting pretty big stuff in s3 doesn't cost that much, especially if it expires after a couple of weeks.

**Comment by ianb** [comment]
Note `MAX_PAGE_HEIGHT` and `MAX_PAGE_WIDTH` define these sizes.

**Comment by ianb** [comment]
We should find some very long pages and test them with download and upload, with the max limit turned off.

**Comment by pdehaan** [comment]
for very long pages, I've always found random reddit posts with lots of comments regularly exceed 5000px high (https://www.reddit.com/r/funny/comments/5q5bmb/who_am_i/) or a bunch of the Apple product pages (http://www.apple.com/macbook-pro/) also return similar results.

**Comment by ianb** [comment]
Oh wait, there is no download for full page!  Pushing this back into triage until we have some design plan here.

**Comment by ianb** [comment]
Since we never created the feature, we can't fix it
