### ISSUE TITLE
MacBook Pro touchbar escape key doesn't escape anything

### ISSUE THREAD

**Issue by johngruen** [mozilla-services/pageshot#2132]

**Comment by ianb** [comment]
I bet this is a general bug, probably about keypress events and the iframe.

**Comment by ianb** [comment]
I saw this earlier (not on a touchbar), but now I can't reproduce it.  I think it might be due to a page interaction rather than a the device.

**Comment by 6a68** [comment]
I can't repro this on my touchbar MBP on release or dev edition. I've tried to hit the key just as the frames are switching, or messing with the focus before/while hitting escape, but it seems fine to me. @ianb Any guess around what triggers the issue when you've seen it?

**Comment by dannycoates** [comment]
In #2389 I made some changes to the unloading behavior including fixing a `keyup` listener bug. Maybe we should close this until someone can reproduce?

**Comment by 6a68** [comment]
:+1:
