### ISSUE TITLE
When copying text all you want is...

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#2164]
Originally submitted by @Folsome via https://github.com/mozilla/testpilot/issues/2175:

> This relates to page shot - when using this excellent tool what you look for is just the characters. To catch the whole document if you try to shrink and then copy you get (this criticism comes in two partidos) UNO the visible only, even though you fingered whole page
DOS - I can occasionally see the entire text on the screen, i.e. the program (page shot) takes down the entirety of characters, then proceeds to cut of the little piece showing (complete idiocy). Super good plus, like it so far, thank you for a great everything! Firefox rocks!

**Comment by ianb** [comment]
I think one problem is the alt text looks distracting.  A second problem is that we're over-capturing text in some situations.  We should split this into two bugs for those two issues.
