### ISSUE TITLE
Determine migration path for current users

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2169]
If we want to allow current users to migrate to the WebExtension version we should research what's possible.  Specifically we'd have to pass the auth information from its current location (about:config) into something the WebExtension can find.

At some point we probably need to make a version of the SDK add-on that handles migration, installs the WebExtension, and uninstalls itself.

**Comment by 6a68** [comment]
We discussed this in engineering mtg today. Sounds like the current plan is:

- wrap the current webextension in a bootstrapped addon (#2222)
- the bootstrapped code will handle telemetry duties (#2218)
- the bootstrapped code will handle migrating data (#2260, just opened)

Closing this 'determine path' bug in favor of those.
