### ISSUE TITLE
Implement context menu for Page Shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2191]
In the WebExtension rewrite we lost the right-click to shoot menu.

A similar [WebExtension API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus) is available.

We should analyze whether there was any engagement with the option currently and if we really want to reimplement this.  (Engineering cost is minimal, but it's surface area.)

**Comment by ckprice** [comment]
Yes we do. Many events.
