### ISSUE TITLE
Create application workflow

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#2198]
Purpose is to inform Ops on possible breaking points for server scaling. Security also noted that this could inform their review. Also informs functional and load testing.

**Comment by ianb** [comment]
I'm working on this in a [Google doc](https://docs.google.com/document/d/1SQLuvr8pjxhl0GPgglAA0eEIX9PwoCSD60qZd_4Bmj4/edit#)

**Comment by johngruen** [comment]
Here's a flow: https://www.lucidchart.com/documents/view/d8415c69-b756-4e13-ad12-b0ac576cb87b

**Comment by ianb** [comment]
Doc is done, sent to some people to review
