### ISSUE TITLE
Plan Testing for Page Shot

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#2200]

**Comment by wresuolc** [comment]
I think we should have a decent amount (>90%?) of coverage on unit/functional tests that run automatically on PRs via some CI.

I'm not sure what the best options are for testing Web Extensions.  I don't think there are (any?) options?

**Comment by ianb** [comment]
We have something that roughly does a functional test in load_test_exercise.py, though it exercises more than verifies.

We have one unit test in test/test-ab-tests.js

We have a smoke test integration test of the add-on in test/test.js, but all it does is install the addon and ensure the button is present.  It could serve as the basis for more integration testing.

For the purpose of running tests in mozilla-central I'd like to have a frontend test for the add-on where all server interaction is mocked out.  I don't think unit tests have much purpose in mozilla-central, as our well defined units of code aren't going to be regressed by Firefox changes.  Our use of APIs and our integration points may be regressed.

**Comment by wresuolc** [comment]
That makes sense.  ckarlof sent me https://testing.googleblog.com/2016/11/what-test-engineers-do-at-google.html which also favors mocked servers.  I think it's a good plan.

**Comment by wresuolc** [comment]
Alright, there is lots of different kinds of testing here.  We all talked about a plan earlier today in the engineering sync up which I'll put below and then close this.

- @pdehaan  is our testing lead.  He has a plan at https://wiki.mozilla.org/QA/PageShot54 .  He's actively working on load testing right now which is on target to hit the end of the month.
- @Standard8 is building the infrastructure and scripts to get Page Shot landed in Firefox.  This includes writing a noop (or simple) mochitest to get us started there.  This is being tracked in #2320 
- @ianb is comfortable stubbing out and mocking the interfaces for integration tests in the browser
- I'd still like to see decent unit/functional test coverage running in CI
