### ISSUE TITLE
Hook up to CircleCI

### ISSUE THREAD

**Issue by ckprice** [mozilla-services/pageshot#2201]
Assigning to @dannycoates

**Comment by pdehaan** [comment]
We're already using [Travis-CI](https://github.com/mozilla-services/pageshot/blob/master/.travis.yml). Does switching to Circle-CI give us any big benefits, or is it just for consistency w/ OPs stuff?

**Comment by ckprice** [comment]
>just for consistency w/ OPs stuff?

More this.

**Comment by ianb** [comment]
Obvious starting place is [.travis.yml](https://github.com/mozilla-services/pageshot/blob/master/.travis.yml)

**Comment by pdehaan** [comment]
Ref: #1647

**Comment by dannycoates** [comment]
Done in #2268
