### ISSUE TITLE
Plan server localization

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2205]
We should have a plan for how to implement localization across the website and add-on.

Questions: 

* What library do we use on the server?  
  * (Possible solution) The [fluent-react](https://github.com/projectfluent/fluent.js/tree/master/fluent-react) library
* What library do we use in the add-on?
  * The WebExtensions [i18n](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n) API, plus the [pontoon-to-webext](https://github.com/bwinton/SnoozeTabs/blob/master/bin/pontoon-to-webext.js) transform script borrowed from the SnoozeTabs repo
* How do we test that we've gotten all the strings?
  * (Possible answer) Pontoon typically adds locales to a repo by committing changes to the master branch directly. We would then package up whatever languages were in the repo when we cut a release.
* How do we determine the locale?  How do we make sure it's the same from the server and add-on's perspective?
  * The WebExtension `i18n` API auto-detects the user's locale. Unfortunately, it uses the UI language (language of Firefox), not the content language (language configured by user in Preferences for viewing websites).
  * On the server, we can try using [fluent-langneg](https://github.com/projectfluent/fluent.js/tree/master/fluent-langneg), an isomorphic language negotiation library, to get either the Accept-Languages header or the value of `navigator.languages`.
* How do we ship strings to Pontoon?
  * See [the MDN page](https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website)

**Comment by pdehaan** [comment]
Ref: #865

**Comment by wresuolc** [comment]
MattN is having this same discussion with the L10n team for their system add-on and he said he'd have it on the Go Faster list so we could follow along.

He's using Pocket as a model which uses .properties files on github (https://github.com/mozilla-l10n/pocket-l10n ) localized by Pontoon.

**Comment by 6a68** [comment]
Looks like this one is still up for grabs, so I'll take it

**Comment by 6a68** [comment]
Here are some official Mozilla l10n process links:

https://wiki.mozilla.org/L10n:NewProjects
https://developer.mozilla.org/en-US/docs/Mozilla/Implementing_Pontoon_in_a_Mozilla_website

**Comment by ianb** [comment]
Seems like we should loop in l10n people on this soon.  @ckprice ?

**Comment by 6a68** [comment]
@ianb Yup, the l10n wiki page I linked above suggests opening a bugzilla bug for l10n planning. I can open that bug.

**Comment by 6a68** [comment]
I"ll also ping MattN to see what's happening

**Comment by 6a68** [comment]
To mention when contacting the l10n folks: UX is currently working on specs which include a new onboarding flow. This will introduce new strings. Not clear when that spec will be ready.

**Comment by ianb** [comment]
I notice that there's some WebExtension i18n support: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/i18n

**Comment by 6a68** [comment]
Pinged #l10n to ask about some stuff, and @flodolo mentioned that the i18n WebExtension library has some shortcomings, both with the localization aspect (plural forms are not supported), as well as technical aspects (the JSON format is incompatible with Pontoon, requiring an additional build step).

Given the react vs l20n.js issues we've seen with test pilot (two libraries racing to modify the DOM), fluent-react seems like the nicest library available: https://www.npmjs.com/package/fluent-react

**Comment by flodolo** [comment]
CC @stasm

**Comment by 6a68** [comment]
I've updated this bug's description with a draft plan, and started a discussion thread on the go-faster list (also CC'd the pageshot-staff list): https://mail.mozilla.org/pipermail/gofaster/2017-March/000626.html

**Comment by stasm** [comment]
> What library do we use on the server? — (Possible solution) The fluent-react library
> What library do we use in the add-on? — (Possible solution) The fluent.js library

fluent.js is a monorepo with a number of packages in it.  The [fluent](https://www.npmjs.com/package/fluent) package is very low-level. For instance, it powers the [fluent-react](https://www.npmjs.com/package/fluent-react) package. As a standalone solution, `fluent` might be a bit too bare-bones. What is the addon's UI written in? Is it React? Also, what do you mean by "on the server"?

**Comment by 6a68** [comment]
@stasm The addon UI is built using innerHTML and DOM APIs, so a low-level tool should be fine, or we can try l20n.js or whatever other tool you'd suggest. [This gist](https://gist.github.com/6a68/e7a84d03aa634c40d5396930fbe9878d) lists all the strings in the addon, along with the files where they are found; the paths are relative to the top-level webextension folder.

**Comment by 6a68** [comment]
As an update, I wound up using the WebExtension i18n library in the add-on. See #2294 for details and links to PRs.

**Comment by 6a68** [comment]
I think we have the addon part of localization completely planned out at this point, so I'm going to remove the 'beta blocker' label and tweak the title.

**Comment by 6a68** [comment]
Hmm. Actually, we have a plan for server localization, too. So, I'm going to go ahead and close this.
