### ISSUE TITLE
Weird SVG+CSS security error when trying to take shot

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#2215]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23284705/cab620ea-f9e1-11e6-81c5-13d6fa7334fc.png)

Trying to take a snap of Test Pilot site, and randomly saw this in a Browser Console:

![browser_console](https://cloud.githubusercontent.com/assets/557895/23284722/e2da1de8-f9e1-11e6-9a31-742398dae717.png)

Specifically:

> Security Error: Content at https://pageshot.net/static/img/glyph-history-16.svg attempted to load https://pageshot.net/static/img/stylesheet.css, but may not load external data when being used as an image.

**Comment by fzzzy** [comment]
This is the offending line:

    <?xml-stylesheet type="text/css" href="stylesheet.css" ?>

Since there is no file named stylesheet.css in that directory, I think it is probably safe to remove that line.

**Comment by johngruen** [comment]
@pdehaan i think this is Test Pilot's aggressive CSP
