### ISSUE TITLE
TypeError while trying to take a shot of the about:addons page

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#2217]
![add-ons_manager](https://cloud.githubusercontent.com/assets/557895/23285089/f3400ab0-f9e3-11e6-844e-1bbbc443f066.png)

### Steps to reproduce:
1. Go to "about:addons", 
1. Open your Browser Console, 
1. Try and take a shot of the page (so you can grab the version info).

### Actual results:

> mozilla-pageshot:Object { _errorType: "TypeError", message: "document.body is undefined", fileName: "resource://gre/modules/commonjs/too…", lineNumber: 750, stack: "\@\resource://gre/modules/commonjs/to…", name: "TypeError" }

![browser_console](https://cloud.githubusercontent.com/assets/557895/23285217/a0beaba6-f9e4-11e6-9af1-3e167bf1a156.png)

**Comment by pdehaan** [comment]
Possibly dupe of #2141.
Not sure if we should block capturing of `about:*` pages, or do better checks for `document.body` since it can seemingly be `undefined` in some cases.

**Comment by ianb** [comment]
This relates to #2236 (which is to test these pages generally)

**Comment by ianb** [comment]
This is with the old add-on, the error looks different with the WebExtension add-on.  We're tracking the WebExtension issue with about pages/etc in #2236
