### ISSUE TITLE
Design Embedded WebExtension

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2222]
For the purposes of Telemetry (#2218) we're going to need to be an [Embedded WebExtension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions#Starting_the_WebExtension).  The wrapper will be a bootstrap extension (not SDK).

I'd like to keep developing as a WebExtension, which means my development won't emit Telemetry, which is OK.  Then we'd build as a bootstrap add-on, and do testing and integration stuff with the bootstrap add-on.

This probably informs our migration path (#2169), as we'll have more options with the bootstrap extension.  The WebExtension should always be able to run without the wrapper, as this is how it will run on Chrome (assuming we eventually are usable on Chrome), and because it's easier to develop that way.

**Comment by ianb** [comment]
Note that assuming we have a pref to turn off PageShot, it will probably suppress the `webExtension.startup()` call, which means almost all of the code will be suppressed, and I think we can really call that "disabling" Page Shot.

**Comment by 6a68** [comment]
As part of the migration, the outer bootstrapped addon's ID should be changed to something @mozilla.org (per IRC convo with Ian)
