### ISSUE TITLE
Reimplement error message when shooting Page Shot pages

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2237]
Page Shot should give an error of some sort when you try to capture a Page Shot page.  *Or* we could disable the button on those pages (perhaps the better answer, if it's not too hard).

**Comment by ianb** [comment]
Note that the location of the service is in `webextension/background/main.js` in `main.getBackend()` – if the button (`browserAction`) can be disabled anytime the active tab is on that domain then that would be great, if that's not possible then you can also just pop up an error message if someone attempts to start Page Shot on one of those pages.

**Comment by dannycoates** [comment]
This was done it #2368
