### ISSUE TITLE
Reimplement about:newtab -> My Shots

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2238]
When you hit the Page Shot button on a new tab page you should be redirected to My Shots.

There might have to be changes to the add-on permission to run on about pages (if so, those changes go in `addon/webextension/manifest.json.template`).

The location of My Shots is in `addon/webextension/background/main.js` in the `main.getBackend()` function, `+ '/shots'`, and it should change the URL of the current (about:blank) tab.

**Comment by niharikak101** [comment]
Working on this, if that's okay!
