### ISSUE TITLE
Put in default Sentry DSN

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2240]
We get the Sentry DSN from the server, but that doesn't let us catch early errors.  We should have a default DSN hardcoded into the add-on, but what DSN depends on whether it is dev, stage, live.  As a result we need to configure it somehow (probably something like write it to `webextension/build/defaultDsn.js`)

**Comment by fzzzy** [comment]
At build time, if the dsn is configured, it should just get written into that file.
