### ISSUE TITLE
"My Shots" button no longer redirects you to the saved shots page 

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2246]
[Affected versions]:
- Nightly 54.0a1 (Build ID: 20170228030203)	
- Page Shot 5.2.3638

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.3638) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from browser toolbar.
3. Click the "My Shots" button from the top right corner of the page.
4. Observe the browser behavior.

[Expected result]:
- The "My Shots" page is opened in a new tab.

[Actual result]:
- The Page Shot overlay is dismissed but the "My Shots" page is not opened.

[Notes:]
- Here is a screen recording with the issue:

![my shots](https://cloud.githubusercontent.com/assets/19226534/23471257/620d2cbc-feb1-11e6-8be7-f02992b97fb1.gif)

**Comment by fzzzy** [comment]
To clarify, only the my shots button on the take a shot ui (on the right hand side) is broken, as shown in the gif. The "My Shots" button on a shot page (on the left hand side) works fine.

**Comment by SoftVision-CosminMuntean** [comment]
I have retested this issue using the latest Page Shot (v. 5.2.10595) custom build and is no longer reproducible. After clicking the "My Shots" button, the "My Shots" page is correctly opened in a new tab.

However, I have observed a strange behavior after installing the add-on on a new Firefox profile:

1. Install the latest Page Shot add-on on a new Firefox profile.
2. Navigate to any website and click the Page Shot button from browser toolbar.
3. Click the "My Shots" button from the top right corner of the page.
4. Observe the browser behavior.

[Expected Results]:
- The "My Shots" page is opened in a new tab.

[Actual Results]:
- The "Install Page Shot" page is wrongly opened in a new tab, even if you have Page Shot already installed.

[Notes]:
- After a selection is saved the issue is no longer reproducible and you are correctly redirected to the "My Shots" page.
- @ian, @fzzzy, this behavior is related to #2274? Or should I log a new issue for this?
- Here is a screen recording with the issue: https://goo.gl/OGIRTp.
