### ISSUE TITLE
Determine Telemetry probes

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2247]
We need to determine what probes we want to send to Telemetry, so we can move the process forward.  These probes have to be part of Firefox itself.

**Comment by ianb** [comment]
See some ideas in #2218

**Comment by ckprice** [comment]
Just noting here that we will want to loop in Georg (as a reviewer) once we have an idea of the type of probes we need.

**Comment by wresuolc** [comment]
I think this can be removed from `beta blocker` and Page Shot in 54 milestone?

**Comment by ianb** [comment]
For KPI we wanted to have some basic Telemetry probes (but not event streams).

**Comment by ianb** [comment]
Closing in preference for #2218
