### ISSUE TITLE
Modify default shot expiry?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-services/pageshot#2253]
Currently if you take a shot, it expires in 14 days.
Should we default to "Indefinitely"? "1 Month"? Leave as 14 days?

https://pageshot.net/agv12yyFrQLwo0zE/xn--e77hd01i.ws
<http://🇨🇦🍕.ws>

**Comment by ianb** [comment]
We've had discussions with Legal, Operations, and Security, and they are all really happy about a default expiration.  It also let's us start out providing modest expectations, and let's people tell us if they don't like it.  So for now we are expecting to stay at 14 days.  Why 14 days?  Eh, seems fine?  We've also found that people have a certain amount of timespan when they retrieve things, and once something is older than that then they tend to forget entirely; that range is somewhere between 2 weeks and a month.
