### ISSUE TITLE
The "Copy" icon and the "Press Ctrl-V to paste." text are missing from the "Link Copied" system notification

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2255]
[Affected versions]:
- Nightly 54.0a1 (Build ID: 20170301030202)	
- Page Shot 5.2.4829

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.4289) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from browser toolbar.
3. Perform a selection and save it.
4. Observe the "Link Copied" system notification.

[Expected result]:
- The "Copy" icon and the "Press Ctrl-V to paste." text are correctly displayed.

[Actual result]:
- The "Copy" icon and the "Press Ctrl-V to paste." text are no longer displayed.

[Notes:]
- Here are two screen shots with the issue:
- Mac OS:
![mac os system notification](https://cloud.githubusercontent.com/assets/19226534/23507934/05fb4592-ff58-11e6-8aed-323b143c008d.png)

- Windows:
![windows page shot system notification](https://cloud.githubusercontent.com/assets/19226534/23507939/0af8c182-ff58-11e6-96a9-fb080cec8078.png)

**Comment by ianb** [comment]
For anyone looking at this, the popup is done in `webextension/background/takeshot.js`.  You have to detect the OS to get the paste instructions right (Mac gets ⌘-V, everyone else Ctrl-V).  The image exists somewhere, it may be specified incorrectly in the notification, and/or it might have to be moved into `webextension/icons/`

**Comment by niharikak101** [comment]
Can I work on this?
