### ISSUE TITLE
The text from "Expired Shot" pages is very small hardly visible

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2258]
[Notes]:
- It seems that the text from "Leave Page Shot" page is also affected.

[Affected versions]:
- Nightly 54.0a1 (Build ID: 20170228030203)	
- Page Shot 5.2.4829

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.4289) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from browser toolbar.
3. Perform a selection and save it.
4. Click the "expires in 14 days" button and changed the expire time to 10 minutes.
5. Wait 10 minutes or change the system date 10 minutes in the future.
6. Refresh the page and observe the text.

[Expected result]:
- The text from the "Expired Shot" pages is perfect visible.

[Actual result]:
- The text from the "Expired Shot" pages is very small and hardly visible.

[Addition Notes:]
- Here are the screen shots with the issue:
![untitled](https://cloud.githubusercontent.com/assets/19226534/23515256/4f10d58e-ff72-11e6-9cbb-7f3c5132e14b.png)
![leave page shot](https://cloud.githubusercontent.com/assets/19226534/23515259/508f6880-ff72-11e6-8d5b-add70b8bd573.png)

**Comment by ianb** [comment]
Note the page is rendered in `server/src/pages/shot/view.js` – this may be an issue with styles, or may be some lack of a proper div wrapping the text.

**Comment by niharikak101** [comment]
Working on this! :)

**Comment by niharikak101** [comment]
There seems to be an issue with the confirmation page as well: 
![confirmation page](https://cloud.githubusercontent.com/assets/16074636/23906442/e2b17292-08c5-11e7-9ef8-ca113b931d7f.png)
