### ISSUE TITLE
Migrate data from Test Pilot experiment

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/pageshot#2260]
If users had Page Shot installed as a Test Pilot experiment, there is some data saved as prefs.

The bootstrapped webextension wrapper should migrate over that data on install.

**Comment by ianb** [comment]
Acceptance/testing process:

1. Run `./bin/run-addon --setup-profile`
2. Confirm that Page Shot is not installed; if it is remove it.
3. Go to [testpilot](https://testpilot.firefox.com/), install the add-on, install Page Shot
4. Make at least one shot to ensure you have an account and can identify it
5. Quit the browser
6. Run `./bin/run-addon --bootstrap` to run with bootstrap.js and migration in place.
7. Ensure the new icon is in place (smaller and dimmer), the old icon is gone, and if you go to My Shots you see the shot you made previously.
8. If you run `./bin/run-addon --setup-profile` you should now see the old Page Shot is gone, but if you reinstall you should still be able to access your old account.
