### ISSUE TITLE
Remove SSL configuration & instructions

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2262]
It turns out that running using https on localhost is no longer necessary (there used to be a different architecture where it was required, but that was changed).

To fix this we need to remove the setting from `.env.dev`, change any other references to `https://localhost:10080` to `http://localhost:10080` and change the README to remove references to SSL

**Comment by niharikak101** [comment]
Can I work on this?

**Comment by ianb** [comment]
Go for it!
