### ISSUE TITLE
Decide what Page Shot button should do when Page Shot is active

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2267]
Just because the implementation fell out that way, after #2244 is fixed clicking the Page Shot button a second time will just reset the interface.

Probably this isn't what we want to do, but we should decide what we do want to do.

**Comment by johngruen** [comment]
@ianb hitting the page shot button a second time doesn't seem to do anything right now

**Comment by ianb** [comment]
The fix hasn't landed yet, will be landed later today.

**Comment by johngruen** [comment]
so the fix just resets it?

**Comment by ianb** [comment]
Yes – before the fix you actually can get two or three overlapping interfaces all overlapping each other.

**Comment by johngruen** [comment]
@ianb Fix is to simply close out the Iframe.

**Comment by ianb** [comment]
Let's leave this open, and you can gaze on the beauty of the flashing interface once #2273 lands.

**Comment by johngruen** [comment]
sounds good

**Comment by ianb** [comment]
This is being implemented in #2389
