### ISSUE TITLE
implement l10n in addon

### ISSUE THREAD

**Issue by 6a68** [mozilla-services/pageshot#2294]
refs #2205

**Comment by ianb** [comment]
Another thing we have to localize is some of the strings in manifest.json.template

Some aren't very visible (e.g., the name and description of the add-on) but at least the browserAction title is a string to be translated.

**Comment by 6a68** [comment]
@stasm I've started extracting strings from the webextension, but I'm not really clear on how I can use fluent.js instead of the standard i18n system: where do I put the .ftl files? how do I load them? do you know of any example webextensions localized using tools other than the built-in i18n?

I'm inclined to just rely on the built-in i18n tools for the initial release, since that approach is clearly documented and will definitely work. However, I'm interested in your thoughts here.

We are planning to wrap the WebExtension in a bootstrapped addon--but I am not particularly interested in sending over strings via some kind of cross-process messaging approach.

**Comment by stasm** [comment]
> (…) but I'm not really clear on how I can use fluent.js instead of the standard i18n system: where do I put the .ftl files? how do I load them?

I have the same questions right now.  We'll want to have a higher-level abstraction on top of the current fluent package.  That's what I meant when I said that fluent was very low-level :) 

> I'm inclined to just rely on the built-in i18n tools for the initial release, since that approach is clearly documented and will definitely work. However, I'm interested in your thoughts here.

I think using the built-in i18n support is a good choice right now.  There's a lot of value in its being documented and stable. I'd like to double-check with @flodolo here. He mentioned a tool for converting between Pontoon and webext's JSON.

> We are planning to wrap the WebExtension in a bootstrapped addon.

Can you explain what this means?

**Comment by flodolo** [comment]
> He mentioned a tool for converting between Pontoon and webext's JSON.

Activity Stream uses this package
https://github.com/mozilla/pontoon-to-json

SnoozeTabs uses an internal conversion system that, IIRC, is based on the package above
https://github.com/bwinton/SnoozeTabs/blob/master/bin/pontoon-to-webext.js

They convert back from .properties to the native JSON format at build time, and use a familiar syntax for placeholders.

For example in SnoozeTabs:

```
confirmTimeTitle=This tab will snooze until {time_exp}.
```

becomes
```JSON
  "confirmTimeTitle": {
    "message": "This tab will snooze until $TIME_EXP$.",
    "placeholders": {
      "time_exp": {
        "content": "$1"
      }
    }
  },
```

And you can also solve the fallback issue in the build step, adding en-US strings if the localization is missing any.

**Comment by 6a68** [comment]
@flodolo Great! Thanks very much :+1:

**Comment by 6a68** [comment]
@stasm Thanks for your feedback as well. About your question: we are using an [embedded webextension](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) because we need the system addon to do a few things that webextensions can't currently do.

**Comment by 6a68** [comment]
It turns out the WebExtension i18n falls back to the `default_locale` in the manifest if a string isn't translated, so our build tool will not need to handle concatenating multiple locales together.
