### ISSUE TITLE
Limit shot size

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/pageshot#2302]
There should be an upper limit on the size of a shot sent to the service to prevent DoS. The PNG of a full 4K screenshot is smaller than 200kB, so 1MB would seem to be a reasonable upper bound.

**Comment by ianb** [comment]
See also #2229

Note we upload some JSON metadata plus the image is encoded as a data URL, so we get some overhead.  I've hit the 1mb limit in my own testing, though that might have included a DOM snapshot.

**Comment by jvehent** [comment]
Closing as dup of #2229.
