### ISSUE TITLE
"Copy the image to the clipboard" button from the Share pop-up is not working

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2303]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170306150342)	
- Page Shot 5.2.12100

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.12100) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click the Page Shot button from the browser toolbar.
3. Perform a selection on the page and save it.
4. Copy any text to clipboard (eg: "this text").
5. Click the "Share" button.
6. Click the "Copy the image to the clipboard" button from the top right corner of the "Share" pop-up.
7. Right click on a text area and from context menu choose the "Paste" option.
8. Observe the text area. 

[Expected result]:
- The saved shot link and the shot source are pasted in the text area.

[Actual result]:
- The copied text from step 4 is pasted instead of the saved shot link and the shot source.

[Addition Notes:]
- Here is the screen recording with the issue: https://goo.gl/8foD4l.
- Here is a screen shot with the browser console:
![errr](https://cloud.githubusercontent.com/assets/19226534/23656335/fd0ade0a-0341-11e7-9806-282aeab0dea8.png)

**Comment by ianb** [comment]
I think we should simply remove this button for launch.  It's not obvious how to recreate its functionality in a WebExtension.  I don't believe `document.execCommand("copy")` can create the kind of rich copied text we want (unless maybe we can make a selection across DOM elements then call copy).

**Comment by ianb** [comment]
We will remove it, tracking in #2322
