### ISSUE TITLE
Create script to copy Page Shot into Firefox

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2318]
We should have a script that will import the addon (everything in `addon/` after running `make addon`) into the Firefox tree.

**Comment by Standard8** [comment]
I have a WIP Makefile change that'll do an export. I have a bit more digging into #2319 to do before I decide if it is the right way to go or not.

In the meantime, here's a simple try push (just tests etc) to check for any adverse impacts:

https://treeherder.mozilla.org/#/jobs?repo=try&revision=4b6533ee47272f4c8712a081af342cdeef12ae1e

**Comment by Standard8** [comment]
The PR referenced provides an `make export_addon` command. This can be modified via EXPORT_MC_LOCATION environment variable to change where it is exported to.

There's a patch on [bug 1346825](https://bugzilla.mozilla.org/show_bug.cgi?id=1346825) that will provide the build system hook-up.
