### ISSUE TITLE
Support `extensions.%NAME%.disabled`

### ISSUE THREAD

**Issue by wresuolc** [mozilla-services/pageshot#2332]
%NAME% is simply whatever we decide to name this thing.  Right now it's "pageshot".

Over in #2304 I talk about reporting the status of `extensions.pageshot.disabled`.  This issue is to actually add and implement that preference.  This preference should be relatively straight-forward.  Check out my sweet pseudocode:

```
   # Somewhere in an init function:
   if extensions.pageshot.disabled == 1:
     return;
```

If `extensions.pageshot.disabled` is missing, we should enable as usual.  The point of this pref is to bail as early as possible if it's not enabled so we don't use up any resources loading libraries and what not.

**Comment by 6a68** [comment]
We have to manually start the webextension from inside the bootstrap.js startup function, so, if the pref is set, we will not start the webextension. I think that should do it.

**Comment by ianb** [comment]
I'm going to name this extensions.pageshot.systemDisabled to make it clearer how it is different than #2333

Though the prefs will be controlled differently, they will have exactly the same effect.  But some people will probably go into about:config and turn them both off just to be Extra Careful.

**Comment by wresuolc** [comment]
Sounds good.  For the record, once we're done rolling this out (a couple weeks?) we can just remove this pref and the code for it altogether.

**Comment by 6a68** [comment]
Grabbing a few of these prefs / initialization / disabling bugs
