### ISSUE TITLE
Bootstrap add-on may block e10s

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2338]
I notice when running `./bin/run-addon --bootstrap` that there is this message in the terminal:

    addons.xpi	DEBUG	Add-on pageshot@mozilla.org blocks e10s rollout.

This seems odd as we have `<em:multiprocessCompatible>true</em:multiprocessCompatible>` in install.rdf

**Comment by 6a68** [comment]
I can look into this

**Comment by 6a68** [comment]
I wouldn't worry too much about this. The error message is emitted [here](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#4512), but a [few lines up](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/internal/XPIProvider.jsm#4500) in the same file, we see that system addons are exempt from this limitation.
