### ISSUE TITLE
Sharing full URLs with query string parameters risk exposing private pages

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/pageshot#2342]
Pageshot currently shares the full URL a shot from taken from in the shot page. This full URL may contain secrets in query string parameters that would allow viewers of a shot to access the original page.

The full URL of the page a shot was taken should be removed from the shot page.

**Comment by johngruen** [comment]
This seems totally reasonable to me

**Comment by ianb** [comment]
Note that stripping query strings from a URL will often lead to a 404 or to an entirely different page.

**Comment by jvehent** [comment]
Can we remove the URL entirely?

**Comment by johngruen** [comment]
Let's compromise here: original URL (even just domain) seems broadly helpful to me.

Query params seems outside the bounds of good taste since users have no idea about the possible threats there. I realize that this will introduce breaking conditions in some cases (@ianb brought p wordpress links) but right now there's not much to suggest people are using this feature (175 clicks in the last two months)

**Comment by jvehent** [comment]
I'm fine with only stripping query string parameters, but as noted by @wresuolc, we still have the risk of credentials appearing in URL paths. That's less common than query strings, but it does exist.

**Comment by johngruen** [comment]
@jvehent can you provide an in-the-wild example of a site where this happens?

**Comment by jvehent** [comment]
I cannot. It's bad practice and most decent sites know better, but I'm sure given a large enough corpus we would find a small percentage of those.

In a way, Google docs are such an example because the random document ID is stored in the URL path, not the query string. Effectively, pageshot will "leak" gdoc URLs via shots.

**Comment by g-k** [comment]
We should strip HTTP basic auth username and password too e.g. from https://Aladdin:OpenSesame@www.example.com/index.html if we don't already.

**Comment by johngruen** [comment]
I'm inclined to go for a more security friendly approach for launch: lets do domain only.

We can re-introduce deeper linking after launch when we have more time to reason about the utility/discoverability of the feature

**Comment by ianb** [comment]
We could preserve the URL but only show it to the owner, though we're not hiding information from non-owners currently so the engineering is non-trivial.  As a result it would probably have to be a post-54 feature.

**Comment by johngruen** [comment]
@ianb sounds like the easiest thing for launch would be to hide the source URL for non-owners? All that stuff is rendered on the server right?

**Comment by ianb** [comment]
No, we send a bunch of information through, so we'd have to be more careful than just hiding the URL in the view.  Keeping the URL but hiding it from everyone would be more feasible, and later we could do the work to show it to owners.  Presumably we would keep the origin in a separate key – we don't do that currently, but it would be easy to add.

**Comment by johngruen** [comment]
Okay, yeah, we should just pass the domain through then.

**Comment by pdehaan** [comment]
FWIW, here's a Cloudapp link: https://cl.ly/1E1c1y3Q023J
There doesn't seem to be any source URLs or anything of real use. Just the image's filename.

<img width="1440" alt="screen_recording_2016-10-17_at_03_24_pm_gif" src="https://cloud.githubusercontent.com/assets/557895/23814212/616cb1aa-0597-11e7-8165-7c23ab91f7e8.png">

**Comment by ianb** [comment]
I put an implementation plan in #2376
