### ISSUE TITLE
"Error: Component returned failure code: 0x80520012" error appears after clicking the Page Shot button

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2345]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170309030216)	
- Page Shot 5.2.1906

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.1906) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click on the "Page Shot" button from the main toolbar.
3. Observe the browser behavior.

[Expected result]:
- The Page Shot overlay covers the entire page.

[Actual result]:
- A "Error: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [mozIJSSubScriptLoader.loadSubScriptWithOptions]" error is displayed.

[Notes:]
- Page Shot functionality correctly works even if the error is displayed.
- Here is a screen shot with browser console errors:
![page shot button error](https://cloud.githubusercontent.com/assets/19226534/23794889/531ee452-059b-11e7-8efd-886ab47127ea.png)

- Here is the screen recording with the issue:
![erorr after clicking the page shot button](https://cloud.githubusercontent.com/assets/19226534/23794893/57c5b238-059b-11e7-90f4-d694dede7332.gif)

**Comment by Standard8** [comment]
I've just found this myself, I'm coming up with a fix for it.
