### ISSUE TITLE
Have CircleCI notify IRC

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2354]
It's helpful to see build status on IRC, as we do for Travis.

**Comment by Standard8** [comment]
Turned on. To do this/change it in future:

- Go to https://circleci.com and log in with github
- Allow them to access your github profile (as necessary)
- If you've not logged in before, you'll be presented with a list of projects to add to your dashboard. You probably should deselect everything except this repo.
- Then on your dashboard, select the cog icon next to the project.
- Under notifications, select 'chat notifications'

The IRC settings can be adjusted on that page.

**Comment by Standard8** [comment]
And I just confirmed, it seems to be working, yay!
