### ISSUE TITLE
Design recall panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#238]
We want a second panel that can be opened at any time, and shows recent shots.

Some features:

- Shows a list of most recent shots, at the bottom a link to the pageshot homepage where you can see all your shots
- Shows the page title, a "copy link" button for each item
- Maybe some icon (favicon)?  Some indication of the clip?  Unsure
- Clicking on a shot opens up a detail view of that shot, with a similar layout to the make-a-shot panel
- It should be possible to drag clips out of the panel and into an editor (like an email)

**Comment by brampitoyo** [comment]
![pageshot-recall-panel](https://cloud.githubusercontent.com/assets/51007/6934445/7116ebd2-d891-11e4-9d6e-f8daf05b814b.jpg)

The recall panel (a.k.a. collection/gallery/library button) was included in the advanced use case video, and can be seen above.


> It should be possible to drag clips out of the panel and into an editor (like an email)

This is a great idea. Can we copy the behaviour of dragging an image from a webpage to the desktop, only this time the image is located inside the PageShot doorhanger?

![selection-handle-animation](https://cloud.githubusercontent.com/assets/51007/6934504/7ffaa4d0-d892-11e4-813a-6c25e1d95a78.gif)

**Comment by ianb** [comment]
> This is a great idea. Can we copy the behaviour of dragging an image from a webpage to the desktop, only this time the image is located inside the PageShot doorhanger?

Not sure I understand – the animation you give seems to be about dragging from the page into the PageShot panel...?  We can't do that for the dumb reason that the panel hides the moment you click on the page to drag.

Do we want to use favicons instead of something based on the clip?

Another possible option is that when you click on a shot we could expand the shot, showing maybe some thumbails of clips or the original link or comments.  That would make it easier to scan through these looking for just the right thing.  I'm talking myself out of the idea – how often will you need to scan for details that aren't in the main listing? – but I'll leave this here.

I assume we want to keep the detail view of a shot as similar to the shot panel as possible.  Of course, as in your mockup, we will want the original link, which during recall is no longer viewable in the URL bar.  I also see a title: should we also have that in the panel?  Do we want to encourage editing the title?  We've talked about that in the past, using the title of the shot similarly to how people use the subject of an email.

**Comment by brampitoyo** [comment]
Let’s talk about this in our Tuesday meeting. I think I can explain it better in person.

**Comment by ianb** [comment]
#379 is for styling.  I think any other changes can go in specific bugs as changes to the currently implemented UI.
