### ISSUE TITLE
Implement new panel design

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#239]
Many of the designs are documented in #185 

Features:
- Clicking on PageShot button opens the panel, does autoselect
- You can resize selection
- You cannot make a new selection until you enter the "Selection" mode
- Full screen clips are handled with another mode
- You can have multiple clips, in a carousel
- You can add items to the carousel, and determine how they are captured (auto/select/full)
- A comment field is attached to each clip
- A link and copy button appear
- Clips can be deleted
- When all clips are deleted, the shot is deleted

**Comment by fzzzy** [comment]
There are too many different features in this bug. I think this issue should be about the visual design refresh, and we need new issues for creating new selections, editing existing selections, and deleting them.
