### ISSUE TITLE
"Error: response fail" error appears after trying to save a shot

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla-services/pageshot#2391]
[Affected versions]:
- Nightly 55.0a1 (Build ID: 20170314030215)	
- Page Shot 5.2.3372

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" is set to "false" and latest Page Shot (5.2.3372) custom build is installed on a new clean profile.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites and navigate to any website.
2. Click on the "Page Shot" button from the main toolbar
3. Perform a selection on the website an save it.
4. Observe the browser behavior.

[Expected result]:
- The selection is successfully saved and you are redirected to the saved shot preview page.

[Actual result]:
- "Error: Error: response fail" error is displayed and you are redirected to the preview page but the shot is not saved.

[Notes:]
- Here is a screen shot with browser console errors:
![page shot error error](https://cloud.githubusercontent.com/assets/19226534/23941780/d946cbdc-0972-11e7-9681-67a0f3f803dc.png)

- Here is a screen recording with the issue:
![page shot error](https://cloud.githubusercontent.com/assets/19226534/23941790/e2cdbfa8-0972-11e7-9d8e-28af33887908.gif)

**Comment by ianb** [comment]
This might just be a problem with the pageshot.dev server, we should confirm that first before looking locally.

**Comment by 6a68** [comment]
I can reproduce on dev and stage, but not locally. @relud any idea what might be going on here? Looks like 400 errors, maybe the auth header name change from `x-pageshot-auth` to `x-screenshots-auth` requires some config update on your side?

**Comment by ianb** [comment]
The server has fallen behind.  `deviceId` removal in particular (from what I see in Sentry).  I should do another update of the server, but #2436 to land.

**Comment by ianb** [comment]
I updated the dev server and it's working again
