### ISSUE TITLE
Add install step to CircleCI

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#2401]
This commit adds something to .travis.yml: https://github.com/mozilla-services/pageshot/pull/2393/files#diff-354f30a63fb0907d4ad57269548329e3

```
install:
  - pip install --user virtualenv
```

I'm not sure... maybe this is handled implicitly by the makefile rules, but maybe we need to do the same thing in the CircleCI config?

**Comment by Standard8** [comment]
CircleCI already has virtualenv installed afaict, travis doesn't which is why it needed it.
