### ISSUE TITLE
Point nginx at static files

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#242]
Bonus points if we put cache-busting query strings into the references to the static files

**Comment by ianb** [comment]
[nginx expire example](http://nicholaskuechler.com/2011/04/24/nginx-how-to-set-expires-headers-for-images/)

**Comment by fzzzy** [comment]
Done. Added the following to /etc/nginx/sites-enabled/default

        location /js/ {
                root /home/ubuntu/pageshot/server/dist-production/;
        }

        location /css/ {
                root /home/ubuntu/pageshot/server/dist-production/;
        }

        location /img/ {
                root /home/ubuntu/pageshot/server/dist-production/;
        }
