### ISSUE TITLE
Design clip drawer on shot page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#243]
The place where the clips live above the page needs to be specified a big more.  It can hold images with a wide variety of resolutions and proportions, so it's a bit tricky.

**Comment by ianb** [comment]
Some stuff we do know:

- Images should display at their original resolution and aspect ratio
- Unless maybe they are too big?  In which case we might want to square off the images or otherwise truncate them
- We want images in `<img>` tags, not as background images, because users should be able to easily drag and copy them
- Clips should be separated out and flow reasonably

**Comment by brampitoyo** [comment]
![pageshot-clip-drawer](https://cloud.githubusercontent.com/assets/51007/6935576/0344b6e4-d8a4-11e4-80c9-d16dc22755c4.png)

While designing the clip drawer, I ran into a two problems that mainly has to do with the clips coexisting with the full page. I think it’ll be solved with time, but I do want to let you know about it in case you could start thinking about it while I’m away.

1. Resizing clip
  * Each clip, an image, must point to a specific location within the full page, located down below.
  * To edit a clip, you must first go into the full page area, then hit the *select* button. Down below, this clip isn’t an image anymore, but a DOM with an area surrounding it that can be resized.
  * As the area gets resized, the clip up above on the drawer must also change to match.
  * Representing a clip as both an image, and the *shortcut* to an area within the DOM, is tricky.

2. Adding comment
  * Each clip can have a comment. Comment is editable on the drawer area up above.
  * Each clip can be resized. To resize, user must go to the full page area down below.
  * Editing comment and resizing clip are done in two separate areas. Is this confusing?

**Comment by ianb** [comment]
This design doesn't make it clear to me where the text comes from, e.g., who wrote "it's literally across the street from Ridhika's new flat?"  As a viewer, when I click on the link I think it should be very clear to me what comes from the page and what comes from the person sharing this with me.  (The ragged edges of a OneShot image are in a sense an indication of where that image came from as well, in that case an excerpt from a larger page.)

I liked the design that was more like a message bubble, and would like to see that here as well.

**Comment by brampitoyo** [comment]
The message bubble returns in the latest round of mockups:
![pageshot-clip](https://cloud.githubusercontent.com/assets/51007/7110030/4f05a742-e1fe-11e4-9c57-c611f8c1b832.png)

Message bubble colour indicator:
* Gray: no comment exists – I considered replacing this with an ellipsis or a plus (not a good candidate, could be mistaken for adding a new clip)
* White: comment exists
* Blue: new comment exists

We could also replace the blue with something that resembles Facebook’s style. Maybe a red circle on the top right side of the message bubble?

![facebook-friends-indicator](https://cloud.githubusercontent.com/assets/51007/7110059/36c20800-e1ff-11e4-9175-6b84a87fe70e.png)

**Comment by ianb** [comment]
This design is now obsolete per other discussions.
