### ISSUE TITLE
Request flow

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#245]
Right now we have a problem where sometimes the initial document upload takes so long that a user can beat PageShot to clicking on the link.  Because of this I think we should upload a kind of filler document immediately.  This would probably be the information we can get from the SDK tab object directly, just url and title.  Then instead of a 404 page, if the user is fast they'll at least get a decent message about upload in progress or something.

We also would be separating out document creation (INSERT) from updating (UPDATE), and avoid the PG transaction silliness.

After the initial document creation we can expect all requests to be updates.  I can't imagine a good reason to do anything but an update, except for bugs.  So PUT seems at best like a dangerous vestigial method.

The delete flow we have isn't entirely authoritative.  That is, without any clips we will delete the shot, but I think it would be natural to think that once you put a clip back you retain the same URL and so on.  So instead of DELETE I think we should flag those pages for being deleted soon.  Maybe this just means a top-level `deleted` property (boolean and/or timestamp).  We'd want to completely purge deleted documents after some amount of time.  The addon however would still know when a page could be completely deleted, typically because the context is gone (e.g., you've deleted the last clip and closed the tab).  In that case I suppose it would issue a real DELETE.  This might be a reasonable way to do delete-with-undo later (once we have the notion of deleting a pageshot after you've fully created it).

**Comment by brampitoyo** [comment]
A good use case for this would be a user who clicked on the PageShot button and, instead of pasting the link elsewhere, clicks on it right away because she wants to see what the screenshot looks like and save it to view offline.

**Comment by ianb** [comment]
For authentication reasons we should also separate INSERT and UPDATE into two kinds of requests: anyone can create a new page, but only the user who created the shot can update a page.

**Comment by ianb** [comment]
Ugh, this all makes comments hard though – because we are attaching comments to the document directly, a third user might add a comment to another person's document.  Maybe we have to split out comments somehow.

**Comment by fzzzy** [comment]
I think that's a decent argument for splitting comments out into another table.

**Comment by ianb** [comment]
I don't think this ticket represents the plan anymore.
