### ISSUE TITLE
Serve XPI and .update.rdf with proper mimetype

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#251]
The pageshot.xpi and pageshot.update.rdf files need to be served up, and with the correct mimetype.  Also relates to #242

**Comment by fzzzy** [comment]
Done, served as https://pageshot.dev.mozaws.net/pageshot/pageshot.update.rdf and https://pageshot.dev.mozaws.net/pageshot/pageshot.xpi with the correct content types.

To do so, I added an include to the nginx.conf (include /etc/nginx/mime.types;) and made sure the corresponding xpi and rdf mime types were included.

**Comment by fzzzy** [comment]
I also added a location /pageshot/ section.
