### ISSUE TITLE
Investigate Hypothes.is

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#266]
[Hypothesis](https://hypothes.is/) is a web annotation project

**Comment by brampitoyo** [comment]
The notion of using annotation as a way to circumvent censorship from site publisher (“add a comment section where there is none!”) is interesting.

**Comment by ianb** [comment]
The site has a lot of nice little animations showing the interface, so I'll only pull out notes of things I found interesting:

1. Comments are Markdown, but they use a editor with controls (that I assume insert the markup)
2. Individual comments have tags with autocompletion.  Tags appear global. I can't actually see a list of just my annotations with a tag, though I'd probably just call that a bug.
3. They have CC copyright declarations on individual comments (I don't see a way to change the license, but it seems implied by one of the animations where the license is more restrictive)
4. Highlight only is also available
5. In addition to a bookmarklet and Chrome extension, they have a proxy so you can annotate any page on any browser.  This proxies a page adding their annotation Javascript.  You can see it [applied to their own site](https://via.hypothes.is/https://hypothes.is/)
6. Passwords must be a minimum of two characters. Accessibility over security ;)
7. Viewing a page with many highlights, I constantly want to be able to click somewhere to clear out the selection.  It bothers me irrationally.
8. An example of two overlapping highlights: ![screen shot 2015-05-05 at 9 29 55 am](https://cloud.githubusercontent.com/assets/44390/7474819/57069854-f309-11e4-8dfa-87b6aa87fc2f.png)
9. Everything is very global. Very much a global overlay on the web.
10. You can have notes applied to no specific location.  The UI is kind of unclear in this case.
11. The bookmarklet is fragile, as anything that might take you away from the page will unload hypothesis, and going back won't fix it without reenabling the bookmarklet.
12. When highlighting the comment widget is placed at mouseup, which if you select down means it is often obscuring something: ![screen shot 2015-05-05 at 9 41 49 am](https://cloud.githubusercontent.com/assets/44390/7475069/0b1206b6-f30b-11e4-866b-2e713eaec023.png)
13. The highlight icon (the icon on the right in the above picture) makes me think: we do text clips, but they aren't highlights.  This is an interesting distinction, even though they are really kind of the same.  I'm glad we're not doing highlighting, feels like weak sauce.

**Comment by brampitoyo** [comment]
I wonder what would happen if the content being highlighted or commented is deleted? Let’s say the site author removed the phrase “this idea”. Would Hypothes.is preserve a copy of the comment section, or would it simply update the page to the newest version (and if so, where does existing highlight/comment go?).

**Comment by brampitoyo** [comment]
Here’s something else that’s interesting. When I open Twitter via Hypothes.is’ web tool, I got a new start page that I never saw before when I open twitter.com normally:

https://via.hypothes.is/https://twitter.com/

**Comment by judell** [comment]
@brampitoyo When text changes we do our best to reanchor annotations. When it vanishes entirely we  can't. But we are looking into using archive.org (and perhaps others) as a fallback.

As for via.hypothes.is, it's a proxy so you should be seeing the login page, not so?

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1ZCzdKssS4XtgKzVCgL2_1HqQ2qK1ynhqIu8n54al2z4/edit)
