### ISSUE TITLE
Add feedback tool

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#29]
This could be as simple as an email address.

**Comment by ianb** [comment]
We have an email address registered, pageshot-feedback@mozilla.com, with [this web admin interface](https://groups.google.com/a/mozilla.com/forum/?hl=en#!aboutgroup/pageshot-feedback)

We still have to put it into the interface.

**Comment by brampitoyo** [comment]
Usually, feedback is collected via a link on the footer that’s written like “Click here to send us [Feedback]()”

I think we could ask for feedback right after the user create a few snaps. For instance, we can say something like “Are you happy or sad with this snap?” with an optional comment box, right in the doorhanger UI.

![pageshot-submit-feedback-doorhanger](https://cloud.githubusercontent.com/assets/51007/6772668/270ffec8-d168-11e4-8e0f-c6f960ef6b88.png)

A more conventional “Send us a snail mail” link could also appear as an item under the library icon, underneath all the listing.

**Comment by ianb** [comment]
Initial feedback will probably be from people more like peers, as the people seeing this tool will be other Mozillians and people in our networks.  For those people we'd want the link to always be there.

We can change the email link dynamically so it always includes the URL of the current shot in the body of the email.  (This is also transparent and easy to delete.)  I don't think we could do much with thumbs-up/down at this point.

**Comment by fzzzy** [comment]
Let's leave this issue open until we want to implement the final feedback design. For an always visible email address for early adopter feedback, I opened #373

**Comment by ianb** [comment]
We have the email link.  #570 will complete this work.
