### ISSUE TITLE
Make addon and server different nodemon tasks

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#290]

**Comment by fzzzy** [comment]
Whoops, I forgot we are not going to preprocess the addon any more. Never mind.

**Comment by ianb** [comment]
We're not going to bundle the panel?

**Comment by fzzzy** [comment]
If we don't bundle the panel, we get correct tracebacks. Wasn't that the point of not preprocessing it?

**Comment by ianb** [comment]
I haven't started debugging the panel yet, so it wasn't annoying me ;)

But if the scripts run in content (i.e., from a `<script>` tag) instead of in a worker or addon, the sourcemap may work?

**Comment by fzzzy** [comment]
Ok, it's worth at least checking out to see what the behavior is then.
