### ISSUE TITLE
Get gulp to only rebuild changed files

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#293]

**Comment by fzzzy** [comment]
https://github.com/gulpjs/gulp#incremental-builds

**Comment by ianb** [comment]
FWIW, I think if we are using nodemon, it is fine if everything is always built from scratch when we run `gulp`, and only in the case when nodemon catches something would we worry about a quicker rebuild.  So in-memory optimizations would work fine.

**Comment by fzzzy** [comment]
I tried gulp-cached and gulp-remember, but it doesn't help because the part that takes all the time is the browserify step -- which has to happen for every file no matter how many files changed.

**Comment by fzzzy** [comment]
This didn't work.
