### ISSUE TITLE
Create loading icon

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#301]
We should probably replace [this otherwise pretty attractive icon](https://github.com/mozilla-services/pageshot/blob/eb6f7dd27ba8f1cd413480b2315b1abffc689384/addon/data/icons/loading.png) that is used for a filler while some stuff is happening.

I think [APNG](http://caniuse.com/#feat=apng) (animated png) would be acceptable if we want an animated throbber.

**Comment by brampitoyo** [comment]
We should use the pageshot icon as the loading icon.
