### ISSUE TITLE
Improve panel clip rendering

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#307]
The clips in the panel have a couple problems:

- If the clip isn't the width of the panel, it shouldn't be sized up
- If the clip is taller than the space of the panel, it should be sized down
- Clips should have some shadow on them

**Comment by ianb** [comment]
One possibility for a tall clip is that we could leave it full-width, but use overflow: scroll.  Might be nice to look for realistic examples where you'd want to take odd-shaped clips (very small, very tall, very wide), imagine how you'd want those actual bits of information to render when in a constrained space.

**Comment by fzzzy** [comment]
I like that idea a lot.

**Comment by brampitoyo** [comment]
The resize logic here is interesting. I can see how a tall-but-narrow and short-but-wide image could be problematic.

I think my goal for the doorhanger preview is to preserve the clip’s aspect ratio to the best possible extent. For instance, if a clip is in the size of a very big square, it should be displayed to fit the doorhanger, but still at a square’s aspect ratio.

Of course, super thin clips break this.

There are a couple of behaviours we can employ to prevent this from happening:

* Have a minimum dimension. Let’s say it’s 40x40px.
  * If I clip something that’s 10x10px, for example, it’s going to be sized up to 40.

* Have a maximum height. Let’s say that it’s 320px.
  * If I clip something that’s super tall and narrow – for example, [a vertical ruler graphic](http://lhonings.home.xs4all.nl/images/rulers/HOscaleruler_mmbig.gif) – it’s going to get resized down until the width becomes 40px, and then the vertical dimension will be cut at 320px.
  * The clip should be vertically aligned to top.
  * At the point in which the image is cut, place a visual indicator (like a torn paper?).

![vertical-ruler](https://cloud.githubusercontent.com/assets/51007/7245971/56949954-e849-11e4-9ee4-6f40479434d0.jpg)

* The maximum width is restricted by the width of the doorhanger, minus padding. Let’s say that it’s 320px.
  * If I clip something that’s super long, like [a horizontal ruler graphic](http://www.lifesizer.com/wp-content/uploads/2012/04/Inches-and-CM-Ruler.png) – it’s going to get resized down until the height becomes 40px, and then the horizontal dimension will be cut at 320px.
  * The clip should be horizontally aligned to left (but we can also align it to center, if we like)
  * At the point in which the image is cut, place a visual indicator.

![horizontal-ruler](https://cloud.githubusercontent.com/assets/51007/7246012/03fd71c4-e84a-11e4-8ca5-3ffe227ace94.jpg)

What do you think?

**Comment by ianb** [comment]
This is no longer relevant to the product
