### ISSUE TITLE
Clip delete in panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#308]
Clips should be deletable in the panel.

@brampitoyo : If the last clip is deleted, what should the panel show?  Add a new clip dialog?  There should be some message about the shot being deleted.

**Comment by brampitoyo** [comment]
I like that idea. When the last clip is deleted, we can do either one of these things:

* Doorhanger closes. When it’s clicked, Pageshot invokes the selection tool that the user has selected bydefault, then let user make a selection. Unless the selection is “Auto”, then the doorhanger will open without prior selection needed.
* Doorhanger remains open and asks user to choose a selection method, like so:

![pageshot-new-selection-menu](https://cloud.githubusercontent.com/assets/51007/7246050/f685a61e-e84a-11e4-9451-be3bad216fe7.png)

And, yes, we should design a notification indicating that the shot is being deleted. I’ll add it to my to-do list.
