### ISSUE TITLE
Design for text clips in panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#310]
When there is a text clip in the panel:

- What should show in the Auto/Select/Visible toggle?  Should we change that toggle entirely?
- How should the text clip render?  We have the larger context, and the selection itself.  It could be bigger than what fits in the panel itself.
- Any styles we want: the text clip is just simple HTML, so any font sizes or colors or anything is stuff we have to set ourselves.  (Though I'm considering capturing some more of the features of the selection, like fonts and colors.)

**Comment by ianb** [comment]
We might want to leave the entire clip in there, even when it is large, and use overflow scroll, plus scrollIntoView to make the selection viewable

**Comment by brampitoyo** [comment]
> What should show in the Auto/Select/Visible toggle? Should we change that toggle entirely?

In the interest of consistency, I think we should keep this toggle intact. That way, our users can easily change selection type at any point.

So if I set my default selection to “Text”, when I click the PageShot button, it will change my cursor to a text selection cursor, then ask me to select something.

> How should the text clip render? We have the larger context, and the selection itself. It could be bigger than what fits in the panel itself.

**On the doorhanger**, we should show just the selection itself. Maybe not even the full selection. For example, we can restrict it to the first 140 characters of the quote – this is an arbitrary limit that we can tweak – followed by an ellipsis. This way, the doorhanger panel will never run out of vertical space. The way I’ve designed it looks like this:
![pageshot-text-selection-doorhanger](https://cloud.githubusercontent.com/assets/51007/7245743/d53bcc78-e844-11e4-881f-c2e452d8bc62.PNG)

**On the web interface**, user can simply click on the link that says “See in full page” and get the context. So we don’t need to show the larger context, right?

![pageshot-web-see-in-full-page](https://cloud.githubusercontent.com/assets/51007/7245758/5d1a862a-e845-11e4-9c38-f77d59fb016a.PNG)

> Any styles we want

See the doorhanger image for an idea of how it could look. My inspiration was reader mode: black Georgia typeface on white background, but with an italic font style.

**Comment by fzzzy** [comment]
I tried using an ellipsis, but with the current implementation it doesn't really work at all. Right now we use scrolling for long text clips and it works ok. If we want to switch to ellipsis it will require more thought and work.

**Comment by brampitoyo** [comment]
Could you provide a screenshot of the current implementation? We can also talk about this tomorrow.

**Comment by fzzzy** [comment]
![screen shot 2015-04-30 at 9 26 10 am](https://cloud.githubusercontent.com/assets/46048/7413586/06b733b4-ef1b-11e4-8651-bddadf4b048f.png)

The Mac scrollbars disappear when you aren't scrolling now, but when you scroll, there's a scroll bar on the right side.

When I try to use ellipsis, it usually just doesn't work at all because the text contents are too complicated and include a bit of html markup sometimes. If I select only pure text, the ellipsis works ok, but most text has bullets or other html stuff in it, causing the ellipsis to just not work at all.

**Comment by ianb** [comment]
No longer present
