### ISSUE TITLE
Improve styling of new-clip screen in panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#312]
This is what it looks like:
![screen shot 2015-04-20 at 1 40 11 pm](https://cloud.githubusercontent.com/assets/44390/7237692/cb3cfae0-e762-11e4-98ba-f05bc0dff47c.png)

I think mostly it needs to fill the screen, and maybe include the link as well.  I think we should leave some room to include text clip instructions (just a line of text worth of instruction)

**Comment by ianb** [comment]
I'm not sure if we have any particular styles we want to add to our buttons.  Australis-like?

**Comment by brampitoyo** [comment]
Here’s what my mockup looks like:
![pageshot-new-selection-menu](https://cloud.githubusercontent.com/assets/51007/7245652/f9382ec0-e842-11e4-8f8d-8e5c797adf03.png)

It’s got a text that says “I want to select”, followed by four options:
* Auto-detect
* Image selection
* Text selection
* Everything visible on the screen

It ends with a link to Cancel, which is separated with a space.

I followed the style found on about:preferences and our “hamburger” menu, like these ones:
![about-preferences-button](https://cloud.githubusercontent.com/assets/51007/7245671/7274a8ae-e843-11e4-97c7-8053ca357e30.png)
![hamburger-menu-cut-copy-paste](https://cloud.githubusercontent.com/assets/51007/7245677/a2dd946a-e843-11e4-91cc-85d0314948b0.png)
