### ISSUE TITLE
Images in text selections can be weird sizes

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#316]
Text selection can capture images, but doesn't necessarily capture the height/width of those images from what I can tell.  [This page](https://www.eff.org/deeplinks/2015/04/justice-charging-eight-grader-felony-hacking) in particular seems to sometimes introduce weird giant asterisks.

**Comment by brampitoyo** [comment]
The ability for the text selection tool to capture image isn’t something I’ve considered before.

When a text is clipped using text selection, it’s saved as DOM text. But when an image is clipped, what happens to the image size and formatting? Does the image get resaved and resized, or do we simply copy the image resource URI into Pageshot?

This feature sounds like it’ll introduce quite a bit of potential brokenness and edge cases.

**Comment by ianb** [comment]
Right now we copy the tag, but point to the original picture.  We'll want to think about these resources eventually, but right now that's what we're doing for CSS and everything else too.

No styles are copied currently, but this ticket is about copying at least some.
