### ISSUE TITLE
Separate comments into another document or API

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#363]
Comments aren't like the rest of the shot document – they are owned by individuals and added to by those individuals, where the main shot is owned only by the shot maker and editable only by that person.

I'm guessing we want a separate table for comments, and those comments will be attached to a particular shot.  (Individual comments will also point to a clip, but that's mostly for resolution on the client, we probably don't need to query comments by anything but shot.)

Maybe we want to keep the read access for comments the same, I'm not sure – but adding comments would need a new server API.

**Comment by fzzzy** [comment]
I don't think we should keep read access the same. We should split it out to a different api.

**Comment by ianb** [comment]
Probably comments should just be a feed then, looking like:

```
[
  {
    id: uuid,
    author: userid,
    created: timestamp,
    clipId: id or null,
    comment: {text: "the comment"} // more stuff can go here in the future
  }
...]
```

When we get a page, we can even just return `{shot: shotObject, comments: commentFeed}`

We'd instantiate Shot with the comment feed as an attribute, but it wouldn't be part of asJson().

On the server, we'd add a comment with something like:

`POST /{id}/{domain}/comments` (or `/comments/{id}/{domain}` ?) with a body of the single comment object.

The comment table would include at least id, author, created, and comment – I guess it could include clipId, but I don't think we'd ever query on it.  We could also put clipId into the comment property.

I think it would be good to do #361 first or along with this change.

**Comment by ianb** [comment]
We no longer have comments
