### ISSUE TITLE
Design way for a shot to be a Hello room/conversation

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#365]
This is the user flow I can imagine:

1. Alice makes a shot and IMs the link to Bob
2. Bob opens the link
3. Bob clicks the "start a conversation" button (the Hello icon, with some name) and gives permission to use his camera
4. Alice will get a notification that Bob would like to start a conversation
5. Alice can join the conversation from the shot page, or by clicking on the notification the shot page will be opened if necessary, and the conversation confirmation will appear

Maybe Alice has to specifically opt in to getting conversation requests from PageShot.  Or maybe not –maybe she only gets to opt out of such notifications.

Alice is using Firefox (that's how she uses PageShot), so she has Hello installed in her browser.  The conversation, though launched by PageShot, is a normal Hello room.

Bob is using Chrome.  PageShot includes the cross-browser Hello code so that a conversation can be embedded on the PageShot page (instead of launching in a separate tab).

Bob can receive notifications, but only if the shot page is open, and if he has opted in to notifications.

/cc @sevaan

**Comment by sevaan** [comment]
Since Alice is the one sending the Page Shot (PS) link, chances are she is sending it because she wants to show Bob something, so we should give her the option to create a conversation (as well as Bob, the receiver). Maybe we can have a Hello button next to the Copy Link button in the PS panel. Instead of sending the link to the image, Alice can, with one click, send a link to a Hello conversation that has the image attached.

We are in the midst of implement the addition of context to a conversation, where users can talk about a webpage...we can just add the option to talk about a certain portion of a page (PS). The image would be displayed as context in the room that someone can look at before joining the conversation.

**Comment by brampitoyo** [comment]
Here’s a mockup of how a visitor who aren’t registered with PageShot or have Hello might be able to call the page author while viewing the snapshot of a page.

https://www.dropbox.com/s/fbbzyhy7xc8osi1/pageshot-hello-call-within-a-shot-video.mov

**Comment by brampitoyo** [comment]
> Instead of sending the link to the image, Alice can, with one click, send a link to a Hello conversation that has the image attached.

This is a smart idea. So the flow goes like this:
1. Alice makes a shot and IMs the Hello link to Bob
2. Bob opens the link
3. Hello opens with both Bob and Alice on the line

But we can think a step further. Can we make Alice and Bob chat in PageShot? After all, it’s possible to have a “Call Bob” or “Call Alice” button and manually click it. So can we simply make it automatic? It has to be opt in, of course. Some won’t want every PageShot page to instantly turn into a video/audio chat room.

So then the flow goes like this:
1. Alice makes a shot and IMs a special PageShot link to Bob. Maybe the URL is suffixed with ``/chat`` or something, and this will tell PageShot to turn audio/video chat on automatically
2. Bob opens the link
3. As long as Alice is viewing the same PageShot link, Bob will automatically be video/audio chatting with Alice

**Comment by sevaan** [comment]
I'm hesitant to make anything automatic without users explicitly saying "Yes, join this conversation". When cameras and audio come on, we always need to defer to user privacy.

But the flow could still work though. We just need a button that says "Chat about this Page Shot" which lets users start a conversation automatically from the page with that Page Shot as the context...then they can invite whomever they want or send out a link from the Hello interface.
