### ISSUE TITLE
Design way to include shots into Hello conversations

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#366]
This is a complement to #365 

1. Alice and Bob start a Hello conversation
2. Alice wants to share something specific with Bob.  She makes a shot of the page she wants to share, highlighting something important she wants to show to Bob
3. PageShot recognizes that there is a Hello room open, and offers to add the shot to that room.  This is equivalent to taking the PageShot URL and pasting it into the conversation.
4. The conversation contains the PageShot link, but also selected information from PageShot.  This includes the clips that Alice selected, and any comments she might have added with those clips (displaying in the conversation as images and captions).
5. As Alice adds items, or anyone adds comments, the Hello conversation live-updates to include those items.

Technically this could probably be done with [oEmbed](http://www.oembed.com/) (see #176); Hello would look at pasted links, and check if they have oEmbed information.  If they do, then the embedded form would be included.  PageShot would provide oEmbed information, and we'd ensure it worked well with Hello.  Using the same technique a YouTube link would turn into an inlined video.  But we could also do some more custom integration, if we want to include a live feed of updates into a conversation in a way that is richer than what oEmbed might allow (I haven't looked closely at what all is allowed in oEmbed)

/cc @sevaan

**Comment by sevaan** [comment]
A chat interface is being added to Hello (spec-in-progress: https://docs.google.com/a/mozilla.com/document/d/1HwYbM4Eru3rHVT3MStO8eeTunJ7pN5PYBingtmwe-bA/edit?usp=sharing) that would be suited to the sharing of Page Shots within Hello.

**Comment by brampitoyo** [comment]
Here’s how the Hello chat interface might look if a PageShot link with multiple clips is pasted into it.

![hello-chat-with-pageshot-link](https://cloud.githubusercontent.com/assets/51007/7450035/39c9793e-f294-11e4-97c1-13d4d0812b97.png)

A PageShot link is rather special in that it could contain multiple clips, each of which may or may not contain one or multiple comments.

To show a full comment thread on a chat window sounds unwise (and not to mention meta, as we’re embedding a chat within a chat). Showing every clip sounds like a better idea, although it could steal a lot of vertical space in a chat window.

So we have a couple of options here, from the most minimal to the least.

1. Show only 1 screenshot of a visible area of the page; ignore all other clips, even if they exist
  * Show that, plus first comment of the first clip
2. Show only the clip that the user currently get the PageShot link from; if you click the Copy Link button on the third clip, the chat window will only show you that clip, not the first or the second
  * Show that, plus first comment on that clip
3. Show first x number of clips; let’s say 3, but we can be less conservative and have a higher limit
  * Show that, plus first comment of each clip
4. Show every clip
  * Show that, plus first comment of each clip

**Comment by sevaan** [comment]
The chat shouldn't be a spot to review and read everything, but rather a driver to get people to visit the actions logged within the chat in their own context; here taking users to the Page Shot.

I like the idea of just having 1 screenshot, maybe with an indicator saying (+3 more) or something, and the first comment (+2 more). Then a user can click through to Page Shot to see all the information in a much more readable state.
