### ISSUE TITLE
Recall panel needs styling

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#379]
It's in there, but it ain't pretty

![screen shot 2015-05-06 at 10 27 36 am](https://cloud.githubusercontent.com/assets/44390/7496585/878c73fa-f3da-11e4-9454-c1597683e236.png)

We can't reasonably do the Australis-style of a panel overlaying a panel, instead we need some back button.  I've replaced the header with one, just as a temporary solution:

![screen shot 2015-05-06 at 10 28 53 am](https://cloud.githubusercontent.com/assets/44390/7496605/b40deea4-f3da-11e4-9740-741557e77aac.png)

Of course we can't add clips or change their type, so that header doesn't make sense.  Otherwise the styling is mostly the same as for the normal panel.

**Comment by brampitoyo** [comment]
Reference design for the recall panel’s list/history view. Note the new link button.

![pageshot-recall-panel-list](https://cloud.githubusercontent.com/assets/51007/7532339/c8de4df2-f5b9-11e4-9c79-c7613a8dddbb.PNG)

Reference design for the individual item view. Note the new back button.

![pageshot-recall-panel-item](https://cloud.githubusercontent.com/assets/51007/7532338/c89f848c-f5b9-11e4-97c4-270e146a487c.PNG)

See #189 for the blue back arrow asset.
