### ISSUE TITLE
Make popup notification when you make a shot that the URL has been copied

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#398]

**Comment by ianb** [comment]
I think this is moot with the new panel splash screen?

**Comment by brampitoyo** [comment]
Yes. Our splash screen moots this issue.

If user chose to bypass the splash screen and go straight to the edit interface, he will already know that the URL has been copied.

**Comment by brampitoyo** [comment]
In addition to the splash interface, when the OS allow it, we will give OS-native notification (issue #443).
