### ISSUE TITLE
Put in share buttons in panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#399]
Next to the link, we should have some share buttons.  In addition to making it clear that you want to share, it makes it clear that the link is intended for sharing.

Proposed first list:

- Facebook
- Twitter
- Pinterest
- Email

Then the link (which you click to open), and then the copy button.

**Comment by ianb** [comment]
Docs:

- [Facebook](https://developers.facebook.com/docs/plugins/share-button): inline JS, not a good solution
- [Twitter](https://dev.twitter.com/web/tweet-button/web-intent): just a link with query string parameters, very easy
- [Pinterest](https://developers.pinterest.com/pin_it/): inline JS, maybe with useful added value, not sure

But much simpler, this site shows you how to make a share links for these: http://www.sharelinkgenerator.com/ – these are all the naive open-a-popup style shares.

**Comment by brampitoyo** [comment]
The share buttons can be seen on at least two places inside the Shot panel:

1. Welcome UI ![pageshot-shot-panel-welcome](https://cloud.githubusercontent.com/assets/51007/7647570/673abe74-fb2b-11e4-8768-d4b8e94b87ab.png)
2. Edit UI ![pageshot-shot-panel-edit](https://cloud.githubusercontent.com/assets/51007/7648330/df02b312-fb35-11e4-800e-0e52c6181006.png)

Naturally, we should also add the share button inside the library panel, when you view individual shots.
