### ISSUE TITLE
Add a way to set name/avatar through panel and site

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#403]
The panel should have a name field above the comment field.  This will trigger a server-side update of the user's display name.

Shot pages should have a menu on the top-left that allows you to set your display name and avatar.  (This would only appear if you have a cookie set by the addon – non-addon-using viewers cannot log in until we have FxA support)

**Comment by brampitoyo** [comment]
> The panel should have a name field above the comment field

Stay tuned for the design of this. There are a few layout variations that I’ve thought of.

> Shot pages should have a menu on the top-left

I’ll have to remind myself to upload the graphic assets for the people/identity panel, too. The icon will come in various sizes.

**Comment by brampitoyo** [comment]
[Video: adding name in the Shot panel](https://www.dropbox.com/s/q0jdhedhoa1hg78/pageshot-add-name-in-shot-panel-video.mov)

[Video: adding name in the web interface](https://www.dropbox.com/s/0jqsoi07vw0z9uo/pageshot-add-name-in-web-video.mov)

**Comment by brampitoyo** [comment]
Assets for the people/identity menu has been uploaded to issue #189.

**Comment by ianb** [comment]
We plan to use the Firefox Account display name and avatar when it becomes available.  For now we're punting on the anonymous use case (though eventually we want to support setting display name and avatar even without login).

**Comment by ianb** [comment]
Relates to the user accounts that we don't expose
