### ISSUE TITLE
Design welcome interface on shot panel

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#409]
Reference design (note that the copy isn’t final and the checkbox may be taken off if not necessary):

![pageshot-shot-panel-welcome](https://cloud.githubusercontent.com/assets/51007/7647570/673abe74-fb2b-11e4-8768-d4b8e94b87ab.png)

The idea is to have a one-pager that precedes the edit interface of the shot panel. This interface serves two purposes:

1. As an introduction to PageShot that explains how it works and what to do with the link
2. As a barebone editing interface that allows:
  * Resizing the auto-selected clip
  * Deleting that clip
  * To add more or edit clips (change selection mode, write comment, modify name/avatar), user must select a link that will be called “Add more clips”, “Start using PageShot”, “Let’s get started”, etc.

Social media icons can be found in #189.

**Comment by fzzzy** [comment]
The final implementation differs slightly from this, but we can open new bugs if we want to change anything.
