### ISSUE TITLE
Consider Express

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#410]
I'm looking at Express, and it looks okay.  We can keep it fairly simple, using the [routing](http://expressjs.com/guide/routing.html) and the [middleware pattern](http://expressjs.com/guide/using-middleware.html) (we shouldn't jump into using any middleware libraries IMHO).  [Error handling](http://expressjs.com/guide/error-handling.html) is probably useful.  [Convenient static files](http://expressjs.com/starter/static-files.html).

No templating.  We keep it simple in a `server.js` file, and don't use the [layout they suggest](http://expressjs.com/starter/generator.html).  No configuration.

**Comment by kitcambridge** [comment]
You might like [restify](https://www.npmjs.com/package/restify), too. It borrows the router from Express, and its middleware are Express-compatible, but a nice alternative if you don't need templating or any of the other frills.

Express ships its middleware as [separate modules](https://github.com/expressjs/), so it's possible to use restify and mix-and-match.

**Comment by ianb** [comment]
After some discussion we're going to go with Express, as it's the most conventional choice.
