### ISSUE TITLE
Large/long clips don't save on live site

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#417]
If you make a clip larger than the screen (how much larger I'm not sure), it doesn't seem to save.  This only happens on the live site.  Maybe some kind of entity size limitation?

**Comment by fzzzy** [comment]
Did you test that they do work on a local instance? If so, perhaps it has something to do with the nginx configuration?

**Comment by ianb** [comment]
Similar actions were working locally that weren't working remotely (though I didn't have the exact same version of the addon installed in both cases, so it could have been something related to that – worth testing by changing the addon settings, but it seems less likely to be the problem).

**Comment by fzzzy** [comment]
Ian figured this out, it was a database issue
