### ISSUE TITLE
Test shot detail page on mobile

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#424]
We haven't even looked at it at all, we should at least look and see if there is any low hanging fruit we can pick.

**Comment by ianb** [comment]
It renders OK.  But if the viewport size was set it would be more interesting, and might allow the embedded page to be responsive.  That's as simple as adding [this](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) to shell.js.
