### ISSUE TITLE
Show metrics/visits on pages

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#43]
We should show the number of unique visitors each page gets (i.e., has anyone else seen this page?)

**Comment by ianb** [comment]
I'm thinking we can keep this separate from the main code, and just have viewers report on whether this is their first visit, and do a separate request to register the visit.  So it'd be something like:

```javascript
if (! localStorage.getItem("seen:" + pageId)) {
  sendRequest("/hit?id=" + pageId).then(function () {
    localStorage.setItem("seen:" + pageId);
  });
}
```

Then we implement the hit tracking somewhat separately.  I suppose we can still report on the hits when we serve up/read the data, but I like trying not to be clever about determining unique hits.

**Comment by fzzzy** [comment]
Dup of #30
