### ISSUE TITLE
Put "alpha" onto the panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#438]
I'd like a little something to scare people off, similar to what Hello has, but with the scarier "alpha":

![screen shot 2015-05-27 at 2 07 06 pm](https://cloud.githubusercontent.com/assets/44390/7845005/b7de49e8-0479-11e5-8a88-6534c5594cd1.png)

**Comment by brampitoyo** [comment]
Alpha flag. Just grab and include in the doorhanger.
![alpha-flag](https://cloud.githubusercontent.com/assets/51007/7853266/10d0f122-0560-11e5-844f-ee7a5101e598.png)
