### ISSUE TITLE
"Get the extension" message shows up when I have the extension

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#440]
Might be a version mismatch, haven't checked.

**Comment by fzzzy** [comment]
This would happen if the addon doesn't fire the custom event to the content page within 2 seconds. Is that too short?

**Comment by ianb** [comment]
I can't reproduce this now.

**Comment by ianb** [comment]
This happens when you use the clip navigation (causing a rerender)

**Comment by kitcambridge** [comment]
I can roll this into #461; re-rendering the entire page for profile refreshes means this shows up a lot more often.

**Comment by fzzzy** [comment]
I guess just keep track of whether it is the first render or not and only call the setTimeout if it is the first render, unless you can think of a better way.

**Comment by ianb** [comment]
We can move it out of render and put it in clientglue too, no?

**Comment by fzzzy** [comment]
That's a good idea.
