### ISSUE TITLE
Copy link doesn't show any indicator it worked

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#443]
When you click the icon it does copy the link, but doesn't give any indication that it happened.  Maybe a popup/notification.

**Comment by fzzzy** [comment]
Bram, can you figure out what this should look like? Doing a popup is going to be technically harder to do than having something appear in the panel for a few seconds, but I can't figure out what it should look like

**Comment by ianb** [comment]
I think we can just use a notifications popup, using the [sdk api](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/notifications) – so at the same place the clipboard copy is called, throw in a call to make a notification.
