### ISSUE TITLE
Schema migrations

### ISSUE THREAD

**Issue by kitcambridge** [mozilla-services/pageshot#446]
I added a few secondary indexes in kitcambridge@c3b01c6542dd71297136b9416ae47f650b3b3858, but Postgres won't support MySQL's `CREATE INDEX IF NOT EXIST` until [version 9.5](http://www.postgresql.org/docs/devel/static/sql-createindex.html). (Incidentally, 9.5 adds [upserts](http://www.postgresql.org/docs/devel/static/sql-insert.html) in the form of `ON CONFLICT UPDATE`, too).

In the meantime, though, it looks like we'll need to roll our own migration code. The FxA folks use https://github.com/mozilla/mysql-patcher; maybe we can adapt it for Postgres?

**Comment by fzzzy** [comment]
https://www.npmjs.com/package/pg-patcher

**Comment by kitcambridge** [comment]
Sweet! I was tired and didn't research further. :wink:

**Comment by ianb** [comment]
When migrating after latest change, we need to be sure we can have body='' and then try to pick up the body from the json

**Comment by fzzzy** [comment]
Add the "head" and "body" columns to the data table.
