### ISSUE TITLE
Research Instapaper Twitter share

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#451]
There's an [article on it](https://medium.com/making-instapaper/instapaper-tweet-shots-5df8587988e8) and it's very similar to OneShot, but with some different design decisions.

**Comment by brampitoyo** [comment]
![Instapaper Tweet Shot](https://d262ilb51hltx0.cloudfront.net/max/800/1*-2jI1O1zfICbk6TjP5kHbg.png)

In a nutshell, Instapaper Tweet Shot works this way:
* Highlight text
* Tap ‘Share’
* Tap ‘Tweet Shot’
* Instapaper auto-generate image of quote:
  * Style is determined by current appearance. If you customise Instapaper to use Georgia font on a dark background, the Tweet Shot will also use Georgia font on a dark background.
  * User doesn’t need to crop or adjust screenshot. Instapaper sets up the aspect ratio and type properties (size, line height, etc.) automatically.
* Add a Tweet message if you like, then tap ‘Post’

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1YAoAZVsYw6-8PgsdnVh1n-yJub6QBq1sAMtctIEzAL0/edit)
