### ISSUE TITLE
Save group of tabs

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#47]
There should be a way to save a group of tabs all at once, to a tag (similar to the direct-to-tag dropdown, only you'd select several tabs instead of just the active one).  The current tab should default to selected.

**Comment by CaptainCalliope** [comment]
Some of these issues are starting to get into some of my use cases and pain points around Evernote, Google Inbox, and Firefox tab groups. Been wishing I could have these three things merged together for awhile. Would love to help brainstorm on this.

**Comment by ianb** [comment]
This doesn't feel like it fits with our flow now, because it means you'd take a shot of a page without doing a selection and confirmation.
