### ISSUE TITLE
Errors in a shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#473]
```
console.log: pageshot: Internal error http://toddwschneider.com/posts/mortgages-are-about-math-open-source-loan-level-analysis-of-fannie-and-freddie/
console.log: pageshot: Error from worker:  : {"name":"ReferenceError","message":"ReferenceError: assignment to undeclared variable href"}
console.log: pageshot: Promise rejected with error: {"name":"ReferenceError","message":"ReferenceError: assignment to undeclared variable href"}
console.log: pageshot: Failed assertion: Bad attr to new Shot(): Array ["name","message"]
```

**Comment by ianb** [comment]
These are errors from the addon

**Comment by kitcambridge** [comment]
Looks like the microformat shiv [doesn't declare the `href` variable](https://github.com/mozilla-services/pageshot/blob/master/addon/data/vendor/microformat-shiv.js#L1197).

**Comment by fzzzy** [comment]
Here is the stack trace. It does look like microformat-shiv is the culprit:

"expand@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:1128:13
expandURLs@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:1120:1
getEValue@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:553:1
getValue@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:504:12
walkChildren@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:464:14
walkTree@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:287:5
get@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:82:13
microformats.getItems@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/vendor/microformat-shiv.js:1180:9
extractData@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/extractor-worker.js:57:19
watchFunction/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/error-utils.js:41:16
@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/donovan/code/pageshot/dist/addon/Profile/extensions/jid1-NeEaf3sAHdKHPA@jetpack.xpi!/bootstrap.js -> resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/loader/sandbox.js -> resource://jid1-neeaf3sahdkhpa-at-jetpack/pageshot/data/extractor-worker.js:139:24
"
