### ISSUE TITLE
Style close link on reminder dialog

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#477]
This:

![screen shot 2015-06-09 at 10 47 39 am](https://cloud.githubusercontent.com/assets/44390/8062372/f8e1939e-0e94-11e5-8815-f0aadd72826d.png)

Should use a unicode cross, not an X, and shouldn't have an underline.

**Comment by kitcambridge** [comment]
I think Bootstrap uses `&times;`. Maybe there's a proper glyph for close buttons, though?
