### ISSUE TITLE
When you redisplay a page that has an active shot, and you have edited it, it is not resized

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#478]
It starts over with the small size:

![screen shot 2015-06-09 at 10 50 41 am](https://cloud.githubusercontent.com/assets/44390/8062462/7525b7fa-0e95-11e5-8418-fbe1874ce5c5.png)

The large size should be sticky.  Maybe a property on the ShotContext.

**Comment by fzzzy** [comment]
The large size is sticky, but no code runs when the panel is displayed, so the code that runs to set the size correctly never runs.
