### ISSUE TITLE
Back button on recall panel needs to be fixed

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#491]
Current state:

![screen shot 2015-06-09 at 5 28 51 pm](https://cloud.githubusercontent.com/assets/44390/8071177/0d2043b8-0ecd-11e5-9986-c2716e6414d0.png)

"Back" should be a button and below the gray area, just above the title.  Should be arrow+text in the button.

**Comment by brampitoyo** [comment]
Reference design:
![pageshot-shot-panel-back-button](https://cloud.githubusercontent.com/assets/51007/8075950/7d5d94a0-0f9a-11e5-9c78-aba52bbe44f0.PNG)

**Comment by brampitoyo** [comment]
![screen shot 2015-07-22 at 10 04 55](https://cloud.githubusercontent.com/assets/51007/8813635/21ba789a-3059-11e5-91e3-eb16bbcee34e.PNG)
