### ISSUE TITLE
Add "full page" button

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#495]
At the bottom of the pages should be a "↓ full page ↓" button.  This button will be "stuck" to bottom of the screen, until the full page scrolls into view and then it will be stuck to the top of the iframe.  Clicking it will scroll the iframe until the "full page" button is at the very top of the page (i.e., scroll just short of the top of the iframe).

**Comment by brampitoyo** [comment]
![pageshot-full-page-button](https://cloud.githubusercontent.com/assets/51007/8075257/33346e60-0f92-11e5-804b-f5b91a133bd0.png)

Alternate title: “Go to page”.
