### ISSUE TITLE
Hide navbar title/link until you scroll up some

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#498]
We should "hide" the title/link in the navbar (`#toolbar)`, both the text and make the background transparent.  Then when you scroll up enough so that the title would be obscured by the navbar, we show the navbar (also hiding the title).  This way we don't double display the title and link when you first open a page.

**Comment by brampitoyo** [comment]
![article-navbar-fade-in](https://cloud.githubusercontent.com/assets/51007/8074501/70826142-0f87-11e5-9b6d-8641a3fa439c.gif)
