### ISSUE TITLE
Implement navbar design

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#499]
![screen shot 2015-06-10 at 11 01 11](https://cloud.githubusercontent.com/assets/51007/8071643/3528cff4-0f60-11e5-8390-91d86c19c6b7.PNG)

**Comment by ianb** [comment]
Notes:

1. Highlight All Clips for later
2. Home button comes when we do the homepage
3. Login button when we get logins
4. Since we don't have user information, it'll just say "saved 8 hours ago" for now
