### ISSUE TITLE
Clicking on a text clip made from a certain page causes an invariant violation error

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#501]
Make a text clip from this page http://books.aidanf.net/learn-swift and click on the clip on the detail page.

Uncaught error: Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .szh86s6qkg.1.0.6:$d8pv7nrc5c39.0 at http://localhost:10080/static/js/server-bundle.js?rev=e7962e90f2e0f44f581a71eb6

**Comment by ianb** [comment]
Text clips are no longer present
