### ISSUE TITLE
Switch clips to using onClick

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#503]
Wrapping text clips in `<a href="#clip=..."></a>` seems like it might be causing problems.  And it does cause styling inconsistencies.  Maybe instead we should just use `onClick={location.hash='#clip='+clipId}` on the div.

**Comment by fzzzy** [comment]
I think image clips should be switched too. It prevents the current nesting of a tags because of the comment button.

**Comment by ianb** [comment]
I don't think this applies to the markup anymore
