### ISSUE TITLE
PageShot web shows default background if site has no background-color declaration in its <body>

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#510]
Original:
http://metservice.com/towns-cities/auckland/auckland-central

PageShot:
http://pageshot.dev.mozaws.net/h7lmd592/metservice.com

I’d like it to give the full-site snapshot a background value of white. Maybe it’s tricky to do?

**Comment by ianb** [comment]
Probably that's one of the reasons this page doesn't work as well as we'd like: http://books.aidanf.net/learn-swift
