### ISSUE TITLE
If you enter a comment and hit + then the comment-in-progress is lost

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#517]

**Comment by ianb** [comment]
Probably we just need an onBlur handler that works like Enter

**Comment by ianb** [comment]
Hitting Escape should revert to the saved comment (and also unfocus the field)

**Comment by fzzzy** [comment]
The browser intercepts escape to close the panel before we can do anything about it, so we'll just have to be ok without having a way to go back to the old comment. The regular os level undo should be able to help for the same use case though.

**Comment by ianb** [comment]
Yeah, Escape was just a bonus, if it doesn't work then so it goes.
