### ISSUE TITLE
More draggable things from Recall panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#525]
You can drag the link out of the recall panel, and you can drag screenshots out.  But maybe we could add more things?  Like the screenshot, title, and link?  I'm not sure how it works, but it at least seems plausible that we can put markup into the panel in a format that makes it drag to something else.  (I'm guessing we'd have CSS that made it look one way in the panel, and another once removed from the panel.)

**Comment by ianb** [comment]
Note that dragging the link doesn't actually work as desired: the link isn't dragged, but the text is, which does not include http://.  I'm not sure how we define draggable chunks of content.

**Comment by brampitoyo** [comment]
I would argue that you need no more than two kinds of draggable elements – both of which have an obvious way to drag out:

* URL: drag out the blue link text
* Image: drag out the thumbnail

You could also argue that dragging out and clicking the “Copy” button are two different actions that does the same thing, so if you can drag thumbnails out, would you also want a “Copy image” button that’s separate from “Copy URL”?

**Comment by ianb** [comment]
Since Recall is gone, this no longer applies
