### ISSUE TITLE
Style library list

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#534]
![screen shot 2015-06-18 at 3 55 39 pm](https://cloud.githubusercontent.com/assets/44390/8242044/7e06fc00-15d2-11e5-9e3a-ba28e2f4a1c8.png)

Link at the bottom should be bg `#eaeaea`, with border like on the panel, `#cccccc`

Link at bottom should be a large target (not just the link)

Copy style of the bookmark panel:

![screen shot 2015-06-18 at 3 57 15 pm](https://cloud.githubusercontent.com/assets/44390/8242079/b7edc73c-15d2-11e5-8865-7a7bdfadef42.png)

**Comment by ianb** [comment]
The title should not be textually truncated, it should use overflow/ellipsis

**Comment by ianb** [comment]
When you click the copy link, it should popup with a copy message (as we do everywhere else now).  We'll get rid of the "copied" text that pops up next to the link icon.

**Comment by brampitoyo** [comment]
Change the colour of doorhanger links to #0095dd.

**Comment by ianb** [comment]
Let's put a header on the panel, so that it looks less strange when you have only one item.  Let's style the top bar (the title bar) the same as the bottom.

**Comment by brampitoyo** [comment]
When you have only one item, is it smarter to just condense the view? That is, the height of the recall panel is variable, based on the content inside it. When there’s only one item saved, it’s short. When there’s 10, it’s long.

**Comment by ianb** [comment]
We have to set the panel size in the addon, not the container that actual renders the list.  This makes it a bit awkward to dynamically set the length.  We could open a followup ticket though.
