### ISSUE TITLE
Style short panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#535]
This:

![screen shot 2015-06-18 at 4 04 06 pm](https://cloud.githubusercontent.com/assets/44390/8242240/b108de4c-15d3-11e5-90b7-afdce2247996.png)

"Copy of page saved:" 13px

cc link: 24px; color: `#0095dd` (generally that's the color of links in the panel, nothing to distinguish visited from unvisited)

"Now go and share it!": 13px; reduce vertical space above this text

Header should be `#eaeaea` as usual, with `#cccccc` border

Try unstyling the Edit button, to make it like other buttons, e.g., for a bookmark:

![screen shot 2015-06-18 at 4 09 38 pm](https://cloud.githubusercontent.com/assets/44390/8242366/71fb2434-15d4-11e5-9245-e8e819790902.png)

**Comment by brampitoyo** [comment]
Reference design:
![pageshot-walkthrough-video 001](https://cloud.githubusercontent.com/assets/51007/8242338/81407fea-15c3-11e5-8fbd-2273f657b559.png)

**Comment by ianb** [comment]
After putting styles in place the edit button feels too small, should do review of it.

![screen shot 2015-07-24 at 1 07 41 pm](https://cloud.githubusercontent.com/assets/44390/8881388/fd4d4a84-3204-11e5-8046-261d626bdac8.png)

**Comment by brampitoyo** [comment]
I was trying to make the button look similar to those found in `about:preferences`

<img width="236" alt="screen shot 2015-07-29 at 10 18 45" src="https://cloud.githubusercontent.com/assets/51007/8945411/4862ca1a-35db-11e5-8543-d28e5972ba07.PNG">

**Comment by ianb** [comment]
I think all we need to do now is restyle the Edit/Add button.  Not sure how to clone that look exactly.

Donovan suggests we have two buttons: Edit does what the button does now.  Add opens the long form of the panel, and does the same thing as the `+` button (i.e., goes immediately to selecting the kind of clip you want to add).

**Comment by brampitoyo** [comment]
That sounds good. Let’s try adding the `add` button, and see how we go.

CSS for the button:
http://codepen.io/brampitoyo/pen/eNwJvy
