### ISSUE TITLE
Style login panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#537]
Here's what it currently looks like:

![screen shot 2015-06-18 at 4 25 30 pm](https://cloud.githubusercontent.com/assets/44390/8242672/aae4a67e-15d6-11e5-9327-65891e37e49f.png)

And after login:

![screen shot 2015-06-18 at 4 26 17 pm](https://cloud.githubusercontent.com/assets/44390/8242683/c49f1a4a-15d6-11e5-8375-ed8976e0703b.png)

**Comment by brampitoyo** [comment]
Reference design:
![identity-panel](https://cloud.githubusercontent.com/assets/51007/8242701/1451e128-15c6-11e5-9313-af1d55d10a9b.PNG)

**Comment by brampitoyo** [comment]
Bram to add details of this panel.

**Comment by brampitoyo** [comment]
* Icon dimension – 80x80 pixels
* Heading – bold, 13px
* Text (“Access your snapshot history…”, “You are signed in as…”) – 13px
* Form field text – 13px

**Comment by ianb** [comment]
I'm not very into the section labeled "Sync" – feels like a peculiar way to describe it.

Also maybe we need to change the language for users who don't have the addon installed, as the value proposition is different.  (They may use Firefox elsewhere, and logging in would give them access to something, but it's complicated.)

**Comment by ianb** [comment]
If you don't have the addon installed we have to disable the login button.  The button should be removed in that case.

Remove the "Sync" title entirely.
