### ISSUE TITLE
Unify text color values

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#538]
#### Doorhanger

I’m following Firefox’s values.

* General text (used for most things): `#333333`
* Form field text: `#000000` (oddly, it’s darker than `#333333`, but there you have it)
* Form field placeholder text: `#bbbbbb` (I think I said `#cccccc` earlier, but it was mistaken)
* Link text: `#0095dd`

#### Web

I’m following pdf.js values.

* White text (used for titles): `#f2f2f2`
* Grey text (used for links like “See in full page” and texts like “8 hours ago”): `#959595`
* Link text: `#0095dd` (same as doorhanger)
* Black text (used for comment when it’s set against a light background): `#333333`

**Comment by ianb** [comment]
I think we'll do this when we clean up our CSS

**Comment by ianb** [comment]
We'll probably do this cleanup somewhere other than this particular ticket.
