### ISSUE TITLE
Resize handles are too hard to get to

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#541]
There's two issues I encounter:

1. They are just too small.  It is hard to grab them.
2. They sometimes are near the edge of the screen.  They become half-size, and the window resizing handle is essentially right next to them.

**Comment by brampitoyo** [comment]
For item 1, the solution might be to enlarge the resize handles?

Fixing item 2 is trickier. We’ll have to think about that one carefully.

**Comment by ianb** [comment]
We can enlarge the target area even if we don't enlarge the handles (or don't enlarge them as much).  In that case we should probably also have a hover effect.

Maybe there's some clever CSS to push the handles in when you are on the edge of the screen, but I'm not sure, and I don't think it's worth doing a Javascript adjustment (especially since it is affected by scrolling, for instance).

**Comment by brampitoyo** [comment]
Another thing we could do, that I mentioned at yesterday’s meeting, is to allow resizing from inside the selectable area.

![resize-from-inside-handle](https://cloud.githubusercontent.com/assets/51007/8712743/23b7f9dc-2bb4-11e5-8bb0-b2d2b58f6d06.PNG)

The cursor changes to resize and the handle can be resized a little bit outside of the handle boundary, but mostly *inside*, to allow for imprecise resizing as well as resizing near the edge of the screen.

OS X already has the behaviour we want, and it looks like this:
![resize-from-inside-handle](https://cloud.githubusercontent.com/assets/51007/8712766/694266cc-2bb4-11e5-8a60-be12b5178360.gif)

**Comment by ianb** [comment]
That's largely what I meant by enlarging the target area.  It will be actual boxes (though invisible), so we need to think in those terms for the actual targets.  I'll code the size of the boxes as a variable so we can tweak them some.  I guess two variables, one for how much it goes outside the selection, and another variable for the inside.

**Comment by ianb** [comment]
There's now [some variables](https://github.com/mozilla-services/pageshot/blob/3dba9c585d86cf6162d54a1fcc79004a9043d1c0/static/css/inline-selection.scss#L1-L6) that you can use to control the exact size.  Initially I've done 10 pixels outside the area (the handles go 5px outside), and 40px on the inside.

It gets a little weird when you make the selection very small (maybe smaller than 80px in this case?) but while it's ugly and awkward it's not unusable.

**Comment by brampitoyo** [comment]
Yes. Your approach is sound. Outside boundary should be smaller than the one inside. Although I think 40px is a bit too large. Try 30px, perhaps, or even 20px?

Either way, we can probably mark this issue as fixed for now and file a new one when we find the area unusable.
