### ISSUE TITLE
Reminder is too hard to close on mobile

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#543]
I keep hitting the link.  It might be literally impossible to close when the screen is too narrow.

Also we have no mobile extension to provide anyway.

**Comment by fzzzy** [comment]
we probably shouldn't show it on mobile at all

**Comment by fzzzy** [comment]
On second thought, I don't see a reason why we shouldn't advertise it on mobile too. It's just as useful info for a mobile user that wants to know how to create shots.
