### ISSUE TITLE
Design front page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#545]
The front page should have a clear download link (clearer than currently), and other reasonably nice stuff.

**Comment by fzzzy** [comment]
For now let's just copy the togetherjs homepage design

**Comment by ianb** [comment]
I think we should do the homepage as a separate directory where everything is static.  I.e., no React, no particular attempt to borrow styles from the rest of the site.  If we want subpages we can do them as in-page transitions with hashes.

**Comment by ianb** [comment]
[Initial design from Bram](f.cl.ly/items/2h3F0e2e370M2V0q1Q0w/pageshot-homepage.PNG)

**Comment by brampitoyo** [comment]
I think of the front page as the start of an onboarding experience. There are three parts to this experience.

The first part tells you all about what PageShot can do:
![pageshot-homepage-animation-1](https://cloud.githubusercontent.com/assets/51007/8711804/47de5dac-2ba9-11e5-94ec-1430ff1c60ad.gif)

The second invites you to try out PageShot to save a real-life page of your choosing:
![pageshot-homepage-animation-2](https://cloud.githubusercontent.com/assets/51007/8711808/510f7956-2ba9-11e5-94ee-4eee632b8a59.gif)

I reckon there should be one additional step after this that involves you getting to email the shot URL/picture to yourself, or share it to your friends, so you not only get to take a shot, but you get to see what it’s meant for. At the moment, though, it’s just a link.

The third step involves following the link to the website and installing the add-on to complete the onboarding process.

![pageshot-homepage-animation-3](https://cloud.githubusercontent.com/assets/51007/8711968/e0e9ed12-2baa-11e5-91ce-e83da5ee95ae.gif)

You can see why I was ambivalent about step 2.5. Getting you to email links to yourself or your friends is a distraction from getting you to install the add-on.

Ideally, we want both. We want to say “Now that you’re done emailing and sharing, this is what that page looks like when you/other people see it later. Now you should install the add-on”.

**Comment by ianb** [comment]
Doing the second step, where you take a shot of an arbitrary page before PageShot is installed, is fairly challenging, it will require us reimplementing much of what PageShot does.  It might be worth doing anyway, but not for First Launch.  (Taking a shot *after* the addon is installed is fairly easy though.)

**Comment by ianb** [comment]
The front page needs a call to action that will be separated between a cases:

1. User is using Firefox and doesn't have PageShot installed (install!)
2. User is using Firefox and does have PageShot installed (hooray!  Tell others?)
3. User is on desktop, but using Chrome or something (just ask to use Firefox?)
4. User is on mobile, and can't install PageShot (see if we can remind them later?)

**Comment by ianb** [comment]
Are these designs still accurate?  They don't seem like what we've been talking about lately.

**Comment by brampitoyo** [comment]
Our home page is going to be hosted on IdeaTown.

**Comment by ianb** [comment]
The page is in place, any tweaks should be opened in followup bugs.
