### ISSUE TITLE
Selecting autoselect when it can't auto-anything goes to visible in a confusing way

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#546]
The current PageShot homepage is a good example.

**Comment by ianb** [comment]
Right now if you hit Edit then "auto-select" on our homepage, it will do nothing, because the auto-select will fail.

In the case of an explicit request to autoselect we could fall back to selecting the full screen.  A user is likely to expect that there be handles, so we should make it a selection instead of how we handle visible selection.

**Comment by fzzzy** [comment]
Unfortunately we can't get to the old homepage any more. Even with a fresh profile it just takes me to an empty page that says "Your Shots". I think that's a bug? Anyway, we should probably put the homepage and the "Your Shots" page at different urls, but that is a different bug.

I will try to find another page that triggers this bug.

**Comment by fzzzy** [comment]
I made it fall back to visible selection when auto select fails, but I didn't make the selection editable. Can we just open another bug to make all visible selections editable? I think it would be nice.
