### ISSUE TITLE
Move clip images into separate objects/tables

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#554]
We want to move the data: urls out of the shot JSON, replacing them with other URLs.

This needs to:

- Put clip images into a different table
- If a clip is deleted, the clip image row should be deleted
- The client needs to know the new (non-data) URL of the clip

I'm thinking we could give a response to the PUT that perhaps is the entire updated shot, or maybe just changes.  Changes would be processed like:

```javascript
let updates = JSON.parse(putRequest.responseText);
let shot = <the original shot>;
function updateShot(shot, updates) {
  for (let key in updates) {
    if (updates[key] === null) {
      delete shot[key];
    } else {
      if (typeof updates[key] == "object") {
        if (key in shot) {
         updateShot(shot[key], updates[key]);
        } else {
          shot[key] = updates[key];
        }
      } else {
        shot[key] = updates[key];
      }
    }
  }
}
```

We could use this update process for the HTML keys, though we'd have to create either/or keys (probably like `bodyHtml` and `bodyHtmlUrl`).  Now that I write it down I regret the update I propose, because for instance with our strict testing in `AbstractShot` we probably require that both these can't be set simultaneously, and so doing property-by-property updates is inappropriate as there is a temporarily invalid state.  We could put this method in AbstractShot and tweak it with Shot-specific stuff.  Also `shot.bodyHtmlUrl = xxx` could automatically wipe `shot.bodyHtml` and vice versa.

**Comment by fzzzy** [comment]
Why does the client need to know the non-data urls? Whenever anybody visits the shot page, they will get the shot data with non-data urls, but I don't see why the client needs to know what those are when the shot is being created.
