### ISSUE TITLE
Move /content/ to a different origin, use CSP

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#556]
Given a separate origin (ideally domain, maybe TLD) for the content frame, and a Content Security Policy restricting the JS locations, we could avoid a number of security problems.

**Comment by ianb** [comment]
This will require some work with content-helper/parent-helper because they do some stuff currently that only works when they are on the same origin

**Comment by fzzzy** [comment]
We should run it on a different port to simulate being on a different domain
