### ISSUE TITLE
Design "copy image" button

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#558]
We have a copy link button, but we also want to add a copy image button that just copies the screenshot to the clipboard instead of the shot url.

**Comment by brampitoyo** [comment]
* [64x64](https://www.dropbox.com/s/jsiu7wm0a6pa01m/copy-image-64.png)
* [32x32](https://www.dropbox.com/s/9zq8ymdbdguloi7/copy-image-32.png)
* [16x16](https://www.dropbox.com/s/mwiwr5x8bfrn25u/copy-image-16.png)
