### ISSUE TITLE
Design "copy html" icon

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#559]
We have a copy link icon, but we also want to add a copy html icon which copies a link to the shot, the shot screenshot, and the shot title to the clipboard as html.

**Comment by brampitoyo** [comment]
* [64x64](https://www.dropbox.com/s/owseil4stnt7kja/copy-code-64.png)
* [32x32](https://www.dropbox.com/s/2fgj41w3nt8gkiy/copy-code-32.png)
* [16x16](https://www.dropbox.com/s/0hmvdn14rt7f93y/copy-code-16.png)
