### ISSUE TITLE
Show an indication that a "visible" screenshot was taken

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#567]
When you get a selection or autoselection the highlight indicates what happened.  But when you do a visible screenshot nothing is shown.

I propose we include an icon in the top left corner, something roughly like:

![screen shot 2015-07-14 at 12 00 16 pm](https://cloud.githubusercontent.com/assets/44390/8677950/eeb5295c-2a1f-11e5-9410-900682d3d5f8.png)

Clicking on it would revert to autoselect.  A similar icon could be put above or inside the autoselect region that would switch to visible.

Arguably we should also shade out the portions of the screen that aren't part of the visible selection (which you would see if you scrolled), but we wouldn't have handles.

**Comment by brampitoyo** [comment]
We can either do an icon, or do a 30x30 pixels semi-transparent blue box. Or maybe do both (icon on top of a box)?

**Comment by ianb** [comment]
Not doing this in favor of #620
