### ISSUE TITLE
Send server data into datadog

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#571]
I think it is statsd-compatible.

**Comment by ianb** [comment]
If we use Google Analytics, the purpose of datadog is anomaly detection.  So it'd be basic info about visitors, visitors to `/api/register`, failed login attempts, stuff like that.  Not information for insight, but to detect problems.

**Comment by ianb** [comment]
We need to confirm this with Benson to see if it's happening with the new production deployment.

**Comment by fzzzy** [comment]
Confirm that our log messages are getting stored in datadog.

**Comment by fzzzy** [comment]
Log messages will be handled automatically; if we want to track specific things, we should open new bugs for those.
