### ISSUE TITLE
Allow editing the shot title

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#573]
Per #441 I find I want to edit the shot title so I can talk about what _I_ am sharing, not what the page was intended to say.

**Comment by fzzzy** [comment]
Bram, can you figure out what the interaction design for this will be like?

**Comment by ianb** [comment]
Work is in cc10632994ccaf1111f312133bf5603b6444a004

Interaction looks like this:

If you are the owner you hover, get a pointer cursor (not a text select cursor) and a pencil appears:

![image](https://cloud.githubusercontent.com/assets/44390/19903088/4d0df924-a03b-11e6-8d62-5a7815635145.png)

Click on it and you get editing:

![image](https://cloud.githubusercontent.com/assets/44390/19903096/5633d0b4-a03b-11e6-9532-6f8914e3c7e9.png)

You can hit Enter to accept, Escape to cancel.  If you blur without editing the title, it goes back to normal.  If you edit the title and blur then the input stays open.

If you erase the title entirely it is reset to the document (or opengraph) title.  So if you edit the title, save, then edit and erase everything, you get the original.

When you save a `.saving` class is added to the title until the save completes.
