### ISSUE TITLE
Design for inline clip highlighting

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#575]
Right now when you click on a clip and see it in context, the clip is outlined in black.  I don't think we want this.  It might have ended up this way as an unintentional effect of implementing the shadowbox effect we have during selection.

I am guessing we want a blue thickish line with less than full opacity.  We could do a full shadowbox but that seems distracting.

**Comment by brampitoyo** [comment]
![pageshot-clips](https://cloud.githubusercontent.com/assets/51007/8711438/ef767224-2ba5-11e5-9b24-b99d3fcba942.png)

Yes. Selected clip should be outlined in thickish blue line:

* #0095dd
* .5 opacity
* Full opacity when mouse over border *and* the inside of the selected area

While the rest of the clips that are not currently selected should be outlined in orange (#ff9500)

**Comment by brampitoyo** [comment]
Full page clips are a bit different. They look like a box that expands into an outline when hovered over:

![pageshot-full-page-clip-highlight-animation](https://cloud.githubusercontent.com/assets/51007/8711585/6b3eb7f8-2ba7-11e5-8468-def05441ef3d.gif)

* Size: 30x30 pixels
* Margin: 15px from left of clip, 15px from top of selected area
* Colour: depending on whether it’s currently selected or unselected

When moused over, the expanded outline colour looks exactly like a moused over clip (#0095dd, full opacity).

**Comment by ianb** [comment]
Specific issues in #653 and #654
