### ISSUE TITLE
Review border on clip

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#578]
This is what clips look like:

![screen shot 2015-07-15 at 4 20 11 pm](https://cloud.githubusercontent.com/assets/44390/8708996/6ae3c28e-2b0d-11e5-807b-010607729585.png)

I'm not sure we need that border?  At least in this case it doesn't look good.

**Comment by brampitoyo** [comment]
I don’t think we need that border. Drop shadow by itself should be sufficient to make the image stand out from the background.
