### ISSUE TITLE
Use one standard copy button instead of multiples

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#584]
Passing "html" to clipboard.set seems to strip out only the visible text from the html in my testing.

**Comment by ianb** [comment]
Let's discuss the buttons we have

Also, do we want rich html to be the default thing copied?  We can make the plaintext version be whatever we want while still adding rich html.

**Comment by brampitoyo** [comment]
In my ideal world, our copy function would be smart enough to know where it will be pasted to.

So if the same thing is pasted to a place, this is what would be pasted:

* Plain text editor: URL, title
* Rich text editor: image, URL, title
* Desktop: image (user can rename image by herself)
* Plain text box: URL, title
* “Smart” text box (like those found on Twitter and Facebook): image, URL, title – the image will be uploaded by the service, or the URL will be decoded into a card.

**Comment by ianb** [comment]
So one "standard" copy, to be used generally:

Plain text: `title - shot_url`

HTML: `<a href="shot_url">title <br> <img src="image_url"></a> <br> source: <a href="source">{domain}</a>`

We'll make an addon setting to allow more than one HTML option, including one without the source.  This is just to allow us to easily try out the different options, not as a long-term preference.

**Comment by brampitoyo** [comment]
The only question that remains is: which button should we use? Currently, we have the chain icon, as well as the `< / >` one.

**Comment by ianb** [comment]
I dislike both buttons, because `</>` definitely doesn't make sense, and the chain I guess refers to a link but doesn't refer to copying.  The Android copy icons don't appeal to me.  A simple clipboard icon? 📋

**Comment by fzzzy** [comment]
I think we should use a clipboard icon.

**Comment by brampitoyo** [comment]
Clipboard icon sounds good. I’ll make a note to design it.

**Comment by brampitoyo** [comment]
Sorry for the overly delayed delivery on these icons. I’ve finally designed them. Attached here.

16x16
![copy-clipboard-16](https://cloud.githubusercontent.com/assets/51007/9676778/ef316b10-5324-11e5-8a49-84d865518efc.png)

32x32
![copy-clipboard-32](https://cloud.githubusercontent.com/assets/51007/9676784/f3982e50-5324-11e5-8b7c-69e920a883ea.png)

64x64
![copy-clipboard-64](https://cloud.githubusercontent.com/assets/51007/9676788/f73cf11c-5324-11e5-9693-498e5482b3c8.png)
