### ISSUE TITLE
Put time limit on pages

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#587]
For initial releases I'm worried about the problems with preserving the content for long periods of time, as well as abuse.  By putting a time limit on every shot we'll avoid that problem, at least initially.

I propose a two-week time limit, after which the shot is disabled for two more weeks but can be reenabled.  After that the shot will be deleted.

We'll need the time limit, but also notifications about the time limit in several places so people are aware.

**Comment by brampitoyo** [comment]
Would putting shots on expiry date invalidate Pageshot’s original idea?

If we do decide to do this, I think it would be important to keep at least some parts of the shot. Maybe the DOM would be gone, bu the selection won’t. It would also be interesting to show a “Countdown before DOM destruction” timer.

And it would also be good to have a way to easily re-shot the DOM, so maybe a link that says “This page is now expired. [Click here to take another snapshot at this point in time].”

**Comment by ianb** [comment]
For now, if the page is too old we'll serve up a placeholder page.  That page will notify the user that the page has expired, and will offer a link to the original page.

For now we won't delete the page from the server.

We should add these columns to the database:

```
url TEXT NOT NULL -- URL of the original page
expire_time DATETIME DEFAULT NOW + INTERVAL '2 weeks'
deleted BOOLEAN NOT NULL DEFAULT FALSE -- when true we've deleted the json, body, head
```

**Comment by fzzzy** [comment]
UPDATE data SET url=(subquery.value::json->>'url') FROM (SELECT value, id FROM data WHERE url IS NULL) AS subquery WHERE data.id = subquery.id;
