### ISSUE TITLE
Implement export

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#588]
If we let people use this, we should let them export what they make.

I propose the export be a static HTML page, ideally a single HTML page (with lots of data: URLs to embed images, even the iframe).  Potentially we could write that as a separate service that just downloads the page and makes it exportable.

**Comment by ianb** [comment]
Maybe with [inliner](https://github.com/remy/inliner)

**Comment by ianb** [comment]
A [concern](https://twitter.com/laurencerowe/status/622091398989246464): "note that many browsers crash when displaying data urls >2MB."

**Comment by kitcambridge** [comment]
There's also [web packages](http://www.w3.org/TR/web-packaging/), and MAFF...but the former is just a sketch at this point, and the latter isn't really portable. Maybe we create a ZIP (or tar) if the embedded assets exceed a certain size?

**Comment by ianb** [comment]
I looked at this a little in #88 as well (500 tickets later...), and another was [WARC](https://en.wikipedia.org/wiki/Web_ARChive).  One big zip with all the files is maybe OK too.

**Comment by ianb** [comment]
Implemented
