### ISSUE TITLE
Edit button should also indicate Add

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#595]
One bit of functionality hidden behind the Edit button is the ability to add more clips.  "Edit" doesn't fully indicate that IMHO.

**Comment by brampitoyo** [comment]
![screen shot 2015-07-22 at 10 13 54](https://cloud.githubusercontent.com/assets/51007/8813811/645e5418-305a-11e5-8ac6-f8383a25dc2b.PNG)

**Comment by ianb** [comment]
I changed this to "Edit / Add"
