### ISSUE TITLE
Put in debug command to keep panel open

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#602]
When debugging the styling, it is nice if the panel can stay open.

**Comment by ianb** [comment]
With the fixing commit, entering `/sticky` into the comment field will trigger the panel to reopen itself, making it inspectable from other windows, or possible to keep it open while inspecting the content (something I've wanted to do while debugging the highlight).

**Comment by brampitoyo** [comment]
It might just be me, but when making any comment which includes the `/sticky` command), the <kbd>Enter</kbd> key fails to do anything. This might be a bug on the June 21 build of the add-on and not related to this bug, though.

**Comment by ianb** [comment]
This hasn't been deployed anywhere yet, so you could only see the effect when running a local build off the branch.

**Comment by brampitoyo** [comment]
@bwinton might have worked on an add-on that keeps doorhangers open, as well?

**Comment by bwinton** [comment]
No, I had a custom build of Firefox that kind of mostly worked, but probably wasn't worth looking at.
