### ISSUE TITLE
Decide on Node HTML parser and DOM representation

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#605]
For #555 we need to parse the HTML on the server and check it (so we need to parse to some kind of DOM).  I don't think it needs to be portable to the browser; the browser needs to generate correct HTML, not parse it.

There's [quite a few options](https://www.google.com/search?q=node+html+parser) and I don't know which to choose.  We don't have to worry about "bad" HTML: the addon should generate correct HTML, and we can reject incorrect HTML.

Once we parse the HTML we'll be checking it for things like `on*` attributes, `<script>` tags, comments and doctypes – none of these should be present.  We might eventually also use this for link rewriting (TBD, depends if we do this in the addon).

**Comment by fzzzy** [comment]
We could actually use dom.js. It has a working html5 parser.

**Comment by ianb** [comment]
Looks like [domino](https://github.com/fgnass/domino) is a good choice (dom.js without proxies)
