### ISSUE TITLE
Hitting Enter in a comment doesn't do much

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#606]
When I enter a comment and hit Enter, it's very unsatisfying.

I think in some cases I want to comment and do the next thing (and so I want the panel to close).  But sometimes I just want to comment and then deliver (e.g., hit a share button).  Not sure how to address both.  Either way, it just doesn't feel satisfying at the moment.

**Comment by brampitoyo** [comment]
In a normal textbox (like a comment section, for example), the <kbd>Enter</kbd> key would be interpreted as a newline. Under it (usually on the right-hand corner), there would be a separate “Comment” button (also called “Post”, “Done”, etc.) to confirm what you have typed in that box.

I’ve observed more services do <kbd>⌘</kbd>+<kbd>Enter</kbd> as a shortcut to instantly comment.

And on Facebook, you get an option of what pressing <kbd>Enter</kbd> does in a direct message context. If the “Press Enter to send” checkbox is checked, then the reply button disappears.

![screen shot 2015-07-27 at 10 47 05](https://cloud.githubusercontent.com/assets/51007/8896345/ed9e050c-344c-11e5-9175-5ee2e9bf1b2b.PNG)

**Comment by ianb** [comment]
There's no "send" in this case, so submitting when you intended to do a newline isn't particularly impactful, though you would then have to go back and re-edit and figure out the key combo (if Enter doesn't do it).

Really there's nothing much that happens when you "finish" a comment, so it's not quite like a submit.

**Comment by brampitoyo** [comment]
Yeah. It’s not at all like “Submit”. What about something like “Save comment”? It tells you that your comment is saved, but can be re-edited later if you like.

**Comment by ianb** [comment]
Since no longer have this comment entry, this particular issue is moot
