### ISSUE TITLE
Fix overflow of link on short panel

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#610]
Like in this example:

![screen shot 2015-07-27 at 11 53 54 am](https://cloud.githubusercontent.com/assets/44390/8912108/2dab243c-3456-11e5-83a8-b575dfd4f348.png)

Probably should use ellipsis or something.

**Comment by brampitoyo** [comment]
Yes. We should totally use elipsis for the link, with enough horizontal space on both sides.

We could even take out the site domain part of the URL, so only the `zmfTtnID` part remains.

So in this case, the URL would be something like `localhost:10080/zmfTtnID`. Thoughts?

**Comment by ianb** [comment]
This UI no longer exists
