### ISSUE TITLE
Configure front page to go through nginx

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#647]
`homepage/` and `/index.html` can go directly through nginx, not through our server

**Comment by fzzzy** [comment]
Fixed, added configuration to /etc/nginx/sites-enabled/default:

        location /homepage/ {
                root /home/ubuntu/pageshot/dist/server/static;
        }

(I always forget that I have to leave off "/homepage/" on the root line, but I figured it out eventually...)
