### ISSUE TITLE
Highlight all clips in page

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#654]
Per #575, all clips in the full page view should be highlighted, with the "active" clip being highlighted more strongly in blue, and all other clips being highlighted in yellow (exact color, width, and opacity of the inactive clips TBD by @brampitoyo)

**Comment by brampitoyo** [comment]
The color value for inactive border is `#ff9500`, and its width and opacity is the same as the active one.

On hover, the opacity becomes `1` and its border colour becomes `#0095dd`.

CSS example here:
http://codepen.io/brampitoyo/pen/gabxQB

**Comment by brampitoyo** [comment]
Here’s a pen that demonstrates the highlight box animation. We should use it sparingly:

http://codepen.io/brampitoyo/pen/doGLzj

**Comment by ianb** [comment]
We no longer support multiple clips.
