### ISSUE TITLE
We should fall back to head/body in JSON

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#655]
Pages like [this one](http://pageshot.dev.mozaws.net/r8qy21sr/f.cl.ly) don't render because we haven't filled in body and head in the table, but they do still exist in the JSON.  We should fall back to that.

**Comment by fzzzy** [comment]
http://www.postgresql.org/docs/9.3/static/functions-json.html

**Comment by ianb** [comment]
Example query: `select character_length((value::json->'body')::TEXT) from data where body is null;`

**Comment by ianb** [comment]
Probably test on one page (find one page where body is null), then make sure the query works and then do it globally on the database.  We can leave the body in the JSON, and just duplicate it to the table.

**Comment by fzzzy** [comment]
First:

  SELECT count(id) FROM data WHERE head IS NULL AND body IS NULL;

Then:

  UPDATE data SET head=(subquery.value::json->'head'), body=(subquery.value::json->'body') FROM (SELECT value, id FROM data WHERE head IS NULL AND body IS NULL) AS subquery WHERE data.id = subquery.id;

**Comment by fzzzy** [comment]
It doesn't work, because it puts a quoted string in the row.

**Comment by fzzzy** [comment]
Looks like I want the ->> operator instead of ->

**Comment by fzzzy** [comment]
Yes. Correct query:

    UPDATE data SET head=(subquery.value::json->>'head'), body=(subquery.value::json->>'body') FROM (SELECT value, id FROM data WHERE head IS NULL AND body IS NULL) AS subquery WHERE data.id = subquery.id;
