### ISSUE TITLE
Design onboarding in shot panel

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#667]
Right after install, the panel should automatically pop open with a welcome panel – no interaction or click needed.

This welcome panel should persist as long as the shot count is at zero – that is, as long as user hasn’t made any shot yet.

If this panel is shown, user cannot take a screenshot by clicking the camera button. Instead, s/he must click on the button that says “Step 1: Save a copy of this page” on the bottom of this panel.

![pageshot-shot-panel-onboarding-firstrun](https://cloud.githubusercontent.com/assets/51007/9104289/b38c7fd2-3c5e-11e5-9678-067248f68c68.gif)

After the first snapshot is taken, the welcome panel no longer appears, so clicking the camera button will instantly take a screenshot, just like usual.

However, as long as the number of shots taken is below 2, an additional message should show on the shot panel. This message says “To view all your saved pages, click the gallery button”.

![pageshot-shot-panel-onboarding-second-shot](https://cloud.githubusercontent.com/assets/51007/9104330/51a3f1e6-3c5f-11e5-8822-2d456dcbf6eb.gif)

Thoughts?

And what about onboarding in library panel? What should we do when the number of shots is at zero?

**Comment by brampitoyo** [comment]
####Step 1
Here’s how you make a shot. Click big camera button to open a special version of the shot panel.

####Step 2
Shot panel opens and invites you to click on the link. Click link to open a special version of PageShot Web.

####Step 3
Here’s what you have created. PageShot Web opens with tutorial overlay. Click big recall button to open a special version of the recall panel.

####Step 4
Here’s how you recall. To get you started, the Recall panel contains the link to the tutorial itself. It invites them to click on the item to view its details. Tutorial ends.

**Comment by brampitoyo** [comment]
#### Step 1

Immediately after PageShot is installed, open this page in a new tab.

![1](https://cloud.githubusercontent.com/assets/51007/9129497/969b49ac-3d2c-11e5-9c91-f3761b849c6a.png)

User is encouraged to click the real toolbar button (instead of the fake one on the page) to take a shot. However, clicking the button on the page will also work.

#### Step 2

A special shot panel opens. It invites you to click on the link that leads to PageShot’s web interface.

![2](https://cloud.githubusercontent.com/assets/51007/9129510/caab2cc6-3d2c-11e5-9074-440feb0eed4d.png)

#### Step 3

PageShot web opens, telling user three things:

* This is what a clip means
* This is how you get to the carbon copy of the page
* This is how you recall

When user scroll down, he gets an information about the clip when seen in context. With multiple arrow on the page, though, this can become confusing. I’m hoping that the orange colour is enough cue to indicate the real tutorial arrow, from the “fake” one on the carbon copy of the page.

![4](https://cloud.githubusercontent.com/assets/51007/9129543/474d4a5c-3d2d-11e5-8290-02d34333d8b4.png)

#### Step 4

When user clicks the recall panel (under any condition, not just firstrun), the tutorial is the first item that populates it.

![5](https://cloud.githubusercontent.com/assets/51007/9129637/5fcf4ffc-3d2e-11e5-8db9-92667cc1da4b.png)

We can populate this list with more than one tutorials. In fact, we can even give tutorials utilising screenshots and captions on PageShot web, similar to how [some people do it on imgur](http://imgur.com/gallery/M9CMp)

**Comment by ianb** [comment]
Notes:

- We'll put `?` buttons on both panels and the shot pages, to link to help
- On the shot page, if you click `?` you get the same overlays as in Step 3
- On the shot panel `?` gets you back to the main help page
- On the recall panel `?` gets you do a different section that explains that panel

The orange overlay in Step 3 should be visually distinct from anything on the tutorial page (Step 1), because in Step 3 it will overlay the tutorial page.

**Comment by ianb** [comment]
Some walkthrough libraries:

* [Intro.js](http://usablica.github.io/intro.js/)
* [Chardin.js](http://heelhook.github.io/chardin.js/) (pretty!)

Intro.js looks like the best.
