### ISSUE TITLE
401 response to PUT should not result in an error message of "server unavailable"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#676]
We should check the response status codes more specifically

**Comment by fzzzy** [comment]
How do I test this? Try to create a shot without having logged in first?

**Comment by ianb** [comment]
Right now (since I haven't finished #677) you can stop the server, start the addon, start the server, then try to make a shot.

**Comment by fzzzy** [comment]
The response code is showing up as 0 for some reason. Until we can see the actual 401 we won't be able to tell the difference between this and the server actually being down.

**Comment by fzzzy** [comment]
If this becomes a problem in the future, let's open a new issue.
