### ISSUE TITLE
Add "report content" functionality

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#678]
By "report content" it could mean abuse, DMCA, illegal content, objectionable content, etc.

**Comment by ianb** [comment]
I think all we need for this on the first version is something that generates a mailto link with the current URL filled into the body.  It's TBD what email the mailto goes to (probably something configurable?), and where it is positioned.

**Comment by brampitoyo** [comment]
The hamburger/three-dots menu is a good place place to put report content. We can call it “Report Shot” or “Report This Shot”?

**Comment by ianb** [comment]
Note: the creator doesn't need to report their own shot (they can delete it if they want).  When you aren't logged in the trash icon could be replaced by a flag.

**Comment by brampitoyo** [comment]
Flag icon:
https://www.dropbox.com/s/acodoa775hpbb6i/flag.svg

**Comment by fzzzy** [comment]
What happens when someone clicks the flag button? Do we want it to just open a mailto link? What email address?

**Comment by ianb** [comment]
Email/mailto to pageshot-feedback@mozilla.com (already setup to email to us).  The subject should be "Flagging shot for abuse" and the body should include that text and the URL of the shot.

**Comment by fzzzy** [comment]
Fixed in https://github.com/mozilla-services/pageshot/pull/1007

**Comment by brampitoyo** [comment]
I would prefer it if, after clicking/tapping the Report button, we simply show a flag that says “content reported”, then either make the button disappear or disabled. It does the same thing, but the user doesn’t have to open his email program, make sure the content is correct, then hit send.

For now, our current behaviour is okay.

**Comment by fzzzy** [comment]
Sure. This is just the simplest thing, for now.
