### ISSUE TITLE
Add "download clip images" functionality

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#683]
Now that clips expire, we should probably give people an easy way to download the clip images as a zipfile (or as the image file if there's only one clip).

**Comment by ianb** [comment]
Is this different than #588 ?

**Comment by fzzzy** [comment]
I was thinking just the clip images rather than the shot detail html + clip images, but both ways of doing it would satisfy the same use case.

**Comment by fzzzy** [comment]
On further thought, you're right that this is a dupe of #588.
