### ISSUE TITLE
Check out Easy Screenshot add-on

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#691]
Developed by our friend at Mozilla China! There’s a potential for collaboration here.
https://addons.mozilla.org/en-US/firefox/addon/easyscreenshot/

**Comment by ianb** [comment]
This creates a menu with drop-down:

![image](https://cloud.githubusercontent.com/assets/44390/18687382/7499e00a-7f45-11e6-8ead-3c4668b04d39.png)

The default is Capture Web Page Region.  When you do this you get a little notification/help saying to double-click to save, or hit Enter, and a button [I know] that dismisses it forever.

Once you create a screenshot you get an image editor:

![image](https://cloud.githubusercontent.com/assets/44390/18687414/adc691de-7f45-11e6-99d6-9b92e6da3e48.png)

When you hit Save (disk) it saves to your Desktop with a name like `Firefox_Screenshot_timestamp.png`.  It your Desktop folder and selects the file, which is nice (compared, for example, to the system screenshot tool).

It has some simple settings:

![image](https://cloud.githubusercontent.com/assets/44390/18687504/05fd97e4-7f46-11e6-9106-1875baf748ee.png)

**Comment by ianb** [comment]
Copied to [gdocs](https://docs.google.com/document/d/1HT-VztroNCUx2OoQ8I8SKNCEOeozqBP4EFJ4brH6gs4/edit)
