### ISSUE TITLE
Navigation bar overflows on mobile

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#694]
Screenshot:

![screenshot_2015-08-19-10-42-30](https://cloud.githubusercontent.com/assets/44390/9361025/27a1d41c-465f-11e5-9aba-fe3858353a1b.png)

Note that the "expires in two weeks" message (and "ago") flows to the next line, and is almost but not entirely hidden

**Comment by brampitoyo** [comment]
We might need to shorted the text, like this:

![pageshot-navigation-bar-mobile](https://cloud.githubusercontent.com/assets/51007/9369112/4c9b3f4e-471b-11e5-9f01-b07bf8ac5838.PNG)

What do you think?

**Comment by ianb** [comment]
I agree "saved" is superfluous.  The expiration message is also truncated.  Maybe that's fine to leave off on mobile?

**Comment by brampitoyo** [comment]
Yes. It should be fine to leave off on mobile (as long as it’s not too hard to design!)

**Comment by ianb** [comment]
These designs (and hence issues) are no longer up-to-date.
