### ISSUE TITLE
"Mozilla PageShot might be making Nightly run slowly"

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#716]
This has been happening for a long time, but it doesn't look like there is a bug open for it. We should take care of this.

**Comment by ianb** [comment]
We should ask about this on the #extdev channel, but I believe this warning won't show up outside of Nightly (or maybe also Dev Edition?)  I also think it's a little bit of a red herring.  You can see some information on about:performance.  Anytime the addon does a burst of work that popup appears – but mostly it's legitimately doing work.  The React rendering also seems to trigger it, but I don't know if we can do much about that either (though if we fix the bug that requires rerender on every update that would help a bit).

**Comment by ianb** [comment]
I haven't seen this often lately, and only during heavy load.
