### ISSUE TITLE
Check if the page being shot is public, warn if not

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#728]
The biggest security risks are when people make a shot of private pages, particularly those controlled by a login.  While we can't absolutely detect those cases, we can detect many of them.

When we detect a private page I'd like us to put up an extra warning.  And also perhaps offer to not include the DOM snapshot, which is where a user is most likely to unintentionally leak information.  This warning would be in place of the shot panel, and require some confirmation ("I understand the risks").

A first thought of how we check if a page is private:

- User makes a shot of `https://mail.google.com/mail/u/0/`
- Sends a request to `https://pageshot.dev.mozaws.net/checkpublic?url=https://mail.google.com/mail/u/0/`
- The server requests `https://mail.google.com/mail/u/0/` (no cookies or anything)
- The server checks for 401 or 403 requests.  It also checks for a redirect (which we presume is a login redirect).

If we want to be a bit fancier:

- Additionally, we can parse the resulting page and look for `<input type="password">` or other hints at a login.  (Doesn't work as well for federated logins, but we could create a list of known login buttons.)
- The client uses the exact same checks, and as part of the request to `/checkpublic` it submits the list of things it found, like `&foundpasswords=fieldName&loginWidget=facebook`
- If the server finds login techniques that the client did not find, then it consider the page to be a "login" page
- An example would be `https://www.facebook.com` which is both the feed homepage and acts as a login form; this would allow us to detect that the public page is a login page, while the feed page doesn't include any login form and so is private.

**Comment by ianb** [comment]
We can use the `anonymous` parameter on [requests](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/request), and then do all this work in the addon instead of round-tripping to the server.

**Comment by ianb** [comment]
Current status:
![screen shot 2015-12-02 at 9 02 20 am](https://cloud.githubusercontent.com/assets/44390/11534267/71e7be3a-98d3-11e5-9c39-846a2795d7cc.png)

**Comment by ianb** [comment]
A bug: the warning shows up temporarily when a page is public (probably treats null as false)

@brampitoyo will design the warning message, which will overlay the rest of the panel, and have an "OK" button (continues as normal) and "Cancel/Delete" which removes the shot.

**Comment by ianb** [comment]
See also #734

**Comment by brampitoyo** [comment]
The warning overlay appears on top of the short panel whenever we detect a non-public page.

It looks like this:
![pageshot-warning-when-saving-private-pages](https://cloud.githubusercontent.com/assets/51007/11805041/69c526a8-a33b-11e5-8a2f-93bc7ec20f67.PNG)

When “Delete” is clicked, the whole panel disappears, and the shot is deleted.

When “Save Anyway” is clicked, the warning overlay fades out, showing the short panel again.

Video of behaviour:
http://cl.ly/3Y3X1O3S1Z2J/pageshot-warning-before-saving-personal-pages.mov

**Comment by ianb** [comment]
Right now the design on this is on hold as we look at other design aspects.

**Comment by ianb** [comment]
We are saving this property: do we want to do anything with it in the new design?

**Comment by ianb** [comment]
If the page is private then after you save the full page (either directly saving the page with no clip, or uploading the full page) we will show a tooltip/title on the Share button that says: "You've saved your personal version of this page. This page is only visible to you until you share the link."
