### ISSUE TITLE
Delete expired shots after grace period

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#730]
We don't have to delete them immediately, but we shouldn't just hide the content indefinitely

**Comment by ianb** [comment]
Related to #729 : during the grace period the author of the shot should get an option to extend the shot lifetime.  (Also we need to define how long the grace period is)

**Comment by fzzzy** [comment]
2 weeks after the shot expired, we should actually delete the shot data, but not the url.

**Comment by ianb** [comment]
There's a UX question about what exactly we need to do with the shot when it is deleted (permanently delete, or leave the URL visible?)

**Comment by ianb** [comment]
The code needs updating so that a deleted shot still shows the original URL, in the same way it does for expired-but-not-deleted shots.

We need to check that the shot index doesn't include deleted shots or expired shots.  (We can make another screen, like `/shots?expired` that shows expired shots.)

Deleted shots should retain their titles in addition to their URL.
