### ISSUE TITLE
Scraping/guessing detection

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#731]
We rely on the URLs being hard to guess.  (a) we should do the math about how hard they really are to guess, (b) we should make guessing harder

I would propose that we track 404 requests by remote address, and rate limit those IPs.  Then if someone is trying to check a lot of addresses, we slow them down.  Only real 404s would indicate fishing.

**Comment by ianb** [comment]
This module seems good... but also doesn't seem right: [express-rate-limit](https://www.npmjs.com/package/express-rate-limit)

**Comment by ianb** [comment]
Also not quite right: [express-brute](https://www.npmjs.com/package/express-brute) – rate-limiting 404 specifically is unclear.

**Comment by ianb** [comment]
We should be able to use one of these, but we have to wrap the rate limiter around only the 404 response

**Comment by ianb** [comment]
Let's just keep the IPs in memory.  So:

```javascript
ips = {};
if (is404) {
  if (req.ip in ips) {
    ips[req.ip][0]++;
  } else {
    ips[req.ip] = [1, Date.now()];
  }
}
if (ips[req.ip] && ips[req.ip][0] > MAX) {
  rejectRequest();
}
setInterval(function () {
  for (ip in ips) {
    if (ips[ip][1] < Date.now() - TIME_LIMIT) {
      delete ips[ip];
    }
  }
}, PERIOD);
```

**Comment by ianb** [comment]
I've added this to a list of questions for a future meeting with @relud and @jvehent

**Comment by jvehent** [comment]
I'd recommend to do this in the logging pipeline. We have plans to detect clients that have high connection rates, and insert their IPs into our global IP reputation service maintained by @g-k.
The pageshot frontend should query the IP reputation endpoint as part of serving a request, and if the reputation is deemed unacceptable, either send a back-off code or completely drop the request.

**Comment by ianb** [comment]
We'll need to figure out exactly what we should be logging and in what format to trigger the feedback into the IP reputation service.

**Comment by jvehent** [comment]
I'm assuming we will implement it using nginx access log, though you do bring a good point about application logs, but maybe as a separate issue?

**Comment by ckprice** [comment]
We'll use IP Reputation service instead.
