### ISSUE TITLE
Put a thumbnail of an image of the entire page above the fold

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#732]
I'm concerned that the full-page capture is deliberately below the fold, meaning that it could be easy to not realize it exists.  We could take a thumbnail of the entire page (as a visual representation that we've *also* captured the entire page) and put it in a more prominent place.  Could also serve the same purpose as the "Full page" button, scrolling to the full content.

Not sure how it could fit into the panel.

**Comment by brampitoyo** [comment]
I don’t know how a thumbnail of the whole page could fit into the Shot panel without taking too much vertical space, especially if the page runs long.

But I’ve thought of a way to show full page on the web interface (where we do have more space).

Have a look:
http://codepen.io/anon/pen/YXvbeZ

Is this a good halfway solution?

**Comment by fzzzy** [comment]
Bram, that doesn't look like the right codepen link. Can you double-check it?

**Comment by brampitoyo** [comment]
Argh. Codepen didn’t save the edit I’ve made to this pen!

**Comment by brampitoyo** [comment]
Let’s try this pen. It should show you something like this:
![pageshot-web-full-page-thumbnail](https://cloud.githubusercontent.com/assets/51007/9748013/afbc98f6-56d5-11e5-86b8-0c594dc57d2e.PNG)

The objective is to give a clear indication that the “Full Page” button contains the whole page, not just an image thumbnail.

**Comment by ianb** [comment]
As designed the thumbnail will overlap the clip image.  Right now the "full screen" button overlaps the clip image, but it's small, while the thumbnail will be large and annoying.
