### ISSUE TITLE
UX for panel warning

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#734]
When we do #728, we'll be warning the user before they can take a shot of a personalized page.  This will take the place of the short panel.  We need a design for it.  The shot will not be taken until the user consents.  We *might* want a "don't ask me again" checkbox.

**Comment by brampitoyo** [comment]
The interface could look like this. Thoughts?

![pageshot-shot-panel-warning-sensitive-websites](https://cloud.githubusercontent.com/assets/51007/10065951/247a8a06-62e1-11e5-8f22-509c8189d22d.PNG)

I tend to think that including a “Don’t ask me again” checkbox is a bad idea.

**Comment by fzzzy** [comment]
I like this. Simple and obvious

**Comment by fzzzy** [comment]
The warning could look like an overlay onto the existing panel.

**Comment by brampitoyo** [comment]
I’ll add a button to close.

**Comment by brampitoyo** [comment]
The button should be put underneath the (Not secure) button and say “Close PageShot”

If we want to emphasise the button a bit more, we can either use a blue or yellow highlight colour as shown in the example below. I prefer blue.

http://codepen.io/brampitoyo/pen/dYpaVy

**Comment by ianb** [comment]
The strategy:

- Progress with taking the shot as normal, before we get back a result about whether the page is private
- If the page is detected as private then we:
  - Obscure the panel with the warning message and cancel/accept
  - Immediately inform the server that the shot is provisional on the dialog.  Expiration goes to, say, 5 minutes.
  - If the user cancels or causes the dialog to close, we immediately delete the shot
  - If the user hits accept we continue with the normal shot process, and tell the server to restore the expiration time

This way if anything goes wrong with the dialog (e.g., the computer is unplugged) then the shot will be deleted in a timely fashion.

We'll need to distinguish between these provisional shots, which should be permanently deleted at expiration time, from normal expired shots.

**Comment by brampitoyo** [comment]
This issue was opened when the warning is shown *before* user can take a shot.

Now that the warning is shown *after* the short panel is open, we should use #728 as a reference design.
