### ISSUE TITLE
Put clear "no confidential information please" message on homepage

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#735]
During the experiment we would rather people not submit confidential information (copies of their email inbox for instance).  We should have a strong warning on the front page.  Maybe even annoyingly strong (blinking?)

**Comment by brampitoyo** [comment]
Yes. We can say something like ”No confidential information”, with a text below it that says something like “PageShot must not be used to save banking, insurance, email and other websites that contains your personal and confidential information.”

Or we can have a one-liner that says “Never use PageShot to save websites that contains personal and sensitive information.”

A perfect place to put this warning is below (or above) the download button.

![pageshot-homepage-install-warning](https://cloud.githubusercontent.com/assets/51007/10065802/5fae7a8a-62df-11e5-89cd-f91c172418ab.PNG)

What do you think?

**Comment by brampitoyo** [comment]
We can use text effects to emphasise the warning message, as well: blink, pulse, colour shift, etc. What’s important is that it’s located at a place that’s not easily missed (if we put it as a banner on top or bottom of the homepage, we’ll have to fight user’s banner blindness).

**Comment by brampitoyo** [comment]
Our home page is going to be hosted on IdeaTown.
