### ISSUE TITLE
If Auto-Detect selects an area large enough to qualify as Visible, warn the user

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#738]
Sometimes, Auto-Select would highlight an area that’s sufficiently close to Visible. For example, it might select the whole page minus a few pixels on the corners. This confused our testers.

We should make sure that Auto-Detect should always select an area that’s important yet small enough, so that it could never be mistaken as Visible. 

Even when Auto-Detect fails to select anything useful, it should still avoid selecting an area that’s as large as visible. Instead, it could ignorantly select an box of (for example) 400x300 px size, located 100px from the top and 100 from the left of the page.

**Comment by ianb** [comment]
When the autoselect "fails" (is the entire screen size) then we should make the selection smaller, maybe by 100px on each side, except snap each of the new borders using the calculated snapping points (so the borders aren't entirely arbitrary).

**Comment by brampitoyo** [comment]
Snapping is a very important piece of the puzzle. It’ll help make our Auto-Detect seem magical (“how does it know to select the boundary between this element and that element?”), and our pilot testers seem to expect it to be so.

**Comment by fzzzy** [comment]
Opened #747 to deal with auto-detect buginess.

**Comment by fzzzy** [comment]
Opened #748 to deal with snapping the selection to be narrower.

**Comment by fzzzy** [comment]
I want to start fixing this by first warning the user if this condition happens. I opened #747 and #748 to fix the actual bugs in this area.
