### ISSUE TITLE
Selection mismatch

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#743]
In [this page](http://www.huffingtonpost.com/food-52/how-to-cook-a-3course-mea_b_8050042.html) when you take multiple clips, the clips start to not be accurate, and the autoselect gives odd results.  The inaccurate clip is shown in this screenshot:

![screen shot 2015-09-15 at 5 27 24 pm](https://cloud.githubusercontent.com/assets/44390/9891877/5b080058-5bcf-11e5-9ab0-93fb2aa73d73.png)

**Comment by fzzzy** [comment]
We don't have multiple clips or autoselect at the moment.
