### ISSUE TITLE
Decide how to tell the user auto-detect selection failed

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#750]

**Comment by brampitoyo** [comment]
I originally thought that we should say something along the lines of “Cannot detect selection automatically” and then select something ‘dumb’, like this:

http://codepen.io/brampitoyo/pen/vNXexN

But then I realise that maybe we don’t need to say anything.

The reasoning is this: whether autodetect succeeds or fails, what user will see as the final result is exactly the same: a selection on the page. Whether that selection is ‘smart’ or ‘dumb’ is a detail that only the system know, but the user doesn’t care about. All the user care about is whether it looks right. And if it doesn’t, he can tweak it manually.

So I think there shouldn’t be any notification, and we should simply select something else.

Unless we truly cannot select anything at all, and then we can display a message that says “Cannot select anything on the page. Click on the Camera button to [try again].”

What do you think?

**Comment by fzzzy** [comment]
I agree it would be best to say nothing, but the temporary issue I am running into is that since it is difficult to implement the behavior where we snap to a narrower grid line which is specced out in the other issue, I'd like to tell the user when the auto selection was close to the size of the page. For now, I'll change the wording to "Cannot detect selection automatically." Once the snapping to narrower grid lines is implemented, we won't need the wording at all.
