### ISSUE TITLE
Design way to delete shot on the website

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#757]

**Comment by brampitoyo** [comment]
Delete shot is a feature that appears alongside the drop down menu to change expiration date.

![expire-ui-2](https://cloud.githubusercontent.com/assets/51007/10093098/f3e58ef6-63a1-11e5-939a-3262612cd8cd.png)

**Comment by ianb** [comment]
For now, when you hit delete we'll use `window.confirm()` to confirm that you want to delete the shot.  The deletion will be permanent, and the page will 404 in the future.  The user will be redirected to the shot index page after confirming.

To do the confirmation we'll put the message in localStorage or a cookie, and check that on page load (such as the load of the shot index page) and pop up a notification in the website.

Note: track (GA) delete button.
