### ISSUE TITLE
When a shot is expired but in a grace period, a user can unexpire the shot

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#758]
There will be a period (2 weeks) when a shot is expired and not publicly visible.  During that time no one can see the page, but when the author of the shot browses to the page they should get an error message and the option to extend the expiration time (similar to #729)

**Comment by brampitoyo** [comment]
I think going from active -> expired -> deleted is highly confusing. I recommend going with just two states: active, and deleted.

So if the expiry date runs out, the shot is deleted. Yes, you can still view the original source, but there’s no grace period. No restore.

The real world analogy is “you can’t unexpire an expired milk”.

If we still want a feature to restore, how about doing something like this example? We strike-through the title, and in place of the expiration counter, we put the text “shot expired” and give a link to restore it.

http://codepen.io/brampitoyo/pen/xwReeW

**Comment by ianb** [comment]
Put an em-dash between "saved on" and "expires in"

Put an em-space between save/cancel/delete

Change "expire in" to "expires in"

Add a countdown to the final deletion of the expired page.

On expired page, when editing expire, instead of "expire in" use "keep for"

On expired page, change "change" to "restore for 2 week".  

When restoring, default to two weeks, and immediately refresh the page.  If you want to edit the expiration time, you can re-edit it then.

Get rid of "1 Second"

Change first item in select box to be "Change..."
