### ISSUE TITLE
Measurements

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#762]
* How often does someone open the recall panel
  * Do authors navigate from recall panel to the shot web page
  * Do authors view the details of shots from within the recall panel
  * Do authors click the link to the original page on the recall panel
  * Do authors share or copy from the recall panel
* Do authors navigate directly to shot (without recall panel)
  * What source did they use to get to the shot?  (I.e., referrer origin)
* Do people navigate from shot index to a shot
* From short panel:
  * Do people click on the link to the shot
  * Clicks on share or copy buttons
  * How often do people click on Edit or Add
* From long panel:
  * Do people click on `+`?
  * Do people delete clips
  * Do people change the selection type?
  * Do people reassert the selection type?
  * Do people make a comment?
  * Do people clear their comment?
* On the shot page:
  * Click clip navigation (up/down)
  * Click on clips
  * Click full page
  * Click link to original page
  * Open login panel
  * Delete account
  * Export shots
  * Change expiration time (separate up and down)

To collect all shot pages as a category, we can rewrite shot page URLs (just for GA) to be `/shot/hash` or maybe `/shot/origin/hash`

**Comment by fzzzy** [comment]
Split out a few that require a bit more effort into #771
