### ISSUE TITLE
Try usabilityhub

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#765]
[Usability Hub](https://usabilityhub.com) lets you do really simple tests for free.  We should try it out.  E.g., Ryan Feeley suggested "a friend told you that firefox now has built-in screenshot feature. click where you would go to take a screenshot." (with an accompanying screenshot of the browser with the PageShot icon on it)

**Comment by brampitoyo** [comment]
I’ve created a test. It turns out that the test works by a credit system (ie. it’s not free).

Preview:
https://usabilityhub.com/preview/eb80ff63f2f3

Cost breakdown:

* $25 for 25 users
* $45 for 50 users
* $85 for 100 users

**Comment by brampitoyo** [comment]
The image I used is this:

![pageshot-windows](https://cloud.githubusercontent.com/assets/51007/10232964/2de6897a-68e8-11e5-89ff-412e057769dd.png)

**Comment by ianb** [comment]
It has been tried!  People understood the icon very well.
