### ISSUE TITLE
Additional measurements

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#771]
Things that were in the original measurements bug that need a bit more discussion.

* Do authors navigate directly to shot (without recall panel)
  * How can we tell?
* What source did they use to get to the shot? (I.e., referrer origin)
  * check to make sure ga logs referrer properly -- what else do we need here?
* Change expiration time
  * We don't support this yet

**Comment by fzzzy** [comment]
Let's calculate direct visits to the shot page by subtracting the number of clicks on the recall panel link from the number of visits to the detail page

**Comment by ianb** [comment]
We're all metric'd up now.
