### ISSUE TITLE
Make the shot fly into the recall panel with an animation

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#781]
If we do this, we won't have to explain the recall panel icon with text, which will reduce the wall of text from the tutorial.

**Comment by brampitoyo** [comment]
![bookmark-star-animation](https://cloud.githubusercontent.com/assets/51007/10384601/5025eadc-6e9a-11e5-890e-2f72441474af.gif)

I originally intended the two panels to interact this way to give our interface a sense of familiarity. ie. saving to bookmark == PageShotting

**Comment by ianb** [comment]
Recall panel is probably going away (as a separate button)
