### ISSUE TITLE
On UI tour, highlight shot URL after shot panel has been opened

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#782]
Currently, it’s not highlighted.

![screen shot 2015-10-09 at 12 28 13](https://cloud.githubusercontent.com/assets/51007/10382536/8ce9c880-6e81-11e5-9dca-83a2390ded55.PNG)

Alternate style in case we can’t do rounded rectangle:

![screen shot 2015-10-09 at 12 29 25](https://cloud.githubusercontent.com/assets/51007/10382542/9e614ffc-6e81-11e5-8971-8a7c95c13bd7.PNG)

**Comment by fzzzy** [comment]
We can't actually use uitour to target an element inside the panel, but I can highlight the url with html inside the panel.

**Comment by fzzzy** [comment]
I can't get css animations to animate smoothly inside the panel, so I just put a border around the link for 2 seconds, then made it disappear.
