### ISSUE TITLE
Write and implement text for UI and in-content tour

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#783]
For in-content tour, we’re looking to modify `data-step` and `data-intro` values found on `server/src/views/frame.js`.

**Comment by brampitoyo** [comment]
The text for the guided tour looks like this.

### 0
User installs PageShot. No tour here.

### 1
* Tutorial page opens (heading: “Welcome to PageShot”)
* UI tour highlights the camera button
* UI tour prints “Click the camera to clip a part of the page ”
* User clicks the camera button

### 2
* Shot panel opens
* UI tour highlights the shot URL
* UI tour prints “Click on the link to see your clip”
* User clicks the shot URL

### 3
* Shot webpage opens
* In-content tour highlights the top part of the page.
* In-content tour prints “This is the title of the page and the link to its source”
* User clicks “Next”

### 4
* In-content tour moves to highlight the shot image
* In-content tour prints “This is your clip. Taking multiple clips is easy. After you click the camera button, click ‘Add Clip’.”
* User clicks “Next”

### 5
* In-content tour moves to highlight the Full Page button and the area underneath
* In-content tour prints “Every time you take a clip, the whole page is also saved”
* User clicks “Next”

### 6
* In-content tour moves to highlight the clip in context
* In-content tour prints “Your clip is highlighted so you always know where it is on the page”
* User clicks “Next”

### 7
* In-content tour disappears
* UI tour is triggered
* UI tour highlights the recall button
* UI tour prints “Click this button to see everything you have saved. Enjoy using PageShot!”
* User clicks the recall button
* UI tour disappears

**Comment by fzzzy** [comment]
I had to leave out step 6 for now, since it is hard to have the tour target the actual clip in the page since it is inside an iframe.
