### ISSUE TITLE
Help button that triggers the tour always

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#795]
? button on both the recall panel and shot panel that opens the tour page and starts the tour

**Comment by fzzzy** [comment]
Bram, can you do a design for this? Where do we need help buttons? In the shot panel, in the recall panel, and in the shot detail page?

**Comment by brampitoyo** [comment]
I’m guessing that we’ll need help buttons both in the shot panel and recall panel.

The behaviour should be that clicking on this button will open the firstrun page in a new tab, and it will also highlight the Shot/camera button. User clicks on the camera button to continue with the tour.

In terms of design, I think we can do a design similar to the help button found on the bottom of the hamburger menu.

![screen shot 2015-10-16 at 16 58 12](https://cloud.githubusercontent.com/assets/51007/10533539/2570a47a-7427-11e5-9572-6c7e5ad48eb7.PNG)

So then:

On the bottom of the Recall panel, we have the link that says “Show All Snaps in PageShot”. To the right of this link, we’ll put a “?” button.

![screen shot 2015-10-16 at 17 05 16](https://cloud.githubusercontent.com/assets/51007/10533676/251317ea-7429-11e5-899c-234b42c2b5b6.PNG)

And on the bottom of the short Shot panel, we have have three buttons: “Add Clip”, “Edit”, and “?”.

![screen-shot-2015-10-16-at-17 12 26](https://cloud.githubusercontent.com/assets/51007/10533706/93168f9c-7429-11e5-81d8-f368f9512850.jpg)

What do you think?
