### ISSUE TITLE
Shot and Recall buttons fail to initialize

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#796]
1444774461135	addons.xpi	WARN	Add-on jid1-NeEaf3sAHdKHPA@jetpack is missing bootstrap method startup
1444774461149	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: experiment
1444774513596	addons.xpi	WARN	Add-on jid1-NeEaf3sAHdKHPA@jetpack is missing bootstrap method shutdown

**Comment by ianb** [comment]
This I'm sure has been fixed
