### ISSUE TITLE
Fullscreen thumbnail doesn't show

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#803]
[Example](https://pageshot.dev.mozaws.net/jmZ2YhPl/pageshot.dev.mozaws.net) (the image [404s](https://pageshot.dev.mozaws.net/images/b1813ab5-f8e8-4e6a-ba72-50c4aad90f1d))

**Comment by fzzzy** [comment]
The thumbnail doesn't show up in development, either. There must have been a merge problem.
