### ISSUE TITLE
Consider rel=self

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#81]
We might want to use `<link rel="self" href="originalUrl">` in our pages.  But I'm not sure what this actually *does*, i.e., if anything uses that.  Search engines?

**Comment by ianb** [comment]
Apparently this link type is not [defined for HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types) (only for Atom feeds I guess)

**Comment by CaptainCalliope** [comment]
Is this related to http://microformats.com/wiki/rel-me ?

**Comment by ianb** [comment]
I don't believe so – rel=me is about identity, in Atom rel=self is a pointer to the original content.

**Comment by ianb** [comment]
I don't think rel=self
