### ISSUE TITLE
Fix .gif link on homepage

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#812]
The link to the gif is there, but the link is broken

From 80c5267d5f03f95e7eff57452670238bc7810300

**Comment by fzzzy** [comment]
I fixed the links, but now the images themselves are missing.

Bram, can you add the images to static/homepage/images and remove whatever irrelevant html is still in static/homepage/index.html?

![screen shot 2015-10-21 at 11 18 21 am](https://cloud.githubusercontent.com/assets/46048/10641048/80e3339c-77e5-11e5-84ba-b3e3365ce4bc.png)
![screen shot 2015-10-21 at 11 18 08 am](https://cloud.githubusercontent.com/assets/46048/10641049/80e9ee4e-77e5-11e5-8a29-46ccf89feb96.png)
