### ISSUE TITLE
Various caption images don’t show on homepage

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#837]
They’ve been linked properly, but maybe I’ve missed a few things so they still don’t show up?

You can find them under `static/homepage/images`:

* `pageshot-button-firefox-toolbar.png` and `@2x`: appears to the right of “Install the Firefox addon”
* `pageshot-bounding-box.png` and `@2x`: appears to the left of “Select clips or highlights from the page”
* `pageshot-share-buttons.png` and `@2x`: appears to the right of “Share the link!”

**Comment by fzzzy** [comment]
It seems like those links should work, but I've added the absolute path "/homepage/" to the beginning to see if that fixes it.
