### ISSUE TITLE
Change event categories/etc

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#842]
From Gareth Cull, some suggestions:

Event category: the "place" the event happened.  So "addon" and "website".  I might be inclined to split homepage into its own category, as it represents the period of time before you use PageShot.

The event action being a rough category of event.  Examples might be nav-click, footer-click, clip-nav

Event label being entirely specific, like up-arrow (under clip-nav), or secondary-body-install-button

**Comment by fzzzy** [comment]
Should probably obfuscate the urls as part of this pr too, while I am at it.
