### ISSUE TITLE
Add "to create use Firefox"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#85]
A little popup to show that you need Firefox to use PageShot (for non-Firefox viewers)

**Comment by ianb** [comment]
Another way to go: "What is PageShot?", and show the features, and push all the features you can only use in Firefox

**Comment by ianb** [comment]
If the addon isn't installed (viewerworker.js can help tell the server page that the addon is installed), then we can also tell people they can install the addon to make shots of their own.

**Comment by fzzzy** [comment]
Is there a way to detect whether the addon is installed, from the server-side code?
