### ISSUE TITLE
Track site load speed in GA

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#888]
GA has some functionality for this, but apparently we aren't doing whatever is necessary for it to collect that information.

**Comment by ianb** [comment]
I can't figure out what's going on here.  Apparently you no longer need to enable Site Speed specifically, it's just automatic.  It's possible that because the domain on the GA account is listed as pageshot.mozilla.org that the timing isn't working or isn't being sampled.

**Comment by ianb** [comment]
We should probably ask Gareth Cull about this

**Comment by johngruen** [comment]
@ckprice to confirm and close

**Comment by ckprice** [comment]
Confirmed that GA does track this out of the box under the "Behavior" tab.
