### ISSUE TITLE
Check out preserve.io

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#899]
https://preserve.io/welcome

“When you preserve a bookmark, we save a copy of it to our servers so no matter what happens, you'll always have a copy.”

**Comment by ianb** [comment]
This requires an invite, it's odd to need that so long after launch.  I requested one.  It's interesting that it just watches your bookmarking activity.

**Comment by ianb** [comment]
Copied to https://github.com/ianb/pagearchive/issues/13
