### ISSUE TITLE
Create backend management interface

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#904]
I think we'll want to do some controlled things manually with PageShot.  I propose a management screen.  This is a couple things like some reporting (size, some activity), the management of the user accounts for #903, and then other stuff in the future.

I guess we could use the normal auth (relying on only accessing the site via a browser with the PageShot add-on), and then hardcode a list of allowed account emails.

While React feels a little excessive, given that we have it all setup we might as well use it.  Maybe we could make this admin an express nested application.  It might be a chance to do React/isomorphism the "right" way (i.e., setup a pattern that makes use of what we've learned).

**Comment by brampitoyo** [comment]
Let me know if some user interface design is needed for this. I’m guessing that the answer would be ‘no’ because you can use Bootstrap, etc. But maybe there’s something!

**Comment by ianb** [comment]
It's only for us, so it can be as ugly as we can bear ;)  But once there's something in place we may want to improve the design.

**Comment by ianb** [comment]
Erg... FxA account logins aren't being recorded in the database.  Regression... at some point?  Maybe a long time ago.

**Comment by ianb** [comment]
The initial implementation is done.  #937 to fix auth, we'll make tickets for specific features we want later.
