### ISSUE TITLE
Test shot pages in IE

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#905]

**Comment by brampitoyo** [comment]
I’ve tested PageShot’s web interface on Internet Explorer 11 running Windows 10.

![pageshot-web-internet-explorer-1](https://cloud.githubusercontent.com/assets/51007/11832283/65ff3f96-a3e9-11e5-8272-44de5d6f2a22.PNG)

![pageshot-web-internet-explorer-2](https://cloud.githubusercontent.com/assets/51007/11832285/6e019d4c-a3e9-11e5-805e-99201a5272f5.PNG)

The page looks alright, except for two problems:

* Clip navigator failed. Clicking the down arrow didn’t take me to the full page, and the part of the page I had saved wasn’t highlighted.
* Header didn’t show up when scrolling down. On the second image, note how the clip navigator stands alone without a grey background that contains page title, source URL, timestamp, etc.

The same error persisted on Edge.

**Comment by brampitoyo** [comment]
(You can ignore the “circlesoundcloud circletwitterbird” etc. text. My internet didn’t work so well this afternoon.)

**Comment by ianb** [comment]
The clip navigator probably failed because there's errors – the basic page renders on the server, but then clip navigation and the header require JavaScript.  We are guessing that there are compatibility problems with IE, since we haven't included browser compatibility shims in the bundle.

**Comment by ianb** [comment]
Probably we need to include this library in the bundles: https://github.com/zloirock/core-js
