### ISSUE TITLE
There’s a long delay between performing action on a clip, and that action propagating to the shot page

### ISSUE THREAD

**Issue by brampitoyo** [mozilla-services/pageshot#907]
This may just be 

Steps to reproduce:

* Click camera button
* Click “Add Clip” and select any option, or resize the current bounding box and move that box around a bit
* The shot panel will appear again after taking this action. Wait for ~5 seconds.
* Open shot page URL

What happens:

* The old clip appeared on the shot page, but the new/resized one doesn’t
* If I waited for a while (~45 seconds), then the clip updates correctly to the new state

**Comment by ianb** [comment]
Ticket #936 will help debug this (though we might be able to reproduce it without those metrics)

**Comment by ianb** [comment]
Ticket #789 might be causing this

**Comment by ianb** [comment]
#789 is fixed, and with the new design I'm not seeing a problem with this.
