### ISSUE TITLE
Rename "never expire" to "indefinite"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#918]
We shouldn't claim that things won't ever expire – it's a chance to emphasize that this service may be taken down.  We should change the name of "never expire" and maybe include a little warning about service promises (or lack thereof).

**Comment by brampitoyo** [comment]
+1. Let’s change the string to “indefinite”.

If our Privacy Policy page can address the fact that the service may be taken down, we don’t need to bother our user with the additional warning.

**Comment by ianb** [comment]
Fixed
