### ISSUE TITLE
FxA id not being updated in database

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#919]
**Update**: this only seems to happen when the login succeeded once, then the database is deleted.  To reproduce: login, stop browser, delete database, restart server, start browser, see if FxA is recorded in database.

The login process completes on the client, but the final step where the account is stored in the database isn't happening.  Might be a regression.

**Comment by fzzzy** [comment]
It does seem to be stored properly, although what happens is a bit confusing and there's not much data stored in the db.

  select id, accountid from devices;

If you see an accountid in the db, which I do after logging in, then there is a corresponding row in the accounts table, with a "token", which I assume is all we get from ff accounts to identify the user?

I tested locally, but I'll see if there's something different about pageshot-dev where it is failing there.

**Comment by ianb** [comment]
I wasn't seeing accountid in devices, including locally.  On the dev server `select id, accountid from devices where accountid is not null;` only returns one row as well.  Maybe there's a case where it is saved from a from-scratch profile, but it's breaking on more long-lived profiles?  For instance I think my local testing profile is older than my local database.

**Comment by fzzzy** [comment]
Yes, it seems to be working with a new profile. I bet you're right that it breaks on some old profiles.

**Comment by ianb** [comment]
Note that the login code is resilient to the database going away (always trying a register if login fails).  Maybe the same doesn't happen for FxA.

**Comment by ianb** [comment]
We're not really showing FxA anyway right now.
