### ISSUE TITLE
Create link back to PageShot "home"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#929]
This is the place where privacy noticed, DMCA takedown info, etc is in there.

**Comment by brampitoyo** [comment]
Shouldn’t T&C, privacy and DMCA notices be parts of the footer and included in every page? If this is the case, then we only need to design this footer. PageShot’s “home” page will naturally include this footer, too. What do you think?

**Comment by ianb** [comment]
On shot pages it doesn't feel right to me to have a footer: the whole captured page is going to live between the top of the page and the footer, and the captured page's footer will be down there too.  It feels to me like everything after "full page" starts should belong to the captured page to avoid this confusion.

**Comment by ianb** [comment]
In the new design we have this in the top-left corner.

**Comment by ianb** [comment]
Implemented
