### ISSUE TITLE
Fix authentication in management/metrics interface

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#937]
Depends on #919 – once fixed we should authenticate off of FxA ids and not deviceId

**Comment by ianb** [comment]
This has become hard because we no longer have any FxA login at all, only deviceId.

**Comment by ckprice** [comment]
Putting into Next Tasks as it's dependent on #919 which is in the same milestone.

**Comment by ianb** [comment]
We don't have any private pages
