### ISSUE TITLE
Think about card views

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#96]
[This article](http://blog.intercom.io/why-cards-are-the-future-of-the-web/) espouses many of the benefits of cards.  PageShot could help create card views of websites.

**Comment by ianb** [comment]
Also look at [this proposal on webcards](https://etherpad.mozilla.org/webcards) and [this proposal on service cards](https://fxos-v3.slack.com/files/djabber/F03AF1DMW/servicelayerusingcards_firefoxosv3.pdf)

**Comment by CaptainCalliope** [comment]
Check out http://embed.ly/

Also possibly relevant is a two-year old discussion on 'Markup APIs' that I think started with @toolness here: http://www.toolness.com/wp/2013/01/building-bridges-between-guis-and-code-with-markup-apis/ and continued here: http://apievangelist.com/2013/01/16/markup-apis-and-api-scripting-platforms/ 

The gist of it was thinking about Web Components as a way to wrap APIs up similar to how some platforms have been offering widgets as a way to interact with them. More recently, Google has been playing with this idea through Polymer. I'm not sure if this is now a divergent or convergent conversation to where the cards conversation is going, but may be relevant to your exploration.

**Comment by CaptainCalliope** [comment]
Btw, is that service cards proposal available on a public channel by chance?

**Comment by CaptainCalliope** [comment]
I'm catching up on the latest card reading right now and I'm starting to think there could be a strong relationship between cards and enabling task continuity. Saving tabs as pages is one thing, but turning a tab into a card that users can attach actions to seems compelling, especially if sent to a friend who gets a notification with an action to take and/or choice to make in response. What kinds of card-based action vocabularies can be create to enable a wide range of personal and collaborative workflows? Is there a level of extensibility that should happen here, or might a sufficient baseline of usable action vocabularies be discovered through user research?

**Comment by brampitoyo** [comment]
We can actually think of PageShot as a way to generate and edit cards, can’t we?

The way you would generate content for the card is by snipping various page elements: words, sentences, paragraphs, images, etc.

So then, you get to customise exactly what’s on the card you’re about to embed on Twitter. Maybe you’d like it to be dominated by image. Maybe you’d like it to be mostly text. Or an infographic. Or a combination of everything.

**Comment by ianb** [comment]
@brampitoyo I feel like we're taking a different direction than card views with the most recent designs...?

**Comment by brampitoyo** [comment]
Yes. I haven’t thought of card lately. We should close this issue but keep it in mind.

It may be possible to resurface some of the ideas here in the feature we always talk about but hardly have found the time to design, which is how to make a totally new listicle/summary by assembling a collection of quotes/images/media from many different sources.
