### ISSUE TITLE
Confirm or fix add-on errors to Sentry

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#969]
Looking at the code, it doesn't seem like errors are going to be sent to Sentry

**Comment by fzzzy** [comment]
Need to install raven on the shot index page.

**Comment by ianb** [comment]
I can't see any recent errors in Sentry, so this is an active problem.

**Comment by wresuolc** [comment]
Sentry stuff is https://bugzilla.mozilla.org/show_bug.cgi?id=1293724

**Comment by ianb** [comment]
I just got an email from a (deliberate) server error, so that part is working.  We still need to confirm that add-on errors get through.

**Comment by fzzzy** [comment]
From reading the code, unhandled add-on errors will be properly sent to sentry, but errors that are caught with watchFunction (which should be most of them) won't be, because they don't have a way to get the sentry public dsn url.

**Comment by fzzzy** [comment]
Scratch that. watchFunction calls unhandled. So unless there is a bug, add-on errors should go to the sentry public dsn if the server is configured with it. So we just need to check that on deploy somehow. We should probably add an add-on trigger error function, but I don't know where to let the user trigger it from. Maybe we can trigger an error if the user clicks the shot button while holding down some modifier keys?
