### ISSUE TITLE
PageShot fails on new profile

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#970]
There's an authentication problem with a new profile, at least on the fzzzy/topbar-prototype branch.  Once you restart the problem goes away, so it might be a race with register and deviceId creation, or some other startup problem.

**Comment by ianb** [comment]
Next step is just to test with a new profile

**Comment by fzzzy** [comment]
I tried 10 times to reproduce this and didn't have any problems. If this happens again, reopen the bug.
