### ISSUE TITLE
Assets for "My Shots"

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#974]
I need the assets for the 9 squares graphic and the > graphic to go in the new My Shots button. I could screenshot them from the mockups, but it would be fuzzy on retina like the other time I did that.

**Comment by brampitoyo** [comment]
https://www.dropbox.com/s/8iqz5jwasggcynd/my-shots.svg?dl=0

**Comment by ianb** [comment]
It's in /static/img/my-shots.png but needs to be saved as SVG (also the PNG is not high enough resolution for retina)
