### ISSUE TITLE
Asset for "three dots" icon

### ISSUE THREAD

**Issue by fzzzy** [mozilla-services/pageshot#975]

**Comment by brampitoyo** [comment]
https://www.dropbox.com/s/7t0tps0uqfqkt4f/menu.svg?dl=1

**Comment by ianb** [comment]
It's in the code as /static/img/menu.png

**Comment by ianb** [comment]
Needs to be saved by SVG

**Comment by fzzzy** [comment]
We're not using the three dots menu at the moment, but bram linked to the svg asset above if we ever need it
