### ISSUE TITLE
Clip image seems to extend to the top of the screen

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#984]
In this screenshot, notice the dropshadow:

![image](https://cloud.githubusercontent.com/assets/44390/13440272/e0162aca-dfb6-11e5-8b41-10a8c77b2ef7.png)

The image seems oversized:

![image](https://cloud.githubusercontent.com/assets/44390/13440298/fba90d20-dfb6-11e5-99ea-f8f10a460e8c.png)

**Comment by ianb** [comment]
@fzzzy: is this fixed?

**Comment by fzzzy** [comment]
Yes, I fixed this.
