### ISSUE TITLE
Implement crosshair highlight

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#989]
The page should look like:

![image](https://cloud.githubusercontent.com/assets/44390/13440956/6277e082-dfba-11e5-98d8-060f0ec368e7.png)

So we need to put an overlay on the page, change the crosshairs to white, default the crosshairs to being partway on the page, and put a pulsing thing on the crosshairs until the user mouses over the content for the first time.

(Ignore the blue; [design](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/127370525))

**Comment by ianb** [comment]
Here's what it looks like:

![image](https://cloud.githubusercontent.com/assets/44390/13546024/cc4dd680-e265-11e5-8e32-84aec6e3ea57.png)

It pulses larger and smaller (factor of 1.2) every second, 20 times over.

I think we'd need a couple elements to make the pulse effect look like what's in the mockup.  This is the relevant style currently for that portion:

```css
  width: 40px;
  height: 40px;
  border-radius: 20px;
  border: 1px solid rgba(255, 255, 0, 0.5);
  background-image: radial-gradient(20px at 50% 50%, rgba(255, 255, 0, 0.1), rgba(255, 255, 0, 0.5));
```

There's also a white center dot (`.pageshot-crosshair-inner`), 10px in diameter.

The crosshairs are `border: 1px solid rgba(255, 255, 255, 0.6)` – 0.6 seemed okay for making it slightly by noticeably translucent.

**Comment by brampitoyo** [comment]
May I see a video/gif demo of the effect?

I don’t think we need a multi-pulse effect exactly like what’s shown.

**Comment by ianb** [comment]
Only change: make the dot in the middle not pulse along with the yellow halo.
