### ISSUE TITLE
Style topbar

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#990]
Style like:

![image](https://cloud.githubusercontent.com/assets/44390/13440989/a0888a0c-dfba-11e5-865e-10d1e61674b5.png)

So change "My Shots" to take up the full height.  Add the icons to the left and right of the page.  Change the vertical-align of the My Shots button so it doesn't push the text up.

([design](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/127370525))

We should have yellow around the save button (a box shadow I suppose), and try to match the [Firefox Style Guide](http://firefoxux.github.io/StyleGuide/#/components/controls).

**Comment by brampitoyo** [comment]
Right-facing arrow icon:

https://www.dropbox.com/s/7jxblz3w71nlyvq/arrow-right.svg

**Comment by ianb** [comment]
Getting the left margin of the My Shots button right is very hard, I can't figure out any padding or margin that I can remove that will put the button entirely on that side.  Also there's a border around My Shots that I can't get rid of.  Here's what it looks like now:

![image](https://cloud.githubusercontent.com/assets/44390/13546020/63b01d90-e265-11e5-8091-a7a5a875be50.png)

Should we make the text not-bold?  What size should the 9 square icon be?  The halo `box-shadow: 0px 0px 10px #ff0`

There is some style at the border of the topbar that I can't figure out.

**Comment by brampitoyo** [comment]
Attached is the measurement document that also includes other design specs (colour, font-size, margins, etc.)

What do you think? Is it possible to implement?

![measurements - save toolbar 2x](https://cloud.githubusercontent.com/assets/51007/13558106/9b5d82d0-e460-11e5-9586-0774cb7494b3.png)

**Comment by ianb** [comment]
Note: the text is no longer bold.  We will attempt to make the My Shots button better, but if we can't then that's fine.
