### ISSUE TITLE
Change design of shot index

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#991]
Design: 

![image](https://cloud.githubusercontent.com/assets/44390/13441087/23dbae5c-dfbb-11e5-915a-0ef13978d8ef.png)

Move title below image.  Use the clip image as the image (sizing rules to be specified by @brampitoyo).  Favicon and domain at bottom.

For shots without a clip (now a common occurrence) we should use the captured images, like we do currently in the shot index.

For now **do not include the share button** (we'll pick that up later).

The image should be resized so it is max-height/width of 260px (with 10px margin).  The cards are 280px wide.  Margin between cards are 30px.

**Comment by ianb** [comment]
@brampitoyo: can you upload the multicolor logo?

**Comment by ianb** [comment]
@brampitoyo: question: when there is no image available (a full page capture of a page with no images) what should we show?

**Comment by brampitoyo** [comment]
Re: multicolour logo – It was designed as a stand-in for the logo that Bryan Bell had designed.

https://www.dropbox.com/s/9u4t3tb385tbg5d/pageshot.svg

Per #1000, we should display this icon at width=32px and height=30px.

**Comment by brampitoyo** [comment]
> when there is no image available […] what should we show?

We should show an image comprised of two screenshot halves: the top of the page and the bottom of the page.

Design specs below:

![measurements - site previews shot index page 2x](https://cloud.githubusercontent.com/assets/51007/13588878/65744176-e538-11e5-839e-db87312a0f1b.png)

**Comment by brampitoyo** [comment]
> […] we don't have a date on this, should we?

I don’t think having a date is necessary. There’s less information to display on the page. If we think that we need it in the future, we can add it.

> Should clicking on the image do anything?
> What should the click target be for the title? A region? Any hover?

The whole box should be one big link to the shot page (except for the favicon + URL and the share button, which do different things). This includes clicking on the title, the image, and all the white space surrounding it.

> How tall should the title area be? What should the heights be for the title and domain name? For the domain name, what's the border/color/padding/radius we should use?

This is addressed in the design guide up above, but perhaps we should create a new issue for it.

> What should we do when we don't have a favicon?

If there’s no favicon, we can simply not have it take up the space. The grey button that leads to the source URL can replace it.

**Comment by ianb** [comment]
Mostly done, one followup in #1070

I didn't understand the different widths, and just did the middle width.  Note that because it uses flex, the heights align across the entire row – so if one card is long, all the cards in that row are long.  A long card could happen with a long title.

I used the color in the spec for the link, which was a blue – but the images have a gray color.
