### ISSUE TITLE
Implement first time slide

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#993]
Per the design:

![image](https://cloud.githubusercontent.com/assets/44390/13441241/d439ed68-dfbb-11e5-96d0-6f352fd2967b.png)

Language isn't final, but shouldn't stop us.  This will have to overlay the current page.  The blur is optional.  There might be an approach in Hello, or we can punt and inject this into content.

Question: is it okay to leave the topbar in here, or do we want to keep the topbar from showing until Let's Go button is pressed?

**Comment by ianb** [comment]
We'll show this when PageShot is first installed: because PageShot is always explicitly installed by the user, they'll be ready to learn more about it right after installation.

If we can use UITour to put in this visual then we should use that.  When the person clicks on the PageShot button the UITour popup would disappear.  If we can't put arbitrary markup in UITour then we might look at using a panel.

We'll leave out "Let's Go" because we're pointing to the button.

For now we'll just put in the text and not worry about images.

**Comment by ianb** [comment]
Can this just be a page that is opened when PageShot is installed?

**Comment by fzzzy** [comment]
Yes, a page that is opened when pageshot is installed is how the current implementation works. I may have just removed it in cleanup though. The page is still in static/homepage/help.html
