### ISSUE TITLE
Put in "this page is only visible to yourself until you share it"

### ISSUE THREAD

**Issue by ianb** [mozilla-services/pageshot#995]
Per the [design](https://mozilla.invisionapp.com/share/GK5KN2O58#/screens/127953938):

![image](https://cloud.githubusercontent.com/assets/44390/13441367/50391402-dfbc-11e5-84c9-445b00d4b8b9.png)

(Ignore the "8")

**Comment by ianb** [comment]
We'll show this message everytime you save a new page.  It will persist for 15 seconds before being hidden.  It won't show up again after that.  If the page is not public then the language will be slightly different to emphasize that you've saved a personal version of the page.

**Comment by fzzzy** [comment]
This is implemented in the fix for #728
